return {

    -- >> SCAN TAB
	BeginItem_TabNameScan = "مسح",
	
	--Button
	Button_CyclesAppearances = "مظهر الدورة",
	Button_SavesAppearance = "حفظ المظهر",
	Button_ClearSavedAppearance = "مسح المظهر المحفوظ",
	Button_UnlockDoor = "تبديل قفل الباب",
	Button_RestoreAccess = "استعادة الوصول",
	Button_UnlockVehicle = "فتح السيارة",
	Button_RepairVehicle = "مركبة الإصلاح",
	Button_OpenCloseDoors = "فتح / إغلاق الأبواب",
	Button_OpenCloseWindows = "فتح/إغلاق ويندوز",
	Button_ToggleEngine = "تبديل المحرك",
	Button_ToggleAIDriver = "تبديل برنامج تشغيل الذكاء الاصطناعي",
	Button_ToggleCamera = "تبديل الكاميرا",
	Button_ToggleRadio = "تبديل الراديو",
	Button_NextRadioStation = "محطة الراديو القادمة",
	Button_TargetMountedVehicle = "مركبة محمولة على الهدف",
	Button_AssignSeats = "تخصيص المقاعد",
	Button_Assign = "تعيين",
	Button_Reset = "إعادة تعيين",
	Button_FakeDie = "يموت وهمية",
	Button_SmallCopy = "نسخ",
	
    --Button Label
	Button_Label_Unfollower = "إلغاء المتابعة",
	Button_Label_Follower = "تابع",
	Button_Label_SaveDespawn = "حفظ ديسباون",
	Button_Label_ClearSavedDespawn = "مسح الانهيار المحفوظ",
	Button_LabelLockTarget = "قفل الهدف",
	Button_LabelUnlockTarget = "فتح الهدف",
	Label_AddToSpawnFavs = "أضف إلى المفضلة التي يمكن نشرها",
	Label_RemoveFromSpawnFavs = "إزالة من المفضلة التي يمكن نشرها",
	
    --Checkbox
	Checkbox_SavedDespawnsActive = "تم حفظ عمليات الإيقاف النشطة",
	Checkbox_KeepAssigned = "حافظ على تعيينك عند تغيير السيارات",
	
    --Warning / Info / Tool Tip
	WarnTextAI_FastTravel = "حدد نقطة السفر السريع على خريطتك للانطلاق",
	WarnText_DontReloadMods = "لا تستخدم إعادة تحميل كافة التعديلات.\nيرجى إعادة تحميل لعبة الحفظ الخاصة بك أو الانتقال إلى منطقة مختلفة.",
	Warning_NoTarget_Desc = "لا يوجد هدف! انظر إلى NPC أو المركبة أو الكائن للبدء",
	ToolTip_DisableCheckboxReloadSave_AbleTotargetClearSavedDespawns = "قم بتعطيل مربع الاختيار هذا وأعد تحميل ملف الحفظ الخاص بك لتتمكن من استهداف مسح عمليات إلغاء النشر المحفوظة",
	
    --Text
	Build_Mode = "وضع البناء",
	Speed = "السرعة:",
	Search = "بحث",
	Clear = "واضح",
	Player = "لاعب",
	Saved = "تم الحفظ",
	Saved_ = "تم الحفظ_",
	Current = "الحالي",
	Current_ = "الحالي",
	Select_Seat = "حدد المقعد",
	Target_Info = "معلومات الهدف",
	Target_Actions = "الإجراءات المستهدفة",
	No_Appearances = "لا المظاهر",
	No_Target = "لا يوجد هدف",
	Favorite_Appearance = "المظهر المفضل",
	Unfavorite_Appearance = "المظهر غير المفضل",
	Blacklist_Appearance = "مظهر القائمة السوداء",
	Unblacklist_Appearance = "مظهر إلغاء القائمة السوداء",
	Saved_Appearance = "المظهر المحفوظ:",
	Current_Appearance = "المظهر الحالي:",
	List_of_Appearances = "قائمة المظاهر",
	Appearance_Trigger = "مظهر الزناد",
	None = "لا شيء",
	Default = "الافتراضي",
	Zone = "المنطقة",
	Area = "المنطقة",
	Position = "الموقف",

	
	-- >> SPAWN TAB
	BeginItem_TabNameSpawn = "تفرخ",
	
	--Button
	Button_Refresh = "تحديث",
	Button_Save = "حفظ",
	Button_Confirm = "تأكيد",
	Button_Cancel = "إلغاء",
	Button_SmallSave = "حفظ",
	Button_SmallRespawn = "إعادة الظهور",
	Button_SmallDespawn = "ينزل",
	Button_SmallDespawn_WithSpace = "ينزل",
	Button_SmallTarget = "الهدف",
	Button_SmallEquipment = "المعدات",
	Button_LabelHostile = "معادية",
	Button_LabelFriendly = "ودية",
	
    --Button Label
	Label_Favorite = "المفضلة",
	Label_Unfavorite = "غير مفضلة",
	
    --Checkbox
    --Warning / Info / Tool Tip
	Warn_PlayerInMenu = "لاعب في القائمة",
	Warn_AMMonlyfunctions_ingame = "AMM تعمل فقط في اللعبة",
	Warn_SpawnWorksInGame = "التفريخ يعمل فقط في اللعبة",
	Warn_InitError = "خطأ في التهيئة",
	Warn_InitError_Info = "يرجى مراجعة AppearanceMenuMod.log لمزيد من المعلومات.",
	
    --Text
	Active_Spawns = "تفرخ نشطة",
	NoActiveSpawns = "لا توجد عمليات نشر نشطة",
	Select_To_Spawn = "حدد لتفرخ",
	No_Results = "لا توجد نتائج",
	ItsEmpty = "انها فارغة :(",
	Existing_Name = "الاسم الموجود",
	Name = "الاسم",
	
	
	
	-- >> SWAP TAB
	BeginItem_TabNameSwap = "مبادلة",
	
	--Button
	Button_SmallRevert = "العودة",
	
    --Button Label
    --Checkbox
    --Warning / Info / Tool Tip
	Warn_ReloadSaveUpdateChanges = "قم بتحديث لعبة الحفظ الخاصة بك لتحديث التغييرات!",
	Warn_NeedReloadSaveUpdateChanges = "سوف تحتاج إلى إعادة تحميل الحفظ الخاص بك لتحديث التغييرات.",
	Warn_ReplacerSwap = "لا يمكنك تبديل البديل! استخدم علامة تبويب الأدوات في وضع الصورة لاستهدافهم، ثم قم بتبديل مظهرهم من علامة التبويب Spawn أو أدوات الهدف.",
	Warning = "تحذير",
	Warning2 = "تحذير:",
	SaveSwap_Tooltip = "احفظ مقايضاتك للاحتفاظ بها بعد إعادة تحميل لعبتك.",
	
    --Text
	CantSwapReplacer = "لا يمكن تبديل الاستبدال",
	Active_Model_Swaps = "مقايضة النموذج النشط",
	Save = "حفظ",
	Restore = "استعادة",
	Current_Target = "الهدف الحالي:",
	Target_ID = "معرف الهدف:",
	SelectSwap_CurrentTarget = "حدد للتبديل مع الهدف الحالي:",
	NoNPC_LookNPC = "لم يتم العثور على NPC! انظر إلى NPC للبدء",
	
	-- Locations Categories
	Residences = "المساكن",
	ArasakaAndCorpo = "أراساكا آند كوربو",
	ClubsAndBars = "النوادي والحانات",
	HotelsAndPleasure = "الفنادق والمتعة",
	UndergroundAndCrime = "تحت الأرض والجريمة",
	GovernmentAndSecurity = "الحكومة والأمن",
	StoryAndUnique = "قصة وفريدة من نوعها",
	Ripperdocs = "ريبردوكس",
	LandmarksAndOpenWorld = "المعالم والعالم المفتوح",
	SpoilersAndHidden = "المفسدين والمخفية",
	UserLocations = "مواقع المستخدم",
	
	
	-- >> DECOR TAB
	BeginItem_TabDecor = "ديكور",
	BeginItem_TabPresets = "الإعدادات المسبقة",
	Begin_ComboPresets = "الإعدادات المسبقة",
	
	--Button
	Button_SmallClone = "استنساخ",
	Button_SmallRemove = "إزالة##",
	Button_SmallRename = "إعادة تسمية##",
	Button_SmallUpdate = "تحديث##",
	Button_SmallCancel = "إلغاء",
	Button_Frame = "الإطار",
	
    --Button Label
	Button_LabelHide = "إخفاء",
	Button_LabelUnhide = "إظهار",
	
    --Checkbox
    --Warning / Info / Tool Tip
	Warn_PersistPropSave = "تفرخ الدعائم لتزيين منزلك أو أي مكان تريده بما يرضي قلبك! حفظ الدعائم لجعلها تستمر!",
	Warn_DespawnInProgress_PleaseWait = "التفريغ قيد التقدم. انتظر من فضلك.",
	Warn_PresetsFolder_Info = "يتم حفظ الإعدادات المسبقة للمستخدم في مجلد AppearanceMenuMod/User/Decor",
	Warn_CustomPresets_Info = "يتضمن هذا الإعداد المسبق الدعائم المخصصة",
	Warn_CustomPropsModders_Info = "الدعائم المخصصة التي أدلى بها:",
	Warn_GamepadDirectMode_Info = "يتيح ذلك تكاملًا أفضل مع الوضع المباشر عند استخدام لوحة الألعاب. كما أنه يتيح نافذة معلومات صغيرة تبقى في مكانها.",
	Warn_PresetTriggerDistanceFar = "قد يؤدي التعيين إلى Far إلى حدوث مشكلات في الأداء.",
	
    --Text
	MovingAll_PropsTo_SavedProps = "نقل جميع الدعائم إلى الدعائم المحفوظة",
	SelectPropSpawn = "حدد الدعامة للنشر:",
	Spawned_Props = "الدعائم المتولدة",
	New_Preset = "إعداد مسبق جديد",
	No_Preset_Available = "لا يوجد إعداد مسبق متاح",
	Preset_TriggerDistance = "مسافة الزناد المحددة مسبقًا",
	MovingSavedProps = "نقل %s إلى الدعائم المحفوظة",
	UpdateTag = "تحديث العلامة",
	Categories = "الفئات",
	Decorating = "تزيين",
	Decor_Tabs = "علامات الديكور",
	Saved_Props = "الدعائم المحفوظة",
	Show_Nearby_Only = "إظهار الأماكن القريبة فقط",
	Show_Lights_Only = "عرض الأضواء فقط",
	Show_LockedTarget_Only = "إظهار الهدف المقفل فقط",
	Show_Customizable_Only = "إظهار للتخصيص فقط",
	Show_CustomProps_Only = "إظهار الدعائم المخصصة فقط",
	ShowOnMap = "عرض على الخريطة",
	Rename = "إعادة تسمية",
	Delete = "حذف",
	Backup = "النسخ الاحتياطي",
	Merge = "دمج",
	Save_All = "حفظ الكل",
	Despawn_All = "تخلص من الكل",
	Save_ToSpecific_Tag = "حفظ إلى علامة محددة",
	Saved_Props2 = "الدعائم المحفوظة:",
	Move_To_Tag = "الانتقال إلى العلامة",
	HideFromMap = "إخفاء من الخريطة",
	RemovingAllPropsFromTag = "إزالة جميع الدعائم من العلامة...",
	RemoveAllProps = "إزالة كافة الدعائم",
	RemoveHomeMarkerMap = "إزالة علامة المنزل من الخريطة",
	TeleportToLocation = "النقل الفوري إلى الموقع",
	TeleportToTrigger = "النقل الفضائي إلى الزناد",
	TeleportToMark = "النقل الفضائي إلى مارك",
	UpdateTagLocation = "تحديث موقع العلامة",
	SharePresetWith_ThisTagOnly = "مشاركة الإعداد المسبق مع هذه العلامة فقط",
	SavedPresetFolder_Info = "تم حفظ الإعداد المسبق في مجلد AppearanceMenuMod/User/Decor",
	NoProps_WithThese_Conditions = "لا الدعائم مع هذه الشروط",
	AddHomeMarkerMap = "أضف علامة المنزل إلى الخريطة",
	Distance = "المسافة",
	Total_Props = "إجمالي الدعائم:",
	Type_Tag_here = "اكتب العلامة هنا",
	In_World = "في العالم",
	Tags = "العلامات",
	Tag = "علامة",
	Both = "كلاهما",	
	
	-- >> POSES TAB
	BeginItem_TabPoses = "يطرح",
	
	--Button
	Button_SmallCopyClipboard = "نسخ إلى الحافظة",
	
    --Button Label
    --Checkbox
    --Warning / Info / Tool Tip
    --Text
	Active_Animations = "الرسوم المتحركة النشطة",
	ShowHistory = "عرض التاريخ",
	ClearHistory = "مسح التاريخ",
	SelectPoseForCurrentTarget = "حدد الوضع للهدف الحالي:",
	LastUsedPoses = "آخر الأوضاع المستخدمة",
	
	
	
	-- >> TOOLS TAB
	BeginItem_TabTools = "أدوات",
	BeginItem_TabPhotoModeNibblesReplacer = "وضع الصورة يقضم بديل",
	BeginCombo_LookAt = "انظر الى",
	BeginCombo_WeatherControl = "التحكم في الطقس",
	
	--Button
	Button_SkipFrame = "تخطي الإطار",
	Button_ToggleLight = "تبديل الضوء",
	Button_ResetScale = "إعادة ضبط المقياس",
	Button_ShowAsLookAtTarget = "إظهار كما ننظر إلى الهدف",
	Button_ResetLookAtTarget = "إعادة ضبط النظرة على الهدف",
	Button_TogglePrimaryWeapon = "تجهيز السلاح الأساسي",
	Button_ToggleSecondaryWeapon = "تجهيز سلاح ثانوي",
	Button_GiveCurrentEquippedWeapon = "إعطاء السلاح المجهز الحالي",
	Button_SmallReset = "إعادة تعيين",
	Button_ResetToPlayer = "إعادة تعيين إلى المشغل",
	Button_ClearSaved = "مسح المحفوظة",
	Button_Cyberpsycho = "تبديل Cyberpsycho",
	Button_ProtectNPCfromActions = "حماية NPC من الإجراءات",
	Button_AllFriendly = "كل ودية",
	Button_AllHostile = "كل معادية",
	Button_AllFollower = "كل المتابعين",
	Button_AllFakeDie = "كل يموت وهمية",
	Button_AllDie = "كل يموت",
	Button_AllDespawn = "كل يتلاشى",
	Button_InvMachineGun = "رشاش",
	Button_InvSpeed2 = "السرعة",
	Button_ToggleMakeup = "تبديل الماكياج",
	Button_TogglePiercings = "تبديل الثقب",
	Button_ToggleSeamfix = "تبديل سيمافيكس",
        Button_TargetV = "الهدف الخامس",
        Button_Target = "الهدف",
        Button_TeleportToLocation = "النقل الفوري إلى الموقع",
        Button_TeleportToTrigger = "النقل الفضائي إلى الزناد",
        Button_TeleportToMark = "النقل الفضائي إلى مارك",
        Button_RandomLocation = "عشوائي",
        Button_ShareCurrentLocation = "مشاركة الموقع الحالي",
	Button_GoBackToLastLocation = "العودة إلى الموقع الأخير",
	Button_DeleteSelectedUserLocation = "حذف موقع المستخدم المحدد",
	
	--Slider / Drag 
	Slider_HeadStiffness = "تصلب الرأس",
	Slider_HeadPoseOverride = "تجاوز وضعية الرأس",
	Slider_ChestStiffness = "تصلب الصدر",
	Slider_ChestPoseOverride = "تجاوز وضعية الصدر",
	Slider_SlowMotion = "حركة بطيئة",
	Slider_DefaultAperture = "الفتحة الافتراضية",
	Slider_DefaultFieldofView = "مجال الرؤية الافتراضي",
	Slider_MovementSpeed = "سرعة الحركة",
	Drag_MovementSpeed = "سرعة الحركة",
	
    --Button Label
	Button_Label_PauseTimeProgression = "وقفة تقدم الوقت",
	Button_Label_UnpauseTimeProgression = "إلغاء الإيقاف المؤقت للتقدم الزمني",
	Button_Label_UnfreezeTime = "وقت إلغاء التجميد",
	Button_Label_FreezeTime = "وقت التجميد",
	Button_Label_OpenLightSettings = "افتح إعدادات الضوء",
	Button_Label_UpdateLightTarget = "تحديث الهدف الخفيف",
	Button_Label_Activate = "تفعيل",
	Button_Label_Deactivate = "إلغاء التنشيط",
	Button_Label_ChangeToCrouchStance = "تغيير إلى موقف الرابض",
	Button_Label_ChangeToStandStance = "التغيير إلى الموقف",
	Button_Label_PickUpTarget = "التقاط الهدف",
	Button_Label_DropTarget = "إسقاط الهدف",
	Button_Label_FreezeTarget = "تجميد الهدف",
	Button_Label_UnfreezeTarget = "إلغاء تجميد الهدف",
	Button_Label_OpenTargetTools = "افتح أدوات الهدف",
	Button_Label_CloseTargetTools = "أغلق أدوات الهدف",
	
    --Checkbox
    --Warning / Info / Tool Tip
	Warn_FileNotFound_CollabsFolder_Error = "الملف غير موجود في مجلد Collabs",
	Warn_ShowXYZ_Orientation_Info = "إظهار أسهم X وY وZ لتسهيل التوجيه عند تحريك الهدف.",
	Warn_LookAtCamera_OptionOff_Info = "قم بإيقاف تشغيل خيار Look At Camera مرة واحدة بعد تغيير هذا الإعداد",
	Warn_DisableLookAtCamera_PhotoMode_Info = "قم بتعطيل \"إلقاء نظرة على الكاميرا\" في وضع الصورة مرة واحدة ليصبح ساري المفعول",
	Warn_RequiresRestart_Info = "يتطلب إعادة تشغيل اللعبة لتصبح نافذة المفعول",
	Warn_SlowMotion_PhotoMode_Info = "تعمل الحركة البطيئة في وضع الصور فقط إذا قمت بإلغاء الإيقاف المؤقت باستخدام IGCS",
	Warn_WeatherControl_RequireCodeware = "يتطلب التحكم في الطقس برنامج Codeware 1.4+",
	Warn_StopNpc_UnequipWeapon_Info = "سيؤدي هذا إلى منع NPC من عدم تجهيز سلاحك المحدد. ملاحظة: سيظل المجلس الوطني لنواب الشعب الصيني غير مجهز حسب الرغبة أثناء القتال.",
	Warn_OutOfCombat_NpcUnequip_Info = "ملاحظة: خارج القتال، سيقوم المجلس الوطني لنواب الشعب الصيني بإلغاء تجهيز السلاح المحدد على الفور.",
	Warn_Photomode_UnfreezeSkipFrames_Info = "في وضع الصورة، سيتخطى Unfreeze Target الإطارات في الأوضاع المتحركة. للحصول على وظيفة (إلغاء) التجميد الكاملة، تحتاج إلى استخدام Otis Camera Tools (IGCS).",
	Warn_UserLocationsFolder_Info = "يتم حفظ مواقع المستخدم في مجلد AppearanceMenuMod/User/Locations",
	Warn_SeeMoreAction_Info = "استهدف V أو NPC لرؤية المزيد من الإجراءات",
	Warn_SeeMoreActionProp_Info = "استهدف NPC أو Prop لرؤية المزيد من الإجراءات",
	Warn_SeamfixPiercingToggle_Info = "سيؤدي هذا إلى حفظ حالة تبديل الماكياج والثقب وSeamfix حتى تغلق اللعبة.",
	Warn_PassiveMode_Info = "سيظل الأعداء يهاجمونك إذا قمت ببدء القتال",
	Warn_TppCameraGameplay_Info = "كاميرا TPP ليست مناسبة للعب العادي، ولكنها ممتعة للمشي ;)",
	Warn_AnimatedHead_PhotoMode_Info = "لن تعمل تعبيرات وضع الصورة أثناء تمكين Animated Head.",
	Warn_ToolsOnly_WorksIngame = "الأدوات تعمل فقط في اللعبة",
	Warn_InvButtonMachineGun_Info = "لقد وجدت ذلك! تمت إضافة رشاش ثقيل إلى المعدات.",
	Warn_InvButton_Info = "لقد وجدت ذلك! الحركة السريعة متاحة الآن.",
	InvButtonTip = "ماذا لو قمت بالنقر هنا؟",
	InvButtonTip2 = "النقر هنا لا يفعل شيئا!",
	InvButtonTip3 = "لا تنقر فوق لقد تم تحذيرك!",
	
    --Text
	Facial_Expression = "تعبيرات الوجه",
	Expressions = "التعبيرات",
	Look_At = "انظر الى",
	Look_At_Camera = "انظر إلى الكاميرا:",
	Target_Tools = "أدوات الهدف",
	Rotation = "دوران",
	Tilt_Rotation = "الميل/الدوران",
	Mode = "الوضع:",
	Precision = "الدقة",
	Relative = "نسبي",
	Direct = "مباشر",
	AdvMovement = "ظرف. الحركة",
	ForceGivenWeapon = "القوة المعطاة للسلاح",
	Scale = "مقياس",
	ProportionalMode = "الوضع النسبي",
	General_Actions = "الإجراءات العامة",
	DisablePassiveMode = "تعطيل الوضع السلبي",
	EnablePassiveMode = "تمكين الوضع السلبي",
	EnableGodMode = "تمكين وضع الله",
	DisableGodMode = "تعطيل وضع الله",
	Infinite_Oxygen = "الأكسجين اللامتناهي",
	Select_Location = "حدد الموقع",
	Select_Expression = "حدد التعبير",
	Select_Category = "حدد الفئة",
	Teleport_Actions = "إجراءات النقل الفضائي",
	Use_Teleport_Animation = "استخدم الرسوم المتحركة للنقل الفضائي",
        Filter_Locations = "مواقع التصفية",
        Locations = "المواقع",
        Default_Locations = "المواقع الافتراضية",
        Collab_Locations = "مواقع التعاون",
        Button_AddTag = "إضافة علامة",
	Button_FilterByTags = "تصفية حسب العلامات",
	Button_Close = "إغلاق",
	Favorite_Selected_Location = "الموقع المحدد المفضل",
	Unfavorite_Selected_Location = "الموقع المحدد غير المفضل",
	Edit_Selected_Location = "تحرير الموقع المحدد",
	Locations_Favorites = "--------- المفضلة ----------",
	Locations_UserLocs = "------- مواقع المستخدم -------",
	Locations_DefaultLocs = "----------- الافتراضي ----------",
	Share_Location = "مشاركة الموقع",
	Edit_Location = "تحرير الموقع",
	TimeWeather_Actions = "إجراءات الوقت والطقس",
	TimeofDay = "الوقت من اليوم",
	Time_Actions = "إجراءات الوقت",
	Rain = "المطر",
	Light_Rain = "مطر خفيف",
	Cloudy = "غائم",
	Fog = "ضباب",
	Heavy_Clouds = "السحب الثقيلة",
	Light_Clouds = "الغيوم الخفيفة",
	Pollution = "التلوث",
	Sandstorm = "عاصفة رملية",
	Sunny = "مشمس",
	Toxic_Rain = "المطر السام",
	Deep_Blue = "ديب بلو",
	Squat_Morning = "صباح القرفصاء",
	Cloudy_Morning = "صباح غائم",
	Rainy_Night = "ليلة ممطرة",
	Courier_Clouds = "الغيوم البريدية",
	Cursor_LockState = "حالة القفل",
	PhotoMode_NibblesReplacer = "وضع الصورة يقضم بديل",
	PhotoModeEnhancements = "تحسينات وضع الصورة",
	Button_ResetReplacerDatabase = "إعادة تعيين قاعدة البيانات البديلة",
	DisablePhotoModeCursor = "تعطيل مؤشر وضع الصورة",
	TPPCamera_Position = "موقف كاميرا TPP",
	AnimatedHeadin_PhotoMode = "رأس متحرك في وضع الصورة",
	LockLook_AtCamera = "قفل نظرة على الكاميرا",
	UnlockLook_AtCamera = "فتح نظرة على الكاميرا",
	Save_Toggles_State = "حفظ حالة التبديل",
	Toggle_V_Head = "تبديل رأس V",
	Toggle_TPP_Camera = "تبديل كاميرا TPP",
	Target_Nibbles = "الهدف يقضم",
	Target_Replacer = "بديل الهدف",
	Left = "اليسار",
	Left_Close = "إغلاق اليسار",
	Right = "صحيح",
	Right_Close = "إغلاق صحيح",
	Center_Close = "إغلاق المركز",
	Center_Far = "مركز بعيد",
	Front_Close = "إغلاق أمامي",
	Front_Far = "الجبهة البعيدة",
	All = "الكل",
	Head_Only = "الرأس فقط",
	Eyes_Only = "عيون فقط",
	Movement = "الحركة",
	V_Actions = "إجراءات الخامس",
	Invisible_V = "غير مرئية V",
	LikeGTA_byGTATravel = "بواسطة GTA السفر",
	EnableSpawnedProps = "تمكين الدعائم الناتجة",
	LightControl = "التحكم في الضوء",
	Equipment = "المعدات",
	
	-- >> DIRECTOR TAB
	BeginItem_TabNameDirector = "مدير",
	BeginItem_TabNameTriggers = "المشغلات",
	BeginCombo_StartAppearance = "بدء المظهر",
	BeginCombo_EndAppearance = "نهاية المظهر",
	BeginCombo_Type = "اكتب",
	BeginCombo_GoToTarget = "اذهب إلى الهدف",
	BeginCombo_PlayVoice = "تشغيل الصوت",
	BeginCombo_Attack = "هجوم",
	BeginCombo_Triggers = "المشغلات",
	BeginCombo_Scripts = "البرامج النصية",
	
	--Button
	Button_Yes = "نعم",
	Button_No = "لا",
	Button_SaveChangesOnly = "حفظ التغييرات فقط",
	Button_RemoveMark = "إزالة مارك",
	Button_EditMark = "تحرير مارك",
        Button_MoveMark = "تحرك مارك",
        Button_MoveUp = "تحرك لأعلى",
        Button_MoveDown = "تحرك للأسفل",
        Button_NewMark = "نيو مارك",
	Button_AddActor = "إضافة ممثل",
	Button_RemoveActor = "إزالة الممثل",
	Button_ChangeActor = "تغيير الممثل",
	Button_RadioOnlyOne = "واحد فقط",
	Button_RadioRandom = "عشوائي",
	Button_RadioSequential = "متسلسل",
	Button_SaveTrigger = "حفظ الزناد",
	Button_NewCamera = "كاميرا جديدة",
	Button_NewScript = "البرنامج النصي الجديد",
	Button_DragSpeed = "السرعة",
	Button_ToggleMarker = "تبديل العلامة",
	Button_TestPose = "وضعية الاختبار",
	Button_StopPose = "وقف تشكل",
	
    --Button Label
	Button_Label_PlayScript = "تشغيل البرنامج النصي",
	Button_Label_StopScript = "إيقاف البرنامج النصي",
	Button_Label_Stopping = "جارٍ الإيقاف...",
	Button_Label_Restarting = "جارٍ إعادة التشغيل...",
	Button_Label_AddMark = "أضف مارك",
	Button_Label_SaveWNewPos = "حفظ مع موقف جديد",
	
    --Checkbox
    --Warning / Info / Tool Tip
	Warn_ActorSingleMark_Info = "سيبقى الممثل على علامة واحدة",
	Warn_ActorRandomMark_Info = "سوف يتحرك الممثل بشكل عشوائي بين العلامات",
	Warn_ActorSequentialMark_Info = "سيتنقل الممثل بين العلامات بالترتيب العددي",
	Warn_DeleteScript_Info = "هل أنت متأكد أنك تريد حذف هذا البرنامج النصي؟",
	Warn_CloseCamForMove_Info = "أغلق القائمة لتتمكن من تحريك الكاميرا",
	Warn_CreateScriptsDesc_Info = "أنشئ نصوصًا لإضافة الممثلين وإلباسهم وتوجيههم لأداء الماكينات ولقطات الشاشة ولعب الأدوار.",
	Warn_PremadeScriptsDesc_Info = "قم بإنشاء مشغلات لتنشيط البرامج النصية المعدة مسبقًا على جهة الاتصال.",
	Warn_CreateCamera_FovZoomDesc_Info = "قم بإنشاء كاميرات للتنقل بحرية، وتعيين مجالات مختلفة للعرض ومستويات التكبير/التصغير.",
	Warn_ShowMarksLocations_Info = "يعرض رمزًا مرئيًا في مواقع التحديد",
	Warn_AutoTalkNpc_Info = "سيؤدي ذلك إلى جعل الشخصيات غير القابلة للعب تتحدث مرة واحدة كل دقيقة عندما تكون ضمن النطاق (الشخصيات غير القابلة للعب ذات الصوت فقط)",
	Warn_DirectActorPlayerPosition_Info = "قم بإنشاء علامة في موضع اللاعب الحالي لتحريك الممثلين وتوجيههم",
	Warn_InMenuDirectorDesc = "المدير يعمل فقط داخل اللعبة",
	
    --Text
	DirectorMode = "وضع المدير",
	SelectActorToReplace = "حدد الممثل ليحل محل:",
	AddActorToCurrentScript = "إضافة ممثل إلى البرنامج النصي الحالي:",
	FacialExpression_WithColon = "تعبيرات الوجه:",
	FavoritePoses_WithColon = "الأوضاع المفضلة:",
	AddFavorites_Desc = "أضف الأوضاع إلى المفضلة في علامة التبويب الأوضاع أولاً",
	HoldDuration = "مدة الانتظار",
	Movement2 = "الحركة:",
	Actions = "الإجراءات:",
	Actors = "الجهات الفاعلة",
	Editing = "التحرير",
	AutoTalk = "الحديث التلقائي",
	ActorMarks = "الممثل ماركس",
	Current_Actors = "الجهات الفاعلة الحالية",
	Marks_Sequence = "تسلسل العلامات:",	
	ShowMarks = "إظهار العلامات",
	Triggers = "المشغلات",
	NewTrigger = "الزناد الجديد",
	ShowTrigger = "عرض الزناد",
	Title = "العنوان",
	Select_Trigger = "حدد المشغل",
	Select_Script = "حدد البرنامج النصي",
	Delete_Trigger = "حذف الزناد",
	Triggers_On_Off = "مشغلات تشغيل/إيقاف",
	Running = "الجري",
	Script_Running = "تشغيل البرنامج النصي...",
	Delete_Script = "حذف البرنامج النصي",
	RepeatInLoop = "كرر في الحلقة",
	ActivationRadius = "نصف قطر التنشيط",
	Activate = "تفعيل",
	Deactivate = "إلغاء التنشيط",
	FOV = "مجال الرؤية",
	Zoom = "تكبير",
	LockFrame = "إطار القفل",
	Walk = "المشي",
	Sprint = "سبرينت",
	Sequential = "متسلسل",
	Cameras = "الكاميرات",
	NodeView = "عرض العقدة",
	TeamA = "فريق أ",
	TeamB = "فريق ب",
	
	
	
	-- >> SETTINGS TAB
	BeginItem_TabNameSettings = "الإعدادات",
	BeginItem_TabNameGeneral = "عام",
	BeginItem_TabNameCompanions = "الصحابة",
	BeginItem_TabNameUI = "واجهة المستخدم",
	BeginItem_TabNameExperimental = "تجريبي",
	BeginItem_TabNamePhotoMode = "وضع الصورة",
	
	--Button
	Button_RevertAllModelSwaps = "التراجع عن جميع مقايضات النماذج",
	Button_RespawnAll = "إعادة إحياء الكل",
	Button_ForceDespawnAll = "فرض إلغاء الكل",
	Button_ClearFavorites = "مسح المفضلة",
	Button_ClearAllSavedAppearances = "مسح كافة المظاهر المحفوظة",
	Button_ClearAllBlacklistedAppearances = "مسح كافة المظاهر المدرجة في القائمة السوداء",
	Button_ClearAllAppearanceTriggers = "مسح كافة مشغلات المظهر",
	Button_ClearAllSavedDespawns = "مسح كافة عمليات الإيقاف المحفوظة",
	Button_SmallCreateTheme = "إنشاء موضوع",
	Button_SmallDeleteTheme = "حذف الموضوع",
	Button_SmallSet = "تعيين",
	Button_ReloadAppearances = "إعادة تحميل المظاهر المخصصة",
	
    --Button Label
    --Checkbox
	Checkbox_SpawnAsCompanion = "تفرخ كمرافق",
	Checkbox_SpawnAsFriendly = "تفرخ ودية",
	Checkbox_InvulnerableCompanion = "رفيق لا يقهر",
	Checkbox_RespawnOnLaunch = "إعادة الظهور عند الإطلاق",
	Checkbox_LockTargetAfterSpawn = "قفل الهدف بعد النشر",
	Checkbox_OpenTargetToolsAfterSpawn = "افتح أدوات الهدف بعد النشر",
	Checkbox_DisplayAxisIndicatorByDefault = "عرض مؤشر المحور بشكل افتراضي",
	Checkbox_PhotoModeEnhancements = "تحسينات وضع الصورة",
	Checkbox_GodModeOnLaunch = "وضع الله عند الإطلاق",
	Checkbox_PassiveModeOnLaunch = "الوضع السلبي عند الإطلاق",
	Checkbox_StreamerMode = "وضع غاسل",
	Checkbox_OpenWCETOverlay = "فتح مع تراكب CET",
	Checkbox_AutoResizingWindow = "نافذة تغيير الحجم التلقائي",
	Checkbox_ScanningReticle = "مسح شبكاني",
	Checkbox_FloatingTargetTools = "أدوات الهدف العائمة",
	Checkbox_TabHeaderDescriptions = "أوصاف رأس علامة التبويب",
	Checkbox_ExpandFavoritesByDefault = "قم بتوسيع المفضلة بشكل افتراضي",
	Checkbox_EnableScrollBars = "تمكين أشرطة التمرير",
	Checkbox_AlwaysDisablePhotoModeCursor = "قم دائمًا بتعطيل مؤشر وضع الصورة",
	Checkbox_Camera = "الكاميرا",
	Checkbox_DepthOfField = "شعبة الشؤون المالية",
	Checkbox_Effect = "تأثير",
	Checkbox_Stickers = "ملصقات",
	Checkbox_LoadSave = "تحميل/حفظ",
	Checkbox_ExperimentalFunstuff = "الاشياء التجريبية / الممتعة",
	Checkbox_EnableFreezeTargetInPhotoMode = "تمكين تجميد الهدف في وضع الصورة",
	Checkbox_WeaponizeCompanions = "تسليح الرفاق",
	Checkbox_AllowPlayerToBeTargetedinPosestab = "السماح للاعب بالاستهداف في علامة التبويب \"الوضعيات\".",
	Checkbox_AllowPlayerAnimationsonNPCs = "السماح بالرسوم المتحركة للاعب على الشخصيات غير القابلة للعب",
	Checkbox_AllowExpressionOnNpcPM = "السماح بالتعبيرات والبحث عن الشخصيات غير القابلة للعب في وضع الصورة",
        Checkbox_ResetTargetPositionPM = "إعادة تعيين موضع الهدف للشخصيات غير القابلة للعب في وضع الصورة",
        Checkbox_EnableRandomLocation = "تمكين الزر العشوائي: نقل اللاعب إلى موقع عشوائي من القائمة",
        Checkbox_RestoreOnLaunch = "استعادة عند الإطلاق",
        Radio_PrimarySlot = "الفتحة الأساسية",
        Radio_SecondarySlot = "فتحة ثانوية",
	
    --Warning / Info / Tool Tip
	Warn_RespawnOnLaunch_Info = "سيؤدي هذا الإعداد إلى تمكين/تعطيل إعادة ظهور الشخصيات غير القابلة للعب المحفوظة مسبقًا عند تحميل اللعبة. تقوم AMM تلقائيًا بحفظ الشخصيات غير القابلة للعب التي تم إنشاؤها عند الخروج من اللعبة.",
	Warn_BannedWords_Info = "سيؤدي هذا الإعداد إلى تمكين/تعطيل ظهور الشخصيات غير القابلة للعب (NPC) التي تحتوي على الكلمات: Naked وnude وxxx وshower وbirthday_suit وpp وpene.",
	Warn_TargetNpcVehicleHotkey = "استهدف NPC أو المركبة لتعيين مفاتيح التشغيل السريع",
	Warn_FirstLaunchDecideTabsExpand_Info = "سيؤدي هذا الإعداد إلى توسيع المفضلة في علامات التبويب Spawn وSwap وDecor بشكل افتراضي عند تشغيل AMM لأول مرة.",
	Warn_ExperimentalTabDesc_Info = "تضيف الميزات التجريبية المزيد من الوظائف، ولكنها قد لا تعمل بشكل جيد ومن هنا جاءت التسمية التجريبية. في الواقع، تم تمكين الميزات التجريبية لدى معظم مستخدمي AMM. لذلك لا تقلق كثيرًا واستمتع بوقتك!",
	Warn_FreezeTargetPhotoMode_Info = "يهدف هذا الإعداد إلى المساعدة في تجميد الرسوم المتحركة من التعديلات التي تضيف رسومًا متحركة مخصصة إلى وضع الصور أو عند إلغاء الإيقاف المؤقت باستخدام IGCS.",
	Warn_WeaponizeCompanions_Info = "سيعطي هذا الأسلحة والقدرات القتالية لجميع الشخصيات غير القابلة للعب. من المتوقع ظهور رسوم متحركة على شكل حرف T ورسوم متحركة غريبة.",
	Warn_PlayerAnimsOnNpc_Info = "قم بتمكين هذا إذا كنت تستخدم تعديلًا يسمح باستخدام الرسوم المتحركة للاعب على الشخصيات غير القابلة للعب.",
	Warn_UnpauseRequiresIGSC = "يتطلب هذا الإعداد من IGCS إلغاء الإيقاف المؤقت للوقت.",
	Warn_NotInstalled = "غير مثبتة",
	Warn_DespawnAllProps = "هل أنت متأكد أنك تريد التخلص من جميع الدعائم؟",
	
    --Text
	AMM_Version = "نسخة أم:",
	CET_Version = "نسخة بتوقيت وسط أوروبا:",
	Codeware_Version = "إصدار برنامج التعليمات البرمجية:",
	Game_Version = "نسخة اللعبة:",
	Companion_Damage = "الضرر المرافق:",
	Companion_Resistance = "مقاومة رفيق:",
	Companion_Distance = "مسافة الرفيق:",
	xDamage = "× الضرر",
	xResistance = "× المقاومة",
	SavedAppearancesHotkeys = "مفاتيح التشغيل السريع للمظاهر المحفوظة",
	Favorites = "المفضلة",
	Appearances = "المظاهر",
	Blacklist = "القائمة السوداء",
	AppearanceTriggers = "مشغلات المظهر",
	SavedDespawns = "حالات الرحيل المحفوظة",
	Interface_Language = "لغة الواجهة:",
	Custom_Appearances = "المظاهر المخصصة",
	PhotoModeAdjustments = "تعديلات وضع الصورة:",
	DisablePhotoModeTabs = "تعطيل علامات تبويب وضع الصورة:",
	List_Height = "ارتفاع القائمة",
	Listbox_Themes = "المواضيع",
	Weaponize = "تسليح",
	NoAppearanceSet = "لم يتم تعيين المظهر",
	
	
	
	-- >> EXTRA	
	--Texts, warns, tips, info's, buttons and labels etc.
	Seat_FrontRight = "الجبهة اليمنى",
	Seat_BackRight = "العودة إلى اليمين",
	Seat_FrontLeft = "الجبهة اليسرى",
	Seat_BackLeft = "العودة إلى اليسار",
	Label_Door = "باب",
	Label_Window = "نافذة",

	Close = "إغلاق",
	Far = "بعيدا",
	Moderate = "معتدل",
	
	-- >> Archives Screen
	Warning_MissingRequiredArchives = "AMM يفتقد واحدًا أو أكثر من الأرشيفات المطلوبة. الرجاء تثبيت أي أرشيف مطلوب مفقود في مجلد الأرشيف/الكمبيوتر/التعديل.",
	Warning_MissingOptionalArchives = "AMM يفتقد أرشيفًا واحدًا أو أكثر. هذه اختيارية ولكنها تضيف وظائف إلى AMM. يمكنك تجاهل هذه التحذيرات، ولكن قد لا يعمل AMM بشكل صحيح.",
	
	
	-->> INIT.LUA
	AMMNeedsAttention = "AMM يحتاج إلى الاهتمام",
	MISSING_ARCHIVES = "المحفوظات المفقودة",
	VERSION_INFORMATION = "معلومات الإصدار",
	CREDITS = "الاعتمادات",
	UPDATE_HISTORY = "تحديث التاريخ",
	Updates = "التحديثات",
	MISSING = "مفقود",
	REQUIRED = "مطلوب",
	OPTIONAL = "اختياري",
	WHATS_NEW = "ما هو الجديد", --Line 83 Function Error

	--Button
	Button_Ignorewarningsforthisversion = "تجاهل التحذيرات لهذا الإصدار",
	Button_Credits = "الاعتمادات",
	Button_Cool = "رائع!",

	--Button Label
	Label_SpawnFavorites = "تفرخ المفضلة",
	Label_SwapFavorites = "مبادلة المفضلة",
	Label_FavoriteAppearances = "المظاهر المفضلة",
	Label_Cancel = "إلغاء",

	--Text
	Hotkey_i = "مفتاح التشغيل السريع %i",

	--Node - Function Error(nil value) 
	Top = "أعلى", --Line 116
	Bottom = "أسفل",
	Off = "إيقاف",
	
	--Voice Overs
	Label_GreetV = "تحية V",
	Label_FearFoll = "الخوف فول",
	Label_FearToll = "حصيلة الخوف",
	Label_FearBeg = "الخوف التسول",
	Label_FearRun = "تشغيل الخوف",
	Label_StealthSearch = "البحث الخفي",
	Label_StealthDeath = "الموت الخفي",
	Label_StealthRestore = "استعادة التخفي",
	Label_StealthEnd = "نهاية التخفي",
	Label_CuriousGrunt = "الناخر الغريب",
	Label_GrappleGrunt = "تصارع الناخر",
	Label_Bump = "عثرة",
	Label_VehicleBump = "عثرة السيارة",
	Label_TurretWarning = "تحذير البرج",
	Label_OctantWarning = "تحذير ثماني",
	Label_DroneWarning = "تحذير بدون طيار",
	Label_MechWarning = "تحذير ميكانيكي",
	Label_EliteWarning = "تحذير النخبة",
	Label_CameraWarning = "تحذير الكاميرا",
	Label_EnemyWarning = "تحذير العدو",
	Label_HeavyWarning = "تحذير شديد",
	Label_SniperWarning = "تحذير قناص",
	Label_AnyDamage = "أي ضرر",
	Label_Danger = "خطر",
	Label_CombatStart = "بداية القتال",
	Label_CombatEnd = "نهاية القتال",
	Label_CombatTargetHit = "ضرب الهدف القتالي",
	Label_PedestrianHit = "ضرب المشاة",
	Label_LightHit = "ضربة خفيفة",
	Label_Curse = "لعنة",
	Label_Irritated = "منزعج",
	Label_GrenadeThrow = "رمي قنبلة يدوية",
	Label_Gotakill = "حصلت على القتل!",
	
	--Expressions
	Neutral = "محايد",
	Joy = "الفرح",
	Smile = "ابتسم",
	Sad = "حزين",
	Surprise = "مفاجأة",
	Aggressive = "عدوانية",
	Anger = "الغضب",
	Interested = "مهتم",
	Disinterested = "غير مهتم",
	Disappointed = "بخيبة أمل",
	Disgust = "الاشمئزاز",
	Exertion = "مجهود",
	Nervous = "عصبي",
	Fear = "الخوف",
	Terrified = "مرعوب",
	Pain = "ألم",
	Sleepy = "نعسان",
	Unconscious = "فاقد الوعي",
	Dead = "ميت",

	-- Extra Expressions
	Frown = "عبوس",
	Shocked = "صدمت",
	Annoyed_2 = "منزعج 2",
	Contempt = "ازدراء",
	Irritated = "منزعج",
	Sceptical_1 = "متشكك 1",
	Sceptical_2 = "متشكك 2",
	Annoyed_1 = "منزعج 1",
	Offended = "بالإهانة",
	Disgusted = "مقرف",
	Disappointed_2 = "بخيبة أمل 2",
	Alert = "تنبيه",
	Crying = "البكاء",
	Embarrassed = "بالحرج",
	Humiliated = "إذلال",
	Impatient = "نفاد الصبر",
	Anguished = "معذب",
	Worried = "قلق",
	Guilty = "مذنب",
	Grieving = "الحزن",
	RestrainedAnger = "الغضب المقيد",
	Afraid = "خائف",
	LookingUpAnnoyed = "البحث عن منزعج",
	Offended_2 = "أساء 2",
	Resentful = "مستاء",
	SadExtra = "اضافية حزينة",
	NervousBreath = "التنفس العصبي",
	ScreamingLong = "الصراخ الطويل",
	ScreamingShort = "الصراخ قصير",
	ScaredBreath = "نفسا خائفا",
	CryingPainful = "البكاء مؤلم",
	SelfReflectAnger = "تعكس الذات الغضب",
	IndulgentSmile = "ابتسامة متسامحة",
	Impressed = "أعجب",
	LongSmile = "ابتسامة طويلة",
	ShortSmile = "ابتسامة قصيرة",
	SimpleSmile = "ابتسامة بسيطة",
	Confident = "واثق",
	Relief = "الإغاثة",
	Impressed_2 = "أعجب 2",
	Admiring = "الإعجاب",
	Fascinated = "مفتون",
	RaisedBrows = "الحواجب المرتفعة",
	LookingUpThinking = "البحث عن التفكير",
	LeftGlanceProcessing = "معالجة النظرة اليسرى",
	LeftGlanceCloseUp = "نظرة سريعة على اليسار عن قرب",
	LookingAround = "النظر حولك",
	LookingDownThinking = "النظر إلى أسفل التفكير",
	LookingAroundAlt = "أبحث حول البديل",
	EyesDartFromLeft = "عيون دارت من اليسار",
	EyesDartFromRight = "عيون دارت من اليمين",
	EyesDartToRight = "عيون دارت إلى اليمين",
	LookingLeft = "النظر إلى اليسار",
	LookingUpThinking_2 = "البحث عن التفكير 2",
	RightGlanceProcessing = "معالجة النظرة الصحيحة",
	LookingDown = "النظر إلى الأسفل",
	Left90GlanceClose = "يسار90نظرة سريعة",
	LookingUp = "البحث عن",
	Right90GlanceClose = "اليمين90نظرة قريبة",
	LookingLeftUp = "النظر إلى اليسار",
	LookingRightUp = "النظر للأعلى",
	ReadingDown = "القراءة للأسفل",
	ReadingUp = "القراءة",
	ReadingMiddle = "القراءة المتوسطة",
	FrontCloseGlance = "نظرة قريبة من الأمام",
	WinkLeft = "غمزة اليسار",
	EyeRoll = "لفة العين",
	Squint = "الحول",
	FalseSmile_2 = "الإبتسامة الزائفة 2",
	FalseSmile_1 = "الإبتسامة الزائفة 1",
	ListeningNewInfo = "الاستماع إلى معلومات جديدة",
	WhatDoYouWant = "ماذا تريد",
	Maybe = "ربما",
	SearchingForWords = "البحث عن الكلمات",
	What = "ماذا",
	Where = "أين",
	SureSure = "بالتأكيد بالتأكيد",
	ListenToMe = "استمع لي",
	StopThePolice = "أوقفوا الشرطة",
	HurryUp = "اسرع",
	ShutUp = "اصمت",
	WinkRight = "غمزة الحق",
	MockingSmile = "ابتسامة ساخرة",
	AsymmetricalSmile = "ابتسامة غير متكافئة",
	SarcasticSmile = "ابتسامة ساخرة",
	Sex = "الجنس",
	LipBite_1 = "عض الشفاه 1",
	LipBite_2 = "عض الشفاه 2",
	Moan = "أنين",
	LipBite_3 = "عض الشفاه 3",
	Pout = "العبوس",
	SexySmile = "ابتسامة مثيرة",
	Swallow = "ابتلاع",
	SensualSmile = "الابتسامة الحسية",
	SexScene_1 = "مشهد الجنس 1",
	SexScene_2 = "مشهد الجنس 2",
	Kiss = "قبلة",
	UsingInhaler = "استخدام جهاز الاستنشاق",
	ShortYawn = "التثاؤب القصير",
	Yawn = "التثاؤب",
	Coughing = "السعال",
	Bite = "لدغة",	
	EatingFast = "الأكل بسرعة",
	ShortDrink = "مشروب قصير",
	Drinking = "الشرب",
	FastBite = "لدغة سريعة",
	LongDrink = "مشروب طويل",
	ShortSmoking = "التدخين القصير",
	LongSmoking = "التدخين الطويل",
	Smoking = "التدخين",
	Eating_1 = "الأكل 1",
	Eating_2 = "الأكل 2",
	Eating_3 = "الأكل 3",
	Eating_4 = "الأكل 4",
	Vomit = "القيء",
	BeingRevived = "يتم إحياؤها",
	MalwarePositive = "البرامج الضارة إيجابية",
	MalwareNegative = "البرامج الضارة سلبية",
	MalwareInfected = "البرامج الضارة المصابة",
	FaceMorphActivate = "تنشيط تحويل الوجه",
	LieNetChairSleep = "كذب صافي كرسي النوم",
	LieNetChairBreathe = "استلقي على كرسي صافي للتنفس",
	NetrunnerDeathUnplugged = "Netrunner الموت غير موصول",
	VeryItchyNose = "حكة شديدة في الأنف",
	RollerCoasterNervous = "السفينة الدوارة العصبية",
	Pfft = "بفت",
	Hahaha = "هاهاها",
	Sniff = "شم",
	Ahaaa = "اهاا",
	Heh = "هيه",
	Huh = "هاه",
	Haaa = "هاا",
	Sigh_Lipsync = "تنهد ليبسينك",
	Hmm = "حسنًا",
	Whispering_1 = "الهمس 1",
	Whispering_2 = "الهمس 2",
	ApprovalYes = "الموافقة نعم",
	SubtleYes = "خفية نعم",
	QuickNoShake = "سريع لا يهز",
	FirmYes = "شركة نعم",
	LongNo = "رقم طويل",
	SubtleNo = "رقم دقيق",
	NoContempt = "لا ازدراء",
	NoDisapproval = "لا يوجد رفض",
	FirmNo = "رقم الشركة",
	NoEnthusiastic = "لا متحمس",
	MockingYes = "السخرية نعم",
	EnthusiasticYes = "متحمس نعم",
	AsymmetricalCornerUp = "زاوية غير متكافئة لأعلى",
	CornersUp = "زوايا لأعلى",
	SoftSigh = "تنهد ناعم",
	BreathGasp = "شهقة الأنفاس",
	AssymetricalSneer = "سخرية غير متناظرة",
	CrimpingLips = "تجعيد الشفاه",
	BrowsDown = "الحواجب للأسفل",
	BrowsLeftUp = "الحواجب للأعلى",
	BrowsRightUp = "الحواجب للأعلى",
	BrowsUp = "الحواجب لأعلى",
	ClosedEyes_1 = "عيون مغلقة 1",
	ClosedEyes_2 = "عيون مغلقة 2",
	EyesClosed = "عيون مغلقة",
	LookRight = "انظر إلى اليمين",
	FastBlink = "وميض سريع",
	SlowBlink = "وميض بطيء",
	NormalBlink = "وميض عادي",
	TinyBlink = "وميض صغير",
	HalfBlink = "نصف وميض",
	RegularSaccade = "ساكاد منتظم",
	FrequentSaccade = "ساككاد المتكررة",
	PhotoCloseupEyes = "صور المقربة عيون",
	PhotoCloseupLips = "صور المقربة الشفاه",
	PhotoCloseupHair = "صور مقربة للشعر",
	PhotoCloseupChin = "الصورة المقربة الذقن",
	PhotoCloseupNose = "الصورة المقربة للأنف",
	PhotoCloseup = "الصورة المقربة",
	PhotoCloseupPleased = "الصورة المقربة يسر",
	PhotoCloseupBody = "الصورة المقربة الجسم",
	PhotoCloseupTeeth = "الصورة المقربة للأسنان",
	PhotoCloseupIN = "الصورة المقربة في",
	PhotoCloseupOUT = "الصورة المقربة خارج",
	Bored = "بالملل",
	Charming = "ساحرة",
	Furious = "غاضب",
	Happy = "سعيد",
	Pissed = "سكران",
	Pleased = "يسر",
	Scared = "خائفة",
	Surprised = "متفاجئ",
	Sadness = "الحزن",
	Whistling = "صفير",
	Singing_1 = "الغناء 1",
	Singing_2 = "الغناء 2",
	Singing_3 = "الغناء 3",
	Alerted = "تم التنبيه",
	Hit_1 = "ضرب 1",
	Hit_2 = "ضرب 2",
	Wounded = "جريح",
	Death = "الموت",

	-- Expressions Category
	Negative = "سلبي",
	Positive = "إيجابي",
	Contemplative = "تأملي",
	Social = "اجتماعي",
	Sexual = "جنسي",
	Action = "العمل",
	Vocal = "صوتي",
	Yes_N_No = "نعم و لا",
	Nuance = "فارق بسيط",
	Static = "ثابت",
	Combat = "القتال",
	
	--Props
	AMM_Props_Desc = "يضيف الدعائم والشخصيات والمركبات. لن يتم إطلاق AMM بدون هذا.",
	AMM_JohnnyCompanion_Desc = "يضيف جوني سيلفرهاند كشخصية قابلة للنشر.",
	AMM_ScenesPack_Desc = "يضيف 9358 مشهدًا متحركًا إلى نظام الوضعيات.\nقم بتنزيله على صفحة Nexus الخاصة بـ AMM.",
	AMM_SoundPack_Desc = "يضيف تأثيرات صوتية قابلة للنشر.",
	AMM_KerryPP_Desc = "يضيف مظهرًا عاريًا جديدًا.",
	AMM_BenjaminStonePP_Desc = "يضيف مظهرًا عاريًا جديدًا.",
	AMM_RiverPP_Desc = "يضيف مظهرًا عاريًا جديدًا.",
	AMM_YorinobuPP_Desc = "يضيف مظهرًا عاريًا جديدًا.",
	AMM_LizzyIncognito_Desc = "يضيف مظهرا جديدا.",
	AMM_MeredithXtra_Desc = "يضيف مظهرا جديدا.",
	AMM_DelamainFix_Desc = "يضيف كامل الجسم إلى ديلامين.",
	AMM_HanakoNoMakeup_Desc = "يسمح لـ AMM بإزالة مكياج Hanako عند استخدام المظهر المخصص.",
	AMM_JudyBodyRevamp_Desc = "يستبدل جسد جودي بجسم جديد محسن.",
	AMM_PanamBodyRevamp_Desc = "يستبدل جسد بانام بجسم جديد محسن.",
	AMM_MistyBodyRevamp_Desc = "يستبدل جسد ميستي بجسم جديد محسن.\nقم بتنزيله على صفحة Nexus الخاصة بـ AMM.",
	AMM_1VesHanakoFixedBodyNaked_Desc = "يستبدل جسد هاناكو بجسم جديد محسن.",
	AMM_PinkyDudeANIMFacialExpressionsFemV_Desc = "تمكين أدوات تعبيرات الوجه على Female V",
	AMM_PinkyDudeANIMFacialExpressionsMaleV_Desc = "تمكين أدوات تعبيرات الوجه على Male V",
	AMM_DinoTattooFixArchive_Desc = "يستبدل الشبكة والملمس.",
	AMM_SongbirdBodyFixArchive_Desc = "يستبدل الجسم لإصلاح المنطقة الرمادية. ليست مثالية بعد.",
	AMM_RitaWheelerCombatEnablerArchive_Desc = "يستبدل ملف الكيان لتمكين الرسوم المتحركة القتالية.",
	AMM_CheriAppearances_Desc = "يضيف مظاهر جديدة. قم بتنزيله على صفحة Nexus الخاصة بـ AMM.",
	AMM_BryceNaked_Desc = "يضيف مظهرًا عاريًا جديدًا. قم بتنزيله على صفحة Nexus الخاصة بـ AMM.",
	AMM_EvelynNaked_Desc = "يصلح جسدها ليسمح بمظهره العاري. قم بتنزيله على صفحة Nexus الخاصة بـ AMM.",
	AMM_SaburoAppearances_Desc = "يضيف مظاهر جديدة. قم بتنزيله على صفحة Nexus الخاصة بـ AMM.",
	AMM_TbugAppearances_Desc = "يضيف مظاهر جديدة. قم بتنزيله على صفحة Nexus الخاصة بـ AMM.",
	AMM_8ug8eagAppearances_Desc = "يضيف مظاهر جديدة. قم بتنزيله على صفحة Nexus الخاصة بـ AMM.",
	
	--Equipments (There is a Function Error(nil value) in this section, These are just labels that are not connected to any localizable strings in the file)
	Fists = "القبضات", --Line 2377 
	Katana = "كاتانا",
	Mantis_Blades = "شفرات السرعوف",
	Machete = "المنجل",
	Hammer = "مطرقة",
	Baton = "باتون",
	Knife = "سكين",
	Crowbar = "المخل",
	Baseball_Bat = "مضرب البيسبول",
	Assault_Rifle = "بندقية هجومية",
	Sidewinder = "سايدويندر",
	Sniper_Rifle = "بندقية قنص",
	Shotgun = "بندقية",
	SMG = "إس إم جي",
	Handgun = "مسدس", --Line 2391
	
	--Warning / Info / Tooltip
	Warn_CantSave_BlacklistedAppearance = "لا يمكنك حفظ مظهر مدرج في القائمة السوداء!",
	Warn_ConfirmDeleteSavedAppearances = "هل أنت متأكد أنك تريد حذف جميع المظاهر المحفوظة؟",
	Warn_ConfirmDeleteBlacklistedAppearances = "هل أنت متأكد أنك تريد حذف جميع المظاهر المدرجة في القائمة السوداء؟",
	Warn_ConfirmDeleteSavedDespawns = "هل أنت متأكد من رغبتك في حذف جميع عمليات الإحباط المحفوظة؟",
	Warn_ConfirmDeleteAppearanceTriggers = "هل أنت متأكد أنك تريد حذف جميع محفزات المظهر لديك؟",
	Warn_ConfirmDeleteCurrentAppearance = "هل أنت متأكد أنك تريد حذف الإعداد المسبق النشط الحالي الخاص بك؟",
	Warn_WeaponizeNpcAnimationIssues = "لن يكون لدى كل الشخصيات غير القابلة للعب الرسوم المتحركة اللازمة لاستخدام كل أنواع الأسلحة. قد تحدث حركات على شكل حرف T ورسوم متحركة غير صحيحة.\nهل أنت متأكد أنك تريد تمكينه؟",
	Warn_ConfirmEnableExperimentalAndSave_Info = "هل أنت متأكد أنك تريد تمكين الميزات التجريبية؟ قد لا تعمل AMM كما هو متوقع. استخدامه على مسؤوليتك الخاصة!",
	Warn_DeleteFavoritesAskWhichOne_Info = "إذا كنت متأكدًا من رغبتك في حذف جميع مفضلاتك، فاختر أيًا منها أدناه:",
	Popup_Error_Title = "خطأ",
	Button_Ok = "حسنًا",
	Popup_FavoriteName = "الاسم المفضل",
	Popup_RenamePreset = "إعادة تسمية الإعداد المسبق",
	Popup_RenameProp = "إعادة تسمية الدعامة",
	Editor_Title = "محرر الموضوع",
	Editor_Field_ThemeName = "اسم الموضوع",
	Editor_Hint_InsertThemeName = "أدخل اسم الموضوع الجديد",
	Error_ThemeNameExists = "اسم الموضوع موجود بالفعل",
}
