return {

    -- >> SCAN TAB
	BeginItem_TabNameScan = "Sken",
	
	--Button
	Button_CyclesAppearances = "Vzhled cyklu",
	Button_SavesAppearance = "Uložit vzhled",
	Button_ClearSavedAppearance = "Vymazat uložený vzhled",
	Button_UnlockDoor = "Přepnout zámek dveří",
	Button_RestoreAccess = "Obnovit přístup",
	Button_UnlockVehicle = "Odemkněte vozidlo",
	Button_RepairVehicle = "Oprava vozidla",
	Button_OpenCloseDoors = "Otevřít/zavřít dveře",
	Button_OpenCloseWindows = "Otevřít/Zavřít Windows",
	Button_ToggleEngine = "Přepnout motor",
	Button_ToggleAIDriver = "Přepnout ovladač AI",
	Button_ToggleCamera = "Přepnout fotoaparát",
	Button_ToggleRadio = "Přepnout rádio",
	Button_NextRadioStation = "Další rozhlasová stanice",
	Button_TargetMountedVehicle = "Cílové montované vozidlo",
	Button_AssignSeats = "Přiřadit sedadla",
	Button_Assign = "Přiřadit",
	Button_Reset = "Resetovat",
	Button_FakeDie = "Fake Die",
	Button_SmallCopy = "Kopírovat",
	
    --Button Label
	Button_Label_Unfollower = "Přestat sledovat",
	Button_Label_Follower = "Následovník",
	Button_Label_SaveDespawn = "Zachraňte Despawna",
	Button_Label_ClearSavedDespawn = "Clear Saved Despawn",
	Button_LabelLockTarget = "Zamknout cíl",
	Button_LabelUnlockTarget = "Odemknout cíl",
	Label_AddToSpawnFavs = "Přidat k Spawnable Favorites",
	Label_RemoveFromSpawnFavs = "Odebrat z oblíbených položek",
	
    --Checkbox
	Checkbox_SavedDespawnsActive = "Uložené despawny jsou aktivní",
	Checkbox_KeepAssigned = "Mějte přiřazeno při výměně auta",
	
    --Warning / Info / Tool Tip
	WarnTextAI_FastTravel = "Vyberte si na mapě bod rychlého cestování a vydejte se",
	WarnText_DontReloadMods = "Nepoužívejte Reload All Mods.\nZnovu načtěte uloženou hru nebo se přesuňte do jiné oblasti.",
	Warning_NoTarget_Desc = "Žádný cíl! Pro začátek se podívejte na NPC, Vozidlo nebo Objekt",
	ToolTip_DisableCheckboxReloadSave_AbleTotargetClearSavedDespawns = "Deaktivujte toto zaškrtávací políčko a znovu načtěte své uložení, abyste mohli cílit na Clear Saved Despawns",
	
    --Text
	Build_Mode = "Režim sestavení",
	Speed = "rychlost:",
	Search = "Hledat",
	Clear = "Vymazat",
	Player = "Hráč",
	Saved = "Uloženo",
	Saved_ = "Uloženo_",
	Current = "Aktuální",
	Current_ = "Aktuální",
	Select_Seat = "Vyberte Sedadlo",
	Target_Info = "Informace o cíli",
	Target_Actions = "Cílové akce",
	No_Appearances = "Žádné zjevení",
	No_Target = "Žádný cíl",
	Favorite_Appearance = "Oblíbený vzhled",
	Unfavorite_Appearance = "Neoblíbený vzhled",
	Blacklist_Appearance = "Vzhled černé listiny",
	Unblacklist_Appearance = "Odstranění černé listiny",
	Saved_Appearance = "Uložený vzhled:",
	Current_Appearance = "Aktuální vzhled:",
	List_of_Appearances = "Seznam vystoupení",
	Appearance_Trigger = "Spouštěč vzhledu",
	None = "žádný",
	Default = "Výchozí",
	Zone = "Zóna",
	Area = "Oblast",
	Position = "Pozice",

	
	-- >> SPAWN TAB
	BeginItem_TabNameSpawn = "Spawn",
	
	--Button
	Button_Refresh = "Obnovit",
	Button_Save = "Uložit",
	Button_Confirm = "Potvrďte",
	Button_Cancel = "Zrušit",
	Button_SmallSave = "Uložit",
	Button_SmallRespawn = "Respawn",
	Button_SmallDespawn = "Despawn",
	Button_SmallDespawn_WithSpace = "Despawn",
	Button_SmallTarget = "Cíl",
	Button_SmallEquipment = "Vybavení",
	Button_LabelHostile = "Nepřátelský",
	Button_LabelFriendly = "Přátelský",
	
    --Button Label
	Label_Favorite = "Oblíbené",
	Label_Unfavorite = "Neoblíbené",
	
    --Checkbox
    --Warning / Info / Tool Tip
	Warn_PlayerInMenu = "Přehrávač v nabídce",
	Warn_AMMonlyfunctions_ingame = "AMM funguje pouze ve hře",
	Warn_SpawnWorksInGame = "Spawnování funguje pouze ve hře",
	Warn_InitError = "Chyba inicializace",
	Warn_InitError_Info = "Další informace naleznete v AppearanceMenuMod.log.",
	
    --Text
	Active_Spawns = "Aktivní spawny",
	NoActiveSpawns = "Žádné aktivní spawny",
	Select_To_Spawn = "Vyberte To Spawn",
	No_Results = "Žádné výsledky",
	ItsEmpty = "Je prázdný :(",
	Existing_Name = "Stávající název",
	Name = "Jméno",
	
	
	
	-- >> SWAP TAB
	BeginItem_TabNameSwap = "Výměna",
	
	--Button
	Button_SmallRevert = "Vrátit zpět",
	
    --Button Label
    --Checkbox
    --Warning / Info / Tool Tip
	Warn_ReloadSaveUpdateChanges = "Znovu načtěte uloženou hru a aktualizujte změny!",
	Warn_NeedReloadSaveUpdateChanges = "Chcete-li aktualizovat změny, budete muset znovu načíst uložení.",
	Warn_ReplacerSwap = "Nemůžete vyměnit náhražku! Pomocí karty nástrojů v režimu fotografie je zaměřte a poté přepněte jejich vzhled z karty Spawn nebo Target Tools.",
	Warning = "VAROVÁNÍ",
	Warning2 = "VAROVÁNÍ:",
	SaveSwap_Tooltip = "Uložte si swapy, abyste je uchovali i po opětovném načtení hry.",
	
    --Text
	CantSwapReplacer = "Nelze vyměnit náhradní",
	Active_Model_Swaps = "Aktivní výměna modelu",
	Save = "Uložit",
	Restore = "Obnovit",
	Current_Target = "Aktuální cíl:",
	Target_ID = "ID cíle:",
	SelectSwap_CurrentTarget = "Vyberte pro výměnu s aktuálním cílem:",
	NoNPC_LookNPC = "Nebylo nalezeno žádné NPC! Pro začátek se podívejte na NPC",
	
	-- Locations Categories
	Residences = "Rezidence",
	ArasakaAndCorpo = "Arasaka & Corpo",
	ClubsAndBars = "Kluby a bary",
	HotelsAndPleasure = "Hotely a potěšení",
	UndergroundAndCrime = "Underground & Crime",
	GovernmentAndSecurity = "Vláda a bezpečnost",
	StoryAndUnique = "Příběh a jedinečný",
	Ripperdocs = "Ripperdocs",
	LandmarksAndOpenWorld = "Památky a otevřený svět",
	SpoilersAndHidden = "Spoilery a skryté",
	UserLocations = "Umístění uživatelů",
	
	
	-- >> DECOR TAB
	BeginItem_TabDecor = "Dekor",
	BeginItem_TabPresets = "Předvolby",
	Begin_ComboPresets = "Předvolby",
	
	--Button
	Button_SmallClone = "Klonovat",
	Button_SmallRemove = "Odebrat##",
	Button_SmallRename = "Přejmenovat##",
	Button_SmallUpdate = "Aktualizace ##",
	Button_SmallCancel = "Zrušit",
	Button_Frame = "Rám",
	
    --Button Label
	Button_LabelHide = "Skrýt",
	Button_LabelUnhide = "Odkrýt",
	
    --Checkbox
    --Warning / Info / Tool Tip
	Warn_PersistPropSave = "Spawn Props pro výzdobu vašeho domu nebo kdekoli, kde chcete, podle vašeho srdce! Uložte rekvizity, aby přetrvávaly!",
	Warn_DespawnInProgress_PleaseWait = "Despawn In Progress. Počkejte prosím.",
	Warn_PresetsFolder_Info = "Uživatelské předvolby jsou uloženy ve složce AppearanceMenuMod/User/Decor",
	Warn_CustomPresets_Info = "Tato předvolba zahrnuje vlastní rekvizity",
	Warn_CustomPropsModders_Info = "Vlastní rekvizity od:",
	Warn_GamepadDirectMode_Info = "To umožňuje lepší integraci s Direct režimem při použití gamepadu. Umožňuje také malé informační okno, které se drží kolem.",
	Warn_PresetTriggerDistanceFar = "Nastavení na Daleko může způsobit problémy s výkonem.",
	
    --Text
	MovingAll_PropsTo_SavedProps = "Přesouvání všech rekvizit do uložených rekvizit",
	SelectPropSpawn = "Vyberte Prop To Spawn:",
	Spawned_Props = "Spawned Props",
	New_Preset = "Nová předvolba",
	No_Preset_Available = "Není k dispozici žádná předvolba",
	Preset_TriggerDistance = "Přednastavená vzdálenost spouštění",
	MovingSavedProps = "Přesouvání %s do uložených rekvizit",
	UpdateTag = "Aktualizovat značku",
	Categories = "Kategorie",
	Decorating = "Zdobení",
	Decor_Tabs = "Dekorační záložky",
	Saved_Props = "Uložené rekvizity",
	Show_Nearby_Only = "Zobrazit pouze v okolí",
	Show_Lights_Only = "Zobrazit pouze světla",
	Show_LockedTarget_Only = "Zobrazit pouze zamčený cíl",
	Show_Customizable_Only = "Zobrazit pouze přizpůsobitelné",
	Show_CustomProps_Only = "Zobrazit pouze vlastní rekvizity",
	ShowOnMap = "Zobrazit na mapě",
	Rename = "Přejmenovat",
	Delete = "Smazat",
	Backup = "Zálohování",
	Merge = "Sloučit",
	Save_All = "Uložit vše",
	Despawn_All = "Despawn All",
	Save_ToSpecific_Tag = "Uložit do konkrétní značky",
	Saved_Props2 = "Uložené rekvizity:",
	Move_To_Tag = "Přesunout na značku",
	HideFromMap = "Skrýt z mapy",
	RemovingAllPropsFromTag = "Odebírání všech rekvizit ze štítku...",
	RemoveAllProps = "Odebrat všechny rekvizity",
	RemoveHomeMarkerMap = "Odebrat značku domova z mapy",
	TeleportToLocation = "Teleportovat na místo",
	TeleportToTrigger = "Teleport ke spouštění",
	TeleportToMark = "Teleport k Markovi",
	UpdateTagLocation = "Aktualizujte umístění značky",
	SharePresetWith_ThisTagOnly = "Sdílet předvolbu pouze s touto značkou",
	SavedPresetFolder_Info = "Předvolba byla uložena do složky AppearanceMenuMod/User/Decor",
	NoProps_WithThese_Conditions = "Žádné rekvizity s těmito podmínkami",
	AddHomeMarkerMap = "Přidat značku domova na mapu",
	Distance = "Vzdálenost",
	Total_Props = "Celkový počet rekvizit:",
	Type_Tag_here = "Zde zadejte Tag",
	In_World = "Ve světě",
	Tags = "Tagy",
	Tag = "Tag",
	Both = "Obojí",	
	
	-- >> POSES TAB
	BeginItem_TabPoses = "pózy",
	
	--Button
	Button_SmallCopyClipboard = "Kopírovat do schránky",
	
    --Button Label
    --Checkbox
    --Warning / Info / Tool Tip
    --Text
	Active_Animations = "Aktivní animace",
	ShowHistory = "Zobrazit historii",
	ClearHistory = "Vymazat historii",
	SelectPoseForCurrentTarget = "Vyberte pozici pro aktuální cíl:",
	LastUsedPoses = "Naposledy použité pózy",
	
	
	
	-- >> TOOLS TAB
	BeginItem_TabTools = "Nástroje",
	BeginItem_TabPhotoModeNibblesReplacer = "Foto režim Nibbles Replacer",
	BeginCombo_LookAt = "Podívejte se na",
	BeginCombo_WeatherControl = "Ovládání počasí",
	
	--Button
	Button_SkipFrame = "Přeskočit snímek",
	Button_ToggleLight = "Přepnout světlo",
	Button_ResetScale = "Resetovat měřítko",
	Button_ShowAsLookAtTarget = "Show As Look At Target",
	Button_ResetLookAtTarget = "Resetovat pohled na cíl",
	Button_TogglePrimaryWeapon = "Vybavte primární zbraní",
	Button_ToggleSecondaryWeapon = "Vybavte sekundární zbraň",
	Button_GiveCurrentEquippedWeapon = "Dejte aktuální vybavenou zbraň",
	Button_SmallReset = "Resetovat",
	Button_ResetToPlayer = "Obnovit na přehrávač",
	Button_ClearSaved = "Vymazat Uloženo",
	Button_Cyberpsycho = "Přepnout Cyberpsycho",
	Button_ProtectNPCfromActions = "Chraňte NPC před akcemi",
	Button_AllFriendly = "Vše přátelské",
	Button_AllHostile = "Všichni nepřátelští",
	Button_AllFollower = "Všichni sledující",
	Button_AllFakeDie = "All Fake Die",
	Button_AllDie = "Všichni zemřou",
	Button_AllDespawn = "Všichni Despawn",
	Button_InvMachineGun = "Kulomet",
	Button_InvSpeed2 = "Rychlost",
	Button_ToggleMakeup = "Přepnout make-up",
	Button_TogglePiercings = "Přepnout piercingy",
	Button_ToggleSeamfix = "Přepnout Seamfix",
        Button_TargetV = "Cíl V",
        Button_Target = "Cíl",
        Button_TeleportToLocation = "Teleportovat na místo",
        Button_TeleportToTrigger = "Teleport ke spouštění",
        Button_TeleportToMark = "Teleport k Markovi",
        Button_RandomLocation = "Náhodné",
        Button_ShareCurrentLocation = "Sdílet aktuální polohu",
	Button_GoBackToLastLocation = "Přejít zpět na poslední místo",
	Button_DeleteSelectedUserLocation = "Smazat vybrané umístění uživatele",
	
	--Slider / Drag 
	Slider_HeadStiffness = "Ztuhlost hlavy",
	Slider_HeadPoseOverride = "Přepsání pozice hlavy",
	Slider_ChestStiffness = "Ztuhlost hrudníku",
	Slider_ChestPoseOverride = "Přepsání pozice hrudníku",
	Slider_SlowMotion = "Zpomalený pohyb",
	Slider_DefaultAperture = "Výchozí clona",
	Slider_DefaultFieldofView = "Výchozí zorné pole",
	Slider_MovementSpeed = "Rychlost pohybu",
	Drag_MovementSpeed = "Rychlost pohybu",
	
    --Button Label
	Button_Label_PauseTimeProgression = "Pozastavit časový průběh",
	Button_Label_UnpauseTimeProgression = "Zrušit pozastavení časového průběhu",
	Button_Label_UnfreezeTime = "Unfreeze Time",
	Button_Label_FreezeTime = "Čas zmrazení",
	Button_Label_OpenLightSettings = "Otevřete Nastavení světla",
	Button_Label_UpdateLightTarget = "Aktualizujte světelný cíl",
	Button_Label_Activate = "Aktivovat",
	Button_Label_Deactivate = "Deaktivovat",
	Button_Label_ChangeToCrouchStance = "Změnit na skrčený postoj",
	Button_Label_ChangeToStandStance = "Změňte postoj ve stoje",
	Button_Label_PickUpTarget = "Vyzvednout cíl",
	Button_Label_DropTarget = "Drop Target",
	Button_Label_FreezeTarget = "Zmrazit cíl",
	Button_Label_UnfreezeTarget = "Rozmrazit cíl",
	Button_Label_OpenTargetTools = "Otevřete Target Tools",
	Button_Label_CloseTargetTools = "Zavřete cílové nástroje",
	
    --Checkbox
    --Warning / Info / Tool Tip
	Warn_FileNotFound_CollabsFolder_Error = "soubor nebyl nalezen ve složce Collabs",
	Warn_ShowXYZ_Orientation_Info = "Zobrazte šipky X, Y a Z pro snazší orientaci při pohybu cíle.",
	Warn_LookAtCamera_OptionOff_Info = "Po změně tohoto nastavení jednou vypněte možnost Pohled na fotoaparát",
	Warn_DisableLookAtCamera_PhotoMode_Info = "Jednou deaktivujte funkci „Podívejte se na fotoaparát“ v režimu Foto, aby se projevila",
	Warn_RequiresRestart_Info = "Vyžaduje restart hry, aby se projevil",
	Warn_SlowMotion_PhotoMode_Info = "Zpomalený pohyb v režimu Foto funguje pouze v případě, že zrušíte pozastavení pomocí IGCS",
	Warn_WeatherControl_RequireCodeware = "Weather Control vyžaduje Codeware 1.4+",
	Warn_StopNpc_UnequipWeapon_Info = "Tím zabráníte NPC odvybavit vaši danou zbraň. Poznámka: NPC se bude během boje stále libovolně vybavovat.",
	Warn_OutOfCombat_NpcUnequip_Info = "Poznámka: Mimo boj NPC okamžitě vybaví danou zbraň.",
	Warn_Photomode_UnfreezeSkipFrames_Info = "V režimu fotografie bude Unfreeze Target přeskakovat snímky v animovaných pózách. Pro plnou funkci (un)freeze musíte použít Otis Camera Tools (IGCS).",
	Warn_UserLocationsFolder_Info = "Umístění uživatelů se ukládají do složky AppearanceMenuMod/User/Locations",
	Warn_SeeMoreAction_Info = "Zacilte na V nebo NPC, abyste viděli více akcí",
	Warn_SeeMoreActionProp_Info = "Zacilte na NPC nebo rekvizitu, abyste viděli více akcí",
	Warn_SeamfixPiercingToggle_Info = "Tím se uloží stav přepínání Makeup, Piercing a Seamfix, dokud hru nezavřete.",
	Warn_PassiveMode_Info = "Nepřátelé na vás budou stále útočit, pokud spustíte boj",
	Warn_TppCameraGameplay_Info = "TPP Camera není vhodná pro běžné hraní, ale je to zábava na procházku ;)",
	Warn_AnimatedHead_PhotoMode_Info = "Když je zapnutá animovaná hlava, výrazy režimu fotografie nebudou fungovat.",
	Warn_ToolsOnly_WorksIngame = "Nástroje fungují pouze ve hře",
	Warn_InvButtonMachineGun_Info = "Našli jste to! Těžký kulomet byl přidán do vybavení.",
	Warn_InvButton_Info = "Našli jste to! Fast Motion je nyní k dispozici.",
	InvButtonTip = "Co když kliknu sem?",
	InvButtonTip2 = "Kliknutí sem nic neudělá!",
	InvButtonTip3 = "NEKLIKNĚTE, BYLI JSTE VAROVÁNI!",
	
    --Text
	Facial_Expression = "Výraz obličeje",
	Expressions = "Výrazy",
	Look_At = "Podívejte se na",
	Look_At_Camera = "Podívejte se na kameru:",
	Target_Tools = "Cílové nástroje",
	Rotation = "Rotace",
	Tilt_Rotation = "Náklon/rotace",
	Mode = "režim:",
	Precision = "Přesnost",
	Relative = "Relativní",
	Direct = "Přímý",
	AdvMovement = "Adv. Pohyb",
	ForceGivenWeapon = "Vynucení dané zbraně",
	Scale = "Měřítko",
	ProportionalMode = "Proporcionální režim",
	General_Actions = "Obecné akce",
	DisablePassiveMode = "Zakázat pasivní režim",
	EnablePassiveMode = "Povolit pasivní režim",
	EnableGodMode = "Povolte režim Boha",
	DisableGodMode = "Zakázat režim Boha",
	Infinite_Oxygen = "Nekonečný kyslík",
	Select_Location = "Vyberte Umístění",
	Select_Expression = "Vyberte Výraz",
	Select_Category = "Vyberte kategorii",
	Teleport_Actions = "Akce teleportu",
	Use_Teleport_Animation = "Použijte animaci teleportu",
        Filter_Locations = "Filtrovat umístění",
        Locations = "Místa",
        Default_Locations = "Výchozí umístění",
        Collab_Locations = "Místa spolupráce",
        Button_AddTag = "Přidat značku",
	Button_FilterByTags = "Filtrovat podle značek",
	Button_Close = "Zavřít",
	Favorite_Selected_Location = "Oblíbené vybrané místo",
	Unfavorite_Selected_Location = "Odebrat z oblíbených vybraných míst",
	Edit_Selected_Location = "Upravit vybrané umístění",
	Locations_Favorites = "--------- Oblíbené ----------",
	Locations_UserLocs = "------- Umístění uživatelů -------",
	Locations_DefaultLocs = "----------- Výchozí ----------",
	Share_Location = "Sdílejte polohu",
	Edit_Location = "Upravit místo",
	TimeWeather_Actions = "Akce s časem a počasím",
	TimeofDay = "Denní doba",
	Time_Actions = "Časové akce",
	Rain = "déšť",
	Light_Rain = "Slabý déšť",
	Cloudy = "Zataženo",
	Fog = "mlha",
	Heavy_Clouds = "těžké mraky",
	Light_Clouds = "lehké mraky",
	Pollution = "Znečištění",
	Sandstorm = "písečná bouře",
	Sunny = "Slunečno",
	Toxic_Rain = "Toxický déšť",
	Deep_Blue = "Tmavě modrá",
	Squat_Morning = "Squat Ráno",
	Cloudy_Morning = "Zataženo ráno",
	Rainy_Night = "Deštivá noc",
	Courier_Clouds = "Kurýrní mraky",
	Cursor_LockState = "Stav uzamčení",
	PhotoMode_NibblesReplacer = "Foto režim Nibbles Replacer",
	PhotoModeEnhancements = "Vylepšení fotografického režimu",
	Button_ResetReplacerDatabase = "Resetujte databázi Replacer",
	DisablePhotoModeCursor = "Zakázat kurzor režimu fotografie",
	TPPCamera_Position = "Pozice kamery TPP",
	AnimatedHeadin_PhotoMode = "Animovaná hlava ve fotografickém režimu",
	LockLook_AtCamera = "Zamknout Pohled Na Fotoaparát",
	UnlockLook_AtCamera = "Odemknout pohled na fotoaparát",
	Save_Toggles_State = "Uložit přepne stav",
	Toggle_V_Head = "Přepnout V hlavu",
	Toggle_TPP_Camera = "Přepnout fotoaparát TPP",
	Target_Nibbles = "Target Nibbles",
	Target_Replacer = "Target Replacer",
	Left = "Vlevo",
	Left_Close = "Vlevo Zavřít",
	Right = "Správně",
	Right_Close = "Vpravo Zavřít",
	Center_Close = "Zavřít střed",
	Center_Far = "Střed daleko",
	Front_Close = "Přední Zavřít",
	Front_Far = "Přední Dál",
	All = "všechny",
	Head_Only = "Pouze hlava",
	Eyes_Only = "Pouze oči",
	Movement = "Pohyb",
	V_Actions = "V Akce",
	Invisible_V = "Neviditelný V",
	LikeGTA_byGTATravel = "od GTA Travel",
	EnableSpawnedProps = "Povolit Spawned Props",
	LightControl = "Ovládání světla",
	Equipment = "Vybavení",
	
	-- >> DIRECTOR TAB
	BeginItem_TabNameDirector = "ředitel",
	BeginItem_TabNameTriggers = "Spouštěče",
	BeginCombo_StartAppearance = "Spustit vzhled",
	BeginCombo_EndAppearance = "Konec vzhledu",
	BeginCombo_Type = "Typ",
	BeginCombo_GoToTarget = "Přejít k cíli",
	BeginCombo_PlayVoice = "Přehrát hlas",
	BeginCombo_Attack = "Útok",
	BeginCombo_Triggers = "Spouštěče",
	BeginCombo_Scripts = "Skripty",
	
	--Button
	Button_Yes = "Ano",
	Button_No = "Ne",
	Button_SaveChangesOnly = "Uložit pouze změny",
	Button_RemoveMark = "Odebrat značku",
	Button_EditMark = "Upravit Mark",
        Button_MoveMark = "Přesuňte Marka",
        Button_MoveUp = "Posunout nahoru",
        Button_MoveDown = "Přesunout dolů",
        Button_NewMark = "Nový Mark",
	Button_AddActor = "Přidat herce",
	Button_RemoveActor = "Odebrat herce",
	Button_ChangeActor = "Změnit herce",
	Button_RadioOnlyOne = "Pouze Jeden",
	Button_RadioRandom = "Náhodné",
	Button_RadioSequential = "Sekvenční",
	Button_SaveTrigger = "Uložit spouštěč",
	Button_NewCamera = "Nový fotoaparát",
	Button_NewScript = "Nový skript",
	Button_DragSpeed = "Rychlost",
	Button_ToggleMarker = "Přepnout značku",
	Button_TestPose = "Test Pose",
	Button_StopPose = "Zastavit pózu",
	
    --Button Label
	Button_Label_PlayScript = "Přehrát skript",
	Button_Label_StopScript = "Zastavit skript",
	Button_Label_Stopping = "Zastavování...",
	Button_Label_Restarting = "Restartování...",
	Button_Label_AddMark = "Přidat Marka",
	Button_Label_SaveWNewPos = "Uložit s novou pozicí",
	
    --Checkbox
    --Warning / Info / Tool Tip
	Warn_ActorSingleMark_Info = "Herec zůstane na single Mark",
	Warn_ActorRandomMark_Info = "Herec se bude náhodně pohybovat mezi značkami",
	Warn_ActorSequentialMark_Info = "Herec se bude pohybovat mezi značkami v číselném pořadí",
	Warn_DeleteScript_Info = "Opravdu chcete smazat tento skript?",
	Warn_CloseCamForMove_Info = "Zavřete nabídku, abyste mohli kamerou pohybovat",
	Warn_CreateScriptsDesc_Info = "Vytvářejte scénáře pro přidávání, oblékání a řízení herců, aby hráli pro machinima, snímky obrazovky a hraní rolí.",
	Warn_PremadeScriptsDesc_Info = "Vytvořte spouštěče pro aktivaci předem připravených skriptů u kontaktu.",
	Warn_CreateCamera_FovZoomDesc_Info = "Vytvářejte kamery, abyste se mohli volně pohybovat, nastavujte různá zorná pole a úrovně přiblížení.",
	Warn_ShowMarksLocations_Info = "Zobrazuje viditelnou ikonu při označení umístění",
	Warn_AutoTalkNpc_Info = "Díky tomu budou NPC mluvit jednou za minutu, když jsou v dosahu (pouze hlasové NPC)",
	Warn_DirectActorPlayerPosition_Info = "Vytvořte značku na aktuální pozici hráče, abyste mohli pohybovat a řídit herce",
	Warn_InMenuDirectorDesc = "Režisér funguje pouze ve hře",
	
    --Text
	DirectorMode = "Režim ředitele",
	SelectActorToReplace = "Vyberte herce, kterého chcete nahradit:",
	AddActorToCurrentScript = "Přidat herce do aktuálního scénáře:",
	FacialExpression_WithColon = "Výraz obličeje:",
	FavoritePoses_WithColon = "Oblíbené pózy:",
	AddFavorites_Desc = "Nejprve přidejte pozice do oblíbených na kartě Pozice",
	HoldDuration = "Doba trvání",
	Movement2 = "pohyb:",
	Actions = "Akce:",
	Actors = "Herci",
	Editing = "Editace",
	AutoTalk = "Auto Talk",
	ActorMarks = "herec Marks",
	Current_Actors = "Současní herci",
	Marks_Sequence = "Pořadí značek:",	
	ShowMarks = "Zobrazit značky",
	Triggers = "Spouštěče",
	NewTrigger = "Nový spouštěč",
	ShowTrigger = "Zobrazit spouštěč",
	Title = "Název",
	Select_Trigger = "Vyberte možnost Spustit",
	Select_Script = "Vyberte Skript",
	Delete_Trigger = "Smazat spouštěč",
	Triggers_On_Off = "Zapnutí/vypnutí spouště",
	Running = "Běh",
	Script_Running = "Skript běží...",
	Delete_Script = "Smazat skript",
	RepeatInLoop = "Opakujte ve smyčce",
	ActivationRadius = "Poloměr aktivace",
	Activate = "Aktivovat",
	Deactivate = "Deaktivovat",
	FOV = "FOV",
	Zoom = "Přiblížení",
	LockFrame = "Zámkový rám",
	Walk = "Procházka",
	Sprint = "Sprint",
	Sequential = "Sekvenční",
	Cameras = "Kamery",
	NodeView = "Zobrazení uzlu",
	TeamA = "Tým A",
	TeamB = "Tým B",
	
	
	
	-- >> SETTINGS TAB
	BeginItem_TabNameSettings = "Nastavení",
	BeginItem_TabNameGeneral = "Obecné",
	BeginItem_TabNameCompanions = "Společníci",
	BeginItem_TabNameUI = "Uživatelské rozhraní",
	BeginItem_TabNameExperimental = "Experimentální",
	BeginItem_TabNamePhotoMode = "Foto režim",
	
	--Button
	Button_RevertAllModelSwaps = "Vrátit všechny výměny modelu",
	Button_RespawnAll = "Znovu spustit vše",
	Button_ForceDespawnAll = "Force Despawn All",
	Button_ClearFavorites = "Vymazat oblíbené",
	Button_ClearAllSavedAppearances = "Vymazat všechny uložené vzhledy",
	Button_ClearAllBlacklistedAppearances = "Vymazat všechny vzhledy na černé listině",
	Button_ClearAllAppearanceTriggers = "Vymazat všechny spouštěče vzhledu",
	Button_ClearAllSavedDespawns = "Vymazat všechny uložené despawny",
	Button_SmallCreateTheme = "Vytvořit motiv",
	Button_SmallDeleteTheme = "Smazat motiv",
	Button_SmallSet = "Set",
	Button_ReloadAppearances = "Znovu načíst vlastní vzhledy",
	
    --Button Label
    --Checkbox
	Checkbox_SpawnAsCompanion = "Spawn jako společník",
	Checkbox_SpawnAsFriendly = "Spawn jako přátelský",
	Checkbox_InvulnerableCompanion = "Nezranitelný společník",
	Checkbox_RespawnOnLaunch = "Respawn při spuštění",
	Checkbox_LockTargetAfterSpawn = "Uzamknout cíl po spawnování",
	Checkbox_OpenTargetToolsAfterSpawn = "Otevřete cílové nástroje po spawn",
	Checkbox_DisplayAxisIndicatorByDefault = "Ve výchozím nastavení zobrazit indikátor osy",
	Checkbox_PhotoModeEnhancements = "Vylepšení fotografického režimu",
	Checkbox_GodModeOnLaunch = "Režim Boha při spuštění",
	Checkbox_PassiveModeOnLaunch = "Pasivní režim při spuštění",
	Checkbox_StreamerMode = "Režim streamování",
	Checkbox_OpenWCETOverlay = "Otevřít s překrytím CET",
	Checkbox_AutoResizingWindow = "Automatická změna velikosti okna",
	Checkbox_ScanningReticle = "Skenování záměrného kříže",
	Checkbox_FloatingTargetTools = "Nástroje pro plovoucí cíl",
	Checkbox_TabHeaderDescriptions = "Popisy záhlaví karet",
	Checkbox_ExpandFavoritesByDefault = "Ve výchozím nastavení rozbalte Oblíbené",
	Checkbox_EnableScrollBars = "Povolit posuvníky",
	Checkbox_AlwaysDisablePhotoModeCursor = "Vždy deaktivovat kurzor režimu fotografie",
	Checkbox_Camera = "Fotoaparát",
	Checkbox_DepthOfField = "DOF",
	Checkbox_Effect = "Efekt",
	Checkbox_Stickers = "Samolepky",
	Checkbox_LoadSave = "Načíst/Uložit",
	Checkbox_ExperimentalFunstuff = "Experimentální/zábavné věci",
	Checkbox_EnableFreezeTargetInPhotoMode = "Povolte zmrazení cíle v režimu fotografie",
	Checkbox_WeaponizeCompanions = "Vyzbrojte společníky",
	Checkbox_AllowPlayerToBeTargetedinPosestab = "Povolit hráče zacílit na kartě Pozice",
	Checkbox_AllowPlayerAnimationsonNPCs = "Povolit animace hráčů na NPC",
	Checkbox_AllowExpressionOnNpcPM = "Povolte výrazy a podívejte se na NPC ve fotografickém režimu",
        Checkbox_ResetTargetPositionPM = "Resetujte cílovou pozici pro NPC v režimu fotografie",
        Checkbox_EnableRandomLocation = "Povolit tlačítko Náhodné: teleportuje hráče na náhodné místo ze seznamu",
        Checkbox_RestoreOnLaunch = "Obnovit při spuštění",
        Radio_PrimarySlot = "Primární slot",
        Radio_SecondarySlot = "Sekundární slot",
	
    --Warning / Info / Tool Tip
	Warn_RespawnOnLaunch_Info = "Toto nastavení povolí/zakáže respawn dříve uložených NPC při zatížení hry. AMM automaticky uloží vaše vytvořené NPC, když opustíte hru.",
	Warn_BannedWords_Info = "Toto nastavení povolí/zakáže vzhledy NPC, které obsahují slova: nahý, nahý, xxx, sprcha, narozeninový_suit, pp a penis.",
	Warn_TargetNpcVehicleHotkey = "Zacilte na NPC nebo vozidlo pro nastavení klávesových zkratek",
	Warn_FirstLaunchDecideTabsExpand_Info = "Toto nastavení ve výchozím nastavení při prvním spuštění AMM rozbalí Oblíbené na kartách Spawn, Swap a Decor.",
	Warn_ExperimentalTabDesc_Info = "Experimentální funkce přidávají další funkce, ale nemusí fungovat tak dobře, jako je označení experimentální. Ve skutečnosti má většina uživatelů AMM povoleny experimentální funkce. Tak se moc nebojte a bavte se!",
	Warn_FreezeTargetPhotoMode_Info = "Toto nastavení má pomoci zmrazit animace z modů, které přidávají vlastní animaci do pozic v režimu Photo nebo když zrušíte pozastavení pomocí IGCS.",
	Warn_WeaponizeCompanions_Info = "To dá zbraně a bojové schopnosti všem NPC. Očekává se T-posing a podivné animace.",
	Warn_PlayerAnimsOnNpc_Info = "Povolte toto, pokud používáte mod, který umožňuje použití animací hráčů na NPC.",
	Warn_UnpauseRequiresIGSC = "Toto nastavení vyžaduje, aby IGCS zrušil čas pozastavení.",
	Warn_NotInstalled = "NENÍ NAINSTALOVÁNO",
	Warn_DespawnAllProps = "Opravdu chcete odstranit všechny rekvizity?",
	
    --Text
	AMM_Version = "Verze AMM:",
	CET_Version = "Verze CET:",
	Codeware_Version = "Verze Codeware:",
	Game_Version = "Verze hry:",
	Companion_Damage = "Poškození společníka:",
	Companion_Resistance = "Odpor společníka:",
	Companion_Distance = "Vzdálenost společníka:",
	xDamage = "x Poškození",
	xResistance = "x Odolnost",
	SavedAppearancesHotkeys = "Uložené klávesové zkratky vzhledů",
	Favorites = "Oblíbené",
	Appearances = "Vystoupení",
	Blacklist = "Černá listina",
	AppearanceTriggers = "Spouštěče vzhledu",
	SavedDespawns = "Zachránění Despawni",
	Interface_Language = "Jazyk rozhraní:",
	Custom_Appearances = "Vlastní vzhledy",
	PhotoModeAdjustments = "Úpravy režimu fotografie:",
	DisablePhotoModeTabs = "Zakázat karty režimu fotografie:",
	List_Height = "Výška seznamu",
	Listbox_Themes = "Témata",
	Weaponize = "Vyzbrojit",
	NoAppearanceSet = "Není nastaven žádný vzhled",
	
	
	
	-- >> EXTRA	
	--Texts, warns, tips, info's, buttons and labels etc.
	Seat_FrontRight = "Přední pravá",
	Seat_BackRight = "Zpět Vpravo",
	Seat_FrontLeft = "Přední levá",
	Seat_BackLeft = "Zpět vlevo",
	Label_Door = "Dveře",
	Label_Window = "okno",

	Close = "Zavřít",
	Far = "Daleko",
	Moderate = "Mírný",
	
	-- >> Archives Screen
	Warning_MissingRequiredArchives = "AMM chybí jeden nebo více požadovaných archivů. Nainstalujte prosím jakýkoli chybějící požadovaný archiv do složky archiv/pc/mod.",
	Warning_MissingOptionalArchives = "AMM chybí jeden nebo více archivů. Ty jsou volitelné, ale přidávají funkcionalitu AMM. Tato varování můžete ignorovat, ale AMM nemusí fungovat správně.",
	
	
	-->> INIT.LUA
	AMMNeedsAttention = "AMM vyžaduje pozornost",
	MISSING_ARCHIVES = "CHYBĚJÍCÍ ARCHIVY",
	VERSION_INFORMATION = "INFORMACE O VERZI",
	CREDITS = "KREDITY",
	UPDATE_HISTORY = "AKTUALIZOVAT HISTORII",
	Updates = "Aktualizace",
	MISSING = "CHYBÍ",
	REQUIRED = "POVINNÉ",
	OPTIONAL = "VOLITELNÉ",
	WHATS_NEW = "CO JE NOVÉHO", --Line 83 Function Error

	--Button
	Button_Ignorewarningsforthisversion = "Ignorovat varování pro tuto verzi",
	Button_Credits = "Kredity",
	Button_Cool = "Skvělé!",

	--Button Label
	Label_SpawnFavorites = "Spawn Favorites",
	Label_SwapFavorites = "Vyměňte oblíbené",
	Label_FavoriteAppearances = "Oblíbené vzhledy",
	Label_Cancel = "Zrušit",

	--Text
	Hotkey_i = "Klávesová zkratka %i",

	--Node - Function Error(nil value) 
	Top = "Nahoru", --Line 116
	Bottom = "Spodní",
	Off = "Vypnuto",
	
	--Voice Overs
	Label_GreetV = "Pozdrav V",
	Label_FearFoll = "Fear Foll",
	Label_FearToll = "Fear Toll",
	Label_FearBeg = "Fear Beg",
	Label_FearRun = "Fear Run",
	Label_StealthSearch = "Stealth Search",
	Label_StealthDeath = "Stealth Death",
	Label_StealthRestore = "Stealth Restore",
	Label_StealthEnd = "Stealth End",
	Label_CuriousGrunt = "Zvědavý Grunt",
	Label_GrappleGrunt = "Grapple Grunt",
	Label_Bump = "Bump",
	Label_VehicleBump = "Náraz vozidla",
	Label_TurretWarning = "Varování věže",
	Label_OctantWarning = "Varování oktantů",
	Label_DroneWarning = "Upozornění na dron",
	Label_MechWarning = "Mech varování",
	Label_EliteWarning = "Elitní varování",
	Label_CameraWarning = "Upozornění na fotoaparát",
	Label_EnemyWarning = "Varování před nepřítelem",
	Label_HeavyWarning = "Silné varování",
	Label_SniperWarning = "Varování odstřelovače",
	Label_AnyDamage = "Jakékoliv poškození",
	Label_Danger = "Nebezpečí",
	Label_CombatStart = "Bojový start",
	Label_CombatEnd = "Konec boje",
	Label_CombatTargetHit = "Bojový cílový zásah",
	Label_PedestrianHit = "Zásah chodce",
	Label_LightHit = "Lehký zásah",
	Label_Curse = "Prokletí",
	Label_Irritated = "Podrážděný",
	Label_GrenadeThrow = "Hod granátem",
	Label_Gotakill = "Mám zabití!",
	
	--Expressions
	Neutral = "Neutrální",
	Joy = "radost",
	Smile = "Usmívej se",
	Sad = "Smutný",
	Surprise = "Překvapení",
	Aggressive = "Agresivní",
	Anger = "Hněv",
	Interested = "Zájem",
	Disinterested = "Nezaujatý",
	Disappointed = "Zklamaný",
	Disgust = "Znechucení",
	Exertion = "Námaha",
	Nervous = "Nervózní",
	Fear = "Strach",
	Terrified = "Vyděšený",
	Pain = "Bolest",
	Sleepy = "Ospalý",
	Unconscious = "V bezvědomí",
	Dead = "Mrtvý",

	-- Extra Expressions
	Frown = "Zamrač se",
	Shocked = "Šokovaný",
	Annoyed_2 = "Naštvaný 2",
	Contempt = "pohrdání",
	Irritated = "Podrážděný",
	Sceptical_1 = "Skeptický 1",
	Sceptical_2 = "Skeptický 2",
	Annoyed_1 = "Naštvaný 1",
	Offended = "Uražený",
	Disgusted = "Znechucený",
	Disappointed_2 = "Zklamaný 2",
	Alert = "Upozornění",
	Crying = "Pláč",
	Embarrassed = "V rozpacích",
	Humiliated = "Ponížený",
	Impatient = "Netrpělivý",
	Anguished = "Ztrápený",
	Worried = "Ustaraný",
	Guilty = "Vinen",
	Grieving = "Truchlení",
	RestrainedAnger = "Zadržovaný hněv",
	Afraid = "Strach",
	LookingUpAnnoyed = "Podívat se Naštvaně",
	Offended_2 = "Uražený 2",
	Resentful = "Rozzlobený",
	SadExtra = "Smutný Extra",
	NervousBreath = "Nervózní dech",
	ScreamingLong = "Dlouho křičel",
	ScreamingShort = "Screaming Short",
	ScaredBreath = "Vyděšený dech",
	CryingPainful = "Pláč bolestný",
	SelfReflectAnger = "Hněv sebereflexe",
	IndulgentSmile = "Shovívavý úsměv",
	Impressed = "dojem",
	LongSmile = "Dlouhý úsměv",
	ShortSmile = "Krátký úsměv",
	SimpleSmile = "Jednoduchý úsměv",
	Confident = "Sebevědomý",
	Relief = "Úleva",
	Impressed_2 = "Zaujatý 2",
	Admiring = "Obdivuji",
	Fascinated = "Fascinován",
	RaisedBrows = "Zvednuté obočí",
	LookingUpThinking = "Při pohledu nahoru myšlení",
	LeftGlanceProcessing = "Zpracování levého pohledu",
	LeftGlanceCloseUp = "Pohled zleva Zblízka",
	LookingAround = "Rozhlížím se kolem",
	LookingDownThinking = "Při pohledu dolů myšlení",
	LookingAroundAlt = "Rozhlédnout se kolem Alt",
	EyesDartFromLeft = "Oči Dart Zleva",
	EyesDartFromRight = "Oči Dart Zprava",
	EyesDartToRight = "Oči šipky doprava",
	LookingLeft = "Při pohledu doleva",
	LookingUpThinking_2 = "Vzhled myšlení 2",
	RightGlanceProcessing = "Zpracování pravého pohledu",
	LookingDown = "Při pohledu dolů",
	Left90GlanceClose = "Left90Lance Close",
	LookingUp = "Pohled nahoru",
	Right90GlanceClose = "Right90Glance Close",
	LookingLeftUp = "Při pohledu vlevo nahoru",
	LookingRightUp = "Při pohledu nahoru",
	ReadingDown = "Čtení dolů",
	ReadingUp = "Reading Up",
	ReadingMiddle = "Střed čtení",
	FrontCloseGlance = "Přední pohled zblízka",
	WinkLeft = "Mrkněte doleva",
	EyeRoll = "Eye Roll",
	Squint = "Mžourat",
	FalseSmile_2 = "Falešný úsměv 2",
	FalseSmile_1 = "Falešný úsměv 1",
	ListeningNewInfo = "Poslech nových informací",
	WhatDoYouWant = "co chceš",
	Maybe = "Možná",
	SearchingForWords = "Hledání Slov",
	What = "co",
	Where = "Kde?",
	SureSure = "Jasně Jasně",
	ListenToMe = "Poslouchej mě",
	StopThePolice = "Zastavte policii",
	HurryUp = "Pospěšte si",
	ShutUp = "Drž hubu",
	WinkRight = "Mrkni doprava",
	MockingSmile = "Posměšný úsměv",
	AsymmetricalSmile = "Asymetrický úsměv",
	SarcasticSmile = "Sarkastický úsměv",
	Sex = "Sex",
	LipBite_1 = "Kousnutí do rtu 1",
	LipBite_2 = "Kousnutí do rtů 2",
	Moan = "Sténat",
	LipBite_3 = "Kousnutí do rtů 3",
	Pout = "Pout",
	SexySmile = "Sexy úsměv",
	Swallow = "Polykat",
	SensualSmile = "Smyslný úsměv",
	SexScene_1 = "Sexuální scéna 1",
	SexScene_2 = "Sexuální scéna 2",
	Kiss = "Polibek",
	UsingInhaler = "Použití inhalátoru",
	ShortYawn = "Krátké zívnutí",
	Yawn = "Zívněte",
	Coughing = "Kašel",
	Bite = "Kousat",	
	EatingFast = "Rychlé stravování",
	ShortDrink = "Krátký nápoj",
	Drinking = "Pití",
	FastBite = "Rychlé kousnutí",
	LongDrink = "Long Drink",
	ShortSmoking = "Krátké kouření",
	LongSmoking = "Dlouhé kouření",
	Smoking = "Kouření",
	Eating_1 = "Stravování 1",
	Eating_2 = "Stravování 2",
	Eating_3 = "Stravování 3",
	Eating_4 = "Stravování 4",
	Vomit = "Zvracet",
	BeingRevived = "Být oživen",
	MalwarePositive = "Malware pozitivní",
	MalwareNegative = "Malware negativní",
	MalwareInfected = "Infikovaný malwarem",
	FaceMorphActivate = "Aktivace morfování obličeje",
	LieNetChairSleep = "Leh Síť Křeslo Spánek",
	LieNetChairBreathe = "Síťová židle Dýchat",
	NetrunnerDeathUnplugged = "Netrunner Death Unplugged",
	VeryItchyNose = "Velmi svědivý nos",
	RollerCoasterNervous = "Nervózní horská dráha",
	Pfft = "Pfft",
	Hahaha = "hahaha",
	Sniff = "Přičichnout",
	Ahaaa = "Ahaaa",
	Heh = "Heh",
	Huh = "Huh",
	Haaa = "Haaa",
	Sigh_Lipsync = "Povzdech Lipsync",
	Hmm = "Hmm",
	Whispering_1 = "Šeptání 1",
	Whispering_2 = "Šeptání 2",
	ApprovalYes = "Schválení Ano",
	SubtleYes = "Jemné Ano",
	QuickNoShake = "Quick No Shake",
	FirmYes = "Firma Ano",
	LongNo = "Dlouhé č",
	SubtleNo = "Jemné č",
	NoContempt = "Žádné pohrdání",
	NoDisapproval = "Žádné zamítnutí",
	FirmNo = "Firma č",
	NoEnthusiastic = "Žádné nadšení",
	MockingYes = "Zesměšňování Ano",
	EnthusiasticYes = "Nadšené Ano",
	AsymmetricalCornerUp = "Asymetrický roh nahoru",
	CornersUp = "Rohy nahoru",
	SoftSigh = "Tichý povzdech",
	BreathGasp = "Lapání dechu",
	AssymetricalSneer = "Asymetrický úšklebek",
	CrimpingLips = "Krimpovací rty",
	BrowsDown = "Brows Down",
	BrowsLeftUp = "Obočí vlevo nahoře",
	BrowsRightUp = "Brows Right Up",
	BrowsUp = "Brows Up",
	ClosedEyes_1 = "Zavřené oči 1",
	ClosedEyes_2 = "Zavřené oči 2",
	EyesClosed = "Zavřené oči",
	LookRight = "Podívejte se správně",
	FastBlink = "Rychlé blikání",
	SlowBlink = "Pomalé blikání",
	NormalBlink = "Normální blikání",
	TinyBlink = "Tiny Blink",
	HalfBlink = "Napůl mrknutí",
	RegularSaccade = "Pravidelná Saccada",
	FrequentSaccade = "Častá Saccada",
	PhotoCloseupEyes = "Fotografie Detailní oči",
	PhotoCloseupLips = "Fotografie Detailní rty",
	PhotoCloseupHair = "Fotografie Detailní vlasy",
	PhotoCloseupChin = "Fotografie Detailní Chin",
	PhotoCloseupNose = "Fotografie Detailní Nos",
	PhotoCloseup = "Detailní fotografie",
	PhotoCloseupPleased = "Detailní foto Potěšilo",
	PhotoCloseupBody = "Fotografie Detailní tělo",
	PhotoCloseupTeeth = "Fotografie Detailní zuby",
	PhotoCloseupIN = "Detailní fotografie IN",
	PhotoCloseupOUT = "Detailní fotografie OUT",
	Bored = "Znuděný",
	Charming = "Okouzlující",
	Furious = "Zuřivý",
	Happy = "Šťastný",
	Pissed = "Naštvaný",
	Pleased = "Potěšilo",
	Scared = "Vyděšený",
	Surprised = "Překvapený",
	Sadness = "Smutek",
	Whistling = "Pískání",
	Singing_1 = "Zpěv 1",
	Singing_2 = "Zpěv 2",
	Singing_3 = "Zpěv 3",
	Alerted = "Upozorněn",
	Hit_1 = "Zásah 1",
	Hit_2 = "Hit 2",
	Wounded = "Zraněný",
	Death = "Smrt",

	-- Expressions Category
	Negative = "Negativní",
	Positive = "Pozitivní",
	Contemplative = "Kontemplativní",
	Social = "Sociální",
	Sexual = "Sexuální",
	Action = "Akce",
	Vocal = "Vokální",
	Yes_N_No = "Ano & Ne",
	Nuance = "Nuance",
	Static = "Statické",
	Combat = "Bojovat",
	
	--Props
	AMM_Props_Desc = "Přidává rekvizity, postavy a vozidla. Bez toho se AMM nespustí.",
	AMM_JohnnyCompanion_Desc = "Přidá Johnnyho Silverhanda jako plodnou postavu.",
	AMM_ScenesPack_Desc = "Přidá 9358 animací scén do systému Poses.\nStáhněte si jej na stránce Nexus společnosti AMM.",
	AMM_SoundPack_Desc = "Přidá plodné zvukové efekty.",
	AMM_KerryPP_Desc = "Přidá nový nahý vzhled.",
	AMM_BenjaminStonePP_Desc = "Přidá nový nahý vzhled.",
	AMM_RiverPP_Desc = "Přidá nový nahý vzhled.",
	AMM_YorinobuPP_Desc = "Přidá nový nahý vzhled.",
	AMM_LizzyIncognito_Desc = "Přidá nový vzhled.",
	AMM_MeredithXtra_Desc = "Přidá nový vzhled.",
	AMM_DelamainFix_Desc = "Přidává celé tělo k Delamain.",
	AMM_HanakoNoMakeup_Desc = "Umožňuje AMM odstranit make-up Hanako při použití vlastního vzhledu.",
	AMM_JudyBodyRevamp_Desc = "Nahrazuje Judyino tělo novým vylepšeným.",
	AMM_PanamBodyRevamp_Desc = "Nahrazuje Panamovo tělo novým vylepšeným.",
	AMM_MistyBodyRevamp_Desc = "Nahrazuje tělo Misty za nové vylepšené.\nStáhněte si jej na stránce Nexus společnosti AMM.",
	AMM_1VesHanakoFixedBodyNaked_Desc = "Nahrazuje Hanako tělo za nové vylepšené.",
	AMM_PinkyDudeANIMFacialExpressionsFemV_Desc = "Aktivuje nástroje pro výrazy obličeje na Female V",
	AMM_PinkyDudeANIMFacialExpressionsMaleV_Desc = "Aktivuje nástroje pro výrazy obličeje na Male V",
	AMM_DinoTattooFixArchive_Desc = "Nahrazuje síťovinu a texturu.",
	AMM_SongbirdBodyFixArchive_Desc = "Nahrazuje tělo pro opravu šedé oblasti. Ještě ne dokonalé.",
	AMM_RitaWheelerCombatEnablerArchive_Desc = "Nahrazuje soubor entity, aby bylo možné povolit bojové animace.",
	AMM_CheriAppearances_Desc = "Přidává nové vzhledy. Stáhněte si jej na stránce Nexus společnosti AMM.",
	AMM_BryceNaked_Desc = "Přidá nový nahý vzhled. Stáhněte si jej na stránce Nexus společnosti AMM.",
	AMM_EvelynNaked_Desc = "Upraví její tělo, aby mohl vypadat nahý. Stáhněte si jej na stránce Nexus společnosti AMM.",
	AMM_SaburoAppearances_Desc = "Přidává nové vzhledy. Stáhněte si jej na stránce Nexus společnosti AMM.",
	AMM_TbugAppearances_Desc = "Přidává nové vzhledy. Stáhněte si jej na stránce Nexus společnosti AMM.",
	AMM_8ug8eagAppearances_Desc = "Přidává nové vzhledy. Stáhněte si jej na stránce Nexus společnosti AMM.",
	
	--Equipments (There is a Function Error(nil value) in this section, These are just labels that are not connected to any localizable strings in the file)
	Fists = "Pěsti", --Line 2377 
	Katana = "Katana",
	Mantis_Blades = "Čepele kudlanky",
	Machete = "mačeta",
	Hammer = "Kladivo",
	Baton = "Obušek",
	Knife = "Nůž",
	Crowbar = "páčidlo",
	Baseball_Bat = "Baseballová pálka",
	Assault_Rifle = "Útočná puška",
	Sidewinder = "Sidewinder",
	Sniper_Rifle = "Odstřelovací puška",
	Shotgun = "Brokovnice",
	SMG = "SMG",
	Handgun = "Pistole", --Line 2391
	
	--Warning / Info / Tooltip
	Warn_CantSave_BlacklistedAppearance = "Vzhled na černé listině nelze uložit!",
	Warn_ConfirmDeleteSavedAppearances = "Opravdu chcete smazat všechny své uložené vzhledy?",
	Warn_ConfirmDeleteBlacklistedAppearances = "Opravdu chcete smazat všechna svá vystoupení na černé listině?",
	Warn_ConfirmDeleteSavedDespawns = "Opravdu chcete smazat všechny své uložené despawny?",
	Warn_ConfirmDeleteAppearanceTriggers = "Opravdu chcete smazat všechny spouštěče vzhledu?",
	Warn_ConfirmDeleteCurrentAppearance = "Opravdu chcete smazat aktuální aktivní předvolbu?",
	Warn_WeaponizeNpcAnimationIssues = "Ne každé NPC bude mít potřebné animace pro použití všech typů zbraní. Může se objevit T-posing a nesprávné animace.\nOpravdu to chcete povolit?",
	Warn_ConfirmEnableExperimentalAndSave_Info = "Opravdu chcete povolit experimentální funkce? AMM nemusí fungovat podle očekávání. Používejte jej na vlastní nebezpečí!",
	Warn_DeleteFavoritesAskWhichOne_Info = "Pokud jste si jisti, že chcete smazat všechny oblíbené položky, vyberte níže, kterou z nich:",
	Popup_Error_Title = "Chyba",
	Button_Ok = "Dobře",
	Popup_FavoriteName = "Oblíbené jméno",
	Popup_RenamePreset = "Přejmenovat předvolbu",
	Popup_RenameProp = "Přejmenovat Prop",
	Editor_Title = "Editor motivů",
	Editor_Field_ThemeName = "Název motivu",
	Editor_Hint_InsertThemeName = "Vložte nový název motivu",
	Error_ThemeNameExists = "Název motivu již existuje",
}
