return {

    -- >> SCAN TAB
	BeginItem_TabNameScan = "Scan",
	
	--Button
	Button_CyclesAppearances = "Aussehen des Zyklus",
	Button_SavesAppearance = "Aussehen speichern",
	Button_ClearSavedAppearance = "Gespeicherte Darstellung löschen",
	Button_UnlockDoor = "Türschloss umschalten",
	Button_RestoreAccess = "Zugriff wiederherstellen",
	Button_UnlockVehicle = "Fahrzeug entriegeln",
	Button_RepairVehicle = "Fahrzeug reparieren",
	Button_OpenCloseDoors = "Türen öffnen/schließen",
	Button_OpenCloseWindows = "Windows öffnen/schließen",
	Button_ToggleEngine = "Motor umschalten",
	Button_ToggleAIDriver = "KI-Treiber umschalten",
	Button_ToggleCamera = "Kamera umschalten",
	Button_ToggleRadio = "Radio umschalten",
	Button_NextRadioStation = "Nächster Radiosender",
	Button_TargetMountedVehicle = "Zielmontiertes Fahrzeug",
	Button_AssignSeats = "Weisen Sie Sitzplätze zu",
	Button_Assign = "Zuweisen",
	Button_Reset = "Zurücksetzen",
	Button_FakeDie = "Gefälschter Würfel",
	Button_SmallCopy = "Kopieren",
	
    --Button Label
	Button_Label_Unfollower = "Unfollower",
	Button_Label_Follower = "Anhänger",
	Button_Label_SaveDespawn = "Speichern Sie Despawn",
	Button_Label_ClearSavedDespawn = "Löschen Sie den gespeicherten Despawn",
	Button_LabelLockTarget = "Ziel sperren",
	Button_LabelUnlockTarget = "Ziel freischalten",
	Label_AddToSpawnFavs = "Zu spawnbaren Favoriten hinzufügen",
	Label_RemoveFromSpawnFavs = "Aus spawnbaren Favoriten entfernen",
	
    --Checkbox
	Checkbox_SavedDespawnsActive = "Gespeicherte Despawns aktiv",
	Checkbox_KeepAssigned = "Beim Fahrzeugwechsel die Zuordnung beibehalten",
	
    --Warning / Info / Tool Tip
	WarnTextAI_FastTravel = "Wählen Sie einen Schnellreisepunkt auf Ihrer Karte aus, um loszulegen",
	WarnText_DontReloadMods = "Verwenden Sie nicht „Alle Mods neu laden“.\nBitte laden Sie Ihren Spielstand neu oder wechseln Sie in einen anderen Bereich.",
	Warning_NoTarget_Desc = "Kein Ziel! Schauen Sie sich zunächst den NPC, das Fahrzeug oder das Objekt an",
	ToolTip_DisableCheckboxReloadSave_AbleTotargetClearSavedDespawns = "Deaktivieren Sie dieses Kontrollkästchen und laden Sie Ihren Speicherstand neu, um auf gelöschte Despawns abzielen zu können",
	
    --Text
	Build_Mode = "Build-Modus",
	Speed = "Geschwindigkeit:",
	Search = "Suche",
	Clear = "Leeren",
	Player = "Spieler",
	Saved = "Gespeichert",
	Saved_ = "Gespeichert_",
	Current = "Aktuell",
	Current_ = "Aktuell",
	Select_Seat = "Wählen Sie Sitzplatz",
	Target_Info = "Zielinformationen",
	Target_Actions = "Zielaktionen",
	No_Appearances = "Keine Auftritte",
	No_Target = "Kein Ziel",
	Favorite_Appearance = "Lieblingsauftritt",
	Unfavorite_Appearance = "Ungünstiges Aussehen",
	Blacklist_Appearance = "Erscheinungsbild auf der schwarzen Liste",
	Unblacklist_Appearance = "Erscheinungsbild von der Blacklist entfernen",
	Saved_Appearance = "Gespeichertes Erscheinungsbild:",
	Current_Appearance = "Aktueller Auftritt:",
	List_of_Appearances = "Liste der Auftritte",
	Appearance_Trigger = "Erscheinungsauslöser",
	None = "Keine",
	Default = "Standard",
	Zone = "Zone",
	Area = "Bereich",
	Position = "Position",

	
	-- >> SPAWN TAB
	BeginItem_TabNameSpawn = "Spawnen",
	
	--Button
	Button_Refresh = "Aktualisieren",
	Button_Save = "Speichern",
	Button_Confirm = "Bestätigen",
	Button_Cancel = "Abbrechen",
	Button_SmallSave = "Speichern",
	Button_SmallRespawn = "Respawn",
	Button_SmallDespawn = "Despawnen",
	Button_SmallDespawn_WithSpace = "Despawnen",
	Button_SmallTarget = "Ziel",
	Button_SmallEquipment = "Ausrüstung",
	Button_LabelHostile = "Feindselig",
	Button_LabelFriendly = "Freundlich",
	
    --Button Label
	Label_Favorite = "Favorit",
	Label_Unfavorite = "Unfavorit",
	
    --Checkbox
    --Warning / Info / Tool Tip
	Warn_PlayerInMenu = "Spieler im Menü",
	Warn_AMMonlyfunctions_ingame = "AMM funktioniert nur im Spiel",
	Warn_SpawnWorksInGame = "Das Spawnen funktioniert nur im Spiel",
	Warn_InitError = "Initialisierungsfehler",
	Warn_InitError_Info = "Weitere Informationen finden Sie im AppearanceMenuMod.log.",
	
    --Text
	Active_Spawns = "Aktive Spawns",
	NoActiveSpawns = "Keine aktiven Spawns",
	Select_To_Spawn = "Wählen Sie „Zum Spawnen“ aus",
	No_Results = "Keine Ergebnisse",
	ItsEmpty = "Es ist leer :(",
	Existing_Name = "Vorhandener Name",
	Name = "Name",
	
	
	
	-- >> SWAP TAB
	BeginItem_TabNameSwap = "Tauschen",
	
	--Button
	Button_SmallRevert = "Zurücksetzen",
	
    --Button Label
    --Checkbox
    --Warning / Info / Tool Tip
	Warn_ReloadSaveUpdateChanges = "Laden Sie Ihr gespeichertes Spiel neu, um die Änderungen zu aktualisieren!",
	Warn_NeedReloadSaveUpdateChanges = "Sie müssen Ihren Speicherstand neu laden, um die Änderungen zu aktualisieren.",
	Warn_ReplacerSwap = "Sie können den Ersatz nicht austauschen! Verwenden Sie die Registerkarte „Werkzeuge“ im Fotomodus, um sie anzuvisieren, und ändern Sie dann ihr Aussehen über die Registerkarte „Spawn“ oder die Zielwerkzeuge.",
	Warning = "WARNUNG",
	Warning2 = "WARNUNG:",
	SaveSwap_Tooltip = "Speichern Sie Ihre Swaps, um sie nach dem Neuladen Ihres Spiels zu behalten.",
	
    --Text
	CantSwapReplacer = "Ersatz kann nicht ausgetauscht werden",
	Active_Model_Swaps = "Aktive Modelltausche",
	Save = "Speichern",
	Restore = "Wiederherstellen",
	Current_Target = "Aktuelles Ziel:",
	Target_ID = "Ziel-ID:",
	SelectSwap_CurrentTarget = "Wählen Sie „Mit aktuellem Ziel tauschen“:",
	NoNPC_LookNPC = "Kein NPC gefunden! Schauen Sie sich zunächst den NPC an",
	
	-- Locations Categories
	Residences = "Residenzen",
	ArasakaAndCorpo = "Arasaka & Corpo",
	ClubsAndBars = "Clubs und Bars",
	HotelsAndPleasure = "Hotels & Vergnügen",
	UndergroundAndCrime = "Untergrund & Kriminalität",
	GovernmentAndSecurity = "Regierung und Sicherheit",
	StoryAndUnique = "Geschichte & Einzigartig",
	Ripperdocs = "Ripperdocs",
	LandmarksAndOpenWorld = "Sehenswürdigkeiten und offene Welt",
	SpoilersAndHidden = "Spoiler & Versteckt",
	UserLocations = "Benutzerstandorte",
	
	
	-- >> DECOR TAB
	BeginItem_TabDecor = "Dekor",
	BeginItem_TabPresets = "Voreinstellungen",
	Begin_ComboPresets = "Voreinstellungen",
	
	--Button
	Button_SmallClone = "Klonen",
	Button_SmallRemove = "Entfernen##",
	Button_SmallRename = "Umbenennen##",
	Button_SmallUpdate = "Aktualisieren##",
	Button_SmallCancel = "Abbrechen",
	Button_Frame = "Rahmen",
	
    --Button Label
	Button_LabelHide = "Verstecken",
	Button_LabelUnhide = "Einblenden",
	
    --Checkbox
    --Warning / Info / Tool Tip
	Warn_PersistPropSave = "Spawn-Requisiten, mit denen Sie Ihr Haus oder jeden beliebigen Ort nach Herzenslust dekorieren können! Speichern Sie Requisiten, damit sie bestehen bleiben!",
	Warn_DespawnInProgress_PleaseWait = "Despawn läuft. Bitte warten.",
	Warn_PresetsFolder_Info = "Benutzervoreinstellungen werden im Ordner AppearanceMenuMod/User/Decor gespeichert",
	Warn_CustomPresets_Info = "Diese Voreinstellung enthält benutzerdefinierte Requisiten",
	Warn_CustomPropsModders_Info = "Maßgeschneiderte Requisiten hergestellt von:",
	Warn_GamepadDirectMode_Info = "Dies ermöglicht eine bessere Integration mit dem Direktmodus bei Verwendung eines Gamepads. Es ermöglicht auch ein kleines Informationsfenster, das hängen bleibt.",
	Warn_PresetTriggerDistanceFar = "Die Einstellung „Far“ kann zu Leistungsproblemen führen.",
	
    --Text
	MovingAll_PropsTo_SavedProps = "Alle Requisiten in gespeicherte Requisiten verschieben",
	SelectPropSpawn = "Wählen Sie die zu spawnende Requisite aus:",
	Spawned_Props = "Gespawnte Requisiten",
	New_Preset = "Neue Voreinstellung",
	No_Preset_Available = "Keine Voreinstellung verfügbar",
	Preset_TriggerDistance = "Voreingestellter Triggerabstand",
	MovingSavedProps = "%s wird zu „Gespeicherte Requisiten“ verschoben",
	UpdateTag = "Tag aktualisieren",
	Categories = "Kategorien",
	Decorating = "Dekorieren",
	Decor_Tabs = "Dekor-Tabs",
	Saved_Props = "Gespeicherte Requisiten",
	Show_Nearby_Only = "Nur in der Nähe anzeigen",
	Show_Lights_Only = "Nur Lichter anzeigen",
	Show_LockedTarget_Only = "Nur gesperrtes Ziel anzeigen",
	Show_Customizable_Only = "Nur anpassbar anzeigen",
	Show_CustomProps_Only = "Nur benutzerdefinierte Requisiten anzeigen",
	ShowOnMap = "Auf der Karte anzeigen",
	Rename = "Umbenennen",
	Delete = "Löschen",
	Backup = "Sicherung",
	Merge = "Zusammenführen",
	Save_All = "Alles speichern",
	Despawn_All = "Alle despawnen",
	Save_ToSpecific_Tag = "Unter einem bestimmten Tag speichern",
	Saved_Props2 = "Gespeicherte Requisiten:",
	Move_To_Tag = "Zum Tag verschieben",
	HideFromMap = "Aus der Karte ausblenden",
	RemovingAllPropsFromTag = "Alle Requisiten werden aus dem Tag entfernt...",
	RemoveAllProps = "Alle Requisiten entfernen",
	RemoveHomeMarkerMap = "Entfernen Sie die Heimatmarkierung von der Karte",
	TeleportToLocation = "Zum Standort teleportieren",
	TeleportToTrigger = "Zum Auslösen teleportieren",
	TeleportToMark = "Teleportieren Sie sich zu Mark",
	UpdateTagLocation = "Tag-Standort aktualisieren",
	SharePresetWith_ThisTagOnly = "Voreinstellung nur mit diesem Tag teilen",
	SavedPresetFolder_Info = "Voreinstellung im Ordner „AppearanceMenuMod/User/Decor“ gespeichert",
	NoProps_WithThese_Conditions = "Keine Requisiten unter diesen Bedingungen",
	AddHomeMarkerMap = "Home-Marker zur Karte hinzufügen",
	Distance = "Entfernung",
	Total_Props = "Gesamte Requisiten:",
	Type_Tag_here = "Geben Sie hier „Tag“ ein",
	In_World = "In der Welt",
	Tags = "Schlagworte",
	Tag = "Etikett",
	Both = "Beides",	
	
	-- >> POSES TAB
	BeginItem_TabPoses = "Posen",
	
	--Button
	Button_SmallCopyClipboard = "In die Zwischenablage kopieren",
	
    --Button Label
    --Checkbox
    --Warning / Info / Tool Tip
    --Text
	Active_Animations = "Aktive Animationen",
	ShowHistory = "Verlauf anzeigen",
	ClearHistory = "Verlauf löschen",
	SelectPoseForCurrentTarget = "Pose für aktuelles Ziel auswählen:",
	LastUsedPoses = "Zuletzt verwendete Posen",
	
	
	
	-- >> TOOLS TAB
	BeginItem_TabTools = "Werkzeuge",
	BeginItem_TabPhotoModeNibblesReplacer = "Fotomodus-Knabbereien-Ersatz",
	BeginCombo_LookAt = "Schauen Sie sich an",
	BeginCombo_WeatherControl = "Wetterkontrolle",
	
	--Button
	Button_SkipFrame = "Frame überspringen",
	Button_ToggleLight = "Licht umschalten",
	Button_ResetScale = "Maßstab zurücksetzen",
	Button_ShowAsLookAtTarget = "Als „Look-At-Target“ anzeigen",
	Button_ResetLookAtTarget = "„Ziel betrachten“ zurücksetzen",
	Button_TogglePrimaryWeapon = "Primärwaffe ausrüsten",
	Button_ToggleSecondaryWeapon = "Sekundärwaffe ausrüsten",
	Button_GiveCurrentEquippedWeapon = "Geben Sie die aktuell ausgerüstete Waffe an",
	Button_SmallReset = "Zurücksetzen",
	Button_ResetToPlayer = "Auf Spieler zurücksetzen",
	Button_ClearSaved = "Löschen Sie „Gespeichert“.",
	Button_Cyberpsycho = "Cyberpsycho umschalten",
	Button_ProtectNPCfromActions = "Schütze NPC vor Aktionen",
	Button_AllFriendly = "Alle freundlich",
	Button_AllHostile = "Alles feindselig",
	Button_AllFollower = "Alle Follower",
	Button_AllFakeDie = "Alle gefälschten Würfel",
	Button_AllDie = "Alle sterben",
	Button_AllDespawn = "Alles Despawn",
	Button_InvMachineGun = "Maschinengewehr",
	Button_InvSpeed2 = "Geschwindigkeit",
	Button_ToggleMakeup = "Make-up umschalten",
	Button_TogglePiercings = "Piercings umschalten",
	Button_ToggleSeamfix = "Nahtfix umschalten",
        Button_TargetV = "Ziel V",
        Button_Target = "Ziel",
        Button_TeleportToLocation = "Zum Standort teleportieren",
        Button_TeleportToTrigger = "Zum Auslösen teleportieren",
        Button_TeleportToMark = "Teleportieren Sie sich zu Mark",
        Button_RandomLocation = "Zufällig",
        Button_ShareCurrentLocation = "Aktuellen Standort teilen",
	Button_GoBackToLastLocation = "Gehen Sie zurück zum letzten Standort",
	Button_DeleteSelectedUserLocation = "Ausgewählten Benutzerstandort löschen",
	
	--Slider / Drag 
	Slider_HeadStiffness = "Kopfsteifheit",
	Slider_HeadPoseOverride = "Überschreiben der Kopfhaltung",
	Slider_ChestStiffness = "Steifheit der Brust",
	Slider_ChestPoseOverride = "Überschreiben der Brusthaltung",
	Slider_SlowMotion = "Zeitlupe",
	Slider_DefaultAperture = "Standardblende",
	Slider_DefaultFieldofView = "Standard-Sichtfeld",
	Slider_MovementSpeed = "Bewegungsgeschwindigkeit",
	Drag_MovementSpeed = "Bewegungsgeschwindigkeit",
	
    --Button Label
	Button_Label_PauseTimeProgression = "Zeitverlauf anhalten",
	Button_Label_UnpauseTimeProgression = "Stoppen Sie den Zeitverlauf",
	Button_Label_UnfreezeTime = "Zeit auftauen",
	Button_Label_FreezeTime = "Zeit einfrieren",
	Button_Label_OpenLightSettings = "Öffnen Sie die Lichteinstellungen",
	Button_Label_UpdateLightTarget = "Lichtziel aktualisieren",
	Button_Label_Activate = "Aktivieren",
	Button_Label_Deactivate = "Deaktivieren",
	Button_Label_ChangeToCrouchStance = "Wechseln Sie in die geduckte Haltung",
	Button_Label_ChangeToStandStance = "Wechseln Sie in die Standhaltung",
	Button_Label_PickUpTarget = "Ziel aufheben",
	Button_Label_DropTarget = "Ziel fallen lassen",
	Button_Label_FreezeTarget = "Ziel einfrieren",
	Button_Label_UnfreezeTarget = "Ziel freigeben",
	Button_Label_OpenTargetTools = "Öffnen Sie die Zieltools",
	Button_Label_CloseTargetTools = "Schließen Sie die Zieltools",
	
    --Checkbox
    --Warning / Info / Tool Tip
	Warn_FileNotFound_CollabsFolder_Error = "Datei nicht im Collabs-Ordner gefunden",
	Warn_ShowXYZ_Orientation_Info = "Zeigen Sie X-, Y- und Z-Pfeile an, um die Orientierung beim Verschieben des Ziels zu erleichtern.",
	Warn_LookAtCamera_OptionOff_Info = "Schalten Sie die Option „Auf die Kamera schauen“ einmal aus, nachdem Sie diese Einstellung geändert haben",
	Warn_DisableLookAtCamera_PhotoMode_Info = "Deaktivieren Sie „In die Kamera schauen“ im Fotomodus einmal, damit es wirksam wird",
	Warn_RequiresRestart_Info = "Erfordert einen Neustart des Spiels, um wirksam zu werden",
	Warn_SlowMotion_PhotoMode_Info = "Zeitlupe im Fotomodus funktioniert nur, wenn Sie die Pause mithilfe von IGCS aufheben",
	Warn_WeatherControl_RequireCodeware = "Weather Control erfordert Codeware 1.4+",
	Warn_StopNpc_UnequipWeapon_Info = "Dadurch wird verhindert, dass der NPC die Waffe ablegt, die Sie ihm gegeben haben. Hinweis: Der NPC kann sich während des Kampfes immer noch nach Belieben ausrüsten.",
	Warn_OutOfCombat_NpcUnequip_Info = "Hinweis: Außerhalb des Kampfes legt der NPC die jeweilige Waffe sofort ab.",
	Warn_Photomode_UnfreezeSkipFrames_Info = "Im Fotomodus überspringt Unfreeze Target Bilder in animierten Posen. Für die vollständige (Ent-)Freeze-Funktionalität müssen Sie Otis Camera Tools (IGCS) verwenden.",
	Warn_UserLocationsFolder_Info = "Benutzerstandorte werden im Ordner AppearanceMenuMod/User/Locations gespeichert",
	Warn_SeeMoreAction_Info = "Zielen Sie auf V oder NPC, um weitere Aktionen anzuzeigen",
	Warn_SeeMoreActionProp_Info = "Zielen Sie auf einen NPC oder eine Requisite, um weitere Aktionen anzuzeigen",
	Warn_SeamfixPiercingToggle_Info = "Dadurch wird der Status der Make-up-, Piercing- und Seamfix-Schalter gespeichert, bis Sie das Spiel schließen.",
	Warn_PassiveMode_Info = "Feinde werden dich immer noch angreifen, wenn du einen Kampf auslöst",
	Warn_TppCameraGameplay_Info = "Für normales Gameplay ist die TPP-Kamera nicht geeignet, aber für einen Spaziergang macht sie Spaß ;)",
	Warn_AnimatedHead_PhotoMode_Info = "Ausdrücke im Fotomodus funktionieren nicht, wenn „Animierter Kopf“ aktiviert ist.",
	Warn_ToolsOnly_WorksIngame = "Tools funktionieren nur im Spiel",
	Warn_InvButtonMachineGun_Info = "Du hast es gefunden! Schweres Maschinengewehr wurde zu den Ausrüstungen hinzugefügt.",
	Warn_InvButton_Info = "Du hast es gefunden! Fast Motion ist jetzt verfügbar.",
	InvButtonTip = "Was passiert, wenn ich hier klicke?",
	InvButtonTip2 = "Ein Klick hierher bringt nichts!",
	InvButtonTip3 = "KLICKEN SIE NICHT, SIE WURDEN GEWARNT!",
	
    --Text
	Facial_Expression = "Gesichtsausdruck",
	Expressions = "Ausdrücke",
	Look_At = "Schauen Sie sich an",
	Look_At_Camera = "Blick in die Kamera:",
	Target_Tools = "Zielwerkzeuge",
	Rotation = "Rotation",
	Tilt_Rotation = "Neigung/Rotation",
	Mode = "Modus:",
	Precision = "Präzision",
	Relative = "Relativ",
	Direct = "Direkt",
	AdvMovement = "Adv. Bewegung",
	ForceGivenWeapon = "Gewalt gegebene Waffe",
	Scale = "Maßstab",
	ProportionalMode = "Proportionalmodus",
	General_Actions = "Allgemeine Aktionen",
	DisablePassiveMode = "Passivmodus deaktivieren",
	EnablePassiveMode = "Aktivieren Sie den Passivmodus",
	EnableGodMode = "Aktivieren Sie den Gott-Modus",
	DisableGodMode = "Deaktivieren Sie den Gottmodus",
	Infinite_Oxygen = "Unendlicher Sauerstoff",
	Select_Location = "Wählen Sie Standort aus",
	Select_Expression = "Wählen Sie Ausdruck aus",
	Select_Category = "Kategorie auswählen",
	Teleport_Actions = "Teleport-Aktionen",
	Use_Teleport_Animation = "Verwenden Sie Teleport-Animation",
        Filter_Locations = "Standorte filtern",
        Locations = "Standorte",
        Default_Locations = "Standardstandorte",
        Collab_Locations = "Collab-Standorte",
        Button_AddTag = "Tag hinzufügen",
	Button_FilterByTags = "Nach Tags filtern",
	Button_Close = "Schließen",
	Favorite_Selected_Location = "Als Favorit ausgewählter Ort",
	Unfavorite_Selected_Location = "Ausgewählten Standort als Favorit entfernen",
	Edit_Selected_Location = "Ausgewählten Standort bearbeiten",
	Locations_Favorites = "--------- Favoriten ----------",
	Locations_UserLocs = "------- Benutzerstandorte -------",
	Locations_DefaultLocs = "----------- Standard ----------",
	Share_Location = "Standort teilen",
	Edit_Location = "Standort bearbeiten",
	TimeWeather_Actions = "Zeit- und Wetteraktionen",
	TimeofDay = "Tageszeit",
	Time_Actions = "Zeitaktionen",
	Rain = "Regen",
	Light_Rain = "Leichter Regen",
	Cloudy = "Bewölkt",
	Fog = "Nebel",
	Heavy_Clouds = "Schwere Wolken",
	Light_Clouds = "Leichte Wolken",
	Pollution = "Verschmutzung",
	Sandstorm = "Sandsturm",
	Sunny = "Sonnig",
	Toxic_Rain = "Giftiger Regen",
	Deep_Blue = "Tiefblau",
	Squat_Morning = "Kniebeugenmorgen",
	Cloudy_Morning = "Bewölkter Morgen",
	Rainy_Night = "Regnerische Nacht",
	Courier_Clouds = "Kurierwolken",
	Cursor_LockState = "Sperrstatus",
	PhotoMode_NibblesReplacer = "Fotomodus-Knabbereien-Ersatz",
	PhotoModeEnhancements = "Verbesserungen im Fotomodus",
	Button_ResetReplacerDatabase = "Ersatzdatenbank zurücksetzen",
	DisablePhotoModeCursor = "Deaktivieren Sie den Fotomodus-Cursor",
	TPPCamera_Position = "TPP-Kameraposition",
	AnimatedHeadin_PhotoMode = "Animierter Kopf im Fotomodus",
	LockLook_AtCamera = "Blick in die Kamera sperren",
	UnlockLook_AtCamera = "Schalten Sie „Blick in die Kamera“ frei",
	Save_Toggles_State = "Speichern schaltet den Status um",
	Toggle_V_Head = "V-Kopf umschalten",
	Toggle_TPP_Camera = "TPP-Kamera umschalten",
	Target_Nibbles = "Ziel-Knabbereien",
	Target_Replacer = "Zielersatz",
	Left = "Links",
	Left_Close = "Links nah",
	Right = "Richtig",
	Right_Close = "Ganz nah dran",
	Center_Close = "Mitte schließen",
	Center_Far = "Mitte weit",
	Front_Close = "Vorne schließen",
	Front_Far = "Vorne weit",
	All = "Alle",
	Head_Only = "Nur Kopf",
	Eyes_Only = "Nur für die Augen",
	Movement = "Bewegung",
	V_Actions = "V-Aktionen",
	Invisible_V = "Unsichtbares V",
	LikeGTA_byGTATravel = "von GTA Travel",
	EnableSpawnedProps = "Aktiviere gespawnte Requisiten",
	LightControl = "Lichtsteuerung",
	Equipment = "Ausrüstung",
	
	-- >> DIRECTOR TAB
	BeginItem_TabNameDirector = "Regisseur",
	BeginItem_TabNameTriggers = "Auslöser",
	BeginCombo_StartAppearance = "Starten Sie das Erscheinungsbild",
	BeginCombo_EndAppearance = "Auftritt beenden",
	BeginCombo_Type = "Typ",
	BeginCombo_GoToTarget = "Gehe zum Ziel",
	BeginCombo_PlayVoice = "Stimme abspielen",
	BeginCombo_Attack = "Angriff",
	BeginCombo_Triggers = "Auslöser",
	BeginCombo_Scripts = "Skripte",
	
	--Button
	Button_Yes = "Ja",
	Button_No = "Nein",
	Button_SaveChangesOnly = "Nur Änderungen speichern",
	Button_RemoveMark = "Markierung entfernen",
	Button_EditMark = "Mark bearbeiten",
        Button_MoveMark = "Markierung verschieben",
        Button_MoveUp = "Nach oben bewegen",
        Button_MoveDown = "Nach unten bewegen",
        Button_NewMark = "Neue Marke",
	Button_AddActor = "Schauspieler hinzufügen",
	Button_RemoveActor = "Schauspieler entfernen",
	Button_ChangeActor = "Schauspieler wechseln",
	Button_RadioOnlyOne = "OnlyOne",
	Button_RadioRandom = "Zufällig",
	Button_RadioSequential = "Sequentielle",
	Button_SaveTrigger = "Auslöser speichern",
	Button_NewCamera = "Neue Kamera",
	Button_NewScript = "Neues Skript",
	Button_DragSpeed = "Geschwindigkeit",
	Button_ToggleMarker = "Markierung umschalten",
	Button_TestPose = "Testpose",
	Button_StopPose = "Stoppen Sie die Pose",
	
    --Button Label
	Button_Label_PlayScript = "Skript abspielen",
	Button_Label_StopScript = "Stoppen Sie das Skript",
	Button_Label_Stopping = "Stoppen...",
	Button_Label_Restarting = "Neustart...",
	Button_Label_AddMark = "Mark hinzufügen",
	Button_Label_SaveWNewPos = "Mit neuer Position speichern",
	
    --Checkbox
    --Warning / Info / Tool Tip
	Warn_ActorSingleMark_Info = "Der Schauspieler bleibt bei einer einzigen Mark",
	Warn_ActorRandomMark_Info = "Der Schauspieler wechselt zufällig zwischen den Markierungen",
	Warn_ActorSequentialMark_Info = "Der Schauspieler bewegt sich in numerischer Reihenfolge zwischen den Markierungen",
	Warn_DeleteScript_Info = "Möchten Sie dieses Skript wirklich löschen?",
	Warn_CloseCamForMove_Info = "Schließen Sie das Menü, um die Kamera bewegen zu können",
	Warn_CreateScriptsDesc_Info = "Erstellen Sie Skripte, um Schauspieler für Machinima, Screenshots und Rollenspiele hinzuzufügen, einzukleiden und anzuweisen.",
	Warn_PremadeScriptsDesc_Info = "Erstellen Sie Trigger, um vorgefertigte Skripte bei Kontakt zu aktivieren.",
	Warn_CreateCamera_FovZoomDesc_Info = "Erstellen Sie Kameras, um sich frei zu bewegen, und stellen Sie verschiedene Sichtfelder und Zoomstufen ein.",
	Warn_ShowMarksLocations_Info = "Zeigt ein sichtbares Symbol an Markierungspositionen an",
	Warn_AutoTalkNpc_Info = "Dadurch sprechen NPCs einmal pro Minute, wenn sie sich in Reichweite befinden (nur NPCs mit Stimme).",
	Warn_DirectActorPlayerPosition_Info = "Erstellen Sie eine Markierung an der aktuellen Spielerposition, um Schauspieler zu bewegen und zu leiten",
	Warn_InMenuDirectorDesc = "Director funktioniert nur im Spiel",
	
    --Text
	DirectorMode = "Regisseurmodus",
	SelectActorToReplace = "Wählen Sie den zu ersetzenden Schauspieler aus:",
	AddActorToCurrentScript = "Schauspieler zum aktuellen Drehbuch hinzufügen:",
	FacialExpression_WithColon = "Gesichtsausdruck:",
	FavoritePoses_WithColon = "Lieblingsposen:",
	AddFavorites_Desc = "Fügen Sie zuerst Posen zu den Favoriten auf der Registerkarte „Posen“ hinzu",
	HoldDuration = "Haltedauer",
	Movement2 = "Bewegung:",
	Actions = "Aktionen:",
	Actors = "Schauspieler",
	Editing = "Bearbeiten",
	AutoTalk = "Auto Talk",
	ActorMarks = "Schauspielermarken",
	Current_Actors = "Aktuelle Schauspieler",
	Marks_Sequence = "Reihenfolge der Markierungen:",	
	ShowMarks = "Markierungen anzeigen",
	Triggers = "Auslöser",
	NewTrigger = "Neuer Auslöser",
	ShowTrigger = "Auslöser anzeigen",
	Title = "Titel",
	Select_Trigger = "Wählen Sie Auslöser",
	Select_Script = "Wählen Sie Skript",
	Delete_Trigger = "Trigger löschen",
	Triggers_On_Off = "Löst Ein/Aus aus",
	Running = "Laufen",
	Script_Running = "Skript wird ausgeführt...",
	Delete_Script = "Skript löschen",
	RepeatInLoop = "In Schleife wiederholen",
	ActivationRadius = "Aktivierungsradius",
	Activate = "Aktivieren",
	Deactivate = "Deaktivieren",
	FOV = "Sichtfeld",
	Zoom = "Zoomen",
	LockFrame = "Rahmen sperren",
	Walk = "Gehen",
	Sprint = "Sprint",
	Sequential = "Sequentielle",
	Cameras = "Kameras",
	NodeView = "Knotenansicht",
	TeamA = "Team A",
	TeamB = "Team B",
	
	
	
	-- >> SETTINGS TAB
	BeginItem_TabNameSettings = "Einstellungen",
	BeginItem_TabNameGeneral = "Allgemein",
	BeginItem_TabNameCompanions = "Begleiter",
	BeginItem_TabNameUI = "Benutzeroberfläche",
	BeginItem_TabNameExperimental = "Experimentell",
	BeginItem_TabNamePhotoMode = "Fotomodus",
	
	--Button
	Button_RevertAllModelSwaps = "Alle Modellwechsel rückgängig machen",
	Button_RespawnAll = "Alle wieder spawnen",
	Button_ForceDespawnAll = "Alle despawnen erzwingen",
	Button_ClearFavorites = "Favoriten löschen",
	Button_ClearAllSavedAppearances = "Alle gespeicherten Erscheinungsbilder löschen",
	Button_ClearAllBlacklistedAppearances = "Löschen Sie alle Auftritte auf der schwarzen Liste",
	Button_ClearAllAppearanceTriggers = "Löschen Sie alle Erscheinungsauslöser",
	Button_ClearAllSavedDespawns = "Löschen Sie alle gespeicherten Despawns",
	Button_SmallCreateTheme = "Thema erstellen",
	Button_SmallDeleteTheme = "Thema löschen",
	Button_SmallSet = "Set",
	Button_ReloadAppearances = "Benutzerdefinierte Erscheinungsbilder neu laden",
	
    --Button Label
    --Checkbox
	Checkbox_SpawnAsCompanion = "Als Begleiter spawnen",
	Checkbox_SpawnAsFriendly = "Als freundlich spawnen",
	Checkbox_InvulnerableCompanion = "Unverwundbarer Begleiter",
	Checkbox_RespawnOnLaunch = "Respawn beim Start",
	Checkbox_LockTargetAfterSpawn = "Ziel nach Spawn sperren",
	Checkbox_OpenTargetToolsAfterSpawn = "Öffnen Sie die Zieltools nach dem Spawnen",
	Checkbox_DisplayAxisIndicatorByDefault = "Achsenanzeige standardmäßig anzeigen",
	Checkbox_PhotoModeEnhancements = "Verbesserungen im Fotomodus",
	Checkbox_GodModeOnLaunch = "Gott-Modus beim Start",
	Checkbox_PassiveModeOnLaunch = "Passiver Modus beim Start",
	Checkbox_StreamerMode = "Streamer-Modus",
	Checkbox_OpenWCETOverlay = "Mit CET-Overlay öffnen",
	Checkbox_AutoResizingWindow = "Automatische Größenänderung des Fensters",
	Checkbox_ScanningReticle = "Absehen scannen",
	Checkbox_FloatingTargetTools = "Schwebende Zielwerkzeuge",
	Checkbox_TabHeaderDescriptions = "Beschreibungen der Registerkartenüberschriften",
	Checkbox_ExpandFavoritesByDefault = "Erweitern Sie standardmäßig die Favoriten",
	Checkbox_EnableScrollBars = "Bildlaufleisten aktivieren",
	Checkbox_AlwaysDisablePhotoModeCursor = "Deaktivieren Sie den Cursor im Fotomodus immer",
	Checkbox_Camera = "Kamera",
	Checkbox_DepthOfField = "DOF",
	Checkbox_Effect = "Wirkung",
	Checkbox_Stickers = "Aufkleber",
	Checkbox_LoadSave = "Laden/Speichern",
	Checkbox_ExperimentalFunstuff = "Experimentelles/lustiges Zeug",
	Checkbox_EnableFreezeTargetInPhotoMode = "Aktivieren Sie „Ziel einfrieren“ im Fotomodus",
	Checkbox_WeaponizeCompanions = "Bewaffnung von Gefährten",
	Checkbox_AllowPlayerToBeTargetedinPosestab = "Auf der Registerkarte „Posen“ können Spieler als Ziel ausgewählt werden",
	Checkbox_AllowPlayerAnimationsonNPCs = "Spieleranimationen auf NPCs zulassen",
	Checkbox_AllowExpressionOnNpcPM = "Erlaube Ausdrücke und suche im Fotomodus nach NPCs",
        Checkbox_ResetTargetPositionPM = "Setzen Sie die Zielposition für NPCs im Fotomodus zurück",
        Checkbox_EnableRandomLocation = "Schaltfläche „Zufällig aktivieren“: Teleportiert den Spieler an einen zufälligen Ort aus der Liste",
        Checkbox_RestoreOnLaunch = "Beim Start wiederherstellen",
        Radio_PrimarySlot = "Primärer Steckplatz",
        Radio_SecondarySlot = "Sekundärer Steckplatz",
	
    --Warning / Info / Tool Tip
	Warn_RespawnOnLaunch_Info = "Diese Einstellung aktiviert/deaktiviert das Respawnen zuvor gespeicherter NPCs beim Laden des Spiels. AMM speichert automatisch Ihre gespawnten NPCs, wenn Sie das Spiel verlassen.",
	Warn_BannedWords_Info = "Diese Einstellung aktiviert/deaktiviert NPC-Auftritte, die die Wörter „naked“, „nude“, „xxx“, „shower“, „birthday_suit“, „pp“ und „penis“ enthalten.",
	Warn_TargetNpcVehicleHotkey = "Zielen Sie auf einen NPC oder ein Fahrzeug, um Hotkeys festzulegen",
	Warn_FirstLaunchDecideTabsExpand_Info = "Diese Einstellung erweitert standardmäßig die Favoriten in den Registerkarten „Spawn“, „Tausch“ und „Dekor“, wenn AMM zum ersten Mal gestartet wird.",
	Warn_ExperimentalTabDesc_Info = "Experimentelle Funktionen bieten mehr Funktionalität, funktionieren aber möglicherweise nicht so gut, daher die Bezeichnung „experimentell“. Tatsächlich haben die meisten AMM-Benutzer experimentelle Funktionen aktiviert. Machen Sie sich also nicht zu viele Sorgen und haben Sie Spaß!",
	Warn_FreezeTargetPhotoMode_Info = "Diese Einstellung soll dabei helfen, Animationen von Mods einzufrieren, die benutzerdefinierte Animationen zu Posen im Fotomodus hinzufügen, oder wenn Sie die Pause mit IGCS aufheben.",
	Warn_WeaponizeCompanions_Info = "Dadurch erhalten alle NPCs Waffen und Kampffähigkeiten. T-Posing und seltsame Animationen werden erwartet.",
	Warn_PlayerAnimsOnNpc_Info = "Aktivieren Sie dies, wenn Sie einen Mod verwenden, der die Verwendung von Spieleranimationen auf NPCs ermöglicht.",
	Warn_UnpauseRequiresIGSC = "Diese Einstellung erfordert, dass IGCS die Zeitpause aufhebt.",
	Warn_NotInstalled = "NICHT INSTALLIERT",
	Warn_DespawnAllProps = "Sind Sie sicher, dass Sie alle Requisiten despawnen möchten?",
	
    --Text
	AMM_Version = "AMM-Version:",
	CET_Version = "CET-Version:",
	Codeware_Version = "Codeware-Version:",
	Game_Version = "Spielversion:",
	Companion_Damage = "Gefährtenschaden:",
	Companion_Resistance = "Gefährtenwiderstand:",
	Companion_Distance = "Begleiterentfernung:",
	xDamage = "x Schaden",
	xResistance = "x Widerstand",
	SavedAppearancesHotkeys = "Hotkeys für gespeicherte Auftritte",
	Favorites = "Favoriten",
	Appearances = "Auftritte",
	Blacklist = "Schwarze Liste",
	AppearanceTriggers = "Erscheinungsauslöser",
	SavedDespawns = "Despawns gerettet",
	Interface_Language = "Schnittstellensprache:",
	Custom_Appearances = "Benutzerdefinierte Auftritte",
	PhotoModeAdjustments = "Anpassungen des Fotomodus:",
	DisablePhotoModeTabs = "Deaktivieren Sie die Registerkarten für den Fotomodus:",
	List_Height = "Listenhöhe",
	Listbox_Themes = "Themen",
	Weaponize = "Bewaffnen",
	NoAppearanceSet = "Kein Erscheinungsbild festgelegt",
	
	
	
	-- >> EXTRA	
	--Texts, warns, tips, info's, buttons and labels etc.
	Seat_FrontRight = "Vorne rechts",
	Seat_BackRight = "Hinten rechts",
	Seat_FrontLeft = "Vorne links",
	Seat_BackLeft = "Hinten links",
	Label_Door = "Tür",
	Label_Window = "Fenster",

	Close = "Schließen",
	Far = "Weit",
	Moderate = "Mäßig",
	
	-- >> Archives Screen
	Warning_MissingRequiredArchives = "AMM fehlt ein oder mehrere erforderliche Archive. Bitte installieren Sie alle fehlenden erforderlichen Archive in Ihrem Archiv/PC/Mod-Ordner.",
	Warning_MissingOptionalArchives = "AMM fehlt ein oder mehrere Archive. Diese sind optional, erweitern aber die Funktionalität von AMM. Sie können diese Warnungen ignorieren, aber AMM funktioniert möglicherweise nicht ordnungsgemäß.",
	
	
	-->> INIT.LUA
	AMMNeedsAttention = "AMM braucht Aufmerksamkeit",
	MISSING_ARCHIVES = "FEHLENDE ARCHIVE",
	VERSION_INFORMATION = "VERSIONSINFORMATIONEN",
	CREDITS = "KREDITE",
	UPDATE_HISTORY = "UPDATE-VERLAUF",
	Updates = "Aktualisierungen",
	MISSING = "FEHLT",
	REQUIRED = "ERFORDERLICH",
	OPTIONAL = "OPTIONAL",
	WHATS_NEW = "WAS IST NEU?", --Line 83 Function Error

	--Button
	Button_Ignorewarningsforthisversion = "Warnungen für diese Version ignorieren",
	Button_Credits = "Credits",
	Button_Cool = "Cool!",

	--Button Label
	Label_SpawnFavorites = "Spawn-Favoriten",
	Label_SwapFavorites = "Favoriten tauschen",
	Label_FavoriteAppearances = "Lieblingsauftritte",
	Label_Cancel = "Abbrechen",

	--Text
	Hotkey_i = "Hotkey %i",

	--Node - Function Error(nil value) 
	Top = "Top", --Line 116
	Bottom = "Unten",
	Off = "Aus",
	
	--Voice Overs
	Label_GreetV = "Grüße V",
	Label_FearFoll = "Angst Fol",
	Label_FearToll = "Angst vor Maut",
	Label_FearBeg = "Angst bitte",
	Label_FearRun = "Angstlauf",
	Label_StealthSearch = "Stealth-Suche",
	Label_StealthDeath = "Heimlicher Tod",
	Label_StealthRestore = "Stealth-Wiederherstellung",
	Label_StealthEnd = "Stealth-Ende",
	Label_CuriousGrunt = "Neugieriger Grunzer",
	Label_GrappleGrunt = "Grapple Grunzen",
	Label_Bump = "Beule",
	Label_VehicleBump = "Fahrzeugstoß",
	Label_TurretWarning = "Turmwarnung",
	Label_OctantWarning = "Oktantenwarnung",
	Label_DroneWarning = "Drohnenwarnung",
	Label_MechWarning = "Mech-Warnung",
	Label_EliteWarning = "Elite-Warnung",
	Label_CameraWarning = "Kamerawarnung",
	Label_EnemyWarning = "Feindwarnung",
	Label_HeavyWarning = "Schwere Warnung",
	Label_SniperWarning = "Scharfschützenwarnung",
	Label_AnyDamage = "Jeglicher Schaden",
	Label_Danger = "Gefahr",
	Label_CombatStart = "Kampfbeginn",
	Label_CombatEnd = "Kampfende",
	Label_CombatTargetHit = "Kampfzieltreffer",
	Label_PedestrianHit = "Fußgängerüberfall",
	Label_LightHit = "Leichter Schlag",
	Label_Curse = "Fluch",
	Label_Irritated = "Gereizt",
	Label_GrenadeThrow = "Granatenwurf",
	Label_Gotakill = "Habe einen Kill!",
	
	--Expressions
	Neutral = "Neutral",
	Joy = "Freude",
	Smile = "Lächle",
	Sad = "Traurig",
	Surprise = "Überraschung",
	Aggressive = "Aggressiv",
	Anger = "Wut",
	Interested = "Interessiert",
	Disinterested = "Desinteressiert",
	Disappointed = "Enttäuscht",
	Disgust = "Ekel",
	Exertion = "Anstrengung",
	Nervous = "Nervös",
	Fear = "Angst",
	Terrified = "Entsetzt",
	Pain = "Schmerz",
	Sleepy = "Schläfrig",
	Unconscious = "Bewusstlos",
	Dead = "Tot",

	-- Extra Expressions
	Frown = "Stirnrunzeln",
	Shocked = "Schockiert",
	Annoyed_2 = "Genervt 2",
	Contempt = "Verachtung",
	Irritated = "Gereizt",
	Sceptical_1 = "Skeptisch 1",
	Sceptical_2 = "Skeptisch 2",
	Annoyed_1 = "Genervt 1",
	Offended = "Beleidigt",
	Disgusted = "Angewidert",
	Disappointed_2 = "Enttäuscht 2",
	Alert = "Alarm",
	Crying = "Weinen",
	Embarrassed = "Peinlich",
	Humiliated = "Gedemütigt",
	Impatient = "Ungeduldig",
	Anguished = "Gequält",
	Worried = "Besorgt",
	Guilty = "Schuldig",
	Grieving = "Trauernd",
	RestrainedAnger = "Zurückhaltende Wut",
	Afraid = "Angst",
	LookingUpAnnoyed = "Genervt nach oben schauen",
	Offended_2 = "Beleidigt 2",
	Resentful = "Nachtragend",
	SadExtra = "Trauriges Extra",
	NervousBreath = "Nervöser Atem",
	ScreamingLong = "Lange schreien",
	ScreamingShort = "Schreiend kurz",
	ScaredBreath = "Angst vor Atem",
	CryingPainful = "Weinen schmerzhaft",
	SelfReflectAnger = "Selbst reflektieren Wut",
	IndulgentSmile = "Nachsichtiges Lächeln",
	Impressed = "Beeindruckt",
	LongSmile = "Langes Lächeln",
	ShortSmile = "Kurzes Lächeln",
	SimpleSmile = "Einfaches Lächeln",
	Confident = "Zuversichtlich",
	Relief = "Erleichterung",
	Impressed_2 = "Beeindruckt 2",
	Admiring = "Bewundern",
	Fascinated = "Fasziniert",
	RaisedBrows = "Hochgezogene Augenbrauen",
	LookingUpThinking = "Nachschlagen und denken",
	LeftGlanceProcessing = "Verarbeitung des linken Blicks",
	LeftGlanceCloseUp = "Linker Blick, Nahaufnahme",
	LookingAround = "Sich umsehen",
	LookingDownThinking = "Nach unten schauen und denken",
	LookingAroundAlt = "Sich umschauen Alt",
	EyesDartFromLeft = "Augen schießen von links",
	EyesDartFromRight = "Augen huschen von rechts",
	EyesDartToRight = "Augen huschen nach rechts",
	LookingLeft = "Blick nach links",
	LookingUpThinking_2 = "Nachschlagen und Denken 2",
	RightGlanceProcessing = "Right-Glance-Verarbeitung",
	LookingDown = "Nach unten schauen",
	Left90GlanceClose = "Left90Blick Schließen",
	LookingUp = "Nach oben schauen",
	Right90GlanceClose = "Rechts90Blick schließen",
	LookingLeftUp = "Nach links oben schauen",
	LookingRightUp = "Ich schaue direkt nach oben",
	ReadingDown = "Nachlesen",
	ReadingUp = "Nachlesen",
	ReadingMiddle = "Mitte lesen",
	FrontCloseGlance = "Vorderer Nahblick",
	WinkLeft = "Wink links",
	EyeRoll = "Augenrollen",
	Squint = "Schielen",
	FalseSmile_2 = "Falsches Lächeln 2",
	FalseSmile_1 = "Falsches Lächeln 1",
	ListeningNewInfo = "Neue Informationen anhören",
	WhatDoYouWant = "Was willst du?",
	Maybe = "Vielleicht",
	SearchingForWords = "Auf der Suche nach Wörtern",
	What = "Was",
	Where = "Wo",
	SureSure = "Sicher, sicher",
	ListenToMe = "Hör mir zu",
	StopThePolice = "Stoppen Sie die Polizei",
	HurryUp = "Beeilen Sie sich",
	ShutUp = "Halt die Klappe",
	WinkRight = "Zwinkere richtig",
	MockingSmile = "Spöttisches Lächeln",
	AsymmetricalSmile = "Asymmetrisches Lächeln",
	SarcasticSmile = "Sarkastisches Lächeln",
	Sex = "Sex",
	LipBite_1 = "Lippenbiss 1",
	LipBite_2 = "Lippenbiss 2",
	Moan = "Stöhnen",
	LipBite_3 = "Lippenbiss 3",
	Pout = "Schmollmund",
	SexySmile = "Sexy Lächeln",
	Swallow = "Schlucken",
	SensualSmile = "Sinnliches Lächeln",
	SexScene_1 = "Sexszene 1",
	SexScene_2 = "Sexszene 2",
	Kiss = "Kuss",
	UsingInhaler = "Verwendung eines Inhalators",
	ShortYawn = "Kurzes Gähnen",
	Yawn = "Gähn",
	Coughing = "Husten",
	Bite = "Biss",	
	EatingFast = "Schnell essen",
	ShortDrink = "Kurzer Drink",
	Drinking = "Trinken",
	FastBite = "Schneller Biss",
	LongDrink = "Longdrink",
	ShortSmoking = "Kurzes Rauchen",
	LongSmoking = "Langes Rauchen",
	Smoking = "Rauchen",
	Eating_1 = "Essen 1",
	Eating_2 = "Essen 2",
	Eating_3 = "Essen 3",
	Eating_4 = "Essen 4",
	Vomit = "Erbrechen",
	BeingRevived = "Wiederbelebt werden",
	MalwarePositive = "Malware positiv",
	MalwareNegative = "Malware negativ",
	MalwareInfected = "Malware infiziert",
	FaceMorphActivate = "Face Morph aktivieren",
	LieNetChairSleep = "Lie Net Chair Sleep",
	LieNetChairBreathe = "Lie Net Chair Atme",
	NetrunnerDeathUnplugged = "Netrunner Death Unplugged",
	VeryItchyNose = "Sehr juckende Nase",
	RollerCoasterNervous = "Achterbahnfahrt nervös",
	Pfft = "Pfft",
	Hahaha = "Hahaha",
	Sniff = "Schnüffel",
	Ahaaa = "Ahaaa",
	Heh = "Heh",
	Huh = "Huh",
	Haaa = "Haaa",
	Sigh_Lipsync = "Seufz Lipsync",
	Hmm = "Hmm",
	Whispering_1 = "Flüstern 1",
	Whispering_2 = "Flüstern 2",
	ApprovalYes = "Genehmigung Ja",
	SubtleYes = "Subtil Ja",
	QuickNoShake = "Schnell ohne Schütteln",
	FirmYes = "Fest Ja",
	LongNo = "Lange Nr",
	SubtleNo = "Subtiles Nein",
	NoContempt = "Keine Verachtung",
	NoDisapproval = "Keine Missbilligung",
	FirmNo = "Firmennr",
	NoEnthusiastic = "Keine Begeisterung",
	MockingYes = "Verspottend Ja",
	EnthusiasticYes = "Begeistert Ja",
	AsymmetricalCornerUp = "Asymmetrische Ecke nach oben",
	CornersUp = "Ecken hoch",
	SoftSigh = "Leiser Seufzer",
	BreathGasp = "Atem schnappen",
	AssymetricalSneer = "Asymmetrisches Hohnlächeln",
	CrimpingLips = "Kräuselnde Lippen",
	BrowsDown = "Brauen nach unten",
	BrowsLeftUp = "Augenbrauen nach oben gelassen",
	BrowsRightUp = "Brauen direkt nach oben",
	BrowsUp = "Augenbrauen hoch",
	ClosedEyes_1 = "Geschlossene Augen 1",
	ClosedEyes_2 = "Geschlossene Augen 2",
	EyesClosed = "Augen geschlossen",
	LookRight = "Schauen Sie richtig",
	FastBlink = "Schnelles Blinken",
	SlowBlink = "Langsames Blinken",
	NormalBlink = "Normales Blinken",
	TinyBlink = "Winziges Blinzeln",
	HalfBlink = "Halbes Blinzeln",
	RegularSaccade = "Regelmäßige Sakkade",
	FrequentSaccade = "Häufige Sakkaden",
	PhotoCloseupEyes = "Foto Nahaufnahme Augen",
	PhotoCloseupLips = "Foto Nahaufnahme Lippen",
	PhotoCloseupHair = "Foto Nahaufnahme Haar",
	PhotoCloseupChin = "Foto Nahaufnahme Kinn",
	PhotoCloseupNose = "Foto Nahaufnahme der Nase",
	PhotoCloseup = "Foto-Nahaufnahme",
	PhotoCloseupPleased = "Foto Nahaufnahme zufrieden",
	PhotoCloseupBody = "Foto Nahaufnahme Körper",
	PhotoCloseupTeeth = "Foto Nahaufnahme Zähne",
	PhotoCloseupIN = "Foto Nahaufnahme IN",
	PhotoCloseupOUT = "Foto Nahaufnahme OUT",
	Bored = "Gelangweilt",
	Charming = "Charmant",
	Furious = "Wütend",
	Happy = "Glücklich",
	Pissed = "Angepisst",
	Pleased = "Zufrieden",
	Scared = "Angst",
	Surprised = "Überrascht",
	Sadness = "Traurigkeit",
	Whistling = "Pfeifen",
	Singing_1 = "Gesang 1",
	Singing_2 = "Gesang 2",
	Singing_3 = "Gesang 3",
	Alerted = "Alarmiert",
	Hit_1 = "Schlagen Sie 1",
	Hit_2 = "Schlag 2",
	Wounded = "Verwundet",
	Death = "Tod",

	-- Expressions Category
	Negative = "Negativ",
	Positive = "Positiv",
	Contemplative = "Nachdenklich",
	Social = "Sozial",
	Sexual = "Sexuell",
	Action = "Aktion",
	Vocal = "Gesang",
	Yes_N_No = "Ja und Nein",
	Nuance = "Nuance",
	Static = "Statisch",
	Combat = "Kampf",
	
	--Props
	AMM_Props_Desc = "Fügt Requisiten, Charaktere und Fahrzeuge hinzu. Ohne dies wird AMM nicht starten.",
	AMM_JohnnyCompanion_Desc = "Fügt Johnny Silverhand als spawnbaren Charakter hinzu.",
	AMM_ScenesPack_Desc = "Fügt dem Posensystem 9358 Szenenanimationen hinzu.\nLaden Sie es auf der Nexus-Seite von AMM herunter.",
	AMM_SoundPack_Desc = "Fügt spawnbare Soundeffekte hinzu.",
	AMM_KerryPP_Desc = "Fügt ein neues nacktes Erscheinungsbild hinzu.",
	AMM_BenjaminStonePP_Desc = "Fügt ein neues nacktes Erscheinungsbild hinzu.",
	AMM_RiverPP_Desc = "Fügt ein neues nacktes Erscheinungsbild hinzu.",
	AMM_YorinobuPP_Desc = "Fügt ein neues nacktes Erscheinungsbild hinzu.",
	AMM_LizzyIncognito_Desc = "Fügt ein neues Erscheinungsbild hinzu.",
	AMM_MeredithXtra_Desc = "Fügt ein neues Erscheinungsbild hinzu.",
	AMM_DelamainFix_Desc = "Verleiht Delamain mehr Fülle.",
	AMM_HanakoNoMakeup_Desc = "Ermöglicht AMM, Hanakos Make-up zu entfernen, wenn „Benutzerdefiniertes Erscheinungsbild“ verwendet wird.",
	AMM_JudyBodyRevamp_Desc = "Ersetzt Judys Körper durch einen neuen, verbesserten.",
	AMM_PanamBodyRevamp_Desc = "Ersetzt Panams Körper durch einen neuen, verbesserten.",
	AMM_MistyBodyRevamp_Desc = "Ersetzt Mistys Körper durch einen neuen, verbesserten.\nLaden Sie es auf der Nexus-Seite von AMM herunter.",
	AMM_1VesHanakoFixedBodyNaked_Desc = "Ersetzt Hanakos Körper durch einen neuen, verbesserten.",
	AMM_PinkyDudeANIMFacialExpressionsFemV_Desc = "Aktiviert Mimik-Tools für Female V",
	AMM_PinkyDudeANIMFacialExpressionsMaleV_Desc = "Aktiviert Mimik-Tools für Male V",
	AMM_DinoTattooFixArchive_Desc = "Ersetzt Mesh und Textur.",
	AMM_SongbirdBodyFixArchive_Desc = "Ersetzt den Textkörper, um den Graubereich zu beheben. Noch nicht perfekt.",
	AMM_RitaWheelerCombatEnablerArchive_Desc = "Ersetzt die Entity-Datei, um Kampfanimationen zu ermöglichen.",
	AMM_CheriAppearances_Desc = "Fügt neue Erscheinungsbilder hinzu. Laden Sie es auf der Nexus-Seite von AMM herunter.",
	AMM_BryceNaked_Desc = "Fügt ein neues nacktes Erscheinungsbild hinzu. Laden Sie es auf der Nexus-Seite von AMM herunter.",
	AMM_EvelynNaked_Desc = "Fixiert ihren Körper, um ein nacktes Aussehen zu ermöglichen. Laden Sie es auf der Nexus-Seite von AMM herunter.",
	AMM_SaburoAppearances_Desc = "Fügt neue Erscheinungsbilder hinzu. Laden Sie es auf der Nexus-Seite von AMM herunter.",
	AMM_TbugAppearances_Desc = "Fügt neue Erscheinungsbilder hinzu. Laden Sie es auf der Nexus-Seite von AMM herunter.",
	AMM_8ug8eagAppearances_Desc = "Fügt neue Erscheinungsbilder hinzu. Laden Sie es auf der Nexus-Seite von AMM herunter.",
	
	--Equipments (There is a Function Error(nil value) in this section, These are just labels that are not connected to any localizable strings in the file)
	Fists = "Fäuste", --Line 2377 
	Katana = "Katana",
	Mantis_Blades = "Mantis-Klingen",
	Machete = "Machete",
	Hammer = "Hammer",
	Baton = "Taktstock",
	Knife = "Messer",
	Crowbar = "Brecheisen",
	Baseball_Bat = "Baseballschläger",
	Assault_Rifle = "Sturmgewehr",
	Sidewinder = "Sidewinder",
	Sniper_Rifle = "Scharfschützengewehr",
	Shotgun = "Schrotflinte",
	SMG = "SMG",
	Handgun = "Pistole", --Line 2391
	
	--Warning / Info / Tooltip
	Warn_CantSave_BlacklistedAppearance = "Sie können einen Auftritt auf der schwarzen Liste nicht speichern!",
	Warn_ConfirmDeleteSavedAppearances = "Sind Sie sicher, dass Sie alle Ihre gespeicherten Auftritte löschen möchten?",
	Warn_ConfirmDeleteBlacklistedAppearances = "Sind Sie sicher, dass Sie alle Ihre auf der schwarzen Liste stehenden Auftritte löschen möchten?",
	Warn_ConfirmDeleteSavedDespawns = "Sind Sie sicher, dass Sie alle Ihre gespeicherten Despawns löschen möchten?",
	Warn_ConfirmDeleteAppearanceTriggers = "Sind Sie sicher, dass Sie alle Ihre Erscheinungsauslöser löschen möchten?",
	Warn_ConfirmDeleteCurrentAppearance = "Sind Sie sicher, dass Sie Ihre aktuell aktive Voreinstellung löschen möchten?",
	Warn_WeaponizeNpcAnimationIssues = "Nicht jeder NPC verfügt über die notwendigen Animationen, um jede Art von Waffe zu verwenden. Es kann zu T-Posing und falschen Animationen kommen.\nSind Sie sicher, dass Sie es aktivieren möchten?",
	Warn_ConfirmEnableExperimentalAndSave_Info = "Sind Sie sicher, dass Sie experimentelle Funktionen aktivieren möchten? AMM funktioniert möglicherweise nicht wie erwartet. Die Nutzung erfolgt auf eigene Gefahr!",
	Warn_DeleteFavoritesAskWhichOne_Info = "Wenn Sie sicher sind, dass Sie alle Ihre Favoriten löschen möchten, wählen Sie unten aus, welchen:",
	Popup_Error_Title = "Fehler",
	Button_Ok = "Okay",
	Popup_FavoriteName = "Lieblingsname",
	Popup_RenamePreset = "Voreinstellung umbenennen",
	Popup_RenameProp = "Requisite umbenennen",
	Editor_Title = "Theme-Editor",
	Editor_Field_ThemeName = "Themenname",
	Editor_Hint_InsertThemeName = "Geben Sie einen neuen Theme-Namen ein",
	Error_ThemeNameExists = "Der Theme-Name ist bereits vorhanden",
}
