return {

    -- >> SCAN TAB
	BeginItem_TabNameScan = "Escanear",
	
	--Button
	Button_CyclesAppearances = "Apariencia del ciclo",
	Button_SavesAppearance = "Guardar apariencia",
	Button_ClearSavedAppearance = "Borrar apariencia guardada",
	Button_UnlockDoor = "Cerradura de puerta de palanca",
	Button_RestoreAccess = "Restaurar acceso",
	Button_UnlockVehicle = "Desbloquear vehículo",
	Button_RepairVehicle = "Reparación de vehículos",
	Button_OpenCloseDoors = "Abrir/cerrar puertas",
	Button_OpenCloseWindows = "Abrir/cerrar ventanas",
	Button_ToggleEngine = "Alternar motor",
	Button_ToggleAIDriver = "Alternar controlador AI",
	Button_ToggleCamera = "Alternar cámara",
	Button_ToggleRadio = "Alternar radio",
	Button_NextRadioStation = "Próxima emisora de radio",
	Button_TargetMountedVehicle = "Vehículo montado en el objetivo",
	Button_AssignSeats = "Asignar asientos",
	Button_Assign = "Asignar",
	Button_Reset = "Reiniciar",
	Button_FakeDie = "Troquel falso",
	Button_SmallCopy = "Copiar",
	
    --Button Label
	Button_Label_Unfollower = "Dejar de seguir",
	Button_Label_Follower = "seguidor",
	Button_Label_SaveDespawn = "Guardar Despawn",
	Button_Label_ClearSavedDespawn = "Borrar desaparición guardada",
	Button_LabelLockTarget = "Bloquear objetivo",
	Button_LabelUnlockTarget = "Desbloquear objetivo",
	Label_AddToSpawnFavs = "Agregar a favoritos generables",
	Label_RemoveFromSpawnFavs = "Eliminar de favoritos generables",
	
    --Checkbox
	Checkbox_SavedDespawnsActive = "Desapariciones guardadas activas",
	Checkbox_KeepAssigned = "Mantener asignado al cambiar de automóvil",
	
    --Warning / Info / Tool Tip
	WarnTextAI_FastTravel = "Seleccione un punto de viaje rápido en su mapa para comenzar",
	WarnText_DontReloadMods = "No utilices Recargar todas las modificaciones.\nVuelve a cargar tu partida guardada o muévete a un área diferente.",
	Warning_NoTarget_Desc = "¡Sin objetivo! Mira el NPC, vehículo u objeto para comenzar.",
	ToolTip_DisableCheckboxReloadSave_AbleTotargetClearSavedDespawns = "Desactive esta casilla de verificación y vuelva a cargar su partida guardada para poder apuntar a Borrar Despawns guardados.",
	
    --Text
	Build_Mode = "Modo de construcción",
	Speed = "Velocidad:",
	Search = "Buscar",
	Clear = "Borrar",
	Player = "Jugador",
	Saved = "Guardado",
	Saved_ = "Guardado_",
	Current = "Actual",
	Current_ = "Actual",
	Select_Seat = "Seleccionar asiento",
	Target_Info = "Información del objetivo",
	Target_Actions = "Acciones objetivo",
	No_Appearances = "Sin apariciones",
	No_Target = "Sin objetivo",
	Favorite_Appearance = "Aparición favorita",
	Unfavorite_Appearance = "Apariencia no favorita",
	Blacklist_Appearance = "Aparición en la lista negra",
	Unblacklist_Appearance = "Apariencia no lista negra",
	Saved_Appearance = "Apariencia guardada:",
	Current_Appearance = "Apariencia actual:",
	List_of_Appearances = "Lista de apariciones",
	Appearance_Trigger = "Activador de apariencia",
	None = "Ninguno",
	Default = "Predeterminado",
	Zone = "Zona",
	Area = "Área",
	Position = "Posición",

	
	-- >> SPAWN TAB
	BeginItem_TabNameSpawn = "engendrar",
	
	--Button
	Button_Refresh = "Actualizar",
	Button_Save = "Guardar",
	Button_Confirm = "Confirmar",
	Button_Cancel = "Cancelar",
	Button_SmallSave = "Guardar",
	Button_SmallRespawn = "Reaparecer",
	Button_SmallDespawn = "Desaparecer",
	Button_SmallDespawn_WithSpace = "Desaparecer",
	Button_SmallTarget = "Objetivo",
	Button_SmallEquipment = "Equipo",
	Button_LabelHostile = "hostil",
	Button_LabelFriendly = "amigable",
	
    --Button Label
	Label_Favorite = "Favorito",
	Label_Unfavorite = "No favorito",
	
    --Checkbox
    --Warning / Info / Tool Tip
	Warn_PlayerInMenu = "Jugador en el menú",
	Warn_AMMonlyfunctions_ingame = "AMM solo funciona en el juego",
	Warn_SpawnWorksInGame = "El desove solo funciona en el juego.",
	Warn_InitError = "Error de inicialización",
	Warn_InitError_Info = "Consulte AppearanceMenuMod.log para obtener más información.",
	
    --Text
	Active_Spawns = "Engendros activos",
	NoActiveSpawns = "No hay engendros activos",
	Select_To_Spawn = "Seleccionar para generar",
	No_Results = "Sin resultados",
	ItsEmpty = "Esta vacio :(",
	Existing_Name = "Nombre existente",
	Name = "Nombre",
	
	
	
	-- >> SWAP TAB
	BeginItem_TabNameSwap = "Intercambiar",
	
	--Button
	Button_SmallRevert = "Revertir",
	
    --Button Label
    --Checkbox
    --Warning / Info / Tool Tip
	Warn_ReloadSaveUpdateChanges = "¡Recarga tu partida guardada para actualizar los cambios!",
	Warn_NeedReloadSaveUpdateChanges = "Deberá volver a cargar su archivo guardado para actualizar los cambios.",
	Warn_ReplacerSwap = "¡No puedes cambiar el sustituto! Utilice la pestaña de herramientas en el modo foto para apuntar a ellos, luego cambie su apariencia desde la pestaña Generar o las Herramientas de destino.",
	Warning = "ADVERTENCIA",
	Warning2 = "ADVERTENCIA:",
	SaveSwap_Tooltip = "Guarda tus intercambios para conservarlos después de recargar tu juego.",
	
    --Text
	CantSwapReplacer = "No se puede cambiar el reemplazo",
	Active_Model_Swaps = "Intercambios de modelos activos",
	Save = "Guardar",
	Restore = "Restaurar",
	Current_Target = "Objetivo actual:",
	Target_ID = "ID de objetivo:",
	SelectSwap_CurrentTarget = "Seleccione para intercambiar con el objetivo actual:",
	NoNPC_LookNPC = "¡No se encontró ningún PNJ! Mira al NPC para comenzar.",
	
	-- Locations Categories
	Residences = "Residencias",
	ArasakaAndCorpo = "Arasaka & Corpo",
	ClubsAndBars = "Discotecas y bares",
	HotelsAndPleasure = "Hoteles y Placer",
	UndergroundAndCrime = "Metro y crimen",
	GovernmentAndSecurity = "Gobierno y seguridad",
	StoryAndUnique = "Historia y Único",
	Ripperdocs = "Destripadores",
	LandmarksAndOpenWorld = "Monumentos y mundo abierto",
	SpoilersAndHidden = "Spoilers y ocultos",
	UserLocations = "Ubicaciones de usuarios",
	
	
	-- >> DECOR TAB
	BeginItem_TabDecor = "Decoración",
	BeginItem_TabPresets = "Preajustes",
	Begin_ComboPresets = "Preajustes",
	
	--Button
	Button_SmallClone = "clonar",
	Button_SmallRemove = "Eliminar##",
	Button_SmallRename = "Cambiar nombre##",
	Button_SmallUpdate = "Actualización##",
	Button_SmallCancel = "Cancelar",
	Button_Frame = "marco",
	
    --Button Label
	Button_LabelHide = "Ocultar",
	Button_LabelUnhide = "Mostrar",
	
    --Checkbox
    --Warning / Info / Tool Tip
	Warn_PersistPropSave = "¡Utiles de generación para decorar tu casa o cualquier lugar que desees a tu gusto! ¡Guarda accesorios para que persistan!",
	Warn_DespawnInProgress_PleaseWait = "Desaparición en progreso. Espere por favor.",
	Warn_PresetsFolder_Info = "Los ajustes preestablecidos del usuario se guardan en la carpeta AppearanceMenuMod/User/Decor",
	Warn_CustomPresets_Info = "Este ajuste preestablecido incluye accesorios personalizados",
	Warn_CustomPropsModders_Info = "Accesorios personalizados hechos por:",
	Warn_GamepadDirectMode_Info = "Esto permite una mejor integración con el modo Directo cuando se usa el gamepad. También habilita una pequeña ventana de información que se mantiene.",
	Warn_PresetTriggerDistanceFar = "Configurarlo en Lejos puede causar problemas de rendimiento.",
	
    --Text
	MovingAll_PropsTo_SavedProps = "Mover todos los accesorios a accesorios guardados",
	SelectPropSpawn = "Seleccione accesorio para generar:",
	Spawned_Props = "Accesorios generados",
	New_Preset = "Nuevo preestablecido",
	No_Preset_Available = "No hay ningún preajuste disponible",
	Preset_TriggerDistance = "Distancia de disparo preestablecida",
	MovingSavedProps = "Mover %s a accesorios guardados",
	UpdateTag = "Actualizar etiqueta",
	Categories = "Categorías",
	Decorating = "decoracion",
	Decor_Tabs = "Pestañas decorativas",
	Saved_Props = "Accesorios guardados",
	Show_Nearby_Only = "Mostrar solo cerca",
	Show_Lights_Only = "Mostrar solo luces",
	Show_LockedTarget_Only = "Mostrar solo objetivo bloqueado",
	Show_Customizable_Only = "Mostrar solo personalizable",
	Show_CustomProps_Only = "Mostrar solo accesorios personalizados",
	ShowOnMap = "Mostrar en el mapa",
	Rename = "Cambiar nombre",
	Delete = "Eliminar",
	Backup = "Copia de seguridad",
	Merge = "fusionar",
	Save_All = "Guardar todo",
	Despawn_All = "Desaparecer todos",
	Save_ToSpecific_Tag = "Guardar en etiqueta específica",
	Saved_Props2 = "Accesorios guardados:",
	Move_To_Tag = "Mover a etiqueta",
	HideFromMap = "Ocultar del mapa",
	RemovingAllPropsFromTag = "Eliminando todos los accesorios de la etiqueta...",
	RemoveAllProps = "Eliminar todos los accesorios",
	RemoveHomeMarkerMap = "Eliminar el marcador de inicio del mapa",
	TeleportToLocation = "Teletransportarse a la ubicación",
	TeleportToTrigger = "Teletransportarse para activar",
	TeleportToMark = "Teletransportarse a marcar",
	UpdateTagLocation = "Actualizar ubicación de etiqueta",
	SharePresetWith_ThisTagOnly = "Compartir preset solo con esta etiqueta",
	SavedPresetFolder_Info = "Preajuste guardado en la carpeta AppearanceMenuMod/User/Decor",
	NoProps_WithThese_Conditions = "No hay accesorios con estas condiciones",
	AddHomeMarkerMap = "Agregar marcador de inicio al mapa",
	Distance = "Distancia",
	Total_Props = "Accesorios totales:",
	Type_Tag_here = "Escriba etiqueta aquí",
	In_World = "en el mundo",
	Tags = "Etiquetas",
	Tag = "Etiqueta",
	Both = "ambos",	
	
	-- >> POSES TAB
	BeginItem_TabPoses = "Poses",
	
	--Button
	Button_SmallCopyClipboard = "Copiar al portapapeles",
	
    --Button Label
    --Checkbox
    --Warning / Info / Tool Tip
    --Text
	Active_Animations = "Animaciones activas",
	ShowHistory = "Mostrar historial",
	ClearHistory = "Borrar historial",
	SelectPoseForCurrentTarget = "Seleccione Pose para el objetivo actual:",
	LastUsedPoses = "Últimas posturas utilizadas",
	
	
	
	-- >> TOOLS TAB
	BeginItem_TabTools = "Herramientas",
	BeginItem_TabPhotoModeNibblesReplacer = "Reemplazo de mordiscos en modo foto",
	BeginCombo_LookAt = "mirar",
	BeginCombo_WeatherControl = "Control del clima",
	
	--Button
	Button_SkipFrame = "Saltar fotograma",
	Button_ToggleLight = "Alternar luz",
	Button_ResetScale = "Restablecer escala",
	Button_ShowAsLookAtTarget = "Mostrar como mirar el objetivo",
	Button_ResetLookAtTarget = "Restablecer Mirar al objetivo",
	Button_TogglePrimaryWeapon = "Equipar arma primaria",
	Button_ToggleSecondaryWeapon = "Equipar arma secundaria",
	Button_GiveCurrentEquippedWeapon = "Dar arma equipada actual",
	Button_SmallReset = "Reiniciar",
	Button_ResetToPlayer = "Restablecer al jugador",
	Button_ClearSaved = "Borrar guardado",
	Button_Cyberpsycho = "Alternar ciberpsicópata",
	Button_ProtectNPCfromActions = "Proteger a los NPC de acciones",
	Button_AllFriendly = "Todo amigable",
	Button_AllHostile = "Todo hostil",
	Button_AllFollower = "Todos los seguidores",
	Button_AllFakeDie = "Todos los troqueles falsos",
	Button_AllDie = "Todos mueren",
	Button_AllDespawn = "Todos desaparecen",
	Button_InvMachineGun = "ametralladora",
	Button_InvSpeed2 = "Velocidad",
	Button_ToggleMakeup = "Alternar maquillaje",
	Button_TogglePiercings = "Alternar perforaciones",
	Button_ToggleSeamfix = "Alternar fijación de costura",
        Button_TargetV = "Objetivo V",
        Button_Target = "Objetivo",
        Button_TeleportToLocation = "Teletransportarse a la ubicación",
        Button_TeleportToTrigger = "Teletransportarse para activar",
        Button_TeleportToMark = "Teletransportarse a marcar",
        Button_RandomLocation = "Aleatorio",
        Button_ShareCurrentLocation = "Compartir ubicación actual",
	Button_GoBackToLastLocation = "Volver a la última ubicación",
	Button_DeleteSelectedUserLocation = "Eliminar la ubicación del usuario seleccionado",
	
	--Slider / Drag 
	Slider_HeadStiffness = "Rigidez de la cabeza",
	Slider_HeadPoseOverride = "Anulación de la postura de la cabeza",
	Slider_ChestStiffness = "Rigidez en el pecho",
	Slider_ChestPoseOverride = "Anulación de la postura del pecho",
	Slider_SlowMotion = "cámara lenta",
	Slider_DefaultAperture = "Apertura predeterminada",
	Slider_DefaultFieldofView = "Campo de visión predeterminado",
	Slider_MovementSpeed = "Velocidad de movimiento",
	Drag_MovementSpeed = "Velocidad de movimiento",
	
    --Button Label
	Button_Label_PauseTimeProgression = "Progresión del tiempo de pausa",
	Button_Label_UnpauseTimeProgression = "Reanudar la progresión del tiempo",
	Button_Label_UnfreezeTime = "Descongelar tiempo",
	Button_Label_FreezeTime = "Congelar el tiempo",
	Button_Label_OpenLightSettings = "Abrir configuración de luz",
	Button_Label_UpdateLightTarget = "Actualizar objetivo de luz",
	Button_Label_Activate = "Activar",
	Button_Label_Deactivate = "Desactivar",
	Button_Label_ChangeToCrouchStance = "Cambiar a la postura agachada",
	Button_Label_ChangeToStandStance = "Cambiar a la postura de pie",
	Button_Label_PickUpTarget = "Recoger objetivo",
	Button_Label_DropTarget = "Objetivo de caída",
	Button_Label_FreezeTarget = "Congelar objetivo",
	Button_Label_UnfreezeTarget = "Descongelar objetivo",
	Button_Label_OpenTargetTools = "Abrir herramientas de destino",
	Button_Label_CloseTargetTools = "Cerrar herramientas de destino",
	
    --Checkbox
    --Warning / Info / Tool Tip
	Warn_FileNotFound_CollabsFolder_Error = "archivo no encontrado en la carpeta Collabs",
	Warn_ShowXYZ_Orientation_Info = "Muestra las flechas X, Y y Z para una orientación más sencilla al mover el objetivo.",
	Warn_LookAtCamera_OptionOff_Info = "Desactive la opción Mirar a la cámara una vez después de cambiar esta configuración",
	Warn_DisableLookAtCamera_PhotoMode_Info = "Desactive 'Mirar a la cámara' en el modo Foto una vez para que surta efecto",
	Warn_RequiresRestart_Info = "Requiere reiniciar el juego para que surta efecto.",
	Warn_SlowMotion_PhotoMode_Info = "La cámara lenta en el modo Foto solo funciona si reanudas la pausa usando IGCS",
	Warn_WeatherControl_RequireCodeware = "El control del clima requiere Codeware 1.4+",
	Warn_StopNpc_UnequipWeapon_Info = "Esto evitará que el NPC desequipe tu arma. Nota: el NPC seguirá desequipándose a voluntad durante el combate.",
	Warn_OutOfCombat_NpcUnequip_Info = "Nota: Fuera de combate, el NPC desequipará el arma dada inmediatamente.",
	Warn_Photomode_UnfreezeSkipFrames_Info = "En el modo Foto, Descongelar objetivo saltará fotogramas en poses animadas. Para obtener la funcionalidad completa de (des)congelación, debe utilizar Otis Camera Tools (IGCS).",
	Warn_UserLocationsFolder_Info = "Las ubicaciones de los usuarios se guardan en la carpeta AppearanceMenuMod/Usuario/Ubicaciones.",
	Warn_SeeMoreAction_Info = "Apunte a V o NPC para ver más acciones",
	Warn_SeeMoreActionProp_Info = "Apunte a NPC o accesorio para ver más acciones",
	Warn_SeamfixPiercingToggle_Info = "Esto guardará el estado de alternancia de Maquillaje, Perforación y Seamfix hasta que cierres el juego.",
	Warn_PassiveMode_Info = "Los enemigos seguirán atacandote si activas el combate.",
	Warn_TppCameraGameplay_Info = "La cámara TPP no es adecuada para jugar normalmente, pero es divertido pasear;)",
	Warn_AnimatedHead_PhotoMode_Info = "Las expresiones del modo Foto no funcionarán mientras Animated Head esté habilitado.",
	Warn_ToolsOnly_WorksIngame = "Las herramientas solo funcionan en el juego.",
	Warn_InvButtonMachineGun_Info = "¡Lo encontraste! Se agregó ametralladora pesada a Equipos.",
	Warn_InvButton_Info = "¡Lo encontraste! Movimiento rápido ya está disponible.",
	InvButtonTip = "¿Qué pasa si hago clic aquí?",
	InvButtonTip2 = "¡Hacer clic aquí no hace nada!",
	InvButtonTip3 = "NO HAGAS CLIC ¡ESTÁS ADVERTIDO!",
	
    --Text
	Facial_Expression = "expresión facial",
	Expressions = "Expresiones",
	Look_At = "mirar",
	Look_At_Camera = "Mira a la cámara:",
	Target_Tools = "Herramientas de destino",
	Rotation = "Rotación",
	Tilt_Rotation = "Inclinación/Rotación",
	Mode = "Modo:",
	Precision = "Precisión",
	Relative = "relativo",
	Direct = "directo",
	AdvMovement = "Adv. movimiento",
	ForceGivenWeapon = "Arma dada por la fuerza",
	Scale = "Escala",
	ProportionalMode = "Modo proporcional",
	General_Actions = "Acciones generales",
	DisablePassiveMode = "Deshabilitar el modo pasivo",
	EnablePassiveMode = "Habilitar modo pasivo",
	EnableGodMode = "Habilitar el modo Dios",
	DisableGodMode = "Desactivar el modo Dios",
	Infinite_Oxygen = "Oxígeno infinito",
	Select_Location = "Seleccionar Ubicación",
	Select_Expression = "Seleccionar expresión",
	Select_Category = "Seleccionar categoría",
	Teleport_Actions = "Acciones de teletransporte",
	Use_Teleport_Animation = "Usar animación de teletransporte",
        Filter_Locations = "Filtrar ubicaciones",
        Locations = "Ubicaciones",
        Default_Locations = "Ubicaciones predeterminadas",
        Collab_Locations = "Ubicaciones de colaboración",
        Button_AddTag = "Agregar etiqueta",
	Button_FilterByTags = "Filtrar por etiquetas",
	Button_Close = "Cerrar",
	Favorite_Selected_Location = "Ubicación seleccionada favorita",
	Unfavorite_Selected_Location = "Ubicación seleccionada no favorita",
	Edit_Selected_Location = "Editar ubicación seleccionada",
	Locations_Favorites = "--------- Favoritos ----------",
	Locations_UserLocs = "------- Ubicaciones de usuarios -------",
	Locations_DefaultLocs = "----------- Predeterminado ----------",
	Share_Location = "Compartir ubicación",
	Edit_Location = "Editar ubicación",
	TimeWeather_Actions = "Acciones de tiempo y clima",
	TimeofDay = "Hora del día",
	Time_Actions = "Acciones de tiempo",
	Rain = "Lluvia",
	Light_Rain = "lluvia ligera",
	Cloudy = "Nublado",
	Fog = "niebla",
	Heavy_Clouds = "Nubes pesadas",
	Light_Clouds = "Nubes de luz",
	Pollution = "Contaminación",
	Sandstorm = "tormenta de arena",
	Sunny = "soleado",
	Toxic_Rain = "Lluvia tóxica",
	Deep_Blue = "azul profundo",
	Squat_Morning = "mañana en cuclillas",
	Cloudy_Morning = "mañana nublada",
	Rainy_Night = "noche lluviosa",
	Courier_Clouds = "Nubes de mensajería",
	Cursor_LockState = "Estado de bloqueo",
	PhotoMode_NibblesReplacer = "Reemplazo de mordiscos en modo foto",
	PhotoModeEnhancements = "Mejoras en el modo Foto",
	Button_ResetReplacerDatabase = "Restablecer base de datos de reemplazo",
	DisablePhotoModeCursor = "Desactivar el cursor del modo fotografía",
	TPPCamera_Position = "Posición de la cámara TPP",
	AnimatedHeadin_PhotoMode = "Cabeza animada en modo foto",
	LockLook_AtCamera = "Bloquear Mirar a la cámara",
	UnlockLook_AtCamera = "Desbloquear Mirar a la cámara",
	Save_Toggles_State = "Guardar estado de alternancia",
	Toggle_V_Head = "Alternar cabezal en V",
	Toggle_TPP_Camera = "Alternar cámara TPP",
	Target_Nibbles = "Mordiscos de destino",
	Target_Replacer = "Reemplazo de destino",
	Left = "Izquierda",
	Left_Close = "Cerrar izquierda",
	Right = "Derecha",
	Right_Close = "Cierre derecho",
	Center_Close = "Centro cerca",
	Center_Far = "Centro lejos",
	Front_Close = "Cierre frontal",
	Front_Far = "Frente lejano",
	All = "Todos",
	Head_Only = "Sólo cabeza",
	Eyes_Only = "Solo ojos",
	Movement = "movimiento",
	V_Actions = "V Acciones",
	Invisible_V = "V invisible",
	LikeGTA_byGTATravel = "por GTA Viajes",
	EnableSpawnedProps = "Habilitar accesorios generados",
	LightControl = "Control de luz",
	Equipment = "Equipo",
	
	-- >> DIRECTOR TAB
	BeginItem_TabNameDirector = "Directora",
	BeginItem_TabNameTriggers = "Desencadenantes",
	BeginCombo_StartAppearance = "Apariencia inicial",
	BeginCombo_EndAppearance = "Apariencia final",
	BeginCombo_Type = "Tipo",
	BeginCombo_GoToTarget = "Ir al objetivo",
	BeginCombo_PlayVoice = "Reproducir voz",
	BeginCombo_Attack = "ataque",
	BeginCombo_Triggers = "Desencadenantes",
	BeginCombo_Scripts = "Guiones",
	
	--Button
	Button_Yes = "si",
	Button_No = "No",
	Button_SaveChangesOnly = "Guardar solo cambios",
	Button_RemoveMark = "Quitar marca",
	Button_EditMark = "Editar marca",
        Button_MoveMark = "Mover marca",
        Button_MoveUp = "Subir",
        Button_MoveDown = "Mover hacia abajo",
        Button_NewMark = "nueva marca",
	Button_AddActor = "Agregar actor",
	Button_RemoveActor = "Quitar actor",
	Button_ChangeActor = "Cambiar actor",
	Button_RadioOnlyOne = "solo uno",
	Button_RadioRandom = "Aleatorio",
	Button_RadioSequential = "secuencial",
	Button_SaveTrigger = "Guardar disparador",
	Button_NewCamera = "Nueva cámara",
	Button_NewScript = "Nuevo guión",
	Button_DragSpeed = "Velocidad",
	Button_ToggleMarker = "Alternar marcador",
	Button_TestPose = "Postura de prueba",
	Button_StopPose = "Postura de parada",
	
    --Button Label
	Button_Label_PlayScript = "Reproducir guión",
	Button_Label_StopScript = "Detener secuencia de comandos",
	Button_Label_Stopping = "Parando...",
	Button_Label_Restarting = "Reiniciando...",
	Button_Label_AddMark = "Agregar marca",
	Button_Label_SaveWNewPos = "Guardar con nueva posición",
	
    --Checkbox
    --Warning / Info / Tool Tip
	Warn_ActorSingleMark_Info = "El actor se quedará con una sola marca.",
	Warn_ActorRandomMark_Info = "El actor se moverá aleatoriamente entre marcas.",
	Warn_ActorSequentialMark_Info = "El actor se moverá entre marcas en orden numérico.",
	Warn_DeleteScript_Info = "¿Está seguro de que desea eliminar este script?",
	Warn_CloseCamForMove_Info = "Cierra el menú para poder mover la cámara",
	Warn_CreateScriptsDesc_Info = "Cree guiones para agregar, vestir y dirigir a los actores para que actúen en machinima, capturas de pantalla y juegos de rol.",
	Warn_PremadeScriptsDesc_Info = "Cree activadores para activar scripts prefabricados al contacto.",
	Warn_CreateCamera_FovZoomDesc_Info = "Cree cámaras para moverse libremente, establezca diferentes campos de visión y niveles de zoom.",
	Warn_ShowMarksLocations_Info = "Muestra un icono visible en las ubicaciones de Marcar",
	Warn_AutoTalkNpc_Info = "Esto hará que los NPC hablen una vez cada minuto cuando estén dentro del alcance (solo NPC con voz)",
	Warn_DirectActorPlayerPosition_Info = "Cree una marca en la posición actual del jugador para mover y dirigir a los actores",
	Warn_InMenuDirectorDesc = "El director solo trabaja dentro del juego.",
	
    --Text
	DirectorMode = "Modo Director",
	SelectActorToReplace = "Seleccione el actor para reemplazar:",
	AddActorToCurrentScript = "Agregar actor al guión actual:",
	FacialExpression_WithColon = "Expresión facial:",
	FavoritePoses_WithColon = "Poses favoritas:",
	AddFavorites_Desc = "Agregue poses a favoritos en la pestaña Poses primero",
	HoldDuration = "Duración de la espera",
	Movement2 = "Movimiento:",
	Actions = "Acciones:",
	Actors = "actores",
	Editing = "Edición",
	AutoTalk = "conversación automática",
	ActorMarks = "Marcas de actores",
	Current_Actors = "Actores actuales",
	Marks_Sequence = "Secuencia de marcas:",	
	ShowMarks = "Mostrar marcas",
	Triggers = "Desencadenantes",
	NewTrigger = "Nuevo disparador",
	ShowTrigger = "Mostrar disparador",
	Title = "Título",
	Select_Trigger = "Seleccionar disparador",
	Select_Script = "Seleccionar guión",
	Delete_Trigger = "Eliminar disparador",
	Triggers_On_Off = "Activadores activados/desactivados",
	Running = "corriendo",
	Script_Running = "Guión en ejecución...",
	Delete_Script = "Eliminar guión",
	RepeatInLoop = "Repetir en bucle",
	ActivationRadius = "Radio de activación",
	Activate = "Activar",
	Deactivate = "Desactivar",
	FOV = "campo de visión",
	Zoom = "Ampliar",
	LockFrame = "Marco de bloqueo",
	Walk = "caminar",
	Sprint = "correr",
	Sequential = "secuencial",
	Cameras = "Cámaras",
	NodeView = "Vista de nodo",
	TeamA = "Equipo A",
	TeamB = "Equipo B",
	
	
	
	-- >> SETTINGS TAB
	BeginItem_TabNameSettings = "Configuración",
	BeginItem_TabNameGeneral = "generales",
	BeginItem_TabNameCompanions = "Compañeros",
	BeginItem_TabNameUI = "Interfaz de usuario",
	BeginItem_TabNameExperimental = "Experimental",
	BeginItem_TabNamePhotoMode = "Modo foto",
	
	--Button
	Button_RevertAllModelSwaps = "Revertir todos los intercambios de modelos",
	Button_RespawnAll = "Reaparecer todos",
	Button_ForceDespawnAll = "Forzar la desaparición de todos",
	Button_ClearFavorites = "Borrar favoritos",
	Button_ClearAllSavedAppearances = "Borrar todas las apariciones guardadas",
	Button_ClearAllBlacklistedAppearances = "Borrar todas las apariciones en la lista negra",
	Button_ClearAllAppearanceTriggers = "Borrar todos los activadores de apariencia",
	Button_ClearAllSavedDespawns = "Borrar todos los desaparecidos guardados",
	Button_SmallCreateTheme = "Crear tema",
	Button_SmallDeleteTheme = "Eliminar tema",
	Button_SmallSet = "conjunto",
	Button_ReloadAppearances = "Recargar apariencias personalizadas",
	
    --Button Label
    --Checkbox
	Checkbox_SpawnAsCompanion = "Generar como compañero",
	Checkbox_SpawnAsFriendly = "Generar como amigable",
	Checkbox_InvulnerableCompanion = "Compañero invulnerable",
	Checkbox_RespawnOnLaunch = "Reaparecer en el lanzamiento",
	Checkbox_LockTargetAfterSpawn = "Bloquear objetivo después de generar",
	Checkbox_OpenTargetToolsAfterSpawn = "Abrir herramientas de destino después de generar",
	Checkbox_DisplayAxisIndicatorByDefault = "Mostrar indicador de eje de forma predeterminada",
	Checkbox_PhotoModeEnhancements = "Mejoras en el modo Foto",
	Checkbox_GodModeOnLaunch = "Modo Dios en el lanzamiento",
	Checkbox_PassiveModeOnLaunch = "Modo pasivo al iniciar",
	Checkbox_StreamerMode = "Modo transmisor",
	Checkbox_OpenWCETOverlay = "Abrir con superposición CET",
	Checkbox_AutoResizingWindow = "Ventana de cambio de tamaño automático",
	Checkbox_ScanningReticle = "Retícula de escaneo",
	Checkbox_FloatingTargetTools = "Herramientas de destino flotante",
	Checkbox_TabHeaderDescriptions = "Descripciones de encabezado de pestaña",
	Checkbox_ExpandFavoritesByDefault = "Expandir favoritos de forma predeterminada",
	Checkbox_EnableScrollBars = "Habilitar barras de desplazamiento",
	Checkbox_AlwaysDisablePhotoModeCursor = "Desactivar siempre el cursor del modo Foto",
	Checkbox_Camera = "cámara",
	Checkbox_DepthOfField = "DOF",
	Checkbox_Effect = "Efecto",
	Checkbox_Stickers = "Pegatinas",
	Checkbox_LoadSave = "Cargar/Guardar",
	Checkbox_ExperimentalFunstuff = "Cosas experimentales/divertidas",
	Checkbox_EnableFreezeTargetInPhotoMode = "Habilitar objetivo congelado en modo foto",
	Checkbox_WeaponizeCompanions = "Armar a tus compañeros",
	Checkbox_AllowPlayerToBeTargetedinPosestab = "Permitir que el jugador sea objetivo en la pestaña Poses",
	Checkbox_AllowPlayerAnimationsonNPCs = "Permitir animaciones de jugadores en NPC",
	Checkbox_AllowExpressionOnNpcPM = "Permitir expresiones y buscar NPC en el modo Foto",
        Checkbox_ResetTargetPositionPM = "Restablecer la posición del objetivo para los NPC del modo Foto",
        Checkbox_EnableRandomLocation = "Habilitar botón aleatorio: teletransporta al jugador a una ubicación aleatoria de la lista",
        Checkbox_RestoreOnLaunch = "Restaurar al iniciar",
        Radio_PrimarySlot = "Ranura primaria",
        Radio_SecondarySlot = "Ranura secundaria",
	
    --Warning / Info / Tool Tip
	Warn_RespawnOnLaunch_Info = "Esta configuración habilitará/deshabilitará la reaparición de NPC previamente guardados al cargar el juego. AMM guarda automáticamente los NPC generados cuando sales del juego.",
	Warn_BannedWords_Info = "Esta configuración habilitará/deshabilitará las apariciones de NPC que contengan las palabras: desnudo, desnudo, xxx, ducha, traje_cumpleaños, pp y pene.",
	Warn_TargetNpcVehicleHotkey = "Apunte a NPC o vehículo para configurar teclas de acceso rápido",
	Warn_FirstLaunchDecideTabsExpand_Info = "Esta configuración expandirá Favoritos en las pestañas Generar, Intercambiar y Decorar de forma predeterminada cuando AMM se inicie por primera vez.",
	Warn_ExperimentalTabDesc_Info = "Las características experimentales agregan más funcionalidad, pero es posible que no funcionen tan bien, de ahí la etiqueta experimental. De hecho, la mayoría de los usuarios de AMM tienen habilitadas las funciones experimentales. ¡Así que no te preocupes demasiado y diviértete!",
	Warn_FreezeTargetPhotoMode_Info = "Esta configuración está destinada a ayudar a congelar animaciones de modificaciones que agregan animaciones personalizadas a las poses del Modo Foto o cuando se reanuda el uso de IGCS.",
	Warn_WeaponizeCompanions_Info = "Esto dará armas y habilidades de combate a todos los NPC. Se esperan poses en T y animaciones extrañas.",
	Warn_PlayerAnimsOnNpc_Info = "Habilítalo si estás usando un mod que permite usar animaciones de jugador en NPC.",
	Warn_UnpauseRequiresIGSC = "Esta configuración requiere que IGCS reanude el tiempo.",
	Warn_NotInstalled = "NO INSTALADO",
	Warn_DespawnAllProps = "¿Estás seguro de que quieres desaparecer todos los accesorios?",
	
    --Text
	AMM_Version = "Versión AMM:",
	CET_Version = "Versión CET:",
	Codeware_Version = "Versión de código:",
	Game_Version = "Versión del juego:",
	Companion_Damage = "Daño al compañero:",
	Companion_Resistance = "Resistencia del compañero:",
	Companion_Distance = "Distancia del acompañante:",
	xDamage = "x Daños",
	xResistance = "x Resistencia",
	SavedAppearancesHotkeys = "Teclas de acceso rápido a apariencias guardadas",
	Favorites = "Favoritos",
	Appearances = "Apariciones",
	Blacklist = "Lista negra",
	AppearanceTriggers = "Desencadenantes de apariencia",
	SavedDespawns = "Desapariciones guardadas",
	Interface_Language = "Idioma de la interfaz:",
	Custom_Appearances = "Apariciones personalizadas",
	PhotoModeAdjustments = "Ajustes del modo de fotografía:",
	DisablePhotoModeTabs = "Deshabilitar las pestañas del modo Foto:",
	List_Height = "Altura de la lista",
	Listbox_Themes = "Temas",
	Weaponize = "Armar",
	NoAppearanceSet = "Sin apariencia establecida",
	
	
	
	-- >> EXTRA	
	--Texts, warns, tips, info's, buttons and labels etc.
	Seat_FrontRight = "Delantero derecho",
	Seat_BackRight = "Atrás a la derecha",
	Seat_FrontLeft = "Delantero izquierdo",
	Seat_BackLeft = "atrás izquierda",
	Label_Door = "puerta",
	Label_Window = "ventana",

	Close = "Cerrar",
	Far = "lejos",
	Moderate = "moderado",
	
	-- >> Archives Screen
	Warning_MissingRequiredArchives = "A AMM le faltan uno o más archivos necesarios. Instale cualquier archivo requerido que falte en su carpeta archive/pc/mod.",
	Warning_MissingOptionalArchives = "A AMM le faltan uno o más archivos. Estos son opcionales pero agregan funcionalidad a AMM. Puede ignorar estas advertencias, pero es posible que AMM no funcione correctamente.",
	
	
	-->> INIT.LUA
	AMMNeedsAttention = "AMM necesita atención",
	MISSING_ARCHIVES = "ARCHIVOS FALTANTES",
	VERSION_INFORMATION = "INFORMACIÓN DE VERSIÓN",
	CREDITS = "CRÉDITOS",
	UPDATE_HISTORY = "ACTUALIZACIÓN DEL HISTORIAL",
	Updates = "Actualizaciones",
	MISSING = "DESAPARECIDO",
	REQUIRED = "REQUERIDO",
	OPTIONAL = "OPCIONAL",
	WHATS_NEW = "QUE HAY DE NUEVO", --Line 83 Function Error

	--Button
	Button_Ignorewarningsforthisversion = "Ignorar advertencias para esta versión",
	Button_Credits = "Créditos",
	Button_Cool = "¡Genial!",

	--Button Label
	Label_SpawnFavorites = "Favoritos de generación",
	Label_SwapFavorites = "Intercambiar favoritos",
	Label_FavoriteAppearances = "Apariciones favoritas",
	Label_Cancel = "Cancelar",

	--Text
	Hotkey_i = "Tecla de acceso rápido %i",

	--Node - Function Error(nil value) 
	Top = "Arriba", --Line 116
	Bottom = "Abajo",
	Off = "Apagado",
	
	--Voice Overs
	Label_GreetV = "saludar a v",
	Label_FearFoll = "miedo a la locura",
	Label_FearToll = "Peaje del miedo",
	Label_FearBeg = "Miedo suplicar",
	Label_FearRun = "carrera de miedo",
	Label_StealthSearch = "Búsqueda sigilosa",
	Label_StealthDeath = "Muerte sigilosa",
	Label_StealthRestore = "Restauración sigilosa",
	Label_StealthEnd = "Fin sigiloso",
	Label_CuriousGrunt = "Gruñido curioso",
	Label_GrappleGrunt = "Gruñido de agarre",
	Label_Bump = "golpe",
	Label_VehicleBump = "Golpe del vehículo",
	Label_TurretWarning = "Advertencia de torreta",
	Label_OctantWarning = "Advertencia de octante",
	Label_DroneWarning = "Advertencia de drones",
	Label_MechWarning = "Advertencia mecánica",
	Label_EliteWarning = "Advertencia de élite",
	Label_CameraWarning = "Advertencia de cámara",
	Label_EnemyWarning = "Advertencia enemiga",
	Label_HeavyWarning = "Advertencia pesada",
	Label_SniperWarning = "Advertencia de francotirador",
	Label_AnyDamage = "Cualquier daño",
	Label_Danger = "Peligro",
	Label_CombatStart = "Inicio del combate",
	Label_CombatEnd = "Fin del combate",
	Label_CombatTargetHit = "Golpe de objetivo de combate",
	Label_PedestrianHit = "Golpe de peatón",
	Label_LightHit = "Golpe ligero",
	Label_Curse = "Maldición",
	Label_Irritated = "irritado",
	Label_GrenadeThrow = "Lanzamiento de granada",
	Label_Gotakill = "¡Conseguí una muerte!",
	
	--Expressions
	Neutral = "Neutro",
	Joy = "alegría",
	Smile = "Sonríe",
	Sad = "triste",
	Surprise = "sorpresa",
	Aggressive = "agresivo",
	Anger = "ira",
	Interested = "Interesado",
	Disinterested = "Desinteresado",
	Disappointed = "decepcionado",
	Disgust = "asco",
	Exertion = "esfuerzo",
	Nervous = "Nervioso",
	Fear = "miedo",
	Terrified = "Aterrorizado",
	Pain = "dolor",
	Sleepy = "sueño",
	Unconscious = "inconsciente",
	Dead = "muerto",

	-- Extra Expressions
	Frown = "fruncir el ceño",
	Shocked = "Conmocionado",
	Annoyed_2 = "Molesto 2",
	Contempt = "Desprecio",
	Irritated = "irritado",
	Sceptical_1 = "Escéptico 1",
	Sceptical_2 = "Escéptico 2",
	Annoyed_1 = "Molesto 1",
	Offended = "ofendido",
	Disgusted = "Disgustado",
	Disappointed_2 = "Decepcionado 2",
	Alert = "Alerta",
	Crying = "llorando",
	Embarrassed = "avergonzado",
	Humiliated = "humillado",
	Impatient = "Impaciente",
	Anguished = "angustiado",
	Worried = "preocupado",
	Guilty = "Culpable",
	Grieving = "duelo",
	RestrainedAnger = "Ira contenida",
	Afraid = "miedo",
	LookingUpAnnoyed = "Mirando hacia arriba molesto",
	Offended_2 = "Ofendido 2",
	Resentful = "resentido",
	SadExtra = "Triste extra",
	NervousBreath = "Aliento Nervioso",
	ScreamingLong = "Gritando mucho",
	ScreamingShort = "Gritando corto",
	ScaredBreath = "Aliento asustado",
	CryingPainful = "Llorando Doloroso",
	SelfReflectAnger = "Autorrefleja la ira",
	IndulgentSmile = "Sonrisa indulgente",
	Impressed = "Impresionado",
	LongSmile = "Sonrisa larga",
	ShortSmile = "sonrisa corta",
	SimpleSmile = "Sonrisa sencilla",
	Confident = "confiado",
	Relief = "Alivio",
	Impressed_2 = "Impresionado 2",
	Admiring = "admirando",
	Fascinated = "Fascinado",
	RaisedBrows = "Cejas levantadas",
	LookingUpThinking = "Mirando hacia arriba Pensando",
	LeftGlanceProcessing = "Procesamiento de mirada izquierda",
	LeftGlanceCloseUp = "Vistazo izquierdo de cerca",
	LookingAround = "mirando a su alrededor",
	LookingDownThinking = "Mirando hacia abajo Pensando",
	LookingAroundAlt = "Mirando alrededor Alt",
	EyesDartFromLeft = "Los ojos se disparan desde la izquierda",
	EyesDartFromRight = "Los ojos se disparan desde la derecha",
	EyesDartToRight = "Los ojos se lanzan hacia la derecha",
	LookingLeft = "mirando hacia la izquierda",
	LookingUpThinking_2 = "Mirando hacia arriba Pensando 2",
	RightGlanceProcessing = "Procesamiento de vista derecha",
	LookingDown = "mirando hacia abajo",
	Left90GlanceClose = "Left90Vistazo Cerrar",
	LookingUp = "mirando hacia arriba",
	Right90GlanceClose = "Vistazo derecho90 Cerrar",
	LookingLeftUp = "Mirando hacia la izquierda",
	LookingRightUp = "Mirando hacia arriba",
	ReadingDown = "Leyendo hacia abajo",
	ReadingUp = "leyendo",
	ReadingMiddle = "Lectura media",
	FrontCloseGlance = "Vistazo frontal cercano",
	WinkLeft = "Guiño a la izquierda",
	EyeRoll = "poner los ojos en blanco",
	Squint = "entrecerrar los ojos",
	FalseSmile_2 = "Falsa sonrisa 2",
	FalseSmile_1 = "Falsa sonrisa 1",
	ListeningNewInfo = "Escuchando nueva información",
	WhatDoYouWant = "¿Qué quieres?",
	Maybe = "tal vez",
	SearchingForWords = "Buscando palabras",
	What = "que",
	Where = "donde",
	SureSure = "seguro seguro",
	ListenToMe = "escúchame",
	StopThePolice = "Detener a la policía",
	HurryUp = "Date prisa",
	ShutUp = "Cállate",
	WinkRight = "Guiño a la derecha",
	MockingSmile = "Sonrisa burlona",
	AsymmetricalSmile = "Sonrisa Asimétrica",
	SarcasticSmile = "Sonrisa sarcástica",
	Sex = "sexo",
	LipBite_1 = "Mordida De Labios 1",
	LipBite_2 = "Mordida De Labios 2",
	Moan = "gemir",
	LipBite_3 = "Mordida De Labios 3",
	Pout = "puchero",
	SexySmile = "sonrisa sexy",
	Swallow = "tragar",
	SensualSmile = "sonrisa sensual",
	SexScene_1 = "Escena de sexo 1",
	SexScene_2 = "Escena de sexo 2",
	Kiss = "Beso",
	UsingInhaler = "Usando inhalador",
	ShortYawn = "Bostezo corto",
	Yawn = "Bostezo",
	Coughing = "Toser",
	Bite = "morder",	
	EatingFast = "Comer rápido",
	ShortDrink = "Bebida corta",
	Drinking = "bebiendo",
	FastBite = "Bocado rápido",
	LongDrink = "Trago largo",
	ShortSmoking = "Fumar corto",
	LongSmoking = "Fumar durante mucho tiempo",
	Smoking = "fumar",
	Eating_1 = "comiendo 1",
	Eating_2 = "comiendo 2",
	Eating_3 = "comiendo 3",
	Eating_4 = "comiendo 4",
	Vomit = "vomitar",
	BeingRevived = "siendo revivido",
	MalwarePositive = "Malware positivo",
	MalwareNegative = "Malware negativo",
	MalwareInfected = "Malware infectado",
	FaceMorphActivate = "Activar transformación de cara",
	LieNetChairSleep = "Acostarse Red Silla Dormir",
	LieNetChairBreathe = "Mentira Red Silla Respirar",
	NetrunnerDeathUnplugged = "Muerte de Netrunner desconectada",
	VeryItchyNose = "mucha picazón en la nariz",
	RollerCoasterNervous = "Montaña rusa nerviosa",
	Pfft = "Pfff",
	Hahaha = "Jajaja",
	Sniff = "olfatear",
	Ahaaa = "Ahaaa",
	Heh = "Je",
	Huh = "Eh",
	Haaa = "Haaa",
	Sigh_Lipsync = "Suspiro sincronización de labios",
	Hmm = "Mmmm",
	Whispering_1 = "susurrando 1",
	Whispering_2 = "susurrando 2",
	ApprovalYes = "Aprobación Sí",
	SubtleYes = "Sutil sí",
	QuickNoShake = "Rápido sin agitar",
	FirmYes = "Firma Sí",
	LongNo = "Largo No",
	SubtleNo = "sutil no",
	NoContempt = "Sin desprecio",
	NoDisapproval = "Sin desaprobación",
	FirmNo = "Firma no",
	NoEnthusiastic = "No entusiasta",
	MockingYes = "Burlarse si",
	EnthusiasticYes = "Entusiasta Sí",
	AsymmetricalCornerUp = "Esquina asimétrica hacia arriba",
	CornersUp = "Esquinas arriba",
	SoftSigh = "Suspiro suave",
	BreathGasp = "Jadeo",
	AssymetricalSneer = "Burla asimétrica",
	CrimpingLips = "Labios prensados",
	BrowsDown = "Cejas hacia abajo",
	BrowsLeftUp = "Cejas hacia arriba",
	BrowsRightUp = "Cejas hacia arriba",
	BrowsUp = "cejas hacia arriba",
	ClosedEyes_1 = "Ojos cerrados 1",
	ClosedEyes_2 = "Ojos cerrados 2",
	EyesClosed = "ojos cerrados",
	LookRight = "mira bien",
	FastBlink = "Parpadeo rápido",
	SlowBlink = "parpadeo lento",
	NormalBlink = "Parpadeo normal",
	TinyBlink = "Pequeño parpadeo",
	HalfBlink = "Medio parpadeo",
	RegularSaccade = "Sacada regular",
	FrequentSaccade = "Sacada frecuente",
	PhotoCloseupEyes = "Foto Primer Plano Ojos",
	PhotoCloseupLips = "Foto Primer Plano Labios",
	PhotoCloseupHair = "Foto Primer Plano Cabello",
	PhotoCloseupChin = "Foto Primer Plano Barbilla",
	PhotoCloseupNose = "Foto Primer Plano Nariz",
	PhotoCloseup = "Foto en primer plano",
	PhotoCloseupPleased = "Foto Primer Plano Satisfecho",
	PhotoCloseupBody = "Foto Primer Plano Cuerpo",
	PhotoCloseupTeeth = "Foto Primer Plano Dientes",
	PhotoCloseupIN = "Foto Primer plano EN",
	PhotoCloseupOUT = "Foto Primer plano FUERA",
	Bored = "Aburrido",
	Charming = "Encantador",
	Furious = "furioso",
	Happy = "feliz",
	Pissed = "enojado",
	Pleased = "contento",
	Scared = "asustado",
	Surprised = "Sorprendido",
	Sadness = "tristeza",
	Whistling = "Silbando",
	Singing_1 = "cantando 1",
	Singing_2 = "cantando 2",
	Singing_3 = "cantando 3",
	Alerted = "Alertado",
	Hit_1 = "Golpea 1",
	Hit_2 = "Golpe 2",
	Wounded = "Heridos",
	Death = "Muerte",

	-- Expressions Category
	Negative = "Negativo",
	Positive = "Positivo",
	Contemplative = "contemplativo",
	Social = "sociales",
	Sexual = "sexuales",
	Action = "acción",
	Vocal = "voz",
	Yes_N_No = "Sí y no",
	Nuance = "Matiz",
	Static = "estática",
	Combat = "combate",
	
	--Props
	AMM_Props_Desc = "Agrega accesorios, personajes y vehículos. AMM no se lanzará sin esto.",
	AMM_JohnnyCompanion_Desc = "Agrega a Johnny Silverhand como personaje que se puede generar.",
	AMM_ScenesPack_Desc = "Agrega 9358 animaciones de escenas al sistema Poses.\nDescárgalo en la página Nexus de AMM.",
	AMM_SoundPack_Desc = "Agrega efectos de sonido que se pueden generar.",
	AMM_KerryPP_Desc = "Agrega una nueva apariencia desnuda.",
	AMM_BenjaminStonePP_Desc = "Agrega una nueva apariencia desnuda.",
	AMM_RiverPP_Desc = "Agrega una nueva apariencia desnuda.",
	AMM_YorinobuPP_Desc = "Agrega una nueva apariencia desnuda.",
	AMM_LizzyIncognito_Desc = "Agrega una nueva apariencia.",
	AMM_MeredithXtra_Desc = "Agrega una nueva apariencia.",
	AMM_DelamainFix_Desc = "Agrega cuerpo completo a Delamain.",
	AMM_HanakoNoMakeup_Desc = "Permite que AMM elimine el maquillaje de Hanako cuando usa Apariencia personalizada.",
	AMM_JudyBodyRevamp_Desc = "Reemplaza el cuerpo de Judy por uno nuevo y mejorado.",
	AMM_PanamBodyRevamp_Desc = "Reemplaza la carrocería de Panam por una nueva mejorada.",
	AMM_MistyBodyRevamp_Desc = "Reemplaza el cuerpo de Misty por uno nuevo y mejorado.\nDescárgalo en la página Nexus de AMM.",
	AMM_1VesHanakoFixedBodyNaked_Desc = "Reemplaza el cuerpo de Hanako por uno nuevo y mejorado.",
	AMM_PinkyDudeANIMFacialExpressionsFemV_Desc = "Habilita herramientas de expresiones faciales en Female V",
	AMM_PinkyDudeANIMFacialExpressionsMaleV_Desc = "Habilita herramientas de expresiones faciales en Male V",
	AMM_DinoTattooFixArchive_Desc = "Reemplaza la malla y la textura.",
	AMM_SongbirdBodyFixArchive_Desc = "Reemplaza el cuerpo para arreglar el área gris. Aún no es perfecto.",
	AMM_RitaWheelerCombatEnablerArchive_Desc = "Reemplaza el archivo de entidad para habilitar animaciones de combate.",
	AMM_CheriAppearances_Desc = "Agrega nuevas apariencias. Descárgalo en la página Nexus de AMM.",
	AMM_BryceNaked_Desc = "Agrega una nueva apariencia desnuda. Descárgalo en la página Nexus de AMM.",
	AMM_EvelynNaked_Desc = "Arregla su cuerpo para permitir una apariencia desnuda. Descárgalo en la página Nexus de AMM.",
	AMM_SaburoAppearances_Desc = "Agrega nuevas apariencias. Descárgalo en la página Nexus de AMM.",
	AMM_TbugAppearances_Desc = "Agrega nuevas apariencias. Descárgalo en la página Nexus de AMM.",
	AMM_8ug8eagAppearances_Desc = "Agrega nuevas apariencias. Descárgalo en la página Nexus de AMM.",
	
	--Equipments (There is a Function Error(nil value) in this section, These are just labels that are not connected to any localizable strings in the file)
	Fists = "puños", --Line 2377 
	Katana = "Katana",
	Mantis_Blades = "Hojas de mantis",
	Machete = "machete",
	Hammer = "Martillo",
	Baton = "bastón",
	Knife = "cuchillo",
	Crowbar = "palanca",
	Baseball_Bat = "Bate de béisbol",
	Assault_Rifle = "Rifle de asalto",
	Sidewinder = "enrollador lateral",
	Sniper_Rifle = "Rifle de francotirador",
	Shotgun = "escopeta",
	SMG = "subfusil",
	Handgun = "pistola", --Line 2391
	
	--Warning / Info / Tooltip
	Warn_CantSave_BlacklistedAppearance = "¡No puedes guardar una aparición en la lista negra!",
	Warn_ConfirmDeleteSavedAppearances = "¿Estás seguro de que deseas eliminar todas tus apariencias guardadas?",
	Warn_ConfirmDeleteBlacklistedAppearances = "¿Estás seguro de que deseas eliminar todas tus apariciones en la lista negra?",
	Warn_ConfirmDeleteSavedDespawns = "¿Estás seguro de que deseas eliminar todos tus desaparecidos guardados?",
	Warn_ConfirmDeleteAppearanceTriggers = "¿Estás seguro de que deseas eliminar todos los activadores de apariencia?",
	Warn_ConfirmDeleteCurrentAppearance = "¿Estás seguro de que deseas eliminar tu preset activo actual?",
	Warn_WeaponizeNpcAnimationIssues = "No todos los NPC tendrán las animaciones necesarias para usar todo tipo de armas. Es posible que se produzcan poses en T y animaciones incorrectas.\n¿Estás seguro de que quieres habilitarlo?",
	Warn_ConfirmEnableExperimentalAndSave_Info = "¿Está seguro de que desea habilitar funciones experimentales? Es posible que AMM no funcione como se esperaba. ¡Úselo bajo su propio riesgo!",
	Warn_DeleteFavoritesAskWhichOne_Info = "Si está seguro de que desea eliminar todos sus favoritos, seleccione cuál a continuación:",
	Popup_Error_Title = "error",
	Button_Ok = "Ok",
	Popup_FavoriteName = "Nombre favorito",
	Popup_RenamePreset = "Cambiar nombre preestablecido",
	Popup_RenameProp = "Cambiar nombre de accesorio",
	Editor_Title = "Editor de temas",
	Editor_Field_ThemeName = "Nombre del tema",
	Editor_Hint_InsertThemeName = "Insertar nuevo nombre de tema",
	Error_ThemeNameExists = "El nombre del tema ya existe",
}
