return {

    -- >> SCAN TAB
	BeginItem_TabNameScan = "Scan",
	
	--Button
	Button_CyclesAppearances = "Apparence du cycle",
	Button_SavesAppearance = "Enregistrer l'apparence",
	Button_ClearSavedAppearance = "Effacer l'apparence enregistrée",
	Button_UnlockDoor = "Verrouillage de porte à bascule",
	Button_RestoreAccess = "Restaurer l'accès",
	Button_UnlockVehicle = "Déverrouiller le véhicule",
	Button_RepairVehicle = "Véhicule de réparation",
	Button_OpenCloseDoors = "Ouvrir/Fermer les portes",
	Button_OpenCloseWindows = "Ouvrir/Fermer les fenêtres",
	Button_ToggleEngine = "Basculer le moteur",
	Button_ToggleAIDriver = "Basculer le pilote IA",
	Button_ToggleCamera = "Basculer la caméra",
	Button_ToggleRadio = "Basculer la radio",
	Button_NextRadioStation = "Station de radio suivante",
	Button_TargetMountedVehicle = "Véhicule monté sur cible",
	Button_AssignSeats = "Attribuer des sièges",
	Button_Assign = "Attribuer",
	Button_Reset = "Réinitialiser",
	Button_FakeDie = "Faux dé",
	Button_SmallCopy = "Copier",
	
    --Button Label
	Button_Label_Unfollower = "Ne plus suivre",
	Button_Label_Follower = "Suiveur",
	Button_Label_SaveDespawn = "Enregistrer la disparition",
	Button_Label_ClearSavedDespawn = "Effacer la disparition enregistrée",
	Button_LabelLockTarget = "Verrouiller la cible",
	Button_LabelUnlockTarget = "Déverrouiller la cible",
	Label_AddToSpawnFavs = "Ajouter aux favoris pouvant être générés",
	Label_RemoveFromSpawnFavs = "Supprimer des favoris pouvant être générés",
	
    --Checkbox
	Checkbox_SavedDespawnsActive = "Disparitions enregistrées actives",
	Checkbox_KeepAssigned = "Conserver l'affectation lors du changement de voiture",
	
    --Warning / Info / Tool Tip
	WarnTextAI_FastTravel = "Sélectionnez un point de voyage rapide sur votre carte pour commencer",
	WarnText_DontReloadMods = "N'utilisez pas Reload All Mods.\nVeuillez recharger votre sauvegarde ou vous déplacer vers une autre zone.",
	Warning_NoTarget_Desc = "Pas de cible ! Regardez le PNJ, le véhicule ou l'objet pour commencer",
	ToolTip_DisableCheckboxReloadSave_AbleTotargetClearSavedDespawns = "Décochez cette case et rechargez votre sauvegarde pour pouvoir cibler Effacer les disparitions enregistrées",
	
    --Text
	Build_Mode = "Mode construction",
	Speed = "Vitesse :",
	Search = "Rechercher",
	Clear = "Effacer",
	Player = "Joueur",
	Saved = "Enregistré",
	Saved_ = "Enregistré_",
	Current = "Actuel",
	Current_ = "Actuel",
	Select_Seat = "Sélectionnez le siège",
	Target_Info = "Informations sur la cible",
	Target_Actions = "Actions ciblées",
	No_Appearances = "Aucune apparition",
	No_Target = "Aucune cible",
	Favorite_Appearance = "Apparence préférée",
	Unfavorite_Appearance = "Apparence défavorisée",
	Blacklist_Appearance = "Apparition de la liste noire",
	Unblacklist_Appearance = "Apparition de la liste noire",
	Saved_Appearance = "Apparence enregistrée :",
	Current_Appearance = "Apparence actuelle :",
	List_of_Appearances = "Liste des apparitions",
	Appearance_Trigger = "Déclencheur d'apparence",
	None = "Aucun",
	Default = "Par défaut",
	Zone = "Zone",
	Area = "Zone",
	Position = "Poste",

	
	-- >> SPAWN TAB
	BeginItem_TabNameSpawn = "Apparition",
	
	--Button
	Button_Refresh = "Actualiser",
	Button_Save = "Enregistrer",
	Button_Confirm = "Confirmer",
	Button_Cancel = "Annuler",
	Button_SmallSave = "Enregistrer",
	Button_SmallRespawn = "Réapparaître",
	Button_SmallDespawn = "Disparaître",
	Button_SmallDespawn_WithSpace = "Disparaître",
	Button_SmallTarget = "Cible",
	Button_SmallEquipment = "Équipement",
	Button_LabelHostile = "Hostile",
	Button_LabelFriendly = "Amical",
	
    --Button Label
	Label_Favorite = "Favoris",
	Label_Unfavorite = "Supprimer des favoris",
	
    --Checkbox
    --Warning / Info / Tool Tip
	Warn_PlayerInMenu = "Joueur dans le menu",
	Warn_AMMonlyfunctions_ingame = "AMM ne fonctionne que dans le jeu",
	Warn_SpawnWorksInGame = "L'apparition ne fonctionne que dans le jeu",
	Warn_InitError = "Erreur d'initialisation",
	Warn_InitError_Info = "Veuillez consulter AppearanceMenuMod.log pour plus d'informations.",
	
    --Text
	Active_Spawns = "Apparitions actives",
	NoActiveSpawns = "Aucune apparition active",
	Select_To_Spawn = "Sélectionnez pour apparaître",
	No_Results = "Aucun résultat",
	ItsEmpty = "C'est vide :(",
	Existing_Name = "Nom existant",
	Name = "Nom",
	
	
	
	-- >> SWAP TAB
	BeginItem_TabNameSwap = "Échange",
	
	--Button
	Button_SmallRevert = "Revenir",
	
    --Button Label
    --Checkbox
    --Warning / Info / Tool Tip
	Warn_ReloadSaveUpdateChanges = "Rechargez votre sauvegarde pour mettre à jour les modifications !",
	Warn_NeedReloadSaveUpdateChanges = "Vous devrez recharger votre sauvegarde pour mettre à jour les modifications.",
	Warn_ReplacerSwap = "Vous ne pouvez pas échanger le remplaçant ! Utilisez l'onglet Outils en mode photo pour les cibler, puis changez leur apparence depuis l'onglet Spawn ou les outils Target.",
	Warning = "AVERTISSEMENT",
	Warning2 = "AVERTISSEMENT :",
	SaveSwap_Tooltip = "Enregistrez vos swaps pour les conserver après avoir rechargé votre jeu.",
	
    --Text
	CantSwapReplacer = "Impossible d'échanger le remplaçant",
	Active_Model_Swaps = "Échanges de modèles actifs",
	Save = "Enregistrer",
	Restore = "Restaurer",
	Current_Target = "Cible actuelle :",
	Target_ID = "ID cible :",
	SelectSwap_CurrentTarget = "Sélectionnez pour échanger avec la cible actuelle :",
	NoNPC_LookNPC = "Aucun PNJ trouvé ! Regardez le PNJ pour commencer",
	
	-- Locations Categories
	Residences = "Résidences",
	ArasakaAndCorpo = "Arasaka & Corpo",
	ClubsAndBars = "Clubs et bars",
	HotelsAndPleasure = "Hôtels & Plaisirs",
	UndergroundAndCrime = "Souterrain et crime",
	GovernmentAndSecurity = "Gouvernement et sécurité",
	StoryAndUnique = "Histoire et Unique",
	Ripperdocs = "Documents sur l'éventreur",
	LandmarksAndOpenWorld = "Monuments et monde ouvert",
	SpoilersAndHidden = "Spoilers et cachés",
	UserLocations = "Emplacements des utilisateurs",
	
	
	-- >> DECOR TAB
	BeginItem_TabDecor = "Décor",
	BeginItem_TabPresets = "Préréglages",
	Begin_ComboPresets = "Préréglages",
	
	--Button
	Button_SmallClone = "Cloner",
	Button_SmallRemove = "Supprimer##",
	Button_SmallRename = "Renommer##",
	Button_SmallUpdate = "Mise à jour##",
	Button_SmallCancel = "Annuler",
	Button_Frame = "Cadre",
	
    --Button Label
	Button_LabelHide = "Masquer",
	Button_LabelUnhide = "Afficher",
	
    --Checkbox
    --Warning / Info / Tool Tip
	Warn_PersistPropSave = "Spawn Props pour décorer votre maison ou partout où vous voulez à votre guise ! Enregistrez les accessoires pour les faire persister !",
	Warn_DespawnInProgress_PleaseWait = "Disparition en cours. S'il vous plaît, attendez.",
	Warn_PresetsFolder_Info = "Les préréglages utilisateur sont enregistrés dans le dossier AppearanceMenuMod/User/Decor",
	Warn_CustomPresets_Info = "Ce préréglage inclut des accessoires personnalisés",
	Warn_CustomPropsModders_Info = "Accessoires personnalisés réalisés par :",
	Warn_GamepadDirectMode_Info = "Cela permet une meilleure intégration avec le mode Direct lors de l'utilisation de la manette de jeu. Il permet également d'afficher une petite fenêtre d'informations qui reste visible.",
	Warn_PresetTriggerDistanceFar = "Le réglage sur Far peut entraîner des problèmes de performances.",
	
    --Text
	MovingAll_PropsTo_SavedProps = "Déplacer tous les accessoires vers les accessoires enregistrés",
	SelectPropSpawn = "Sélectionnez un accessoire à générer :",
	Spawned_Props = "Accessoires générés",
	New_Preset = "Nouveau préréglage",
	No_Preset_Available = "Aucun préréglage disponible",
	Preset_TriggerDistance = "Distance de déclenchement prédéfinie",
	MovingSavedProps = "Déplacer %s vers les accessoires enregistrés",
	UpdateTag = "Mettre à jour la balise",
	Categories = "Catégories",
	Decorating = "Décoration",
	Decor_Tabs = "Onglets de décoration",
	Saved_Props = "Accessoires enregistrés",
	Show_Nearby_Only = "Afficher à proximité uniquement",
	Show_Lights_Only = "Afficher uniquement les lumières",
	Show_LockedTarget_Only = "Afficher uniquement la cible verrouillée",
	Show_Customizable_Only = "Afficher uniquement les éléments personnalisables",
	Show_CustomProps_Only = "Afficher uniquement les accessoires personnalisés",
	ShowOnMap = "Afficher sur la carte",
	Rename = "Renommer",
	Delete = "Supprimer",
	Backup = "Sauvegarde",
	Merge = "Fusionner",
	Save_All = "Enregistrer tout",
	Despawn_All = "Tout faire disparaître",
	Save_ToSpecific_Tag = "Enregistrer dans une balise spécifique",
	Saved_Props2 = "Accessoires enregistrés :",
	Move_To_Tag = "Déplacer vers la balise",
	HideFromMap = "Masquer de la carte",
	RemovingAllPropsFromTag = "Suppression de tous les accessoires de la balise...",
	RemoveAllProps = "Supprimer tous les accessoires",
	RemoveHomeMarkerMap = "Supprimer le marqueur de domicile de la carte",
	TeleportToLocation = "Téléportation vers l'emplacement",
	TeleportToTrigger = "Téléportation pour déclencher",
	TeleportToMark = "Téléportation pour marquer",
	UpdateTagLocation = "Mettre à jour l'emplacement de la balise",
	SharePresetWith_ThisTagOnly = "Partager le préréglage avec cette balise uniquement",
	SavedPresetFolder_Info = "Préréglage enregistré dans le dossier AppearanceMenuMod/User/Decor",
	NoProps_WithThese_Conditions = "Aucun accessoire dans ces conditions",
	AddHomeMarkerMap = "Ajouter un marqueur de domicile à la carte",
	Distance = "Distance",
	Total_Props = "Total des accessoires :",
	Type_Tag_here = "Tapez la balise ici",
	In_World = "Dans le monde",
	Tags = "Balises",
	Tag = "Étiquette",
	Both = "Les deux",	
	
	-- >> POSES TAB
	BeginItem_TabPoses = "Poses",
	
	--Button
	Button_SmallCopyClipboard = "Copier dans le presse-papiers",
	
    --Button Label
    --Checkbox
    --Warning / Info / Tool Tip
    --Text
	Active_Animations = "Animations actives",
	ShowHistory = "Afficher l'historique",
	ClearHistory = "Effacer l'historique",
	SelectPoseForCurrentTarget = "Sélectionnez Pose pour la cible actuelle :",
	LastUsedPoses = "Dernières poses utilisées",
	
	
	
	-- >> TOOLS TAB
	BeginItem_TabTools = "Outils",
	BeginItem_TabPhotoModeNibblesReplacer = "Remplacement des grignotages du mode photo",
	BeginCombo_LookAt = "Regardez",
	BeginCombo_WeatherControl = "Contrôle météorologique",
	
	--Button
	Button_SkipFrame = "Sauter le cadre",
	Button_ToggleLight = "Basculer la lumière",
	Button_ResetScale = "Réinitialiser l'échelle",
	Button_ShowAsLookAtTarget = "Afficher comme regarder la cible",
	Button_ResetLookAtTarget = "Réinitialiser le regard sur la cible",
	Button_TogglePrimaryWeapon = "Équiper l'arme principale",
	Button_ToggleSecondaryWeapon = "Équiper une arme secondaire",
	Button_GiveCurrentEquippedWeapon = "Donner l'arme actuellement équipée",
	Button_SmallReset = "Réinitialiser",
	Button_ResetToPlayer = "Réinitialiser au joueur",
	Button_ClearSaved = "Effacer Enregistré",
	Button_Cyberpsycho = "Basculer Cyberpsycho",
	Button_ProtectNPCfromActions = "Protéger le PNJ des actions",
	Button_AllFriendly = "Tous conviviaux",
	Button_AllHostile = "Tous hostiles",
	Button_AllFollower = "Tous les abonnés",
	Button_AllFakeDie = "Tous les faux meurent",
	Button_AllDie = "Tous meurent",
	Button_AllDespawn = "Tous disparaissent",
	Button_InvMachineGun = "Mitrailleuse",
	Button_InvSpeed2 = "Vitesse",
	Button_ToggleMakeup = "Basculer le maquillage",
	Button_TogglePiercings = "Basculer les piercings",
	Button_ToggleSeamfix = "Activer/Désactiver Seamfix",
        Button_TargetV = "Cible V",
        Button_Target = "Cible",
        Button_TeleportToLocation = "Téléportation vers l'emplacement",
        Button_TeleportToTrigger = "Téléportation pour déclencher",
        Button_TeleportToMark = "Téléportation pour marquer",
        Button_RandomLocation = "Aléatoire",
        Button_ShareCurrentLocation = "Partager l'emplacement actuel",
	Button_GoBackToLastLocation = "Revenir au dernier emplacement",
	Button_DeleteSelectedUserLocation = "Supprimer l'emplacement de l'utilisateur sélectionné",
	
	--Slider / Drag 
	Slider_HeadStiffness = "Raideur de la tête",
	Slider_HeadPoseOverride = "Remplacement de la pose de la tête",
	Slider_ChestStiffness = "Raideur thoracique",
	Slider_ChestPoseOverride = "Remplacement de la pose de la poitrine",
	Slider_SlowMotion = "Ralenti",
	Slider_DefaultAperture = "Ouverture par défaut",
	Slider_DefaultFieldofView = "Champ de vision par défaut",
	Slider_MovementSpeed = "Vitesse de déplacement",
	Drag_MovementSpeed = "Vitesse de déplacement",
	
    --Button Label
	Button_Label_PauseTimeProgression = "Progression du temps de pause",
	Button_Label_UnpauseTimeProgression = "Reprendre la progression temporelle",
	Button_Label_UnfreezeTime = "Temps de dégel",
	Button_Label_FreezeTime = "Temps de gel",
	Button_Label_OpenLightSettings = "Ouvrir les paramètres d'éclairage",
	Button_Label_UpdateLightTarget = "Mettre à jour la cible lumineuse",
	Button_Label_Activate = "Activer",
	Button_Label_Deactivate = "Désactiver",
	Button_Label_ChangeToCrouchStance = "Passer à la position accroupie",
	Button_Label_ChangeToStandStance = "Changer la position debout",
	Button_Label_PickUpTarget = "Ramasser la cible",
	Button_Label_DropTarget = "Laisser tomber la cible",
	Button_Label_FreezeTarget = "Geler la cible",
	Button_Label_UnfreezeTarget = "Dégeler la cible",
	Button_Label_OpenTargetTools = "Outils cibles ouverts",
	Button_Label_CloseTargetTools = "Fermer les outils cibles",
	
    --Checkbox
    --Warning / Info / Tool Tip
	Warn_FileNotFound_CollabsFolder_Error = "fichier introuvable dans le dossier Collabs",
	Warn_ShowXYZ_Orientation_Info = "Afficher les flèches X, Y et Z pour une orientation plus facile lors du déplacement de la cible.",
	Warn_LookAtCamera_OptionOff_Info = "Désactivez l'option Regarder la caméra une fois après avoir modifié ce paramètre.",
	Warn_DisableLookAtCamera_PhotoMode_Info = "Désactivez une fois « Regarder l'appareil photo » en mode photo pour prendre effet.",
	Warn_RequiresRestart_Info = "Nécessite le redémarrage du jeu pour prendre effet",
	Warn_SlowMotion_PhotoMode_Info = "Le ralenti en mode photo ne fonctionne que si vous réactivez l'utilisation d'IGCS",
	Warn_WeatherControl_RequireCodeware = "Le contrôle météo nécessite Codeware 1.4+",
	Warn_StopNpc_UnequipWeapon_Info = "Cela empêchera le PNJ de déséquiper votre arme donnée. Remarque : le PNJ se déséquipera toujours à volonté pendant le combat.",
	Warn_OutOfCombat_NpcUnequip_Info = "Remarque : hors combat, le PNJ déséquipera immédiatement l'arme donnée.",
	Warn_Photomode_UnfreezeSkipFrames_Info = "En mode photo, Unfreeze Target ignorera les images dans les poses animées. Pour bénéficier de la fonctionnalité complète de (dé)gelage, vous devez utiliser Otis Camera Tools (IGCS).",
	Warn_UserLocationsFolder_Info = "Les emplacements des utilisateurs sont enregistrés dans le dossier AppearanceMenuMod/User/Locations",
	Warn_SeeMoreAction_Info = "Ciblez V ou PNJ pour voir plus d'actions",
	Warn_SeeMoreActionProp_Info = "Ciblez un PNJ ou un accessoire pour voir plus d'actions",
	Warn_SeamfixPiercingToggle_Info = "Cela enregistrera l'état des bascules Maquillage, Piercing et Seamfix jusqu'à ce que vous fermiez le jeu.",
	Warn_PassiveMode_Info = "Les ennemis vous attaqueront toujours si vous déclenchez le combat",
	Warn_TppCameraGameplay_Info = "La caméra TPP n'est pas adaptée au jeu régulier, mais c'est amusant pour une promenade ;)",
	Warn_AnimatedHead_PhotoMode_Info = "Les expressions du mode photo ne fonctionneront pas lorsque la tête animée est activée.",
	Warn_ToolsOnly_WorksIngame = "Les outils ne fonctionnent que dans le jeu",
	Warn_InvButtonMachineGun_Info = "Vous l'avez trouvé ! La mitrailleuse lourde a été ajoutée aux équipements.",
	Warn_InvButton_Info = "Vous l'avez trouvé ! Fast Motion est maintenant disponible.",
	InvButtonTip = "Et si je clique ici ?",
	InvButtonTip2 = "Cliquer ici ne fait rien !",
	InvButtonTip3 = "NE CLIQUEZ PAS, VOUS AVEZ ÉTÉ AVERTI !",
	
    --Text
	Facial_Expression = "Expression du visage",
	Expressions = "Expressions",
	Look_At = "Regardez",
	Look_At_Camera = "Regardez la caméra :",
	Target_Tools = "Outils cibles",
	Rotation = "Rotation",
	Tilt_Rotation = "Inclinaison/Rotation",
	Mode = "Mode :",
	Precision = "Précision",
	Relative = "Parent",
	Direct = "Direct",
	AdvMovement = "Av. Mouvement",
	ForceGivenWeapon = "Force donnée à l'arme",
	Scale = "Échelle",
	ProportionalMode = "Mode proportionnel",
	General_Actions = "Actions générales",
	DisablePassiveMode = "Désactiver le mode passif",
	EnablePassiveMode = "Activer le mode passif",
	EnableGodMode = "Activer le mode Dieu",
	DisableGodMode = "Désactiver le mode Dieu",
	Infinite_Oxygen = "Oxygène infini",
	Select_Location = "Sélectionnez un emplacement",
	Select_Expression = "Sélectionnez une expression",
	Select_Category = "Sélectionnez une catégorie",
	Teleport_Actions = "Actions de téléportation",
	Use_Teleport_Animation = "Utiliser l'animation de téléportation",
        Filter_Locations = "Filtrer les emplacements",
        Locations = "Emplacements",
        Default_Locations = "Emplacements par défaut",
        Collab_Locations = "Lieux de collaboration",
        Button_AddTag = "Ajouter une balise",
	Button_FilterByTags = "Filtrer par balises",
	Button_Close = "Fermer",
	Favorite_Selected_Location = "Emplacement sélectionné favori",
	Unfavorite_Selected_Location = "Supprimer l'emplacement sélectionné comme favori",
	Edit_Selected_Location = "Modifier l'emplacement sélectionné",
	Locations_Favorites = "--------- Favoris ----------",
	Locations_UserLocs = "------- Emplacements des utilisateurs -------",
	Locations_DefaultLocs = "----------- Par défaut ----------",
	Share_Location = "Partager l'emplacement",
	Edit_Location = "Modifier l'emplacement",
	TimeWeather_Actions = "Actions temporelles et météorologiques",
	TimeofDay = "Heure de la journée",
	Time_Actions = "Actions temporelles",
	Rain = "Pluie",
	Light_Rain = "Pluie légère",
	Cloudy = "Nuageux",
	Fog = "Brouillard",
	Heavy_Clouds = "Nuages lourds",
	Light_Clouds = "Nuages ​​légers",
	Pollution = "Pollution",
	Sandstorm = "Tempête de sable",
	Sunny = "Ensoleillé",
	Toxic_Rain = "Pluie toxique",
	Deep_Blue = "Bleu profond",
	Squat_Morning = "Matin accroupi",
	Cloudy_Morning = "Matin nuageux",
	Rainy_Night = "Nuit pluvieuse",
	Courier_Clouds = "Nuages ​​de courrier",
	Cursor_LockState = "État de verrouillage",
	PhotoMode_NibblesReplacer = "Remplacement des grignotages du mode photo",
	PhotoModeEnhancements = "Améliorations du mode photo",
	Button_ResetReplacerDatabase = "Réinitialiser la base de données de remplacement",
	DisablePhotoModeCursor = "Désactiver le curseur du mode photo",
	TPPCamera_Position = "Position de la caméra TPP",
	AnimatedHeadin_PhotoMode = "Tête animée en mode photo",
	LockLook_AtCamera = "Verrouiller Regarder la caméra",
	UnlockLook_AtCamera = "Déverrouiller Regarder la caméra",
	Save_Toggles_State = "Enregistrer l'état des bascules",
	Toggle_V_Head = "Basculer la tête en V",
	Toggle_TPP_Camera = "Basculer la caméra TPP",
	Target_Nibbles = "Cibler les amuse-gueules",
	Target_Replacer = "Remplacement de cible",
	Left = "Gauche",
	Left_Close = "Fermer à gauche",
	Right = "À droite",
	Right_Close = "Fermer à droite",
	Center_Close = "Fermeture centrale",
	Center_Far = "Centre éloigné",
	Front_Close = "Fermeture avant",
	Front_Far = "Avant loin",
	All = "Tout",
	Head_Only = "Tête seulement",
	Eyes_Only = "Yeux seulement",
	Movement = "Mouvement",
	V_Actions = "Actions V",
	Invisible_V = "Invisible V",
	LikeGTA_byGTATravel = "par Voyage GTA",
	EnableSpawnedProps = "Activer les accessoires générés",
	LightControl = "Contrôle de la lumière",
	Equipment = "Équipement",
	
	-- >> DIRECTOR TAB
	BeginItem_TabNameDirector = "Réalisateur",
	BeginItem_TabNameTriggers = "Déclencheurs",
	BeginCombo_StartAppearance = "Apparition de départ",
	BeginCombo_EndAppearance = "Fin de l'apparence",
	BeginCombo_Type = "Tapez",
	BeginCombo_GoToTarget = "Aller à la cible",
	BeginCombo_PlayVoice = "Jouer la voix",
	BeginCombo_Attack = "Attaque",
	BeginCombo_Triggers = "Déclencheurs",
	BeginCombo_Scripts = "Scripts",
	
	--Button
	Button_Yes = "Oui",
	Button_No = "Non",
	Button_SaveChangesOnly = "Enregistrer les modifications uniquement",
	Button_RemoveMark = "Supprimer la marque",
	Button_EditMark = "Modifier la marque",
        Button_MoveMark = "Déplacer la marque",
        Button_MoveUp = "Monter",
        Button_MoveDown = "Descendre",
        Button_NewMark = "Nouvelle marque",
	Button_AddActor = "Ajouter un acteur",
	Button_RemoveActor = "Supprimer l'acteur",
	Button_ChangeActor = "Changer d'acteur",
	Button_RadioOnlyOne = "Un seul",
	Button_RadioRandom = "Aléatoire",
	Button_RadioSequential = "Séquentiel",
	Button_SaveTrigger = "Enregistrer le déclencheur",
	Button_NewCamera = "Nouvelle caméra",
	Button_NewScript = "Nouveau scénario",
	Button_DragSpeed = "Vitesse",
	Button_ToggleMarker = "Basculer le marqueur",
	Button_TestPose = "Pose d'essai",
	Button_StopPose = "Arrêter la pose",
	
    --Button Label
	Button_Label_PlayScript = "Lire le script",
	Button_Label_StopScript = "Arrêter le script",
	Button_Label_Stopping = "Arrêter...",
	Button_Label_Restarting = "Redémarrage...",
	Button_Label_AddMark = "Ajouter une marque",
	Button_Label_SaveWNewPos = "Économisez avec un nouveau poste",
	
    --Checkbox
    --Warning / Info / Tool Tip
	Warn_ActorSingleMark_Info = "L'acteur restera sur une seule marque",
	Warn_ActorRandomMark_Info = "L'acteur se déplacera aléatoirement entre les marques",
	Warn_ActorSequentialMark_Info = "L'acteur se déplacera entre les marques dans l'ordre numérique",
	Warn_DeleteScript_Info = "Êtes-vous sûr de vouloir supprimer ce script ?",
	Warn_CloseCamForMove_Info = "Fermez le menu pour pouvoir déplacer la caméra",
	Warn_CreateScriptsDesc_Info = "Créez des scripts pour ajouter, habiller et diriger les acteurs à jouer pour le machinima, les captures d'écran et les jeux de rôle.",
	Warn_PremadeScriptsDesc_Info = "Créez des déclencheurs pour activer des scripts prédéfinis au contact.",
	Warn_CreateCamera_FovZoomDesc_Info = "Créez des caméras pour vous déplacer librement, définissez différents champs de vision et niveaux de zoom.",
	Warn_ShowMarksLocations_Info = "Affiche une icône visible aux emplacements de marquage",
	Warn_AutoTalkNpc_Info = "Cela fera parler les PNJ une fois par minute lorsqu'ils sont à portée (PNJ vocaux uniquement).",
	Warn_DirectActorPlayerPosition_Info = "Créer une marque à la position actuelle du joueur pour déplacer et diriger les acteurs",
	Warn_InMenuDirectorDesc = "Le réalisateur ne fonctionne que dans le jeu",
	
    --Text
	DirectorMode = "Mode Réalisateur",
	SelectActorToReplace = "Sélectionnez l'acteur à remplacer :",
	AddActorToCurrentScript = "Ajouter un acteur au script actuel :",
	FacialExpression_WithColon = "Expression du visage :",
	FavoritePoses_WithColon = "Poses préférées :",
	AddFavorites_Desc = "Ajoutez d'abord des poses aux favoris dans l'onglet Poses",
	HoldDuration = "Durée de conservation",
	Movement2 = "Mouvement :",
	Actions = "Actions :",
	Actors = "Acteurs",
	Editing = "Édition",
	AutoTalk = "Conversation automatique",
	ActorMarks = "Marques d'acteur",
	Current_Actors = "Acteurs actuels",
	Marks_Sequence = "Séquence de marques :",	
	ShowMarks = "Afficher les marques",
	Triggers = "Déclencheurs",
	NewTrigger = "Nouveau déclencheur",
	ShowTrigger = "Afficher le déclencheur",
	Title = "Titre",
	Select_Trigger = "Sélectionnez le déclencheur",
	Select_Script = "Sélectionnez le script",
	Delete_Trigger = "Supprimer le déclencheur",
	Triggers_On_Off = "Déclencheurs marche/arrêt",
	Running = "Courir",
	Script_Running = "Script en cours d'exécution...",
	Delete_Script = "Supprimer le script",
	RepeatInLoop = "Répéter en boucle",
	ActivationRadius = "Rayon d'activation",
	Activate = "Activer",
	Deactivate = "Désactiver",
	FOV = "Champ de vision",
	Zoom = "Zoomer",
	LockFrame = "Cadre de verrouillage",
	Walk = "Marcher",
	Sprint = "Sprint",
	Sequential = "Séquentiel",
	Cameras = "Caméras",
	NodeView = "Vue des nœuds",
	TeamA = "Équipe A",
	TeamB = "Équipe B",
	
	
	
	-- >> SETTINGS TAB
	BeginItem_TabNameSettings = "Réglages",
	BeginItem_TabNameGeneral = "Général",
	BeginItem_TabNameCompanions = "Compagnons",
	BeginItem_TabNameUI = "Interface",
	BeginItem_TabNameExperimental = "Expérimental",
	BeginItem_TabNamePhotoMode = "Mode photo",
	
	--Button
	Button_RevertAllModelSwaps = "Annuler tous les échanges de modèles",
	Button_RespawnAll = "Tout réapparaître",
	Button_ForceDespawnAll = "Forcer la disparition de tout",
	Button_ClearFavorites = "Effacer les favoris",
	Button_ClearAllSavedAppearances = "Effacer toutes les apparences enregistrées",
	Button_ClearAllBlacklistedAppearances = "Effacer toutes les apparences sur la liste noire",
	Button_ClearAllAppearanceTriggers = "Effacer tous les déclencheurs d’apparence",
	Button_ClearAllSavedDespawns = "Effacer toutes les disparitions enregistrées",
	Button_SmallCreateTheme = "Créer un thème",
	Button_SmallDeleteTheme = "Supprimer le thème",
	Button_SmallSet = "Ensemble",
	Button_ReloadAppearances = "Recharger les apparences personnalisées",
	
    --Button Label
    --Checkbox
	Checkbox_SpawnAsCompanion = "Apparaître en tant que compagnon",
	Checkbox_SpawnAsFriendly = "Apparaître aussi amicalement",
	Checkbox_InvulnerableCompanion = "Compagnon invulnérable",
	Checkbox_RespawnOnLaunch = "Réapparaître au lancement",
	Checkbox_LockTargetAfterSpawn = "Verrouiller la cible après l'apparition",
	Checkbox_OpenTargetToolsAfterSpawn = "Ouvrir les outils cibles après l'apparition",
	Checkbox_DisplayAxisIndicatorByDefault = "Afficher l'indicateur d'axe par défaut",
	Checkbox_PhotoModeEnhancements = "Améliorations du mode photo",
	Checkbox_GodModeOnLaunch = "Mode Dieu au lancement",
	Checkbox_PassiveModeOnLaunch = "Mode passif au lancement",
	Checkbox_StreamerMode = "Mode Streamer",
	Checkbox_OpenWCETOverlay = "Ouvrir avec la superposition CET",
	Checkbox_AutoResizingWindow = "Fenêtre de redimensionnement automatique",
	Checkbox_ScanningReticle = "Réticule de numérisation",
	Checkbox_FloatingTargetTools = "Outils de cible flottante",
	Checkbox_TabHeaderDescriptions = "Descriptions des en-têtes d'onglets",
	Checkbox_ExpandFavoritesByDefault = "Développer les favoris par défaut",
	Checkbox_EnableScrollBars = "Activer les barres de défilement",
	Checkbox_AlwaysDisablePhotoModeCursor = "Toujours désactiver le curseur du mode photo",
	Checkbox_Camera = "Appareil photo",
	Checkbox_DepthOfField = "DOF",
	Checkbox_Effect = "Effet",
	Checkbox_Stickers = "Autocollants",
	Checkbox_LoadSave = "Charger/Enregistrer",
	Checkbox_ExperimentalFunstuff = "Trucs expérimentaux/amusants",
	Checkbox_EnableFreezeTargetInPhotoMode = "Activer la cible gelée en mode photo",
	Checkbox_WeaponizeCompanions = "Armer les compagnons",
	Checkbox_AllowPlayerToBeTargetedinPosestab = "Autoriser le joueur à être ciblé dans l'onglet Poses",
	Checkbox_AllowPlayerAnimationsonNPCs = "Autoriser les animations des joueurs sur les PNJ",
	Checkbox_AllowExpressionOnNpcPM = "Autoriser les expressions et rechercher les PNJ en mode photo",
        Checkbox_ResetTargetPositionPM = "Réinitialiser la position cible pour les PNJ en mode photo",
        Checkbox_EnableRandomLocation = "Activer le bouton Aléatoire : téléporter le joueur vers un emplacement aléatoire de la liste",
        Checkbox_RestoreOnLaunch = "Restaurer au lancement",
        Radio_PrimarySlot = "Emplacement principal",
        Radio_SecondarySlot = "Emplacement secondaire",
	
    --Warning / Info / Tool Tip
	Warn_RespawnOnLaunch_Info = "Ce paramètre activera/désactivera la réapparition des PNJ précédemment enregistrés au chargement du jeu. AMM enregistre automatiquement vos PNJ générés lorsque vous quittez le jeu.",
	Warn_BannedWords_Info = "Ce paramètre activera/désactivera les apparences de PNJ contenant les mots : nu, nu, xxx, douche, anniversaire_suit, pp et pénis.",
	Warn_TargetNpcVehicleHotkey = "Cibler un PNJ ou un véhicule pour définir des raccourcis clavier",
	Warn_FirstLaunchDecideTabsExpand_Info = "Ce paramètre développera les Favoris dans les onglets Spawn, Swap et Decor par défaut lors du premier lancement d'AMM.",
	Warn_ExperimentalTabDesc_Info = "Les fonctionnalités expérimentales ajoutent plus de fonctionnalités, mais elles pourraient ne pas fonctionner aussi bien, d'où le label expérimental. En fait, la plupart des utilisateurs d'AMM ont activé les fonctionnalités expérimentales. Alors ne vous inquiétez pas trop et amusez-vous !",
	Warn_FreezeTargetPhotoMode_Info = "Ce paramètre est destiné à aider à geler les animations des mods qui ajoutent une animation personnalisée aux poses du mode photo ou lorsque vous reprenez l'utilisation d'IGCS.",
	Warn_WeaponizeCompanions_Info = "Cela donnera des armes et des capacités de combat à tous les PNJ. Des poses en T et des animations bizarres sont attendues.",
	Warn_PlayerAnimsOnNpc_Info = "Activez cette option si vous utilisez un mod qui permet d'utiliser les animations des joueurs sur les PNJ.",
	Warn_UnpauseRequiresIGSC = "Ce paramètre nécessite qu'IGCS réactive le temps.",
	Warn_NotInstalled = "NON INSTALLÉ",
	Warn_DespawnAllProps = "Êtes-vous sûr de vouloir supprimer tous les accessoires ?",
	
    --Text
	AMM_Version = "Version AMM :",
	CET_Version = "Version CET :",
	Codeware_Version = "Version du logiciel de code :",
	Game_Version = "Version du jeu :",
	Companion_Damage = "Dégâts du compagnon :",
	Companion_Resistance = "Résistance du compagnon :",
	Companion_Distance = "Distance du compagnon :",
	xDamage = "x Dommages",
	xResistance = "x Résistance",
	SavedAppearancesHotkeys = "Raccourcis clavier des apparences enregistrées",
	Favorites = "Favoris",
	Appearances = "Apparitions",
	Blacklist = "Liste noire",
	AppearanceTriggers = "Déclencheurs d’apparence",
	SavedDespawns = "Disparitions enregistrées",
	Interface_Language = "Langue de l'interface :",
	Custom_Appearances = "Apparitions personnalisées",
	PhotoModeAdjustments = "Ajustements du mode photo :",
	DisablePhotoModeTabs = "Désactivez les onglets du mode photo :",
	List_Height = "Hauteur de la liste",
	Listbox_Themes = "Thèmes",
	Weaponize = "Armer",
	NoAppearanceSet = "Aucun ensemble d'apparence",
	
	
	
	-- >> EXTRA	
	--Texts, warns, tips, info's, buttons and labels etc.
	Seat_FrontRight = "Avant Droit",
	Seat_BackRight = "Retour à droite",
	Seat_FrontLeft = "Avant gauche",
	Seat_BackLeft = "Arrière gauche",
	Label_Door = "Porte",
	Label_Window = "Fenêtre",

	Close = "Fermer",
	Far = "Loin",
	Moderate = "Modéré",
	
	-- >> Archives Screen
	Warning_MissingRequiredArchives = "Il manque une ou plusieurs archives requises dans AMM. Veuillez installer toute archive requise manquante dans votre dossier archive/pc/mod.",
	Warning_MissingOptionalArchives = "Il manque une ou plusieurs archives à AMM. Ceux-ci sont facultatifs mais ajoutent des fonctionnalités à AMM. Vous pouvez ignorer ces avertissements, mais AMM risque de ne pas fonctionner correctement.",
	
	
	-->> INIT.LUA
	AMMNeedsAttention = "L'AMM a besoin d'attention",
	MISSING_ARCHIVES = "ARCHIVES MANQUANTES",
	VERSION_INFORMATION = "INFORMATIONS SUR LA VERSION",
	CREDITS = "CRÉDITS",
	UPDATE_HISTORY = "HISTORIQUE DES MISE À JOUR",
	Updates = "Mises à jour",
	MISSING = "MANQUANT",
	REQUIRED = "OBLIGATOIRE",
	OPTIONAL = "OPTIONNEL",
	WHATS_NEW = "QUOI DE NEUF", --Line 83 Function Error

	--Button
	Button_Ignorewarningsforthisversion = "Ignorer les avertissements pour cette version",
	Button_Credits = "Crédits",
	Button_Cool = "Génial !",

	--Button Label
	Label_SpawnFavorites = "Favoris d'apparition",
	Label_SwapFavorites = "Échanger les favoris",
	Label_FavoriteAppearances = "Apparitions préférées",
	Label_Cancel = "Annuler",

	--Text
	Hotkey_i = "Raccourci %i",

	--Node - Function Error(nil value) 
	Top = "Haut", --Line 116
	Bottom = "En bas",
	Off = "Désactivé",
	
	--Voice Overs
	Label_GreetV = "Saluer V",
	Label_FearFoll = "Peur",
	Label_FearToll = "Péage de peur",
	Label_FearBeg = "Peur mendier",
	Label_FearRun = "Course de peur",
	Label_StealthSearch = "Recherche furtive",
	Label_StealthDeath = "Mort furtive",
	Label_StealthRestore = "Restauration furtive",
	Label_StealthEnd = "Fin furtive",
	Label_CuriousGrunt = "Grunt curieux",
	Label_GrappleGrunt = "Grunt du grappin",
	Label_Bump = "Bosse",
	Label_VehicleBump = "Bosse de véhicule",
	Label_TurretWarning = "Avertissement de tourelle",
	Label_OctantWarning = "Avertissement d'octant",
	Label_DroneWarning = "Avertissement concernant les drones",
	Label_MechWarning = "Avertissement mécanique",
	Label_EliteWarning = "Avertissement d'élite",
	Label_CameraWarning = "Avertissement de la caméra",
	Label_EnemyWarning = "Avertissement de l'ennemi",
	Label_HeavyWarning = "Avertissement important",
	Label_SniperWarning = "Avertissement de tireur d'élite",
	Label_AnyDamage = "Tout dommage",
	Label_Danger = "Danger",
	Label_CombatStart = "Début du combat",
	Label_CombatEnd = "Fin du combat",
	Label_CombatTargetHit = "Cible de combat touchée",
	Label_PedestrianHit = "Piéton heurté",
	Label_LightHit = "Coup léger",
	Label_Curse = "Malédiction",
	Label_Irritated = "Irrité",
	Label_GrenadeThrow = "Lancer de grenade",
	Label_Gotakill = "J'ai tué !",
	
	--Expressions
	Neutral = "Neutre",
	Joy = "Joie",
	Smile = "Sourire",
	Sad = "Triste",
	Surprise = "Surprise",
	Aggressive = "Agressif",
	Anger = "Colère",
	Interested = "Intéressé",
	Disinterested = "Désintéressé",
	Disappointed = "Déçu",
	Disgust = "Dégoût",
	Exertion = "Effort",
	Nervous = "Nerveux",
	Fear = "Peur",
	Terrified = "Terrifié",
	Pain = "Douleur",
	Sleepy = "Somnolent",
	Unconscious = "Inconscient",
	Dead = "Mort",

	-- Extra Expressions
	Frown = "Froncer les sourcils",
	Shocked = "Choqué",
	Annoyed_2 = "Ennuyé 2",
	Contempt = "Mépris",
	Irritated = "Irrité",
	Sceptical_1 = "Sceptique 1",
	Sceptical_2 = "Sceptique 2",
	Annoyed_1 = "Ennuyé 1",
	Offended = "Offensé",
	Disgusted = "Dégoûté",
	Disappointed_2 = "Déçu 2",
	Alert = "Alerte",
	Crying = "Pleurer",
	Embarrassed = "Embarrassé",
	Humiliated = "Humilié",
	Impatient = "Impatient",
	Anguished = "Angoissé",
	Worried = "Inquiet",
	Guilty = "Coupable",
	Grieving = "Deuil",
	RestrainedAnger = "Colère contenue",
	Afraid = "Peur",
	LookingUpAnnoyed = "Levant les yeux ennuyé",
	Offended_2 = "Offensé 2",
	Resentful = "plein de ressentiment",
	SadExtra = "Triste supplément",
	NervousBreath = "Souffle nerveux",
	ScreamingLong = "Crier longtemps",
	ScreamingShort = "Cri court",
	ScaredBreath = "Souffle effrayé",
	CryingPainful = "Pleurer douloureux",
	SelfReflectAnger = "Réflexion personnelle sur la colère",
	IndulgentSmile = "Sourire indulgent",
	Impressed = "Impressionné",
	LongSmile = "Long sourire",
	ShortSmile = "Sourire court",
	SimpleSmile = "Sourire simple",
	Confident = "Confiant",
	Relief = "Soulagement",
	Impressed_2 = "Impressionné 2",
	Admiring = "Admiratif",
	Fascinated = "Fasciné",
	RaisedBrows = "Sourcils levés",
	LookingUpThinking = "Regarder vers le haut Réfléchir",
	LeftGlanceProcessing = "Traitement du regard gauche",
	LeftGlanceCloseUp = "Regard gauche gros plan",
	LookingAround = "Regarder autour de soi",
	LookingDownThinking = "Regarder vers le bas, Réfléchir",
	LookingAroundAlt = "Regarder autour de vous Alt",
	EyesDartFromLeft = "Les yeux s'élancent de la gauche",
	EyesDartFromRight = "Les yeux s'élancent de droite",
	EyesDartToRight = "Les yeux pointent vers la droite",
	LookingLeft = "Regarder à gauche",
	LookingUpThinking_2 = "Regarder vers le haut, réfléchir 2",
	RightGlanceProcessing = "Traitement du bon coup d'oeil",
	LookingDown = "Regarder vers le bas",
	Left90GlanceClose = "Gauche90Regard Fermer",
	LookingUp = "Regarder vers le haut",
	Right90GlanceClose = "Droit90Coup d'oeil Fermer",
	LookingLeftUp = "Regarder vers la gauche",
	LookingRightUp = "Regarder vers le haut",
	ReadingDown = "Lecture vers le bas",
	ReadingUp = "Lire",
	ReadingMiddle = "Lecture au milieu",
	FrontCloseGlance = "Coup d'oeil rapproché",
	WinkLeft = "Clin d'oeil à gauche",
	EyeRoll = "Roulement des yeux",
	Squint = "Loucher",
	FalseSmile_2 = "Faux sourire 2",
	FalseSmile_1 = "Faux sourire 1",
	ListeningNewInfo = "Écoute de nouvelles informations",
	WhatDoYouWant = "Que veux-tu",
	Maybe = "Peut-être",
	SearchingForWords = "Recherche de mots",
	What = "Quoi",
	Where = "Où",
	SureSure = "Bien sûr, bien sûr",
	ListenToMe = "Écoute-moi",
	StopThePolice = "Arrêtez la police",
	HurryUp = "Dépêchez-vous",
	ShutUp = "Tais-toi",
	WinkRight = "Clin d'œil à droite",
	MockingSmile = "Sourire moqueur",
	AsymmetricalSmile = "Sourire asymétrique",
	SarcasticSmile = "Sourire sarcastique",
	Sex = "Sexe",
	LipBite_1 = "Morsure de lèvre 1",
	LipBite_2 = "Morsure de lèvre 2",
	Moan = "Gémir",
	LipBite_3 = "Morsure de lèvre 3",
	Pout = "Moue",
	SexySmile = "Sourire sexy",
	Swallow = "Avaler",
	SensualSmile = "Sourire sensuel",
	SexScene_1 = "Scène de sexe 1",
	SexScene_2 = "Scène de sexe 2",
	Kiss = "Baiser",
	UsingInhaler = "Utilisation de l'inhalateur",
	ShortYawn = "Bâillement court",
	Yawn = "Bâiller",
	Coughing = "Toux",
	Bite = "Morsure",	
	EatingFast = "Manger vite",
	ShortDrink = "Boisson courte",
	Drinking = "Boire",
	FastBite = "Morsure rapide",
	LongDrink = "Boisson longue",
	ShortSmoking = "Fumer court",
	LongSmoking = "Fumer longtemps",
	Smoking = "Fumer",
	Eating_1 = "Manger 1",
	Eating_2 = "Manger 2",
	Eating_3 = "Manger 3",
	Eating_4 = "Manger 4",
	Vomit = "Vomir",
	BeingRevived = "Être relancé",
	MalwarePositive = "Logiciel malveillant positif",
	MalwareNegative = "Logiciel malveillant négatif",
	MalwareInfected = "Logiciel malveillant infecté",
	FaceMorphActivate = "Activer la transformation du visage",
	LieNetChairSleep = "Lie Net Chaise Sommeil",
	LieNetChairBreathe = "Lie Net Chaise Respirer",
	NetrunnerDeathUnplugged = "Netrunner Death débranché",
	VeryItchyNose = "Nez très irritant",
	RollerCoasterNervous = "Montagnes russes nerveuses",
	Pfft = "Pfft",
	Hahaha = "Hahaha",
	Sniff = "Renifler",
	Ahaaa = "Ahaaa",
	Heh = "Hé",
	Huh = "Hein",
	Haaa = "Haaa",
	Sigh_Lipsync = "Soupir Lipsync",
	Hmm = "Hum",
	Whispering_1 = "Chuchotant 1",
	Whispering_2 = "Chuchotement 2",
	ApprovalYes = "Approbation Oui",
	SubtleYes = "Subtil Oui",
	QuickNoShake = "Rapide sans secousse",
	FirmYes = "Ferme Oui",
	LongNo = "Longue non",
	SubtleNo = "Subtil Non",
	NoContempt = "Pas de mépris",
	NoDisapproval = "Aucune désapprobation",
	FirmNo = "Numéro d'entreprise",
	NoEnthusiastic = "Pas d'enthousiaste",
	MockingYes = "Moqueur Oui",
	EnthusiasticYes = "Enthousiaste Oui",
	AsymmetricalCornerUp = "Coin asymétrique vers le haut",
	CornersUp = "Coins vers le haut",
	SoftSigh = "Soupir doux",
	BreathGasp = "Halètement",
	AssymetricalSneer = "Ricanement asymétrique",
	CrimpingLips = "Lèvres de sertissage",
	BrowsDown = "Sourcils vers le bas",
	BrowsLeftUp = "Sourcils laissés en haut",
	BrowsRightUp = "Sourcils vers le haut",
	BrowsUp = "Sourcils vers le haut",
	ClosedEyes_1 = "Yeux fermés 1",
	ClosedEyes_2 = "Yeux fermés 2",
	EyesClosed = "Yeux fermés",
	LookRight = "Regardez bien",
	FastBlink = "Clignotement rapide",
	SlowBlink = "Clignotement lent",
	NormalBlink = "Clignotement normal",
	TinyBlink = "Petit clignement",
	HalfBlink = "Clignement à moitié",
	RegularSaccade = "Saccade régulière",
	FrequentSaccade = "Saccades fréquentes",
	PhotoCloseupEyes = "Yeux en gros plan",
	PhotoCloseupLips = "Photo Gros Plan Lèvres",
	PhotoCloseupHair = "Photo Gros Plan Cheveux",
	PhotoCloseupChin = "Photo Gros Plan Menton",
	PhotoCloseupNose = "Photo Gros Plan Nez",
	PhotoCloseup = "Photo en gros plan",
	PhotoCloseupPleased = "Photo en gros plan heureux",
	PhotoCloseupBody = "Photo Gros Plan Corps",
	PhotoCloseupTeeth = "Photo Gros Plan Dents",
	PhotoCloseupIN = "Photo en gros plan DANS",
	PhotoCloseupOUT = "Photo en gros plan",
	Bored = "Ennuyé",
	Charming = "Charmant",
	Furious = "Furieux",
	Happy = "Heureux",
	Pissed = "Énervé",
	Pleased = "Heureux",
	Scared = "Peur",
	Surprised = "Surpris",
	Sadness = "Tristesse",
	Whistling = "Sifflement",
	Singing_1 = "Chanter 1",
	Singing_2 = "Chanter 2",
	Singing_3 = "Chanter 3",
	Alerted = "Alerté",
	Hit_1 = "Frapper 1",
	Hit_2 = "Frapper 2",
	Wounded = "Blessé",
	Death = "Mort",

	-- Expressions Category
	Negative = "Négatif",
	Positive = "Positif",
	Contemplative = "Contemplatif",
	Social = "Social",
	Sexual = "Sexuel",
	Action = "Action",
	Vocal = "Voix",
	Yes_N_No = "Oui et non",
	Nuance = "Nuances",
	Static = "Statique",
	Combat = "Combattre",
	
	--Props
	AMM_Props_Desc = "Ajoute des accessoires, des personnages et des véhicules. AMM ne se lancera pas sans cela.",
	AMM_JohnnyCompanion_Desc = "Ajoute Johnny Silverhand comme personnage pouvant être généré.",
	AMM_ScenesPack_Desc = "Ajoute 9358 animations de scène au système Poses.\nTéléchargez-le sur la page Nexus d'AMM.",
	AMM_SoundPack_Desc = "Ajoute des effets sonores pouvant être générés.",
	AMM_KerryPP_Desc = "Ajoute une nouvelle apparence nue.",
	AMM_BenjaminStonePP_Desc = "Ajoute une nouvelle apparence nue.",
	AMM_RiverPP_Desc = "Ajoute une nouvelle apparence nue.",
	AMM_YorinobuPP_Desc = "Ajoute une nouvelle apparence nue.",
	AMM_LizzyIncognito_Desc = "Ajoute une nouvelle apparence.",
	AMM_MeredithXtra_Desc = "Ajoute une nouvelle apparence.",
	AMM_DelamainFix_Desc = "Ajoute du corps à Delamain.",
	AMM_HanakoNoMakeup_Desc = "Permet à AMM de supprimer le maquillage de Hanako lors de l'utilisation de l'apparence personnalisée.",
	AMM_JudyBodyRevamp_Desc = "Remplace le corps de Judy par un nouveau corps amélioré.",
	AMM_PanamBodyRevamp_Desc = "Remplace le corps de Panam par un nouveau corps amélioré.",
	AMM_MistyBodyRevamp_Desc = "Remplace le corps de Misty par un nouveau corps amélioré.\nTéléchargez-le sur la page Nexus d'AMM.",
	AMM_1VesHanakoFixedBodyNaked_Desc = "Remplace le corps de Hanako par un nouveau corps amélioré.",
	AMM_PinkyDudeANIMFacialExpressionsFemV_Desc = "Active les outils d'expressions faciales sur Female V",
	AMM_PinkyDudeANIMFacialExpressionsMaleV_Desc = "Active les outils d'expressions faciales sur Male V",
	AMM_DinoTattooFixArchive_Desc = "Remplace le maillage et la texture.",
	AMM_SongbirdBodyFixArchive_Desc = "Remplace le corps pour corriger la zone grise. Pas encore parfait.",
	AMM_RitaWheelerCombatEnablerArchive_Desc = "Remplace le fichier d'entité afin d'activer les animations de combat.",
	AMM_CheriAppearances_Desc = "Ajoute de nouvelles apparences. Téléchargez-le sur la page Nexus d'AMM.",
	AMM_BryceNaked_Desc = "Ajoute une nouvelle apparence nue. Téléchargez-le sur la page Nexus d'AMM.",
	AMM_EvelynNaked_Desc = "Répare son corps pour permettre une apparence nue. Téléchargez-le sur la page Nexus d'AMM.",
	AMM_SaburoAppearances_Desc = "Ajoute de nouvelles apparences. Téléchargez-le sur la page Nexus d'AMM.",
	AMM_TbugAppearances_Desc = "Ajoute de nouvelles apparences. Téléchargez-le sur la page Nexus d'AMM.",
	AMM_8ug8eagAppearances_Desc = "Ajoute de nouvelles apparences. Téléchargez-le sur la page Nexus d'AMM.",
	
	--Equipments (There is a Function Error(nil value) in this section, These are just labels that are not connected to any localizable strings in the file)
	Fists = "Poings", --Line 2377 
	Katana = "Katana",
	Mantis_Blades = "Lames de mante",
	Machete = "Machette",
	Hammer = "Marteau",
	Baton = "Bâton",
	Knife = "Couteau",
	Crowbar = "Pied de biche",
	Baseball_Bat = "Batte de baseball",
	Assault_Rifle = "Fusil d'assaut",
	Sidewinder = "Sidewinder",
	Sniper_Rifle = "Fusil de précision",
	Shotgun = "Fusil de chasse",
	SMG = "SMG",
	Handgun = "Arme de poing", --Line 2391
	
	--Warning / Info / Tooltip
	Warn_CantSave_BlacklistedAppearance = "Vous ne pouvez pas enregistrer une apparence sur liste noire !",
	Warn_ConfirmDeleteSavedAppearances = "Êtes-vous sûr de vouloir supprimer toutes vos apparitions enregistrées ?",
	Warn_ConfirmDeleteBlacklistedAppearances = "Êtes-vous sûr de vouloir supprimer toutes vos apparitions sur liste noire ?",
	Warn_ConfirmDeleteSavedDespawns = "Êtes-vous sûr de vouloir supprimer toutes vos disparitions enregistrées ?",
	Warn_ConfirmDeleteAppearanceTriggers = "Êtes-vous sûr de vouloir supprimer tous vos déclencheurs d'apparence ?",
	Warn_ConfirmDeleteCurrentAppearance = "Êtes-vous sûr de vouloir supprimer votre préréglage actif actuel ?",
	Warn_WeaponizeNpcAnimationIssues = "Tous les PNJ n'auront pas les animations nécessaires pour utiliser chaque type d'arme. Des poses en T et des animations incorrectes peuvent se produire.\nÊtes-vous sûr de vouloir l'activer ?",
	Warn_ConfirmEnableExperimentalAndSave_Info = "Êtes-vous sûr de vouloir activer les fonctionnalités expérimentales ? AMM pourrait ne pas fonctionner comme prévu. Utilisez-le à vos propres risques !",
	Warn_DeleteFavoritesAskWhichOne_Info = "Si vous êtes sûr de vouloir supprimer tous vos favoris, sélectionnez lequel ci-dessous :",
	Popup_Error_Title = "Erreur",
	Button_Ok = "D'accord",
	Popup_FavoriteName = "Nom préféré",
	Popup_RenamePreset = "Renommer le préréglage",
	Popup_RenameProp = "Renommer l'accessoire",
	Editor_Title = "Éditeur de thème",
	Editor_Field_ThemeName = "Nom du thème",
	Editor_Hint_InsertThemeName = "Insérer un nouveau nom de thème",
	Error_ThemeNameExists = "Le nom du thème existe déjà",
}
