return {

    -- >> SCAN TAB
	BeginItem_TabNameScan = "Beolvasás",
	
	--Button
	Button_CyclesAppearances = "Ciklus megjelenése",
	Button_SavesAppearance = "Megjelenés mentése",
	Button_ClearSavedAppearance = "Mentett megjelenés törlése",
	Button_UnlockDoor = "Kapcsolja be az ajtózárat",
	Button_RestoreAccess = "Hozzáférés visszaállítása",
	Button_UnlockVehicle = "Oldja fel a járművet",
	Button_RepairVehicle = "Járműjavítás",
	Button_OpenCloseDoors = "Ajtók nyitása/zárása",
	Button_OpenCloseWindows = "Windows megnyitása/zárása",
	Button_ToggleEngine = "Motor váltása",
	Button_ToggleAIDriver = "AI Driver váltása",
	Button_ToggleCamera = "Kamera váltása",
	Button_ToggleRadio = "Rádió váltása",
	Button_NextRadioStation = "Következő rádióállomás",
	Button_TargetMountedVehicle = "Célra szerelt jármű",
	Button_AssignSeats = "Helyek hozzárendelése",
	Button_Assign = "Hozzárendelés",
	Button_Reset = "Reset",
	Button_FakeDie = "Hamis Die",
	Button_SmallCopy = "Másolás",
	
    --Button Label
	Button_Label_Unfollower = "Követés megszüntetése",
	Button_Label_Follower = "Követő",
	Button_Label_SaveDespawn = "Mentse a Despawnt",
	Button_Label_ClearSavedDespawn = "Mentett Despawn törlése",
	Button_LabelLockTarget = "Cél zárolása",
	Button_LabelUnlockTarget = "Unlock Target",
	Label_AddToSpawnFavs = "Add hozzá a spawnable kedvencekhez",
	Label_RemoveFromSpawnFavs = "Eltávolítás a Spawnable Kedvencek közül",
	
    --Checkbox
	Checkbox_SavedDespawnsActive = "Mentett Despawns aktív",
	Checkbox_KeepAssigned = "Maradjon hozzárendelve autóváltáskor",
	
    --Warning / Info / Tool Tip
	WarnTextAI_FastTravel = "Az induláshoz válasszon egy gyorsutazási pontot a térképen",
	WarnText_DontReloadMods = "Ne használja a Reload All Mods lehetőséget.\nKérjük, töltse be újra a mentési játékot, vagy lépjen át egy másik területre.",
	Warning_NoTarget_Desc = "Nincs cél! Kezdésként tekintse meg az NPC-t, a járművet vagy az objektumot",
	ToolTip_DisableCheckboxReloadSave_AbleTotargetClearSavedDespawns = "Tiltsa le ezt a jelölőnégyzetet, és töltse be újra a mentést, hogy célozhassa a Mentett deszpawnok törlését",
	
    --Text
	Build_Mode = "Építő mód",
	Speed = "Sebesség:",
	Search = "Keresés",
	Clear = "Törlés",
	Player = "Játékos",
	Saved = "Mentve",
	Saved_ = "Mentett_",
	Current = "Aktuális",
	Current_ = "Aktuális",
	Select_Seat = "Válassza az Ülés lehetőséget",
	Target_Info = "Cél információ",
	Target_Actions = "Célműveletek",
	No_Appearances = "Nincs megjelenés",
	No_Target = "Nincs cél",
	Favorite_Appearance = "Kedvenc megjelenés",
	Unfavorite_Appearance = "Nem kedvelt megjelenés",
	Blacklist_Appearance = "Feketelista megjelenése",
	Unblacklist_Appearance = "Unblacklist Megjelenés",
	Saved_Appearance = "Mentett megjelenés:",
	Current_Appearance = "Jelenlegi megjelenés:",
	List_of_Appearances = "Megjelenések listája",
	Appearance_Trigger = "Megjelenés trigger",
	None = "Nincs",
	Default = "Alapértelmezett",
	Zone = "Zóna",
	Area = "Terület",
	Position = "Pozíció",

	
	-- >> SPAWN TAB
	BeginItem_TabNameSpawn = "Létrehozás",
	
	--Button
	Button_Refresh = "Frissítés",
	Button_Save = "Mentés",
	Button_Confirm = "Erősítse meg",
	Button_Cancel = "Mégsem",
	Button_SmallSave = "Mentés",
	Button_SmallRespawn = "Respawn",
	Button_SmallDespawn = "Despawn",
	Button_SmallDespawn_WithSpace = "Despawn",
	Button_SmallTarget = "Cél",
	Button_SmallEquipment = "Berendezés",
	Button_LabelHostile = "Ellenséges",
	Button_LabelFriendly = "Barátságos",
	
    --Button Label
	Label_Favorite = "Kedvenc",
	Label_Unfavorite = "Nem kedvenc",
	
    --Checkbox
    --Warning / Info / Tool Tip
	Warn_PlayerInMenu = "Játékos a menüben",
	Warn_AMMonlyfunctions_ingame = "Az AMM csak játékban működik",
	Warn_SpawnWorksInGame = "A spawning csak játékban működik",
	Warn_InitError = "Inicializálási hiba",
	Warn_InitError_Info = "Kérjük, nézze meg az AppearanceMenuMod.log oldalt további információkért.",
	
    --Text
	Active_Spawns = "Aktív spawnok",
	NoActiveSpawns = "Nincs aktív spawn",
	Select_To_Spawn = "Válassza a Spawn lehetőséget",
	No_Results = "Nincs eredmény",
	ItsEmpty = "Üres :(",
	Existing_Name = "Meglévő név",
	Name = "Név",
	
	
	
	-- >> SWAP TAB
	BeginItem_TabNameSwap = "Csere",
	
	--Button
	Button_SmallRevert = "Vissza",
	
    --Button Label
    --Checkbox
    --Warning / Info / Tool Tip
	Warn_ReloadSaveUpdateChanges = "Töltse be újra a mentési játékot a változások frissítéséhez!",
	Warn_NeedReloadSaveUpdateChanges = "A módosítások frissítéséhez újra be kell töltenie a mentést.",
	Warn_ReplacerSwap = "A csere nem cserélhető! Használja az Eszközök lapot fénykép módban, hogy megcélozza őket, majd módosítsa a megjelenésüket a Spawn fülről vagy a Target Toolsról.",
	Warning = "FIGYELMEZTETÉS",
	Warning2 = "FIGYELMEZTETÉS:",
	SaveSwap_Tooltip = "Mentse el a csereügyleteket, hogy megőrizze őket a játék újratöltése után.",
	
    --Text
	CantSwapReplacer = "Csere nem cserélhető",
	Active_Model_Swaps = "Aktív modellcserék",
	Save = "Mentés",
	Restore = "Visszaállítás",
	Current_Target = "Jelenlegi cél:",
	Target_ID = "Célazonosító:",
	SelectSwap_CurrentTarget = "Válassza ki a jelenlegi céllal való cserét:",
	NoNPC_LookNPC = "Nem található NPC! Kezdésként nézze meg az NPC-t",
	
	-- Locations Categories
	Residences = "Rezidensek",
	ArasakaAndCorpo = "Arasaka & Corpo",
	ClubsAndBars = "Klubok és bárok",
	HotelsAndPleasure = "Szállodák és öröm",
	UndergroundAndCrime = "Underground & Crime",
	GovernmentAndSecurity = "Kormányzat és biztonság",
	StoryAndUnique = "Történet és egyedi",
	Ripperdocs = "Ripperdocs",
	LandmarksAndOpenWorld = "Látványosságok és nyitott világ",
	SpoilersAndHidden = "Spoilerek és rejtett",
	UserLocations = "Felhasználói helyek",
	
	
	-- >> DECOR TAB
	BeginItem_TabDecor = "Dekoráció",
	BeginItem_TabPresets = "Előbeállítások",
	Begin_ComboPresets = "Előbeállítások",
	
	--Button
	Button_SmallClone = "Klón",
	Button_SmallRemove = "Eltávolítás##",
	Button_SmallRename = "Átnevezés ##",
	Button_SmallUpdate = "Frissítés##",
	Button_SmallCancel = "Mégsem",
	Button_Frame = "Keret",
	
    --Button Label
	Button_LabelHide = "Elrejtés",
	Button_LabelUnhide = "Felfed",
	
    --Checkbox
    --Warning / Info / Tool Tip
	Warn_PersistPropSave = "Spawn Props, hogy díszítse a házat, vagy bárhol, ahol csak akarja, hogy a szíve elégedett! Mentse el a kellékeket, hogy fennmaradjanak!",
	Warn_DespawnInProgress_PleaseWait = "Despawn folyamatban. Kérem, várjon.",
	Warn_PresetsFolder_Info = "A felhasználói beállítások az AppearanceMenuMod/User/Decor mappába kerülnek mentésre",
	Warn_CustomPresets_Info = "Ez az előre beállított egyedi kellékeket tartalmaz",
	Warn_CustomPropsModders_Info = "Egyedi kellékek:",
	Warn_GamepadDirectMode_Info = "Ez lehetővé teszi a jobb integrációt a Direct móddal játékvezérlő használatakor. Lehetővé teszi egy kis információs ablakot is, amely körül ragad.",
	Warn_PresetTriggerDistanceFar = "A távoli beállítás teljesítménybeli problémákat okozhat.",
	
    --Text
	MovingAll_PropsTo_SavedProps = "Az összes kellék áthelyezése a mentett kellékek közé",
	SelectPropSpawn = "Válassza a Prop To Spawn lehetőséget:",
	Spawned_Props = "Spawned Props",
	New_Preset = "Új előbeállítás",
	No_Preset_Available = "Nincs elérhető előbeállítás",
	Preset_TriggerDistance = "Előre beállított trigger távolság",
	MovingSavedProps = "%s áthelyezése a Mentett kellékek közé",
	UpdateTag = "Címke frissítése",
	Categories = "Kategóriák",
	Decorating = "Díszítés",
	Decor_Tabs = "Dekorációs lapok",
	Saved_Props = "Mentett kellékek",
	Show_Nearby_Only = "Csak a közelben mutat",
	Show_Lights_Only = "Csak a fények megjelenítése",
	Show_LockedTarget_Only = "Csak a zárolt cél megjelenítése",
	Show_Customizable_Only = "Csak a testreszabható megjelenítése",
	Show_CustomProps_Only = "Csak egyéni kellékek megjelenítése",
	ShowOnMap = "Megjelenítés a térképen",
	Rename = "Átnevezés",
	Delete = "Törölje",
	Backup = "Biztonsági mentés",
	Merge = "Egyesítés",
	Save_All = "Az összes mentése",
	Despawn_All = "Despawn All",
	Save_ToSpecific_Tag = "Mentés adott címkére",
	Saved_Props2 = "Mentett kellékek:",
	Move_To_Tag = "Áthelyezés címkére",
	HideFromMap = "Elrejtés a térképről",
	RemovingAllPropsFromTag = "Az összes kellék eltávolítása a címkéről...",
	RemoveAllProps = "Távolítsa el az összes kelléket",
	RemoveHomeMarkerMap = "Távolítsa el az otthonjelzőt a térképről",
	TeleportToLocation = "Teleportálás a helyszínre",
	TeleportToTrigger = "Teleportálás a triggerhez",
	TeleportToMark = "Teleportálj Markhoz",
	UpdateTagLocation = "Frissítse a címke helyét",
	SharePresetWith_ThisTagOnly = "Előbeállítások megosztása csak ezzel a címkével",
	SavedPresetFolder_Info = "Előbeállítás mentve az AppearanceMenuMod/User/Decor mappába",
	NoProps_WithThese_Conditions = "Ilyen feltételekkel nincs kellék",
	AddHomeMarkerMap = "Otthonjelző hozzáadása a térképhez",
	Distance = "Távolság",
	Total_Props = "Összes kellék:",
	Type_Tag_here = "Írja be ide a címkét",
	In_World = "Világban",
	Tags = "Címkék",
	Tag = "Címke",
	Both = "Mindkettőt",	
	
	-- >> POSES TAB
	BeginItem_TabPoses = "Pózok",
	
	--Button
	Button_SmallCopyClipboard = "Másolás a vágólapra",
	
    --Button Label
    --Checkbox
    --Warning / Info / Tool Tip
    --Text
	Active_Animations = "Aktív animációk",
	ShowHistory = "Előzmények megjelenítése",
	ClearHistory = "Törölje az előzményeket",
	SelectPoseForCurrentTarget = "Válassza ki a pózt az aktuális célponthoz:",
	LastUsedPoses = "Utoljára használt pózok",
	
	
	
	-- >> TOOLS TAB
	BeginItem_TabTools = "Eszközök",
	BeginItem_TabPhotoModeNibblesReplacer = "Photo Mode Nibbles Replacer",
	BeginCombo_LookAt = "Nézd meg",
	BeginCombo_WeatherControl = "Időjárás szabályozás",
	
	--Button
	Button_SkipFrame = "Keret kihagyása",
	Button_ToggleLight = "Fény váltása",
	Button_ResetScale = "Skála visszaállítása",
	Button_ShowAsLookAtTarget = "Megjelenítés célpontként",
	Button_ResetLookAtTarget = "Reset Look At Target",
	Button_TogglePrimaryWeapon = "Felszerelni az elsődleges fegyvert",
	Button_ToggleSecondaryWeapon = "Felszerelni másodlagos fegyvert",
	Button_GiveCurrentEquippedWeapon = "Adja meg a jelenlegi felszerelt fegyvert",
	Button_SmallReset = "Reset",
	Button_ResetToPlayer = "Reset To Player",
	Button_ClearSaved = "Törlés Mentett",
	Button_Cyberpsycho = "Váltás a Cyberpsycho",
	Button_ProtectNPCfromActions = "Védje meg az NPC-t a műveletektől",
	Button_AllFriendly = "Minden barátságos",
	Button_AllHostile = "Minden ellenséges",
	Button_AllFollower = "Minden követő",
	Button_AllFakeDie = "All Fake Die",
	Button_AllDie = "Mind meghalnak",
	Button_AllDespawn = "Minden Despawn",
	Button_InvMachineGun = "Géppuska",
	Button_InvSpeed2 = "Sebesség",
	Button_ToggleMakeup = "Smink váltása",
	Button_TogglePiercings = "Piercingek váltása",
	Button_ToggleSeamfix = "Varratjavítás váltása",
        Button_TargetV = "Célpont V",
        Button_Target = "Cél",
        Button_TeleportToLocation = "Teleportálás a helyszínre",
        Button_TeleportToTrigger = "Teleportálás a triggerhez",
        Button_TeleportToMark = "Teleportálj Markhoz",
        Button_RandomLocation = "Véletlenszerű",
        Button_ShareCurrentLocation = "Aktuális hely megosztása",
	Button_GoBackToLastLocation = "Vissza az utolsó helyre",
	Button_DeleteSelectedUserLocation = "A kiválasztott felhasználói hely törlése",
	
	--Slider / Drag 
	Slider_HeadStiffness = "Fejmerevség",
	Slider_HeadPoseOverride = "Fejpóz felülbírálása",
	Slider_ChestStiffness = "Mellkasi merevség",
	Slider_ChestPoseOverride = "Mellkas póz felülbírálása",
	Slider_SlowMotion = "Lassú mozgás",
	Slider_DefaultAperture = "Alapértelmezett rekesz",
	Slider_DefaultFieldofView = "Alapértelmezett látómező",
	Slider_MovementSpeed = "Mozgási sebesség",
	Drag_MovementSpeed = "Mozgási sebesség",
	
    --Button Label
	Button_Label_PauseTimeProgression = "Az idő előrehaladásának szüneteltetése",
	Button_Label_UnpauseTimeProgression = "Az idő előrehaladásának szüneteltetése",
	Button_Label_UnfreezeTime = "Feloldási idő",
	Button_Label_FreezeTime = "Lefagyasztási idő",
	Button_Label_OpenLightSettings = "Nyissa meg a Fénybeállítások",
	Button_Label_UpdateLightTarget = "A Light Target frissítése",
	Button_Label_Activate = "Aktiválja",
	Button_Label_Deactivate = "Deaktiválás",
	Button_Label_ChangeToCrouchStance = "Váltson görnyedt helyzetre",
	Button_Label_ChangeToStandStance = "Váltson Állóállásra",
	Button_Label_PickUpTarget = "Pick Up Target",
	Button_Label_DropTarget = "Drop Target",
	Button_Label_FreezeTarget = "Freeze Target",
	Button_Label_UnfreezeTarget = "Oldja fel a célpontot",
	Button_Label_OpenTargetTools = "Nyissa meg a Target Tools alkalmazást",
	Button_Label_CloseTargetTools = "Zárja be a Céleszközöket",
	
    --Checkbox
    --Warning / Info / Tool Tip
	Warn_FileNotFound_CollabsFolder_Error = "fájl nem található a Collabs mappában",
	Warn_ShowXYZ_Orientation_Info = "Mutasson X, Y és Z nyilakat a könnyebb tájékozódás érdekében a cél mozgatásakor.",
	Warn_LookAtCamera_OptionOff_Info = "A beállítás módosítása után egyszer kapcsolja KI a Look At Camera opciót",
	Warn_DisableLookAtCamera_PhotoMode_Info = "A 'Look At Camera' egyszeri kikapcsolása Fotó módban, hogy életbe lépjen",
	Warn_RequiresRestart_Info = "A játék újraindítása szükséges ahhoz, hogy életbe lépjen",
	Warn_SlowMotion_PhotoMode_Info = "A lassított felvétel Fénykép módban csak akkor működik, ha az IGCS használatával feloldja a szünetet",
	Warn_WeatherControl_RequireCodeware = "Az időjárás szabályozáshoz Codeware 1.4+ szükséges",
	Warn_StopNpc_UnequipWeapon_Info = "Ez megakadályozza az NPC-t abban, hogy feloldja az adott fegyveredet. Megjegyzés: az NPC továbbra is tetszés szerint felveszi a harcot.",
	Warn_OutOfCombat_NpcUnequip_Info = "Megjegyzés: A harcon kívül az NPC azonnal feloldja az adott fegyvert.",
	Warn_Photomode_UnfreezeSkipFrames_Info = "Fénykép módban a Unfreeze Target kihagyja az animált pózok képkockáit. A teljes lefagyási funkcióhoz az Otis Camera Tools (IGCS) alkalmazást kell használnia.",
	Warn_UserLocationsFolder_Info = "A felhasználók helyei az AppearanceMenuMod/User/Locations mappába kerülnek mentésre",
	Warn_SeeMoreAction_Info = "További műveletek megtekintéséhez célozza meg a V-t vagy az NPC-t",
	Warn_SeeMoreActionProp_Info = "További műveletek megtekintéséhez célozza meg az NPC-t vagy a Prop-ot",
	Warn_SeamfixPiercingToggle_Info = "Ez elmenti a Makeup, Piercing és Seamfix kapcsolók állapotát a játék bezárásáig.",
	Warn_PassiveMode_Info = "Az ellenségek akkor is megtámadnak, ha harcot indítasz",
	Warn_TppCameraGameplay_Info = "A TPP Camera nem alkalmas normál játékra, de jó szórakozás egy sétához ;)",
	Warn_AnimatedHead_PhotoMode_Info = "A fénykép mód kifejezései nem működnek, ha az Animált fej be van kapcsolva.",
	Warn_ToolsOnly_WorksIngame = "Az eszközök csak játékban működnek",
	Warn_InvButtonMachineGun_Info = "Megtaláltad! A Heavy Machine Gun bekerült az Equipments közé.",
	Warn_InvButton_Info = "Megtaláltad! A Fast Motion már elérhető.",
	InvButtonTip = "Mi van, ha ide kattintok?",
	InvButtonTip2 = "Ha ide kattintasz, az nem ér semmit!",
	InvButtonTip3 = "NE KATTINTSON A FIGYELMEZTETÉSRE!",
	
    --Text
	Facial_Expression = "Arckifejezés",
	Expressions = "Kifejezések",
	Look_At = "Nézd meg",
	Look_At_Camera = "Nézd meg a kamerát:",
	Target_Tools = "Céleszközök",
	Rotation = "Forgatás",
	Tilt_Rotation = "Döntés/Forgatás",
	Mode = "Mód:",
	Precision = "Precizitás",
	Relative = "Rokon",
	Direct = "Közvetlen",
	AdvMovement = "Adv. Mozgás",
	ForceGivenWeapon = "Force Given Weapon",
	Scale = "Skála",
	ProportionalMode = "Arányos mód",
	General_Actions = "Általános intézkedések",
	DisablePassiveMode = "Passzív mód letiltása",
	EnablePassiveMode = "Passzív mód engedélyezése",
	EnableGodMode = "Engedélyezze az Isten módot",
	DisableGodMode = "Az Isten mód letiltása",
	Infinite_Oxygen = "Végtelen oxigén",
	Select_Location = "Válassza a Hely lehetőséget",
	Select_Expression = "Válassza a Kifejezés lehetőséget",
	Select_Category = "Válassza a Kategóriát",
	Teleport_Actions = "Teleport műveletek",
	Use_Teleport_Animation = "Használja a Teleport Animációt",
        Filter_Locations = "Helyek szűrése",
        Locations = "Helyszínek",
        Default_Locations = "Alapértelmezett helyek",
        Collab_Locations = "Együttműködési helyek",
        Button_AddTag = "Címke hozzáadása",
	Button_FilterByTags = "Szűrés címkék szerint",
	Button_Close = "Bezárás",
	Favorite_Selected_Location = "Kedvenc kiválasztott hely",
	Unfavorite_Selected_Location = "Kiválasztott hely eltávolítása a kedvencek közül",
	Edit_Selected_Location = "Kijelölt hely szerkesztése",
	Locations_Favorites = "--------- Kedvencek ----------",
	Locations_UserLocs = "------- Felhasználói helyek -------",
	Locations_DefaultLocs = "----------- Alapértelmezett ----------",
	Share_Location = "Hely megosztása",
	Edit_Location = "Hely szerkesztése",
	TimeWeather_Actions = "Idő és időjárás műveletek",
	TimeofDay = "Napszak",
	Time_Actions = "Időbeli műveletek",
	Rain = "Eső",
	Light_Rain = "enyhe eső",
	Cloudy = "Felhős",
	Fog = "Köd",
	Heavy_Clouds = "Erős felhők",
	Light_Clouds = "Könnyű felhők",
	Pollution = "Szennyezés",
	Sandstorm = "Homokvihar",
	Sunny = "Napos",
	Toxic_Rain = "Mérgező eső",
	Deep_Blue = "Mélykék",
	Squat_Morning = "Guggolás reggel",
	Cloudy_Morning = "Felhős reggel",
	Rainy_Night = "Esős éjszaka",
	Courier_Clouds = "Futárfelhők",
	Cursor_LockState = "Lezárási állapot",
	PhotoMode_NibblesReplacer = "Photo Mode Nibbles Replacer",
	PhotoModeEnhancements = "Fénykép mód fejlesztései",
	Button_ResetReplacerDatabase = "Reset Replacer Database",
	DisablePhotoModeCursor = "Fotó mód kurzor letiltása",
	TPPCamera_Position = "TPP kamera pozíció",
	AnimatedHeadin_PhotoMode = "Animált fej fotó módban",
	LockLook_AtCamera = "Lock Nézd meg a kamerát",
	UnlockLook_AtCamera = "Oldja fel a Nézd meg a kamerát",
	Save_Toggles_State = "Állapot mentése",
	Toggle_V_Head = "V-fej váltása",
	Toggle_TPP_Camera = "Kapcsolja be a TPP kamerát",
	Target_Nibbles = "Célpont Nibbles",
	Target_Replacer = "Cél csere",
	Left = "Balra",
	Left_Close = "Left Close",
	Right = "Igaz",
	Right_Close = "Jobbra Bezárás",
	Center_Close = "Központ bezárása",
	Center_Far = "Központ távol",
	Front_Close = "Elülső Zárás",
	Front_Far = "Elöl Távol",
	All = "Mind",
	Head_Only = "Csak fej",
	Eyes_Only = "Csak szemek",
	Movement = "Mozgás",
	V_Actions = "V Akciók",
	Invisible_V = "Láthatatlan V",
	LikeGTA_byGTATravel = "a GTA Travel által",
	EnableSpawnedProps = "Spawned Props engedélyezése",
	LightControl = "Fényszabályozás",
	Equipment = "Berendezés",
	
	-- >> DIRECTOR TAB
	BeginItem_TabNameDirector = "Rendező",
	BeginItem_TabNameTriggers = "Kiváltók",
	BeginCombo_StartAppearance = "Kezdő megjelenés",
	BeginCombo_EndAppearance = "Végső megjelenés",
	BeginCombo_Type = "Írja be",
	BeginCombo_GoToTarget = "Ugrás a célponthoz",
	BeginCombo_PlayVoice = "Play Voice",
	BeginCombo_Attack = "Támadás",
	BeginCombo_Triggers = "Kiváltók",
	BeginCombo_Scripts = "Szkriptek",
	
	--Button
	Button_Yes = "Igen",
	Button_No = "Nem",
	Button_SaveChangesOnly = "Csak a módosítások mentése",
	Button_RemoveMark = "Jelölés eltávolítása",
	Button_EditMark = "Mark szerkesztése",
        Button_MoveMark = "Mark mozgatása",
        Button_MoveUp = "Mozgás felfelé",
        Button_MoveDown = "Mozgás lefelé",
        Button_NewMark = "Új Mark",
	Button_AddActor = "Színész hozzáadása",
	Button_RemoveActor = "Távolítsa el a színészt",
	Button_ChangeActor = "Színészváltás",
	Button_RadioOnlyOne = "Csak Egy",
	Button_RadioRandom = "Véletlenszerű",
	Button_RadioSequential = "Szekvenciális",
	Button_SaveTrigger = "Indító mentése",
	Button_NewCamera = "Új kamera",
	Button_NewScript = "Új Script",
	Button_DragSpeed = "Sebesség",
	Button_ToggleMarker = "Jelölő váltása",
	Button_TestPose = "Teszt póz",
	Button_StopPose = "Állj póz",
	
    --Button Label
	Button_Label_PlayScript = "Script lejátszása",
	Button_Label_StopScript = "Stop Script",
	Button_Label_Stopping = "Leállítás...",
	Button_Label_Restarting = "Újraindítás...",
	Button_Label_AddMark = "Jelölés hozzáadása",
	Button_Label_SaveWNewPos = "Mentés új pozícióval",
	
    --Checkbox
    --Warning / Info / Tool Tip
	Warn_ActorSingleMark_Info = "A színész egyetlen Markon marad",
	Warn_ActorRandomMark_Info = "A színész véletlenszerűen mozog a Marks között",
	Warn_ActorSequentialMark_Info = "A színész számsorrendben mozog a jelek között",
	Warn_DeleteScript_Info = "Biztosan törli ezt a szkriptet?",
	Warn_CloseCamForMove_Info = "A kamera mozgatásához zárja be a menüt",
	Warn_CreateScriptsDesc_Info = "Készítsen forgatókönyveket, hogy felvegye, öltöztesse fel és irányítsa a színészeket a machinimákhoz, képernyőképekhez és szerepjátékokhoz.",
	Warn_PremadeScriptsDesc_Info = "Hozzon létre triggereket az előre elkészített szkriptek aktiválásához a kapcsolattartón.",
	Warn_CreateCamera_FovZoomDesc_Info = "Hozzon létre kamerákat a szabad mozgáshoz, különböző nézetmezők és nagyítási szintek beállításához.",
	Warn_ShowMarksLocations_Info = "Egy látható ikont jelenít meg a helyek megjelölésénél",
	Warn_AutoTalkNpc_Info = "Ezzel az NPC-k percenként egyszer beszélnek, ha hatótávolságon belül vannak (csak a hangos NPC-k)",
	Warn_DirectActorPlayerPosition_Info = "A szereplők mozgatásához és irányításához hozzon létre jelölést az aktuális játékos pozícióban",
	Warn_InMenuDirectorDesc = "A rendező csak játékban dolgozik",
	
    --Text
	DirectorMode = "Rendező mód",
	SelectActorToReplace = "Válassza ki a lecserélni kívánt színészt:",
	AddActorToCurrentScript = "Színész hozzáadása az aktuális szkripthez:",
	FacialExpression_WithColon = "Arckifejezés:",
	FavoritePoses_WithColon = "Kedvenc pózok:",
	AddFavorites_Desc = "Először a Pózok lapon adja hozzá a pózokat a kedvencekhez",
	HoldDuration = "Tartás időtartama",
	Movement2 = "Mozgás:",
	Actions = "Műveletek:",
	Actors = "Színészek",
	Editing = "Szerkesztés",
	AutoTalk = "Auto Talk",
	ActorMarks = "Marks színész",
	Current_Actors = "Jelenlegi szereplők",
	Marks_Sequence = "Jelek sorrendje:",	
	ShowMarks = "Jelek megjelenítése",
	Triggers = "Kiváltók",
	NewTrigger = "Új trigger",
	ShowTrigger = "Kioldó megjelenítése",
	Title = "Cím",
	Select_Trigger = "Válassza a Trigger lehetőséget",
	Select_Script = "Válassza a Script lehetőséget",
	Delete_Trigger = "Trigger törlése",
	Triggers_On_Off = "Triggerek be/ki",
	Running = "Futás",
	Script_Running = "Szkript fut...",
	Delete_Script = "Szkript törlése",
	RepeatInLoop = "Ismételje meg a hurokban",
	ActivationRadius = "Aktiválási sugár",
	Activate = "Aktiválja",
	Deactivate = "Deaktiválás",
	FOV = "FOV",
	Zoom = "Zoom",
	LockFrame = "Lock Frame",
	Walk = "Séta",
	Sprint = "Sprint",
	Sequential = "Szekvenciális",
	Cameras = "Fényképezőgépek",
	NodeView = "Csomópont nézet",
	TeamA = "A csapat",
	TeamB = "B csapat",
	
	
	
	-- >> SETTINGS TAB
	BeginItem_TabNameSettings = "Beállítások",
	BeginItem_TabNameGeneral = "Általános",
	BeginItem_TabNameCompanions = "Társak",
	BeginItem_TabNameUI = "Felhasználói felület",
	BeginItem_TabNameExperimental = "Kísérleti",
	BeginItem_TabNamePhotoMode = "Fotómód",
	
	--Button
	Button_RevertAllModelSwaps = "Az összes modellcsere visszaállítása",
	Button_RespawnAll = "Respawn All",
	Button_ForceDespawnAll = "Force Despawn All",
	Button_ClearFavorites = "Kedvencek törlése",
	Button_ClearAllSavedAppearances = "Minden mentett megjelenés törlése",
	Button_ClearAllBlacklistedAppearances = "Minden feketelistán szereplő megjelenés törlése",
	Button_ClearAllAppearanceTriggers = "Minden megjelenési trigger törlése",
	Button_ClearAllSavedDespawns = "Az összes mentett despawn törlése",
	Button_SmallCreateTheme = "Téma létrehozása",
	Button_SmallDeleteTheme = "Téma törlése",
	Button_SmallSet = "Állítsa be",
	Button_ReloadAppearances = "Egyéni megjelenések újratöltése",
	
    --Button Label
    --Checkbox
	Checkbox_SpawnAsCompanion = "Spawn társként",
	Checkbox_SpawnAsFriendly = "Spawn As Friendly",
	Checkbox_InvulnerableCompanion = "Sebezhetetlen Társ",
	Checkbox_RespawnOnLaunch = "Respawn On Launch",
	Checkbox_LockTargetAfterSpawn = "Cél zárolása Spawn után",
	Checkbox_OpenTargetToolsAfterSpawn = "Nyissa meg a Target Tools alkalmazást Spawn után",
	Checkbox_DisplayAxisIndicatorByDefault = "A tengelyjelző megjelenítése alapértelmezés szerint",
	Checkbox_PhotoModeEnhancements = "Fénykép mód fejlesztései",
	Checkbox_GodModeOnLaunch = "God Mode On Launch",
	Checkbox_PassiveModeOnLaunch = "Passzív mód indításkor",
	Checkbox_StreamerMode = "Streamer mód",
	Checkbox_OpenWCETOverlay = "Megnyitás CET Overlay-vel",
	Checkbox_AutoResizingWindow = "Automatikus átméretezés ablak",
	Checkbox_ScanningReticle = "Szkennelési irányzék",
	Checkbox_FloatingTargetTools = "Lebegő céleszközök",
	Checkbox_TabHeaderDescriptions = "Lapfejlécek leírása",
	Checkbox_ExpandFavoritesByDefault = "Alapértelmezés szerint bontsa ki a Kedvenceket",
	Checkbox_EnableScrollBars = "Gördítősávok engedélyezése",
	Checkbox_AlwaysDisablePhotoModeCursor = "Mindig tiltsa le a Fénykép mód kurzort",
	Checkbox_Camera = "Fényképezőgép",
	Checkbox_DepthOfField = "DOF",
	Checkbox_Effect = "Hatás",
	Checkbox_Stickers = "Matricák",
	Checkbox_LoadSave = "Betöltés/Mentés",
	Checkbox_ExperimentalFunstuff = "Kísérleti/szórakoztató dolgok",
	Checkbox_EnableFreezeTargetInPhotoMode = "Cél kimerevítése engedélyezése Fotó módban",
	Checkbox_WeaponizeCompanions = "Fegyverezze fel a társakat",
	Checkbox_AllowPlayerToBeTargetedinPosestab = "Engedélyezze a játékos célzását a Pózok lapon",
	Checkbox_AllowPlayerAnimationsonNPCs = "Játékos animációk engedélyezése NPC-ken",
	Checkbox_AllowExpressionOnNpcPM = "Kifejezések engedélyezése és NPC-k keresése Fotó módban",
        Checkbox_ResetTargetPositionPM = "Célpozíció alaphelyzetbe állítása a fénykép üzemmódú NPC-khez",
        Checkbox_EnableRandomLocation = "Véletlenszerű gomb engedélyezése: teleportálja a játékost egy véletlenszerű helyre a listából",
        Checkbox_RestoreOnLaunch = "Visszaállítás indításkor",
        Radio_PrimarySlot = "Elsődleges Slot",
        Radio_SecondarySlot = "Másodlagos Slot",
	
    --Warning / Info / Tool Tip
	Warn_RespawnOnLaunch_Info = "Ez a beállítás engedélyezi/letiltja a korábban elmentett NPC-k újraindítását a játék betöltésekor. Az AMM automatikusan elmenti a létrehozott NPC-ket, amikor kilép a játékból.",
	Warn_BannedWords_Info = "Ez a beállítás engedélyezi/letiltja azokat az NPC megjelenéseket, amelyek a következő szavakat tartalmazzák: meztelenül, meztelenül, xxx, zuhany, születésnapi_öltöny, pp és pénisz.",
	Warn_TargetNpcVehicleHotkey = "Célozzon meg NPC-t vagy járművet a gyorsbillentyűk beállításához",
	Warn_FirstLaunchDecideTabsExpand_Info = "Ez a beállítás alapértelmezés szerint kibővíti a Kedvenceket a Spawn, Swap és Decor lapokon az AMM első indításakor.",
	Warn_ExperimentalTabDesc_Info = "A kísérleti funkciók több funkciót adnak hozzá, de előfordulhat, hogy nem működnek olyan jól, így a kísérleti címke. Valójában a legtöbb AMM felhasználónál engedélyezve vannak a kísérleti funkciók. Szóval ne aggódj túl sokat és érezd jól magad!",
	Warn_FreezeTargetPhotoMode_Info = "Ennek a beállításnak az a célja, hogy segítsen lefagyasztani az animációkat olyan modokból, amelyek egyéni animációt adnak a Photo Mode pózokhoz, vagy amikor az IGCS használatával feloldja a szünetet.",
	Warn_WeaponizeCompanions_Info = "Ez fegyvereket és harci képességeket ad minden NPC-nek. T-pózolás és furcsa animációk várhatók.",
	Warn_PlayerAnimsOnNpc_Info = "Engedélyezze ezt, ha olyan modot használ, amely lehetővé teszi a Player Animációk használatát NPC-ken.",
	Warn_UnpauseRequiresIGSC = "Ez a beállítás megköveteli az IGCS-nek a szüneteltetési időt.",
	Warn_NotInstalled = "NEM TELEPÍTETT",
	Warn_DespawnAllProps = "Biztos benne, hogy a Despawn All Props funkciót szeretné végrehajtani?",
	
    --Text
	AMM_Version = "AMM verzió:",
	CET_Version = "CET verzió:",
	Codeware_Version = "Codeware verzió:",
	Game_Version = "Játék verzió:",
	Companion_Damage = "Társ sérülése:",
	Companion_Resistance = "Társellenállás:",
	Companion_Distance = "Társ távolság:",
	xDamage = "x Kár",
	xResistance = "x Ellenállás",
	SavedAppearancesHotkeys = "Mentett megjelenések gyorsbillentyűi",
	Favorites = "Kedvencek",
	Appearances = "Megjelenések",
	Blacklist = "Feketelista",
	AppearanceTriggers = "Megjelenés triggerek",
	SavedDespawns = "Mentett Despawns",
	Interface_Language = "Interfész nyelve:",
	Custom_Appearances = "Egyedi megjelenések",
	PhotoModeAdjustments = "Fotó mód beállításai:",
	DisablePhotoModeTabs = "Fotó mód lapok letiltása:",
	List_Height = "Lista magassága",
	Listbox_Themes = "Témák",
	Weaponize = "Fegyverezni",
	NoAppearanceSet = "Nincs megjelenés beállítva",
	
	
	
	-- >> EXTRA	
	--Texts, warns, tips, info's, buttons and labels etc.
	Seat_FrontRight = "Jobb első",
	Seat_BackRight = "Vissza Jobbra",
	Seat_FrontLeft = "Bal első",
	Seat_BackLeft = "Vissza Balra",
	Label_Door = "Ajtó",
	Label_Window = "Ablak",

	Close = "Bezárás",
	Far = "Távol",
	Moderate = "Mérsékelt",
	
	-- >> Archives Screen
	Warning_MissingRequiredArchives = "Az AMM-ből hiányzik egy vagy több szükséges archívum. Kérjük, telepítse a hiányzó szükséges archívumot az archívum/pc/mod mappába.",
	Warning_MissingOptionalArchives = "Az AMM-ből hiányzik egy vagy több archívum. Ezek nem kötelezőek, de további funkciókat adnak az AMM-hez. Figyelmen kívül hagyhatja ezeket a figyelmeztetéseket, de előfordulhat, hogy az AMM nem működik megfelelően.",
	
	
	-->> INIT.LUA
	AMMNeedsAttention = "Az AMM figyelmet igényel",
	MISSING_ARCHIVES = "HIÁNYZÓ ARCHÍVUM",
	VERSION_INFORMATION = "VERZIÓ INFORMÁCIÓK",
	CREDITS = "HITELEK",
	UPDATE_HISTORY = "FRISSÍTÉS ELŐZMÉNYEK",
	Updates = "Frissítések",
	MISSING = "HIÁNYZIK",
	REQUIRED = "KÖTELEZŐ",
	OPTIONAL = "OPCIONÁLIS",
	WHATS_NEW = "ÚJDONSÁGOK", --Line 83 Function Error

	--Button
	Button_Ignorewarningsforthisversion = "Figyelmen kívül hagyja az erre a verzióra vonatkozó figyelmeztetéseket",
	Button_Credits = "Kredit",
	Button_Cool = "Cool!",

	--Button Label
	Label_SpawnFavorites = "Spawn Kedvencek",
	Label_SwapFavorites = "Kedvencek cseréje",
	Label_FavoriteAppearances = "Kedvenc megjelenések",
	Label_Cancel = "Mégsem",

	--Text
	Hotkey_i = "%i gyorsbillentyű",

	--Node - Function Error(nil value) 
	Top = "Top", --Line 116
	Bottom = "Alul",
	Off = "Ki",
	
	--Voice Overs
	Label_GreetV = "Üdvözöljük V",
	Label_FearFoll = "Félelem Foll",
	Label_FearToll = "Fear Toll",
	Label_FearBeg = "Fear Beg",
	Label_FearRun = "Fear Run",
	Label_StealthSearch = "Stealth Search",
	Label_StealthDeath = "Stealth Death",
	Label_StealthRestore = "Stealth Restore",
	Label_StealthEnd = "Stealth End",
	Label_CuriousGrunt = "Kíváncsi Grunt",
	Label_GrappleGrunt = "Grapple Grunt",
	Label_Bump = "Bump",
	Label_VehicleBump = "Jármű Bump",
	Label_TurretWarning = "Torony figyelmeztetés",
	Label_OctantWarning = "Oktáns figyelmeztetés",
	Label_DroneWarning = "Drón figyelmeztetés",
	Label_MechWarning = "Mech Figyelmeztetés",
	Label_EliteWarning = "Elit figyelmeztetés",
	Label_CameraWarning = "Kamera Figyelmeztetés",
	Label_EnemyWarning = "Ellenséges figyelmeztetés",
	Label_HeavyWarning = "Erős figyelmeztetés",
	Label_SniperWarning = "Sniper Figyelmeztetés",
	Label_AnyDamage = "Bármilyen sérülés",
	Label_Danger = "Veszély",
	Label_CombatStart = "Combat Start",
	Label_CombatEnd = "Harc vége",
	Label_CombatTargetHit = "Combat Target Hit",
	Label_PedestrianHit = "Gyalogos találat",
	Label_LightHit = "Light Hit",
	Label_Curse = "Átok",
	Label_Irritated = "Irritált",
	Label_GrenadeThrow = "Gránátdobás",
	Label_Gotakill = "Megölték!",
	
	--Expressions
	Neutral = "Semleges",
	Joy = "Öröm",
	Smile = "Mosolyogj",
	Sad = "Szomorú",
	Surprise = "Meglepetés",
	Aggressive = "Agresszív",
	Anger = "Harag",
	Interested = "Érdekelt",
	Disinterested = "Érdektelen",
	Disappointed = "Csalódott",
	Disgust = "Undor",
	Exertion = "Erőfeszítés",
	Nervous = "Ideges",
	Fear = "Félelem",
	Terrified = "rémülten",
	Pain = "Fájdalom",
	Sleepy = "Álmos",
	Unconscious = "Eszméletlen",
	Dead = "Halott",

	-- Extra Expressions
	Frown = "A homlokát ráncolva",
	Shocked = "Megdöbbenve",
	Annoyed_2 = "Bosszús 2",
	Contempt = "Megvetés",
	Irritated = "Irritált",
	Sceptical_1 = "Szkeptikus 1",
	Sceptical_2 = "Szkeptikus 2",
	Annoyed_1 = "Bosszantott 1",
	Offended = "megsértődött",
	Disgusted = "Undorodva",
	Disappointed_2 = "Csalódott 2",
	Alert = "Figyelmeztetés",
	Crying = "Sírás",
	Embarrassed = "Zavarban",
	Humiliated = "Megalázva",
	Impatient = "Türelmetlen",
	Anguished = "gyötrődve",
	Worried = "aggódik",
	Guilty = "Bűnös",
	Grieving = "Gyászoló",
	RestrainedAnger = "Visszafogott harag",
	Afraid = "Félek",
	LookingUpAnnoyed = "Bosszankodva néz fel",
	Offended_2 = "Sértett 2",
	Resentful = "Neheztelő",
	SadExtra = "Szomorú Extra",
	NervousBreath = "Ideges légzés",
	ScreamingLong = "Hosszú sikoltozás",
	ScreamingShort = "Screaming Short",
	ScaredBreath = "Ijedt lélegzet",
	CryingPainful = "Fájdalmas sírás",
	SelfReflectAnger = "Önreflektor Harag",
	IndulgentSmile = "Kényeztető mosoly",
	Impressed = "Lenyűgözött",
	LongSmile = "Hosszú mosoly",
	ShortSmile = "Rövid mosoly",
	SimpleSmile = "Egyszerű mosoly",
	Confident = "Magabiztos",
	Relief = "Megkönnyebbülés",
	Impressed_2 = "Lenyűgözött 2",
	Admiring = "Gyönyörködni",
	Fascinated = "Elbűvölt",
	RaisedBrows = "Felvont szemöldök",
	LookingUpThinking = "Felnézett gondolkodás",
	LeftGlanceProcessing = "Left Glance feldolgozás",
	LeftGlanceCloseUp = "Bal pillantás közelről",
	LookingAround = "Körülnézni",
	LookingDownThinking = "Lenézve Gondolkodva",
	LookingAroundAlt = "Körülnézve Alt",
	EyesDartFromLeft = "Eyes Dart Balról",
	EyesDartFromRight = "Eyes Dart Jobbról",
	EyesDartToRight = "Eyes Dart To Right",
	LookingLeft = "Balra nézve",
	LookingUpThinking_2 = "Felnézett gondolkodás 2",
	RightGlanceProcessing = "Jobb pillantás feldolgozás",
	LookingDown = "Lefelé nézve",
	Left90GlanceClose = "Left90Glance Bezárás",
	LookingUp = "Felnéz",
	Right90GlanceClose = "Jobb 90Glance Bezárás",
	LookingLeftUp = "Balra felfelé nézve",
	LookingRightUp = "Felfelé néz",
	ReadingDown = "Leolvasás",
	ReadingUp = "Felolvasás",
	ReadingMiddle = "Középső olvasás",
	FrontCloseGlance = "Első közeli pillantás",
	WinkLeft = "Kacsints balra",
	EyeRoll = "Eye Roll",
	Squint = "Hunyorog",
	FalseSmile_2 = "Hamis mosoly 2",
	FalseSmile_1 = "Hamis mosoly 1",
	ListeningNewInfo = "Új információk hallgatása",
	WhatDoYouWant = "Mit akarsz",
	Maybe = "Talán",
	SearchingForWords = "Szavak keresése",
	What = "Mit",
	Where = "Hol",
	SureSure = "Persze Persze",
	ListenToMe = "Figyelj rám",
	StopThePolice = "Állítsd meg a Rendőrséget",
	HurryUp = "Siess",
	ShutUp = "Fogd be",
	WinkRight = "Kacsints jobbra",
	MockingSmile = "Gúnyos mosoly",
	AsymmetricalSmile = "Aszimmetrikus mosoly",
	SarcasticSmile = "Szarkasztikus mosoly",
	Sex = "Szex",
	LipBite_1 = "Ajakharapás 1",
	LipBite_2 = "Ajakharapás 2",
	Moan = "Nyög",
	LipBite_3 = "Ajakharapás 3",
	Pout = "Pout",
	SexySmile = "Szexi mosoly",
	Swallow = "Nyelj le",
	SensualSmile = "Érzéki mosoly",
	SexScene_1 = "1. szexjelenet",
	SexScene_2 = "2. szexjelenet",
	Kiss = "Kiss",
	UsingInhaler = "Az inhalátor használata",
	ShortYawn = "Rövid ásítás",
	Yawn = "Ásítson",
	Coughing = "Köhögés",
	Bite = "Harapni",	
	EatingFast = "Gyors evés",
	ShortDrink = "Rövid ital",
	Drinking = "Ivás",
	FastBite = "Gyors harapás",
	LongDrink = "Long Drink",
	ShortSmoking = "Rövid dohányzás",
	LongSmoking = "Hosszú dohányzás",
	Smoking = "Dohányzás",
	Eating_1 = "Evés 1",
	Eating_2 = "Evés 2",
	Eating_3 = "Evés 3",
	Eating_4 = "Evés 4",
	Vomit = "hányni",
	BeingRevived = "Újjáéledni",
	MalwarePositive = "Rosszindulatú program",
	MalwareNegative = "Rosszindulatú program negatív",
	MalwareInfected = "Rosszindulatú program fertőzött",
	FaceMorphActivate = "Face Morph aktiválása",
	LieNetChairSleep = "Hazugságháló szék alvás",
	LieNetChairBreathe = "Hazugságháló szék Lélegezz",
	NetrunnerDeathUnplugged = "Netrunner Death Unplugged",
	VeryItchyNose = "Nagyon viszkető orr",
	RollerCoasterNervous = "Hullámvasút ideges",
	Pfft = "Pfft",
	Hahaha = "Hahaha",
	Sniff = "Szippantás",
	Ahaaa = "Ahaaa",
	Heh = "Heh",
	Huh = "Huh",
	Haaa = "Haaa",
	Sigh_Lipsync = "Sóhajt Lipsync",
	Hmm = "Hmm",
	Whispering_1 = "Suttogás 1",
	Whispering_2 = "Suttogás 2",
	ApprovalYes = "Jóváhagyás Igen",
	SubtleYes = "Finom Igen",
	QuickNoShake = "Gyors No Shake",
	FirmYes = "Cég Igen",
	LongNo = "Hosszú sz",
	SubtleNo = "Finom sz",
	NoContempt = "Nincs megvetés",
	NoDisapproval = "Nincs elutasítás",
	FirmNo = "számú cég",
	NoEnthusiastic = "Nem lelkes",
	MockingYes = "Gúnyos Igen",
	EnthusiasticYes = "Lelkes Igen",
	AsymmetricalCornerUp = "Aszimmetrikus sarok felfelé",
	CornersUp = "Corners Up",
	SoftSigh = "Halk sóhaj",
	BreathGasp = "Lélegzet zihálás",
	AssymetricalSneer = "Aszimmetrikus gúny",
	CrimpingLips = "Crimping Lips",
	BrowsDown = "Szemöldök lefelé",
	BrowsLeftUp = "Szemöldök bal felfelé",
	BrowsRightUp = "Szemöldök jobbra felfelé",
	BrowsUp = "Felvonja a szemöldökét",
	ClosedEyes_1 = "Csukott szemek 1",
	ClosedEyes_2 = "Csukott szemek 2",
	EyesClosed = "Csukott szemek",
	LookRight = "Nézz Jobbra",
	FastBlink = "Gyors pislogás",
	SlowBlink = "Lassú pislogás",
	NormalBlink = "Normál Pislogás",
	TinyBlink = "Apró pislogás",
	HalfBlink = "Fél pislogás",
	RegularSaccade = "Rendszeres Saccade",
	FrequentSaccade = "Gyakori Saccade",
	PhotoCloseupEyes = "Fotó Vértes szemek",
	PhotoCloseupLips = "Fotó Vértes ajkak",
	PhotoCloseupHair = "Fotó Vértes haj",
	PhotoCloseupChin = "Fotó Vértes álla",
	PhotoCloseupNose = "Fotó Vértes orr",
	PhotoCloseup = "Fotó Vértes",
	PhotoCloseupPleased = "Fotó Vértes Örülök",
	PhotoCloseupBody = "Fotó Vértes test",
	PhotoCloseupTeeth = "Fotó Vértes fogak",
	PhotoCloseupIN = "Fotó Vértes IN",
	PhotoCloseupOUT = "Fotó Vértes OUT",
	Bored = "unatkozni",
	Charming = "Bájos",
	Furious = "Dühös",
	Happy = "Boldog",
	Pissed = "Dühös",
	Pleased = "elégedett",
	Scared = "megijedt",
	Surprised = "meglepett",
	Sadness = "Szomorúság",
	Whistling = "Fütyülve",
	Singing_1 = "Éneklés 1",
	Singing_2 = "Éneklés 2",
	Singing_3 = "Éneklés 3",
	Alerted = "Figyelmeztetett",
	Hit_1 = "1. találat",
	Hit_2 = "2. találat",
	Wounded = "Megsebesült",
	Death = "Halál",

	-- Expressions Category
	Negative = "Negatív",
	Positive = "Pozitív",
	Contemplative = "Szemlélődő",
	Social = "Társadalmi",
	Sexual = "Szexuális",
	Action = "Akció",
	Vocal = "Ének",
	Yes_N_No = "Igen és Nem",
	Nuance = "Árnyalat",
	Static = "Statikus",
	Combat = "Harc",
	
	--Props
	AMM_Props_Desc = "Kellékeket, karaktereket és járműveket ad hozzá. Az AMM e nélkül nem indul el.",
	AMM_JohnnyCompanion_Desc = "Hozzáadja Johnny Silverhandet, mint egy ivarozható karaktert.",
	AMM_ScenesPack_Desc = "9358 jelenet-animációt ad a Poses rendszerhez.\nTöltse le az AMM Nexus oldaláról.",
	AMM_SoundPack_Desc = "Felvethető hanghatásokat ad hozzá.",
	AMM_KerryPP_Desc = "Új meztelen megjelenést ad.",
	AMM_BenjaminStonePP_Desc = "Új meztelen megjelenést ad.",
	AMM_RiverPP_Desc = "Új meztelen megjelenést ad.",
	AMM_YorinobuPP_Desc = "Új meztelen megjelenést ad.",
	AMM_LizzyIncognito_Desc = "Új megjelenést ad.",
	AMM_MeredithXtra_Desc = "Új megjelenést ad.",
	AMM_DelamainFix_Desc = "Teljes testet ad a Delamainhez.",
	AMM_HanakoNoMakeup_Desc = "Lehetővé teszi az AMM számára Hanako sminkjének eltávolítását az Egyéni megjelenés használatakor.",
	AMM_JudyBodyRevamp_Desc = "Judy testét egy új, továbbfejlesztett testre cseréli.",
	AMM_PanamBodyRevamp_Desc = "Panam testét egy új, továbbfejlesztett testre cseréli.",
	AMM_MistyBodyRevamp_Desc = "Lecseréli Misty testét egy új, továbbfejlesztett testre.\nTöltse le az AMM Nexus oldaláról.",
	AMM_1VesHanakoFixedBodyNaked_Desc = "Hanako testét egy új, továbbfejlesztett testre cseréli.",
	AMM_PinkyDudeANIMFacialExpressionsFemV_Desc = "Engedélyezi az arckifejezési eszközöket a Female V-n",
	AMM_PinkyDudeANIMFacialExpressionsMaleV_Desc = "Arckifejezési eszközöket engedélyez a Male V-n",
	AMM_DinoTattooFixArchive_Desc = "Helyettesíti a hálót és a textúrát.",
	AMM_SongbirdBodyFixArchive_Desc = "Kicseréli a testet a szürke terület rögzítésére. Még nem tökéletes.",
	AMM_RitaWheelerCombatEnablerArchive_Desc = "Lecseréli az entitásfájlt, hogy engedélyezze a harci animációkat.",
	AMM_CheriAppearances_Desc = "Új megjelenéseket ad. Töltse le az AMM Nexus oldaláról.",
	AMM_BryceNaked_Desc = "Új meztelen megjelenést ad. Töltse le az AMM Nexus oldaláról.",
	AMM_EvelynNaked_Desc = "Rögzíti a testét, hogy lehetővé tegye meztelen megjelenését. Töltse le az AMM Nexus oldaláról.",
	AMM_SaburoAppearances_Desc = "Új megjelenéseket ad. Töltse le az AMM Nexus oldaláról.",
	AMM_TbugAppearances_Desc = "Új megjelenéseket ad. Töltse le az AMM Nexus oldaláról.",
	AMM_8ug8eagAppearances_Desc = "Új megjelenéseket ad. Töltse le az AMM Nexus oldaláról.",
	
	--Equipments (There is a Function Error(nil value) in this section, These are just labels that are not connected to any localizable strings in the file)
	Fists = "Öklök", --Line 2377 
	Katana = "Katana",
	Mantis_Blades = "Sáska pengék",
	Machete = "Machete",
	Hammer = "Kalapács",
	Baton = "Baton",
	Knife = "Kést",
	Crowbar = "Vargavas",
	Baseball_Bat = "Baseball ütő",
	Assault_Rifle = "Rohampuska",
	Sidewinder = "Sidewinder",
	Sniper_Rifle = "Mesterlövész puska",
	Shotgun = "Sörétes puska",
	SMG = "SMG",
	Handgun = "Kézifegyver", --Line 2391
	
	--Warning / Info / Tooltip
	Warn_CantSave_BlacklistedAppearance = "A feketelistán szereplő megjelenést nem mentheti meg!",
	Warn_ConfirmDeleteSavedAppearances = "Biztosan törli az összes mentett megjelenését?",
	Warn_ConfirmDeleteBlacklistedAppearances = "Biztosan törölni szeretnéd az összes feketelistán szereplő megjelenésedet?",
	Warn_ConfirmDeleteSavedDespawns = "Biztosan törli az összes mentett despawn-ját?",
	Warn_ConfirmDeleteAppearanceTriggers = "Biztos benne, hogy törölni szeretné az összes megjelenési triggert?",
	Warn_ConfirmDeleteCurrentAppearance = "Biztos benne, hogy törölni kívánja az aktuális aktív beállítást?",
	Warn_WeaponizeNpcAnimationIssues = "Nem minden NPC rendelkezik a szükséges animációkkal minden fegyvertípus használatához. T-pózolás és helytelen animációk fordulhatnak elő.\nBiztosan engedélyezi?",
	Warn_ConfirmEnableExperimentalAndSave_Info = "Biztosan engedélyezi a kísérleti funkciókat? Előfordulhat, hogy az AMM nem működik a várt módon. Használja saját felelősségére!",
	Warn_DeleteFavoritesAskWhichOne_Info = "Ha biztos benne, hogy törölni akarja az összes kedvencét, válassza ki az alábbiakat:",
	Popup_Error_Title = "Hiba",
	Button_Ok = "Rendben",
	Popup_FavoriteName = "Kedvenc név",
	Popup_RenamePreset = "Preset átnevezése",
	Popup_RenameProp = "Rename Prop",
	Editor_Title = "Témaszerkesztő",
	Editor_Field_ThemeName = "Téma neve",
	Editor_Hint_InsertThemeName = "Új témanév beszúrása",
	Error_ThemeNameExists = "A téma neve már létezik",
}
