return {

    -- >> SCAN TAB
	BeginItem_TabNameScan = "Scansione",
	
	--Button
	Button_CyclesAppearances = "Aspetto del ciclo",
	Button_SavesAppearance = "Salva aspetto",
	Button_ClearSavedAppearance = "Cancella aspetto salvato",
	Button_UnlockDoor = "Attiva/disattiva il blocco della porta",
	Button_RestoreAccess = "Ripristina accesso",
	Button_UnlockVehicle = "Sblocca veicolo",
	Button_RepairVehicle = "Riparare il veicolo",
	Button_OpenCloseDoors = "Apri/Chiudi porte",
	Button_OpenCloseWindows = "Apri/Chiudi Windows",
	Button_ToggleEngine = "Attiva/disattiva motore",
	Button_ToggleAIDriver = "Attiva/disattiva il driver AI",
	Button_ToggleCamera = "Attiva/disattiva fotocamera",
	Button_ToggleRadio = "Attiva/disattiva la radio",
	Button_NextRadioStation = "Prossima stazione radio",
	Button_TargetMountedVehicle = "Veicolo montato sul bersaglio",
	Button_AssignSeats = "Assegnare i posti",
	Button_Assign = "Assegnare",
	Button_Reset = "Ripristina",
	Button_FakeDie = "Muore falso",
	Button_SmallCopy = "Copia",
	
    --Button Label
	Button_Label_Unfollower = "Unfollower",
	Button_Label_Follower = "Seguace",
	Button_Label_SaveDespawn = "Salva Despawn",
	Button_Label_ClearSavedDespawn = "Cancella la scomparsa salvata",
	Button_LabelLockTarget = "Blocca bersaglio",
	Button_LabelUnlockTarget = "Sblocca bersaglio",
	Label_AddToSpawnFavs = "Aggiungi ai preferiti generabili",
	Label_RemoveFromSpawnFavs = "Rimuovi dai preferiti generabili",
	
    --Checkbox
	Checkbox_SavedDespawnsActive = "I salvati scompaiono attivi",
	Checkbox_KeepAssigned = "Mantieni assegnato quando cambi auto",
	
    --Warning / Info / Tool Tip
	WarnTextAI_FastTravel = "Seleziona un punto di viaggio rapido sulla mappa per iniziare",
	WarnText_DontReloadMods = "Non utilizzare Ricarica tutte le mod.\nRicarica il gioco salvato o spostati in un'altra area.",
	Warning_NoTarget_Desc = "Nessun obiettivo! Per iniziare, guarda l'NPC, il veicolo o l'oggetto",
	ToolTip_DisableCheckboxReloadSave_AbleTotargetClearSavedDespawns = "Disabilita questa casella di controllo e ricarica il salvataggio per poter prendere di mira Cancella i Despawn salvati",
	
    --Text
	Build_Mode = "Modalità Costruisci",
	Speed = "Velocità:",
	Search = "Cerca",
	Clear = "Chiaro",
	Player = "Giocatore",
	Saved = "Salvato",
	Saved_ = "Salvato_",
	Current = "Corrente",
	Current_ = "Corrente",
	Select_Seat = "Seleziona posto",
	Target_Info = "Informazioni sul bersaglio",
	Target_Actions = "Azioni mirate",
	No_Appearances = "Nessuna apparizione",
	No_Target = "Nessun obiettivo",
	Favorite_Appearance = "Aspetto preferito",
	Unfavorite_Appearance = "Aspetto sfavorevole",
	Blacklist_Appearance = "Aspetto nella lista nera",
	Unblacklist_Appearance = "Aspetto della lista nera",
	Saved_Appearance = "Aspetto salvato:",
	Current_Appearance = "Aspetto attuale:",
	List_of_Appearances = "Elenco delle apparizioni",
	Appearance_Trigger = "Trigger dell'aspetto",
	None = "Nessuno",
	Default = "Predefinito",
	Zone = "Zona",
	Area = "Zona",
	Position = "Posizione",

	
	-- >> SPAWN TAB
	BeginItem_TabNameSpawn = "Generare",
	
	--Button
	Button_Refresh = "Aggiorna",
	Button_Save = "Salva",
	Button_Confirm = "Conferma",
	Button_Cancel = "Annulla",
	Button_SmallSave = "Salva",
	Button_SmallRespawn = "Rinascita",
	Button_SmallDespawn = "Scomparsa",
	Button_SmallDespawn_WithSpace = "Scomparsa",
	Button_SmallTarget = "Obiettivo",
	Button_SmallEquipment = "Attrezzatura",
	Button_LabelHostile = "Ostile",
	Button_LabelFriendly = "Amichevole",
	
    --Button Label
	Label_Favorite = "Preferito",
	Label_Unfavorite = "Sfavorito",
	
    --Checkbox
    --Warning / Info / Tool Tip
	Warn_PlayerInMenu = "Giocatore nel menu",
	Warn_AMMonlyfunctions_ingame = "L'AMM funziona solo nel gioco",
	Warn_SpawnWorksInGame = "La generazione funziona solo nel gioco",
	Warn_InitError = "Errore di inizializzazione",
	Warn_InitError_Info = "Per ulteriori informazioni, controlla AppearanceMenuMod.log.log.",
	
    --Text
	Active_Spawns = "Spawn attivi",
	NoActiveSpawns = "Nessuna generazione attiva",
	Select_To_Spawn = "Seleziona Per generare",
	No_Results = "Nessun risultato",
	ItsEmpty = "È vuoto :(",
	Existing_Name = "Nome esistente",
	Name = "Nome",
	
	
	
	-- >> SWAP TAB
	BeginItem_TabNameSwap = "Scambia",
	
	--Button
	Button_SmallRevert = "Ripristina",
	
    --Button Label
    --Checkbox
    --Warning / Info / Tool Tip
	Warn_ReloadSaveUpdateChanges = "Ricarica il gioco salvato per aggiornare le modifiche!",
	Warn_NeedReloadSaveUpdateChanges = "Dovrai ricaricare il salvataggio per aggiornare le modifiche.",
	Warn_ReplacerSwap = "Non puoi scambiare il sostituto! Utilizza la scheda Strumenti in modalità foto per mirarli, quindi cambia il loro aspetto dalla scheda Spawn o dagli Strumenti di destinazione.",
	Warning = "ATTENZIONE",
	Warning2 = "ATTENZIONE:",
	SaveSwap_Tooltip = "Salva i tuoi scambi per conservarli dopo aver ricaricato il gioco.",
	
    --Text
	CantSwapReplacer = "Impossibile scambiare il sostituto",
	Active_Model_Swaps = "Scambi di modelli attivi",
	Save = "Salva",
	Restore = "Ripristina",
	Current_Target = "Obiettivo attuale:",
	Target_ID = "ID destinazione:",
	SelectSwap_CurrentTarget = "Selezionare per scambiare con il target corrente:",
	NoNPC_LookNPC = "Nessun NPC trovato! Guarda l'NPC per iniziare",
	
	-- Locations Categories
	Residences = "Residenze",
	ArasakaAndCorpo = "Arasaka & Corpo",
	ClubsAndBars = "Club e bar",
	HotelsAndPleasure = "Alberghi e piacere",
	UndergroundAndCrime = "Metropolitana e criminalità",
	GovernmentAndSecurity = "Governo e sicurezza",
	StoryAndUnique = "Storia e unico",
	Ripperdocs = "Ripperdoc",
	LandmarksAndOpenWorld = "Punti di riferimento e mondo aperto",
	SpoilersAndHidden = "Spoiler e contenuti nascosti",
	UserLocations = "Posizioni degli utenti",
	
	
	-- >> DECOR TAB
	BeginItem_TabDecor = "Arredamento",
	BeginItem_TabPresets = "Preimpostazioni",
	Begin_ComboPresets = "Preimpostazioni",
	
	--Button
	Button_SmallClone = "Clonare",
	Button_SmallRemove = "Rimuovi##",
	Button_SmallRename = "Rinomina##",
	Button_SmallUpdate = "Aggiornamento##",
	Button_SmallCancel = "Annulla",
	Button_Frame = "Cornice",
	
    --Button Label
	Button_LabelHide = "Nasconditi",
	Button_LabelUnhide = "Scopri",
	
    --Checkbox
    --Warning / Info / Tool Tip
	Warn_PersistPropSave = "Genera oggetti di scena per decorare la tua casa o ovunque tu voglia a tuo piacimento! Salva gli oggetti di scena per farli persistere!",
	Warn_DespawnInProgress_PleaseWait = "Scomparsa in corso. Attendere prego.",
	Warn_PresetsFolder_Info = "Le preimpostazioni utente vengono salvate nella cartella AppearanceMenuMod/User/Decor",
	Warn_CustomPresets_Info = "Questa preimpostazione include oggetti di scena personalizzati",
	Warn_CustomPropsModders_Info = "Oggetti di scena personalizzati realizzati da:",
	Warn_GamepadDirectMode_Info = "Ciò consente una migliore integrazione con la modalità Diretta quando si utilizza il gamepad. Abilita inoltre una piccola finestra di informazioni che resta visibile.",
	Warn_PresetTriggerDistanceFar = "L'impostazione su Lontano potrebbe causare problemi di prestazioni.",
	
    --Text
	MovingAll_PropsTo_SavedProps = "Spostamento di tutti gli oggetti sugli oggetti salvati",
	SelectPropSpawn = "Seleziona l'oggetto per generare:",
	Spawned_Props = "Oggetti di scena generati",
	New_Preset = "Nuova preimpostazione",
	No_Preset_Available = "Nessuna preimpostazione disponibile",
	Preset_TriggerDistance = "Distanza di attivazione preimpostata",
	MovingSavedProps = "Spostamento di %s sugli oggetti salvati",
	UpdateTag = "Aggiorna etichetta",
	Categories = "Categorie",
	Decorating = "Decorare",
	Decor_Tabs = "Schede di decorazione",
	Saved_Props = "Oggetti di scena salvati",
	Show_Nearby_Only = "Mostra solo nelle vicinanze",
	Show_Lights_Only = "Mostra solo luci",
	Show_LockedTarget_Only = "Mostra solo target bloccato",
	Show_Customizable_Only = "Mostra solo personalizzabile",
	Show_CustomProps_Only = "Mostra solo oggetti di scena personalizzati",
	ShowOnMap = "Mostra sulla mappa",
	Rename = "Rinominare",
	Delete = "Elimina",
	Backup = "Backup",
	Merge = "Unisci",
	Save_All = "Salva tutto",
	Despawn_All = "Sparisci tutti",
	Save_ToSpecific_Tag = "Salva su tag specifico",
	Saved_Props2 = "Oggetti salvati:",
	Move_To_Tag = "Sposta nel tag",
	HideFromMap = "Nascondi dalla mappa",
	RemovingAllPropsFromTag = "Rimozione di tutti gli oggetti di scena dal tag...",
	RemoveAllProps = "Rimuovi tutti gli oggetti di scena",
	RemoveHomeMarkerMap = "Rimuovi l'indicatore di casa dalla mappa",
	TeleportToLocation = "Teletrasporto alla posizione",
	TeleportToTrigger = "Teletrasporto per attivare",
	TeleportToMark = "Teletrasporto per Mark",
	UpdateTagLocation = "Aggiorna la posizione del tag",
	SharePresetWith_ThisTagOnly = "Condividi la preimpostazione solo con questo tag",
	SavedPresetFolder_Info = "Preimpostazione salvata nella cartella AppearanceMenuMod/User/Decor",
	NoProps_WithThese_Conditions = "Nessun oggetto di scena con queste condizioni",
	AddHomeMarkerMap = "Aggiungi indicatore di casa alla mappa",
	Distance = "Distanza",
	Total_Props = "Oggetti di scena totali:",
	Type_Tag_here = "Digita Tag qui",
	In_World = "Nel mondo",
	Tags = "Tag",
	Tag = "Etichetta",
	Both = "Entrambi",	
	
	-- >> POSES TAB
	BeginItem_TabPoses = "Pose",
	
	--Button
	Button_SmallCopyClipboard = "Copia negli appunti",
	
    --Button Label
    --Checkbox
    --Warning / Info / Tool Tip
    --Text
	Active_Animations = "Animazioni attive",
	ShowHistory = "Mostra cronologia",
	ClearHistory = "Cancella cronologia",
	SelectPoseForCurrentTarget = "Seleziona Posa per target attuale:",
	LastUsedPoses = "Ultime pose utilizzate",
	
	
	
	-- >> TOOLS TAB
	BeginItem_TabTools = "Strumenti",
	BeginItem_TabPhotoModeNibblesReplacer = "Sostitutivo dei bocconcini in modalità foto",
	BeginCombo_LookAt = "Guarda",
	BeginCombo_WeatherControl = "Controllo del tempo",
	
	--Button
	Button_SkipFrame = "Salta fotogramma",
	Button_ToggleLight = "Attiva/disattiva la luce",
	Button_ResetScale = "Reimposta scala",
	Button_ShowAsLookAtTarget = "Mostra come guarda bersaglio",
	Button_ResetLookAtTarget = "Reimposta Guarda il bersaglio",
	Button_TogglePrimaryWeapon = "Equipaggia l'arma primaria",
	Button_ToggleSecondaryWeapon = "Equipaggia l'arma secondaria",
	Button_GiveCurrentEquippedWeapon = "Dai l'arma attualmente equipaggiata",
	Button_SmallReset = "Ripristina",
	Button_ResetToPlayer = "Reimposta su lettore",
	Button_ClearSaved = "Cancella salvato",
	Button_Cyberpsycho = "Attiva/disattiva Cyberpsico",
	Button_ProtectNPCfromActions = "Proteggi l'NPC dalle azioni",
	Button_AllFriendly = "Tutti amichevoli",
	Button_AllHostile = "Tutti ostili",
	Button_AllFollower = "Tutti i follower",
	Button_AllFakeDie = "Tutti i falsi muoiono",
	Button_AllDie = "Tutti muoiono",
	Button_AllDespawn = "Tutti scompaiono",
	Button_InvMachineGun = "Mitragliatrice",
	Button_InvSpeed2 = "Velocità",
	Button_ToggleMakeup = "Attiva/disattiva il trucco",
	Button_TogglePiercings = "Attiva/disattiva i piercing",
	Button_ToggleSeamfix = "Attiva/disattiva Seamfix",
        Button_TargetV = "Obiettivo V",
        Button_Target = "Obiettivo",
        Button_TeleportToLocation = "Teletrasporto alla posizione",
        Button_TeleportToTrigger = "Teletrasporto per attivare",
        Button_TeleportToMark = "Teletrasporto per Mark",
        Button_RandomLocation = "Casuale",
        Button_ShareCurrentLocation = "Condividi la posizione corrente",
	Button_GoBackToLastLocation = "Torna all'ultima posizione",
	Button_DeleteSelectedUserLocation = "Elimina la posizione dell'utente selezionato",
	
	--Slider / Drag 
	Slider_HeadStiffness = "Rigidità della testa",
	Slider_HeadPoseOverride = "Ignora la posa della testa",
	Slider_ChestStiffness = "Rigidità toracica",
	Slider_ChestPoseOverride = "Ignora la posa del torace",
	Slider_SlowMotion = "Al rallentatore",
	Slider_DefaultAperture = "Apertura predefinita",
	Slider_DefaultFieldofView = "Campo visivo predefinito",
	Slider_MovementSpeed = "Velocità di movimento",
	Drag_MovementSpeed = "Velocità di movimento",
	
    --Button Label
	Button_Label_PauseTimeProgression = "Progressione del tempo di pausa",
	Button_Label_UnpauseTimeProgression = "Progressione temporale di riattivazione",
	Button_Label_UnfreezeTime = "Tempo di sblocco",
	Button_Label_FreezeTime = "Congelare il tempo",
	Button_Label_OpenLightSettings = "Apri Impostazioni luce",
	Button_Label_UpdateLightTarget = "Aggiorna target luce",
	Button_Label_Activate = "Attiva",
	Button_Label_Deactivate = "Disattiva",
	Button_Label_ChangeToCrouchStance = "Passa alla posizione accovacciata",
	Button_Label_ChangeToStandStance = "Passa alla posizione in piedi",
	Button_Label_PickUpTarget = "Raccogli bersaglio",
	Button_Label_DropTarget = "Rilascia bersaglio",
	Button_Label_FreezeTarget = "Congela bersaglio",
	Button_Label_UnfreezeTarget = "Scongela destinazione",
	Button_Label_OpenTargetTools = "Apri Strumenti di destinazione",
	Button_Label_CloseTargetTools = "Chiudi Strumenti di destinazione",
	
    --Checkbox
    --Warning / Info / Tool Tip
	Warn_FileNotFound_CollabsFolder_Error = "file non trovato nella cartella Collabs",
	Warn_ShowXYZ_Orientation_Info = "Mostra le frecce X, Y e Z per un orientamento più semplice quando si sposta il bersaglio.",
	Warn_LookAtCamera_OptionOff_Info = "Disattiva l'opzione Guarda fotocamera una volta dopo aver modificato questa impostazione",
	Warn_DisableLookAtCamera_PhotoMode_Info = "Disabilita \"Guarda fotocamera\" una volta in modalità foto per avere effetto",
	Warn_RequiresRestart_Info = "Richiede il riavvio del gioco per avere effetto",
	Warn_SlowMotion_PhotoMode_Info = "Il rallentatore in modalità foto funziona solo se riattivi la pausa utilizzando IGCS",
	Warn_WeatherControl_RequireCodeware = "Weather Control richiede Codeware 1.4+",
	Warn_StopNpc_UnequipWeapon_Info = "Ciò impedirà all'NPC di togliere l'equipaggiamento alla tua arma. Nota: l'NPC si disequipaggerà comunque a piacimento durante il combattimento.",
	Warn_OutOfCombat_NpcUnequip_Info = "Nota: fuori dal combattimento, l'NPC disequipaggerà immediatamente l'arma fornita.",
	Warn_Photomode_UnfreezeSkipFrames_Info = "In modalità foto, Sblocca destinazione salterà i fotogrammi nelle pose animate. Per la funzionalità completa di (s)blocco, è necessario utilizzare Otis Camera Tools (IGCS).",
	Warn_UserLocationsFolder_Info = "Le posizioni degli utenti vengono salvate nella cartella AppearanceMenuMod/User/Locations",
	Warn_SeeMoreAction_Info = "Scegli come bersaglio V o NPC per vedere più azioni",
	Warn_SeeMoreActionProp_Info = "Scegli come target un NPC o un oggetto per vedere più azioni",
	Warn_SeamfixPiercingToggle_Info = "Ciò salverà lo stato di attivazione/disattivazione del trucco, del piercing e della correzione della cucitura fino alla chiusura del gioco.",
	Warn_PassiveMode_Info = "I nemici ti attaccheranno comunque se attivi il combattimento",
	Warn_TppCameraGameplay_Info = "La TPP Camera non è adatta per il gioco normale, ma è divertente fare una passeggiata ;)",
	Warn_AnimatedHead_PhotoMode_Info = "Le espressioni in modalità foto non funzioneranno mentre la testa animata è abilitata.",
	Warn_ToolsOnly_WorksIngame = "Gli strumenti funzionano solo nel gioco",
	Warn_InvButtonMachineGun_Info = "L'hai trovato! La mitragliatrice pesante è stata aggiunta agli equipaggiamenti.",
	Warn_InvButton_Info = "L'hai trovato! Il movimento rapido è ora disponibile.",
	InvButtonTip = "Cosa succede se clicco qui?",
	InvButtonTip2 = "Cliccando qui non succede nulla!",
	InvButtonTip3 = "NON CLICCARE SEI STATO AVVISATO!",
	
    --Text
	Facial_Expression = "Espressione facciale",
	Expressions = "Espressioni",
	Look_At = "Guarda",
	Look_At_Camera = "Guarda la fotocamera:",
	Target_Tools = "Strumenti di destinazione",
	Rotation = "Rotazione",
	Tilt_Rotation = "Inclinazione/Rotazione",
	Mode = "Modalità:",
	Precision = "Precisione",
	Relative = "Relativo",
	Direct = "Diretto",
	AdvMovement = "Avv. Movimento",
	ForceGivenWeapon = "Arma data dalla forza",
	Scale = "Scala",
	ProportionalMode = "Modalità proporzionale",
	General_Actions = "Azioni generali",
	DisablePassiveMode = "Disabilita la modalità passiva",
	EnablePassiveMode = "Abilita la modalità passiva",
	EnableGodMode = "Abilita la modalità Dio",
	DisableGodMode = "Disabilita la modalità Dio",
	Infinite_Oxygen = "Ossigeno infinito",
	Select_Location = "Seleziona Posizione",
	Select_Expression = "Seleziona Espressione",
	Select_Category = "Seleziona Categoria",
	Teleport_Actions = "Azioni di teletrasporto",
	Use_Teleport_Animation = "Usa l'animazione del teletrasporto",
        Filter_Locations = "Filtra posizioni",
        Locations = "Posizioni",
        Default_Locations = "Posizioni predefinite",
        Collab_Locations = "Sedi di collaborazione",
        Button_AddTag = "Aggiungi etichetta",
	Button_FilterByTags = "Filtra per tag",
	Button_Close = "Chiudi",
	Favorite_Selected_Location = "Posizione selezionata preferita",
	Unfavorite_Selected_Location = "Posizione selezionata non preferita",
	Edit_Selected_Location = "Modifica la posizione selezionata",
	Locations_Favorites = "--------- Preferiti ----------",
	Locations_UserLocs = "------- Posizioni degli utenti -------",
	Locations_DefaultLocs = "----------- Predefinito ----------",
	Share_Location = "Condividi posizione",
	Edit_Location = "Modifica posizione",
	TimeWeather_Actions = "Azioni su tempo e meteo",
	TimeofDay = "Ora del giorno",
	Time_Actions = "Azioni temporali",
	Rain = "Pioggia",
	Light_Rain = "Pioggia leggera",
	Cloudy = "Nuvoloso",
	Fog = "Nebbia",
	Heavy_Clouds = "Nuvole pesanti",
	Light_Clouds = "Nuvole leggere",
	Pollution = "Inquinamento",
	Sandstorm = "Tempesta di sabbia",
	Sunny = "Soleggiato",
	Toxic_Rain = "Pioggia tossica",
	Deep_Blue = "Blu profondo",
	Squat_Morning = "Mattina tozza",
	Cloudy_Morning = "Mattina nuvolosa",
	Rainy_Night = "Notte piovosa",
	Courier_Clouds = "Nuvole di corriere",
	Cursor_LockState = "Blocca stato",
	PhotoMode_NibblesReplacer = "Sostitutivo dei bocconcini in modalità foto",
	PhotoModeEnhancements = "Miglioramenti della modalità foto",
	Button_ResetReplacerDatabase = "Reimposta il database sostitutivo",
	DisablePhotoModeCursor = "Disabilita il cursore della modalità foto",
	TPPCamera_Position = "Posizione della telecamera TPP",
	AnimatedHeadin_PhotoMode = "Testa animata in modalità foto",
	LockLook_AtCamera = "Blocca lo sguardo alla fotocamera",
	UnlockLook_AtCamera = "Sblocca Guarda la fotocamera",
	Save_Toggles_State = "Salva cambia stato",
	Toggle_V_Head = "Attiva/disattiva la testa a V",
	Toggle_TPP_Camera = "Attiva/disattiva la fotocamera TPP",
	Target_Nibbles = "Obiettivo Stuzzichini",
	Target_Replacer = "Sostituto del bersaglio",
	Left = "A sinistra",
	Left_Close = "Sinistra Chiudi",
	Right = "Giusto",
	Right_Close = "Giusto vicino",
	Center_Close = "Centro vicino",
	Center_Far = "Centro lontano",
	Front_Close = "Chiusura anteriore",
	Front_Far = "Fronte lontano",
	All = "Tutto",
	Head_Only = "Solo testa",
	Eyes_Only = "Solo occhi",
	Movement = "Movimento",
	V_Actions = "Azioni V",
	Invisible_V = "L'invisibile V",
	LikeGTA_byGTATravel = "a cura di GTA Travel",
	EnableSpawnedProps = "Abilita oggetti di scena generati",
	LightControl = "Controllo della luce",
	Equipment = "Attrezzatura",
	
	-- >> DIRECTOR TAB
	BeginItem_TabNameDirector = "Direttore",
	BeginItem_TabNameTriggers = "Trigger",
	BeginCombo_StartAppearance = "Inizia Aspetto",
	BeginCombo_EndAppearance = "Aspetto finale",
	BeginCombo_Type = "Digitare",
	BeginCombo_GoToTarget = "Vai al bersaglio",
	BeginCombo_PlayVoice = "Riproduci voce",
	BeginCombo_Attack = "Attacco",
	BeginCombo_Triggers = "Trigger",
	BeginCombo_Scripts = "Script",
	
	--Button
	Button_Yes = "Sì",
	Button_No = "No",
	Button_SaveChangesOnly = "Salva solo le modifiche",
	Button_RemoveMark = "Rimuovi Marco",
	Button_EditMark = "Modifica Marco",
        Button_MoveMark = "Sposta Marco",
        Button_MoveUp = "Spostati in alto",
        Button_MoveDown = "Sposta giù",
        Button_NewMark = "Nuovo Marco",
	Button_AddActor = "Aggiungi attore",
	Button_RemoveActor = "Rimuovi attore",
	Button_ChangeActor = "Cambia attore",
	Button_RadioOnlyOne = "SoloUno",
	Button_RadioRandom = "Casuale",
	Button_RadioSequential = "Sequenziale",
	Button_SaveTrigger = "Salva trigger",
	Button_NewCamera = "Nuova fotocamera",
	Button_NewScript = "Nuova sceneggiatura",
	Button_DragSpeed = "Velocità",
	Button_ToggleMarker = "Attiva/disattiva indicatore",
	Button_TestPose = "Prova di posa",
	Button_StopPose = "Interrompi la posa",
	
    --Button Label
	Button_Label_PlayScript = "Riproduci la sceneggiatura",
	Button_Label_StopScript = "Interrompi la sceneggiatura",
	Button_Label_Stopping = "Arresto...",
	Button_Label_Restarting = "Riavvio...",
	Button_Label_AddMark = "Aggiungi Marco",
	Button_Label_SaveWNewPos = "Salva con nuova posizione",
	
    --Checkbox
    --Warning / Info / Tool Tip
	Warn_ActorSingleMark_Info = "L'attore rimarrà su un singolo Mark",
	Warn_ActorRandomMark_Info = "L'attore si sposterà casualmente tra i marchi",
	Warn_ActorSequentialMark_Info = "L'attore si sposterà tra i Mark in ordine numerico",
	Warn_DeleteScript_Info = "Sei sicuro di voler eliminare questo script?",
	Warn_CloseCamForMove_Info = "Chiudere il menu per poter spostare la telecamera",
	Warn_CreateScriptsDesc_Info = "Crea script per aggiungere, vestire e dirigere gli attori affinché si esibiscano per machinima, screenshot e giochi di ruolo.",
	Warn_PremadeScriptsDesc_Info = "Crea trigger per attivare script predefiniti al contatto.",
	Warn_CreateCamera_FovZoomDesc_Info = "Crea telecamere per muoverti liberamente, imposta diversi campi visivi e livelli di zoom.",
	Warn_ShowMarksLocations_Info = "Visualizza un'icona visibile nelle posizioni dei segni",
	Warn_AutoTalkNpc_Info = "Ciò farà parlare gli NPC una volta al minuto quando si trovano nel raggio d'azione (solo NPC doppiati)",
	Warn_DirectActorPlayerPosition_Info = "Crea Mark nella posizione attuale del giocatore per muovere e dirigere gli attori",
	Warn_InMenuDirectorDesc = "Il regista funziona solo nel gioco",
	
    --Text
	DirectorMode = "Modalità regista",
	SelectActorToReplace = "Seleziona l'attore da sostituire:",
	AddActorToCurrentScript = "Aggiungi attore alla sceneggiatura corrente:",
	FacialExpression_WithColon = "Espressione facciale:",
	FavoritePoses_WithColon = "Pose preferite:",
	AddFavorites_Desc = "Aggiungi prima le pose ai preferiti nella scheda Pose",
	HoldDuration = "Mantieni durata",
	Movement2 = "Movimento:",
	Actions = "Azioni:",
	Actors = "Attori",
	Editing = "Modifica",
	AutoTalk = "Conversazione automatica",
	ActorMarks = "L'attore segna",
	Current_Actors = "Attori attuali",
	Marks_Sequence = "Sequenza dei segni:",	
	ShowMarks = "Mostra segni",
	Triggers = "Trigger",
	NewTrigger = "Nuovo grilletto",
	ShowTrigger = "Mostra trigger",
	Title = "Titolo",
	Select_Trigger = "Seleziona Attiva",
	Select_Script = "Seleziona Copione",
	Delete_Trigger = "Elimina trigger",
	Triggers_On_Off = "Attivazione/disattivazione dei trigger",
	Running = "Correre",
	Script_Running = "Script in esecuzione...",
	Delete_Script = "Elimina copione",
	RepeatInLoop = "Ripeti in loop",
	ActivationRadius = "Raggio di attivazione",
	Activate = "Attiva",
	Deactivate = "Disattiva",
	FOV = "FOV",
	Zoom = "Zoom",
	LockFrame = "Blocca cornice",
	Walk = "Cammina",
	Sprint = "Sprint",
	Sequential = "Sequenziale",
	Cameras = "Fotocamere",
	NodeView = "Vista nodo",
	TeamA = "Squadra A",
	TeamB = "Squadra B",
	
	
	
	-- >> SETTINGS TAB
	BeginItem_TabNameSettings = "Impostazioni",
	BeginItem_TabNameGeneral = "Generale",
	BeginItem_TabNameCompanions = "Compagni",
	BeginItem_TabNameUI = "Interfaccia utente",
	BeginItem_TabNameExperimental = "Sperimentale",
	BeginItem_TabNamePhotoMode = "Modalità foto",
	
	--Button
	Button_RevertAllModelSwaps = "Ripristina tutti gli scambi di modelli",
	Button_RespawnAll = "Rigenera tutto",
	Button_ForceDespawnAll = "Forza la scomparsa di tutti",
	Button_ClearFavorites = "Cancella preferiti",
	Button_ClearAllSavedAppearances = "Cancella tutti gli aspetti salvati",
	Button_ClearAllBlacklistedAppearances = "Cancella tutti gli aspetti della lista nera",
	Button_ClearAllAppearanceTriggers = "Cancella tutti i trigger di aspetto",
	Button_ClearAllSavedDespawns = "Cancella tutti gli scomparsi salvati",
	Button_SmallCreateTheme = "Crea tema",
	Button_SmallDeleteTheme = "Elimina tema",
	Button_SmallSet = "Impostato",
	Button_ReloadAppearances = "Ricarica aspetti personalizzati",
	
    --Button Label
    --Checkbox
	Checkbox_SpawnAsCompanion = "Genera come compagno",
	Checkbox_SpawnAsFriendly = "Genera come amichevole",
	Checkbox_InvulnerableCompanion = "Compagno invulnerabile",
	Checkbox_RespawnOnLaunch = "Ricomparsa al lancio",
	Checkbox_LockTargetAfterSpawn = "Blocca il bersaglio dopo lo spawn",
	Checkbox_OpenTargetToolsAfterSpawn = "Apri Strumenti di destinazione dopo lo spawn",
	Checkbox_DisplayAxisIndicatorByDefault = "Visualizza l'indicatore dell'asse per impostazione predefinita",
	Checkbox_PhotoModeEnhancements = "Miglioramenti della modalità foto",
	Checkbox_GodModeOnLaunch = "Modalità God al lancio",
	Checkbox_PassiveModeOnLaunch = "Modalità passiva all'avvio",
	Checkbox_StreamerMode = "Modalità streaming",
	Checkbox_OpenWCETOverlay = "Apri con sovrapposizione CET",
	Checkbox_AutoResizingWindow = "Finestra di ridimensionamento automatico",
	Checkbox_ScanningReticle = "Reticolo di scansione",
	Checkbox_FloatingTargetTools = "Strumenti di destinazione mobile",
	Checkbox_TabHeaderDescriptions = "Descrizioni dell'intestazione della scheda",
	Checkbox_ExpandFavoritesByDefault = "Espandi Preferiti per impostazione predefinita",
	Checkbox_EnableScrollBars = "Abilita le barre di scorrimento",
	Checkbox_AlwaysDisablePhotoModeCursor = "Disabilita sempre il cursore della modalità foto",
	Checkbox_Camera = "Fotocamera",
	Checkbox_DepthOfField = "DOF",
	Checkbox_Effect = "Effetto",
	Checkbox_Stickers = "Adesivi",
	Checkbox_LoadSave = "Carica/Salva",
	Checkbox_ExperimentalFunstuff = "Roba sperimentale/divertente",
	Checkbox_EnableFreezeTargetInPhotoMode = "Abilita Blocca destinazione in modalità foto",
	Checkbox_WeaponizeCompanions = "Arma i compagni",
	Checkbox_AllowPlayerToBeTargetedinPosestab = "Consenti al giocatore di essere preso di mira nella scheda Pose",
	Checkbox_AllowPlayerAnimationsonNPCs = "Consenti animazioni giocatore sugli NPC",
	Checkbox_AllowExpressionOnNpcPM = "Consenti espressioni e cerca NPC in modalità foto",
        Checkbox_ResetTargetPositionPM = "Ripristina la posizione target per gli NPC in modalità foto",
        Checkbox_EnableRandomLocation = "Abilita pulsante casuale: teletrasporta il giocatore in una posizione casuale dall'elenco",
        Checkbox_RestoreOnLaunch = "Ripristina all'avvio",
        Radio_PrimarySlot = "Slot primario",
        Radio_SecondarySlot = "Slot secondario",
	
    --Warning / Info / Tool Tip
	Warn_RespawnOnLaunch_Info = "Questa impostazione abiliterà/disabiliterà il respawn degli NPC precedentemente salvati al caricamento del gioco. AMM salva automaticamente i tuoi NPC generati quando esci dal gioco.",
	Warn_BannedWords_Info = "Questa impostazione abiliterà/disabiliterà gli aspetti NPC che contengono le parole: nudo, nudo, xxx, doccia, compleanno_abito, pp e pene.",
	Warn_TargetNpcVehicleHotkey = "Scegli come target un NPC o un veicolo per impostare i tasti di scelta rapida",
	Warn_FirstLaunchDecideTabsExpand_Info = "Questa impostazione espanderà i Preferiti nelle schede Spawn, Scambia e Decor per impostazione predefinita al primo avvio di AMM.",
	Warn_ExperimentalTabDesc_Info = "Le funzionalità sperimentali aggiungono più funzionalità, ma potrebbero non funzionare così bene, a causa dell'etichetta sperimentale. In effetti, la maggior parte degli utenti AMM ha le funzionalità sperimentali abilitate. Quindi non preoccuparti troppo e divertiti!",
	Warn_FreezeTargetPhotoMode_Info = "Questa impostazione ha lo scopo di aiutare a congelare le animazioni dei mod che aggiungono animazioni personalizzate alle pose in modalità foto o quando riattivi la pausa utilizzando IGCS.",
	Warn_WeaponizeCompanions_Info = "Ciò fornirà armi e abilità di combattimento a tutti gli NPC. Sono previste pose a T e animazioni strane.",
	Warn_PlayerAnimsOnNpc_Info = "Abilita questa opzione se stai utilizzando una mod che consente di utilizzare le animazioni del giocatore sugli NPC.",
	Warn_UnpauseRequiresIGSC = "Questa impostazione richiede che IGCS riattivi il tempo.",
	Warn_NotInstalled = "NON INSTALLATO",
	Warn_DespawnAllProps = "Sei sicuro di voler far scomparire tutti gli oggetti di scena?",
	
    --Text
	AMM_Version = "Versione AMM:",
	CET_Version = "Versione CET:",
	Codeware_Version = "Versione del codice:",
	Game_Version = "Versione del gioco:",
	Companion_Damage = "Danno al compagno:",
	Companion_Resistance = "Resistenza del compagno:",
	Companion_Distance = "Distanza compagno:",
	xDamage = "x Danno",
	xResistance = "x Resistenza",
	SavedAppearancesHotkeys = "Tasti di scelta rapida degli aspetti salvati",
	Favorites = "Preferiti",
	Appearances = "Apparenze",
	Blacklist = "Lista nera",
	AppearanceTriggers = "Trigger dell'aspetto",
	SavedDespawns = "Despawn salvati",
	Interface_Language = "Lingua dell'interfaccia:",
	Custom_Appearances = "Aspetti personalizzati",
	PhotoModeAdjustments = "Regolazioni della modalità foto:",
	DisablePhotoModeTabs = "Disabilita le schede della modalità foto:",
	List_Height = "Altezza elenco",
	Listbox_Themes = "Temi",
	Weaponize = "Armare",
	NoAppearanceSet = "Nessun aspetto impostato",
	
	
	
	-- >> EXTRA	
	--Texts, warns, tips, info's, buttons and labels etc.
	Seat_FrontRight = "Anteriore destro",
	Seat_BackRight = "Indietro a destra",
	Seat_FrontLeft = "Anteriore sinistro",
	Seat_BackLeft = "Dietro a sinistra",
	Label_Door = "Porta",
	Label_Window = "Finestra",

	Close = "Chiudi",
	Far = "Lontano",
	Moderate = "Moderato",
	
	-- >> Archives Screen
	Warning_MissingRequiredArchives = "Ad AMM mancano uno o più archivi richiesti. Installa eventuali archivi richiesti mancanti nella cartella archive/pc/mod.",
	Warning_MissingOptionalArchives = "Ad AMM mancano uno o più archivi. Questi sono facoltativi ma aggiungono funzionalità ad AMM. Puoi ignorare questi avvisi, ma AMM potrebbe non funzionare correttamente.",
	
	
	-->> INIT.LUA
	AMMNeedsAttention = "L'AMM ha bisogno di attenzione",
	MISSING_ARCHIVES = "ARCHIVI MANCANTI",
	VERSION_INFORMATION = "INFORMAZIONI SULLA VERSIONE",
	CREDITS = "CREDITI",
	UPDATE_HISTORY = "AGGIORNAMENTO DELLA CRONOLOGIA",
	Updates = "Aggiornamenti",
	MISSING = "MANCANTE",
	REQUIRED = "RICHIESTO",
	OPTIONAL = "FACOLTATIVO",
	WHATS_NEW = "COSA C'È DI NUOVO", --Line 83 Function Error

	--Button
	Button_Ignorewarningsforthisversion = "Ignora gli avvisi per questa versione",
	Button_Credits = "Crediti",
	Button_Cool = "Fantastico!",

	--Button Label
	Label_SpawnFavorites = "Genera preferiti",
	Label_SwapFavorites = "Scambia preferiti",
	Label_FavoriteAppearances = "Apparizioni preferite",
	Label_Cancel = "Annulla",

	--Text
	Hotkey_i = "Tasto di scelta rapida %i",

	--Node - Function Error(nil value) 
	Top = "In alto", --Line 116
	Bottom = "In basso",
	Off = "Spento",
	
	--Voice Overs
	Label_GreetV = "Saluta V",
	Label_FearFoll = "Paura Folle",
	Label_FearToll = "Pedaggio della paura",
	Label_FearBeg = "La paura implora",
	Label_FearRun = "Corsa alla paura",
	Label_StealthSearch = "Ricerca invisibile",
	Label_StealthDeath = "Morte furtiva",
	Label_StealthRestore = "Ripristino invisibile",
	Label_StealthEnd = "Fine furtiva",
	Label_CuriousGrunt = "Grugnito curioso",
	Label_GrappleGrunt = "Grugnito di presa",
	Label_Bump = "Urto",
	Label_VehicleBump = "Urto del veicolo",
	Label_TurretWarning = "Avviso torretta",
	Label_OctantWarning = "Avvertimento ottante",
	Label_DroneWarning = "Avviso drone",
	Label_MechWarning = "Avviso meccanizzato",
	Label_EliteWarning = "Avvertimento d'élite",
	Label_CameraWarning = "Avviso fotocamera",
	Label_EnemyWarning = "Avvertimento del nemico",
	Label_HeavyWarning = "Avvertimento pesante",
	Label_SniperWarning = "Avvertimento cecchino",
	Label_AnyDamage = "Qualsiasi danno",
	Label_Danger = "Pericolo",
	Label_CombatStart = "Inizio del combattimento",
	Label_CombatEnd = "Fine del combattimento",
	Label_CombatTargetHit = "Colpito il bersaglio del combattimento",
	Label_PedestrianHit = "Colpo pedonale",
	Label_LightHit = "Colpo leggero",
	Label_Curse = "Maledizione",
	Label_Irritated = "Irritato",
	Label_GrenadeThrow = "Lancio di granate",
	Label_Gotakill = "Ho ucciso!",
	
	--Expressions
	Neutral = "Neutro",
	Joy = "Gioia",
	Smile = "Sorridi",
	Sad = "Triste",
	Surprise = "Sorpresa",
	Aggressive = "Aggressivo",
	Anger = "Rabbia",
	Interested = "Interessato",
	Disinterested = "Disinteressato",
	Disappointed = "Deluso",
	Disgust = "Disgusto",
	Exertion = "Sforzo",
	Nervous = "Nervoso",
	Fear = "Paura",
	Terrified = "Terrorizzato",
	Pain = "Dolore",
	Sleepy = "Assonnato",
	Unconscious = "Inconscio",
	Dead = "Morto",

	-- Extra Expressions
	Frown = "cipiglio",
	Shocked = "Scioccato",
	Annoyed_2 = "Infastidito 2",
	Contempt = "Disprezzo",
	Irritated = "Irritato",
	Sceptical_1 = "Scettico 1",
	Sceptical_2 = "Scettico 2",
	Annoyed_1 = "Infastidito 1",
	Offended = "Offeso",
	Disgusted = "Disgustato",
	Disappointed_2 = "Deluso 2",
	Alert = "Avviso",
	Crying = "Piangere",
	Embarrassed = "Imbarazzato",
	Humiliated = "Umiliato",
	Impatient = "Impaziente",
	Anguished = "Angosciato",
	Worried = "Preoccupato",
	Guilty = "Colpevole",
	Grieving = "Lutto",
	RestrainedAnger = "Rabbia trattenuta",
	Afraid = "Paura",
	LookingUpAnnoyed = "Alzando lo sguardo infastidito",
	Offended_2 = "Offeso 2",
	Resentful = "Risentito",
	SadExtra = "Triste extra",
	NervousBreath = "Respiro nervoso",
	ScreamingLong = "Urlando a lungo",
	ScreamingShort = "Urlando corto",
	ScaredBreath = "Respiro spaventato",
	CryingPainful = "Piangere doloroso",
	SelfReflectAnger = "Auto-riflettere la rabbia",
	IndulgentSmile = "Sorriso indulgente",
	Impressed = "Impressionato",
	LongSmile = "Sorriso lungo",
	ShortSmile = "Breve sorriso",
	SimpleSmile = "Sorriso semplice",
	Confident = "Fiducioso",
	Relief = "Sollievo",
	Impressed_2 = "Impressionato 2",
	Admiring = "Ammirando",
	Fascinated = "Affascinato",
	RaisedBrows = "Sopracciglia sollevate",
	LookingUpThinking = "Guardando in alto pensando",
	LeftGlanceProcessing = "Elaborazione dello sguardo a sinistra",
	LeftGlanceCloseUp = "Sguardo a sinistra da vicino",
	LookingAround = "Guardandosi intorno",
	LookingDownThinking = "Guardando in basso pensando",
	LookingAroundAlt = "Guardandosi intornoAlt",
	EyesDartFromLeft = "Gli occhi sfrecciano da sinistra",
	EyesDartFromRight = "Gli occhi sfrecciano da destra",
	EyesDartToRight = "Gli occhi sfrecciano verso destra",
	LookingLeft = "Guardando a sinistra",
	LookingUpThinking_2 = "Guardare in alto pensando 2",
	RightGlanceProcessing = "Elaborazione del colpo d'occhio destro",
	LookingDown = "Guardando in basso",
	Left90GlanceClose = "Left90Sguardo Chiudi",
	LookingUp = "Guardando in alto",
	Right90GlanceClose = "Right90Glance Chiudi",
	LookingLeftUp = "Guardando a sinistra in alto",
	LookingRightUp = "Guardando in alto",
	ReadingDown = "Leggere",
	ReadingUp = "Leggere",
	ReadingMiddle = "Medio di lettura",
	FrontCloseGlance = "Sguardo ravvicinato anteriore",
	WinkLeft = "Occhiolino a sinistra",
	EyeRoll = "Alzare gli occhi",
	Squint = "Strizza gli occhi",
	FalseSmile_2 = "Falso sorriso 2",
	FalseSmile_1 = "Falso sorriso 1",
	ListeningNewInfo = "Ascolto di nuove informazioni",
	WhatDoYouWant = "Cosa vuoi",
	Maybe = "Forse",
	SearchingForWords = "Alla ricerca di parole",
	What = "Cosa",
	Where = "Dove",
	SureSure = "Certo certo",
	ListenToMe = "Ascoltami",
	StopThePolice = "Fermare la polizia",
	HurryUp = "Sbrigati",
	ShutUp = "Stai zitto",
	WinkRight = "Occhiolino, giusto",
	MockingSmile = "Sorriso beffardo",
	AsymmetricalSmile = "Sorriso asimmetrico",
	SarcasticSmile = "Sorriso sarcastico",
	Sex = "Sesso",
	LipBite_1 = "Morso alle labbra 1",
	LipBite_2 = "Morso alle labbra 2",
	Moan = "Gemiti",
	LipBite_3 = "Morso alle labbra 3",
	Pout = "Broncio",
	SexySmile = "Sorriso sexy",
	Swallow = "Ingoiare",
	SensualSmile = "Sorriso sensuale",
	SexScene_1 = "Scena di sesso 1",
	SexScene_2 = "Scena di sesso 2",
	Kiss = "Bacio",
	UsingInhaler = "Utilizzando l'inalatore",
	ShortYawn = "Breve sbadiglio",
	Yawn = "Sbadiglio",
	Coughing = "Tosse",
	Bite = "Mordere",	
	EatingFast = "Mangiare velocemente",
	ShortDrink = "Bevanda breve",
	Drinking = "Bere",
	FastBite = "Morso veloce",
	LongDrink = "Bevanda lunga",
	ShortSmoking = "Breve fumo",
	LongSmoking = "Fumare a lungo",
	Smoking = "Fumare",
	Eating_1 = "Mangiare 1",
	Eating_2 = "Mangiare 2",
	Eating_3 = "Mangiare 3",
	Eating_4 = "Mangiare 4",
	Vomit = "Vomito",
	BeingRevived = "Essere rianimato",
	MalwarePositive = "Malware positivo",
	MalwareNegative = "Malware negativo",
	MalwareInfected = "Malware infetto",
	FaceMorphActivate = "Attiva Morph faccia",
	LieNetChairSleep = "Sonno sulla sedia a rete",
	LieNetChairBreathe = "Lie Net Chair Respira",
	NetrunnerDeathUnplugged = "Morte di Netrunner scollegato",
	VeryItchyNose = "Naso molto pruriginoso",
	RollerCoasterNervous = "Montagne russe nervose",
	Pfft = "Pfft",
	Hahaha = "Ahahah",
	Sniff = "Annusare",
	Ahaaa = "Ahaaa",
	Heh = "Eh",
	Huh = "Eh",
	Haaa = "Ahah",
	Sigh_Lipsync = "Sigh Lipsync",
	Hmm = "Hmm",
	Whispering_1 = "Sussurrare 1",
	Whispering_2 = "Sussurrare 2",
	ApprovalYes = "Approvazione Sì",
	SubtleYes = "Sottile sì",
	QuickNoShake = "Veloce senza agitare",
	FirmYes = "Azienda sì",
	LongNo = "Lungo n",
	SubtleNo = "Sottile no",
	NoContempt = "Nessun disprezzo",
	NoDisapproval = "Nessuna disapprovazione",
	FirmNo = "Ditta n",
	NoEnthusiastic = "Nessun entusiasmo",
	MockingYes = "Beffardo sì",
	EnthusiasticYes = "Entusiasta sì",
	AsymmetricalCornerUp = "Angolo asimmetrico verso l'alto",
	CornersUp = "Angoli in alto",
	SoftSigh = "Sospiro dolce",
	BreathGasp = "Respiro affannoso",
	AssymetricalSneer = "Sogghigno asimmetrico",
	CrimpingLips = "Strizzare le labbra",
	BrowsDown = "Sopracciglia abbassate",
	BrowsLeftUp = "Sopracciglia rivolte verso l'alto",
	BrowsRightUp = "Sopracciglia dritte",
	BrowsUp = "Sopracciglia",
	ClosedEyes_1 = "Occhi chiusi 1",
	ClosedEyes_2 = "Occhi chiusi 2",
	EyesClosed = "Occhi chiusi",
	LookRight = "Guarda bene",
	FastBlink = "Lampeggio veloce",
	SlowBlink = "Lampeggio lento",
	NormalBlink = "Lampeggio normale",
	TinyBlink = "Piccolo battito di ciglia",
	HalfBlink = "Mezzo battito di ciglia",
	RegularSaccade = "Saccade regolare",
	FrequentSaccade = "Saccade frequente",
	PhotoCloseupEyes = "Occhi del primo piano della foto",
	PhotoCloseupLips = "Labbra del primo piano della foto",
	PhotoCloseupHair = "Capelli del primo piano della foto",
	PhotoCloseupChin = "Foto Primo piano del mento",
	PhotoCloseupNose = "Naso del primo piano della foto",
	PhotoCloseup = "Primo piano della foto",
	PhotoCloseupPleased = "Primo piano della foto soddisfatto",
	PhotoCloseupBody = "Foto Primo Piano Del Corpo",
	PhotoCloseupTeeth = "Denti del primo piano della foto",
	PhotoCloseupIN = "Foto Primo piano IN",
	PhotoCloseupOUT = "Primo piano della foto FUORI",
	Bored = "Annoiato",
	Charming = "Affascinante",
	Furious = "Furioso",
	Happy = "Felice",
	Pissed = "Incazzato",
	Pleased = "Contento",
	Scared = "Spaventato",
	Surprised = "Sorpreso",
	Sadness = "Tristezza",
	Whistling = "Fischiare",
	Singing_1 = "Cantare 1",
	Singing_2 = "Cantare 2",
	Singing_3 = "Cantare 3",
	Alerted = "Allertato",
	Hit_1 = "Premi 1",
	Hit_2 = "Colpisci 2",
	Wounded = "Ferito",
	Death = "Morte",

	-- Expressions Category
	Negative = "Negativo",
	Positive = "Positivo",
	Contemplative = "Contemplativo",
	Social = "Sociale",
	Sexual = "Sessuale",
	Action = "Azione",
	Vocal = "Vocale",
	Yes_N_No = "Sì e no",
	Nuance = "Sfumatura",
	Static = "Statico",
	Combat = "Combattimento",
	
	--Props
	AMM_Props_Desc = "Aggiunge oggetti di scena, personaggi e veicoli. AMM non verrà avviato senza questo.",
	AMM_JohnnyCompanion_Desc = "Aggiunge Johnny Silverhand come personaggio generabile.",
	AMM_ScenesPack_Desc = "Aggiunge 9358 animazioni di scene al sistema Poses.\nScaricalo dalla pagina Nexus di AMM.",
	AMM_SoundPack_Desc = "Aggiunge effetti sonori generabili.",
	AMM_KerryPP_Desc = "Aggiunge un nuovo aspetto nudo.",
	AMM_BenjaminStonePP_Desc = "Aggiunge un nuovo aspetto nudo.",
	AMM_RiverPP_Desc = "Aggiunge un nuovo aspetto nudo.",
	AMM_YorinobuPP_Desc = "Aggiunge un nuovo aspetto nudo.",
	AMM_LizzyIncognito_Desc = "Aggiunge un nuovo aspetto.",
	AMM_MeredithXtra_Desc = "Aggiunge un nuovo aspetto.",
	AMM_DelamainFix_Desc = "Aggiunge corpo completo a Delamain.",
	AMM_HanakoNoMakeup_Desc = "Consente ad AMM di rimuovere il trucco di Hanako quando utilizza l'aspetto personalizzato.",
	AMM_JudyBodyRevamp_Desc = "Sostituisce il corpo di Judy con uno nuovo e migliorato.",
	AMM_PanamBodyRevamp_Desc = "Sostituisce il corpo di Panam con uno nuovo e migliorato.",
	AMM_MistyBodyRevamp_Desc = "Sostituisce il corpo di Misty con uno nuovo e migliorato.\nScaricalo dalla pagina Nexus di AMM.",
	AMM_1VesHanakoFixedBodyNaked_Desc = "Sostituisce il corpo di Hanako con uno nuovo e migliorato.",
	AMM_PinkyDudeANIMFacialExpressionsFemV_Desc = "Abilita gli strumenti per le espressioni facciali su Female V",
	AMM_PinkyDudeANIMFacialExpressionsMaleV_Desc = "Abilita gli strumenti per le espressioni facciali su Male V",
	AMM_DinoTattooFixArchive_Desc = "Sostituisce mesh e texture.",
	AMM_SongbirdBodyFixArchive_Desc = "Sostituisce il corpo per correggere l'area grigia. Non ancora perfetto.",
	AMM_RitaWheelerCombatEnablerArchive_Desc = "Sostituisce il file entità per abilitare le animazioni di combattimento.",
	AMM_CheriAppearances_Desc = "Aggiunge nuove apparizioni. Scaricalo dalla pagina Nexus di AMM.",
	AMM_BryceNaked_Desc = "Aggiunge un nuovo aspetto nudo. Scaricalo dalla pagina Nexus di AMM.",
	AMM_EvelynNaked_Desc = "Corregge il suo corpo per consentire l'apparenza nuda. Scaricalo dalla pagina Nexus di AMM.",
	AMM_SaburoAppearances_Desc = "Aggiunge nuove apparizioni. Scaricalo dalla pagina Nexus di AMM.",
	AMM_TbugAppearances_Desc = "Aggiunge nuove apparizioni. Scaricalo dalla pagina Nexus di AMM.",
	AMM_8ug8eagAppearances_Desc = "Aggiunge nuove apparizioni. Scaricalo dalla pagina Nexus di AMM.",
	
	--Equipments (There is a Function Error(nil value) in this section, These are just labels that are not connected to any localizable strings in the file)
	Fists = "Pugni", --Line 2377 
	Katana = "Katana",
	Mantis_Blades = "Lame di Mantide",
	Machete = "Machete",
	Hammer = "Martello",
	Baton = "Bastone",
	Knife = "Coltello",
	Crowbar = "Piede di porco",
	Baseball_Bat = "Mazza da baseball",
	Assault_Rifle = "Fucile d'assalto",
	Sidewinder = "Sidewinder",
	Sniper_Rifle = "Fucile da cecchino",
	Shotgun = "Fucile",
	SMG = "SMG",
	Handgun = "Pistola", --Line 2391
	
	--Warning / Info / Tooltip
	Warn_CantSave_BlacklistedAppearance = "Non è possibile salvare un'apparizione nella lista nera!",
	Warn_ConfirmDeleteSavedAppearances = "Sei sicuro di voler eliminare tutte le tue apparizioni salvate?",
	Warn_ConfirmDeleteBlacklistedAppearances = "Sei sicuro di voler eliminare tutte le tue apparizioni nella lista nera?",
	Warn_ConfirmDeleteSavedDespawns = "Sei sicuro di voler eliminare tutti i tuoi scomparsi salvati?",
	Warn_ConfirmDeleteAppearanceTriggers = "Sei sicuro di voler eliminare tutti i trigger di aspetto?",
	Warn_ConfirmDeleteCurrentAppearance = "Sei sicuro di voler eliminare il preset attivo corrente?",
	Warn_WeaponizeNpcAnimationIssues = "Non tutti gli NPC avranno le animazioni necessarie per utilizzare ogni tipo di arma. Potrebbero verificarsi pose a T e animazioni errate.\nSei sicuro di volerlo abilitare?",
	Warn_ConfirmEnableExperimentalAndSave_Info = "Sei sicuro di voler abilitare le funzionalità sperimentali? AMM potrebbe non funzionare come previsto. Usalo a tuo rischio e pericolo!",
	Warn_DeleteFavoritesAskWhichOne_Info = "Se sei sicuro di voler eliminare tutti i tuoi preferiti, seleziona quale di seguito:",
	Popup_Error_Title = "Errore",
	Button_Ok = "Ok",
	Popup_FavoriteName = "Nome preferito",
	Popup_RenamePreset = "Rinomina preimpostazione",
	Popup_RenameProp = "Rinomina Prop",
	Editor_Title = "Redattore del tema",
	Editor_Field_ThemeName = "Nome del tema",
	Editor_Hint_InsertThemeName = "Inserisci il nuovo nome del tema",
	Error_ThemeNameExists = "Il nome del tema esiste già",
}
