return {

    -- >> SCAN TAB
	BeginItem_TabNameScan = "スキャン",
	
	--Button
	Button_CyclesAppearances = "サイクルの外観",
	Button_SavesAppearance = "外観の保存",
	Button_ClearSavedAppearance = "保存された外観をクリア",
	Button_UnlockDoor = "ドアロックの切り替え",
	Button_RestoreAccess = "アクセスを復元する",
	Button_UnlockVehicle = "車両のロックを解除する",
	Button_RepairVehicle = "修理車両",
	Button_OpenCloseDoors = "ドアの開閉",
	Button_OpenCloseWindows = "窓を開閉する",
	Button_ToggleEngine = "エンジンの切り替え",
	Button_ToggleAIDriver = "AIドライバーの切り替え",
	Button_ToggleCamera = "カメラの切り替え",
	Button_ToggleRadio = "ラジオの切り替え",
	Button_NextRadioStation = "次のラジオ局",
	Button_TargetMountedVehicle = "対象搭載車両",
	Button_AssignSeats = "座席の割り当て",
	Button_Assign = "割り当てる",
	Button_Reset = "リセット",
	Button_FakeDie = "フェイクダイ",
	Button_SmallCopy = "コピー",
	
    --Button Label
	Button_Label_Unfollower = "アンフォロワー",
	Button_Label_Follower = "フォロワー",
	Button_Label_SaveDespawn = "デスポーンを保存する",
	Button_Label_ClearSavedDespawn = "保存されたデスポーンをクリアする",
	Button_LabelLockTarget = "ターゲットをロックする",
	Button_LabelUnlockTarget = "ターゲットのロックを解除する",
	Label_AddToSpawnFavs = "生成可能なお気に入りに追加",
	Label_RemoveFromSpawnFavs = "生成可能なお気に入りから削除",
	
    --Checkbox
	Checkbox_SavedDespawnsActive = "保存されたデスポーンがアクティブ",
	Checkbox_KeepAssigned = "車を乗り換えるときも割り当てを維持する",
	
    --Warning / Info / Tool Tip
	WarnTextAI_FastTravel = "マップ上でファスト トラベル ポイントを選択して出発します",
	WarnText_DontReloadMods = "「すべての Mod をリロード」は使用しないでください。\n保存したゲームをリロードするか、別のエリアに移動してください。",
	Warning_NoTarget_Desc = "ターゲットがいない！開始するには、NPC、車両、またはオブジェクトを確認してください",
	ToolTip_DisableCheckboxReloadSave_AbleTotargetClearSavedDespawns = "このチェックボックスを無効にしてセーブをリロードし、Clear Saved Despawns をターゲットにできるようにします。",
	
    --Text
	Build_Mode = "ビルドモード",
	Speed = "速度:",
	Search = "検索",
	Clear = "クリア",
	Player = "プレーヤー",
	Saved = "保存されました",
	Saved_ = "保存しました_",
	Current = "現在",
	Current_ = "現在",
	Select_Seat = "座席を選択してください",
	Target_Info = "ターゲット情報",
	Target_Actions = "ターゲットアクション",
	No_Appearances = "出演なし",
	No_Target = "ターゲットがありません",
	Favorite_Appearance = "お気に入りの外観",
	Unfavorite_Appearance = "気に入らない外観",
	Blacklist_Appearance = "ブラックリストの外観",
	Unblacklist_Appearance = "ブラックリストから外された外観",
	Saved_Appearance = "保存された外観:",
	Current_Appearance = "現在の外観:",
	List_of_Appearances = "出演作品一覧",
	Appearance_Trigger = "出現トリガー",
	None = "なし",
	Default = "デフォルト",
	Zone = "ゾーン",
	Area = "エリア",
	Position = "ポジション",

	
	-- >> SPAWN TAB
	BeginItem_TabNameSpawn = "スポーン",
	
	--Button
	Button_Refresh = "リフレッシュ",
	Button_Save = "保存",
	Button_Confirm = "確認する",
	Button_Cancel = "キャンセル",
	Button_SmallSave = "保存",
	Button_SmallRespawn = "リスポーン",
	Button_SmallDespawn = "デスポーン",
	Button_SmallDespawn_WithSpace = "デスポーン",
	Button_SmallTarget = "ターゲット",
	Button_SmallEquipment = "設備",
	Button_LabelHostile = "敵対的な",
	Button_LabelFriendly = "フレンドリー",
	
    --Button Label
	Label_Favorite = "お気に入り",
	Label_Unfavorite = "気に入らない",
	
    --Checkbox
    --Warning / Info / Tool Tip
	Warn_PlayerInMenu = "プレーヤーインメニュー",
	Warn_AMMonlyfunctions_ingame = "AMMはゲーム内でのみ機能します",
	Warn_SpawnWorksInGame = "スポーンはゲーム内でのみ機能します",
	Warn_InitError = "初期化エラー",
	Warn_InitError_Info = "詳細については、AppearanceMenuMod.log を確認してください。",
	
    --Text
	Active_Spawns = "アクティブなスポーン",
	NoActiveSpawns = "アクティブなスポーンはありません",
	Select_To_Spawn = "スポーンするように選択してください",
	No_Results = "結果はありません",
	ItsEmpty = "空です:(",
	Existing_Name = "既存の名前",
	Name = "名前",
	
	
	
	-- >> SWAP TAB
	BeginItem_TabNameSwap = "スワップ",
	
	--Button
	Button_SmallRevert = "元に戻す",
	
    --Button Label
    --Checkbox
    --Warning / Info / Tool Tip
	Warn_ReloadSaveUpdateChanges = "保存したゲームをリロードして変更を更新してください。",
	Warn_NeedReloadSaveUpdateChanges = "変更を更新するには、保存をリロードする必要があります。",
	Warn_ReplacerSwap = "交換品は交換できません！写真モードでツール タブを使用してそれらをターゲットにし、スポーン タブまたはターゲット ツールから外観を切り替えます。",
	Warning = "警告",
	Warning2 = "警告:",
	SaveSwap_Tooltip = "ゲームをリロードした後もスワップを保存してください。",
	
    --Text
	CantSwapReplacer = "リプレイサーを交換できない",
	Active_Model_Swaps = "アクティブなモデルのスワップ",
	Save = "保存",
	Restore = "復元",
	Current_Target = "現在の目標:",
	Target_ID = "ターゲットID:",
	SelectSwap_CurrentTarget = "現在のターゲットと交換することを選択してください:",
	NoNPC_LookNPC = "NPCが見つかりません!まずはNPCを見てください",
	
	-- Locations Categories
	Residences = "住宅",
	ArasakaAndCorpo = "アラサカ＆コーポ",
	ClubsAndBars = "クラブ&バー",
	HotelsAndPleasure = "ホテル＆プレジャー",
	UndergroundAndCrime = "アンダーグラウンドと犯罪",
	GovernmentAndSecurity = "政府とセキュリティ",
	StoryAndUnique = "ストーリーとユニークな",
	Ripperdocs = "リッパードキュメント",
	LandmarksAndOpenWorld = "ランドマークとオープンワールド",
	SpoilersAndHidden = "ネタバレと隠し要素",
	UserLocations = "ユーザーの所在地",
	
	
	-- >> DECOR TAB
	BeginItem_TabDecor = "装飾",
	BeginItem_TabPresets = "プリセット",
	Begin_ComboPresets = "プリセット",
	
	--Button
	Button_SmallClone = "クローン",
	Button_SmallRemove = "削除##",
	Button_SmallRename = "名前を変更##",
	Button_SmallUpdate = "アップデート##",
	Button_SmallCancel = "キャンセル",
	Button_Frame = "フレーム",
	
    --Button Label
	Button_LabelHide = "隠す",
	Button_LabelUnhide = "再表示",
	
    --Checkbox
    --Warning / Info / Tool Tip
	Warn_PersistPropSave = "小道具をスポーンして、家や好きな場所を心ゆくまで飾りましょう!小道具を保存して永続化します。",
	Warn_DespawnInProgress_PleaseWait = "デスポーン中です。お待ちください。",
	Warn_PresetsFolder_Info = "ユーザープリセットはAppearanceMenuMod/User/Decorフォルダーに保存されます。",
	Warn_CustomPresets_Info = "このプリセットにはカスタム プロップが含まれています",
	Warn_CustomPropsModders_Info = "カスタム小道具の作成者:",
	Warn_GamepadDirectMode_Info = "これにより、ゲームパッドを使用するときにダイレクト モードとの統合が向上します。また、小さな情報ウィンドウを常時表示することもできます。",
	Warn_PresetTriggerDistanceFar = "Far に設定すると、パフォーマンスの問題が発生する可能性があります。",
	
    --Text
	MovingAll_PropsTo_SavedProps = "すべてのプロップを保存されたプロップに移動する",
	SelectPropSpawn = "スポーンするプロップを選択:",
	Spawned_Props = "スポーンされたプロップ",
	New_Preset = "新しいプリセット",
	No_Preset_Available = "利用可能なプリセットがありません",
	Preset_TriggerDistance = "プリセットトリガー距離",
	MovingSavedProps = "%s を保存された Props に移動しています",
	UpdateTag = "タグの更新",
	Categories = "カテゴリー",
	Decorating = "飾り付け",
	Decor_Tabs = "装飾タブ",
	Saved_Props = "保存されたプロップ",
	Show_Nearby_Only = "近隣のみを表示",
	Show_Lights_Only = "ライトのみを表示",
	Show_LockedTarget_Only = "ロックされたターゲットのみを表示",
	Show_Customizable_Only = "カスタマイズ可能なもののみを表示",
	Show_CustomProps_Only = "カスタム プロップのみを表示",
	ShowOnMap = "地図上に表示",
	Rename = "名前の変更",
	Delete = "削除",
	Backup = "バックアップ",
	Merge = "マージ",
	Save_All = "すべて保存",
	Despawn_All = "すべてデスポーン",
	Save_ToSpecific_Tag = "特定のタグに保存",
	Saved_Props2 = "保存された小道具:",
	Move_To_Tag = "タグに移動",
	HideFromMap = "地図から隠す",
	RemovingAllPropsFromTag = "タグからすべての Props を削除しています...",
	RemoveAllProps = "すべての小道具を削除する",
	RemoveHomeMarkerMap = "地図からホームマーカーを削除",
	TeleportToLocation = "場所へテレポート",
	TeleportToTrigger = "トリガーへのテレポート",
	TeleportToMark = "マークへテレポート",
	UpdateTagLocation = "タグの場所を更新する",
	SharePresetWith_ThisTagOnly = "このタグのみでプリセットを共有",
	SavedPresetFolder_Info = "プリセットをAppearanceMenuMod/User/Decorフォルダに保存しました",
	NoProps_WithThese_Conditions = "これらの条件では小道具はありません",
	AddHomeMarkerMap = "ホームマーカーをマップに追加",
	Distance = "距離",
	Total_Props = "総小道具:",
	Type_Tag_here = "ここにタグを入力してください",
	In_World = "世界で",
	Tags = "タグ",
	Tag = "タグ",
	Both = "両方",	
	
	-- >> POSES TAB
	BeginItem_TabPoses = "ポーズ",
	
	--Button
	Button_SmallCopyClipboard = "クリップボードにコピー",
	
    --Button Label
    --Checkbox
    --Warning / Info / Tool Tip
    --Text
	Active_Animations = "アクティブなアニメーション",
	ShowHistory = "履歴の表示",
	ClearHistory = "履歴をクリアする",
	SelectPoseForCurrentTarget = "現在のターゲットのポーズを選択:",
	LastUsedPoses = "最後に使用したポーズ",
	
	
	
	-- >> TOOLS TAB
	BeginItem_TabTools = "ツール",
	BeginItem_TabPhotoModeNibblesReplacer = "フォトモードニブルリプレイサー",
	BeginCombo_LookAt = "見てください",
	BeginCombo_WeatherControl = "天候制御",
	
	--Button
	Button_SkipFrame = "スキップフレーム",
	Button_ToggleLight = "ライトの切り替え",
	Button_ResetScale = "スケールをリセット",
	Button_ShowAsLookAtTarget = "ターゲットを見て表示",
	Button_ResetLookAtTarget = "ルックアットターゲットをリセット",
	Button_TogglePrimaryWeapon = "プライマリ武器を装備する",
	Button_ToggleSecondaryWeapon = "セカンダリ武器を装備する",
	Button_GiveCurrentEquippedWeapon = "現在装備している武器を与える",
	Button_SmallReset = "リセット",
	Button_ResetToPlayer = "プレーヤーにリセット",
	Button_ClearSaved = "保存済みをクリア",
	Button_Cyberpsycho = "Toggle サイバーサイコ",
	Button_ProtectNPCfromActions = "NPCをアクションから守る",
	Button_AllFriendly = "オールフレンドリー",
	Button_AllHostile = "すべて敵対的",
	Button_AllFollower = "すべてのフォロワー",
	Button_AllFakeDie = "オールフェイクダイ",
	Button_AllDie = "全員死ぬ",
	Button_AllDespawn = "すべてデスポーン",
	Button_InvMachineGun = "マシンガン",
	Button_InvSpeed2 = "速度",
	Button_ToggleMakeup = "メイクアップを切り替える",
	Button_TogglePiercings = "トグルピアス",
	Button_ToggleSeamfix = "シームフィックスの切り替え",
        Button_TargetV = "ターゲットV",
        Button_Target = "ターゲット",
        Button_TeleportToLocation = "場所へテレポート",
        Button_TeleportToTrigger = "トリガーへのテレポート",
        Button_TeleportToMark = "マークへテレポート",
        Button_RandomLocation = "ランダム",
        Button_ShareCurrentLocation = "現在地を共有する",
	Button_GoBackToLastLocation = "最後の場所に戻る",
	Button_DeleteSelectedUserLocation = "選択したユーザーの場所を削除",
	
	--Slider / Drag 
	Slider_HeadStiffness = "頭の硬さ",
	Slider_HeadPoseOverride = "頭ポーズのオーバーライド",
	Slider_ChestStiffness = "胸の硬さ",
	Slider_ChestPoseOverride = "胸ポーズオーバーライド",
	Slider_SlowMotion = "スローモーション",
	Slider_DefaultAperture = "デフォルトの絞り",
	Slider_DefaultFieldofView = "デフォルトの視野",
	Slider_MovementSpeed = "移動速度",
	Drag_MovementSpeed = "移動速度",
	
    --Button Label
	Button_Label_PauseTimeProgression = "時間の進行を一時停止する",
	Button_Label_UnpauseTimeProgression = "時間の進行の一時停止を解除する",
	Button_Label_UnfreezeTime = "解凍時間",
	Button_Label_FreezeTime = "フリーズタイム",
	Button_Label_OpenLightSettings = "ライト設定を開く",
	Button_Label_UpdateLightTarget = "ライトターゲットの更新",
	Button_Label_Activate = "アクティブ化する",
	Button_Label_Deactivate = "非アクティブ化",
	Button_Label_ChangeToCrouchStance = "しゃがみ姿勢に変更する",
	Button_Label_ChangeToStandStance = "スタンドスタンスに変更",
	Button_Label_PickUpTarget = "ピックアップターゲット",
	Button_Label_DropTarget = "ドロップターゲット",
	Button_Label_FreezeTarget = "ターゲットをフリーズする",
	Button_Label_UnfreezeTarget = "ターゲットの凍結を解除する",
	Button_Label_OpenTargetTools = "ターゲットツールを開く",
	Button_Label_CloseTargetTools = "ターゲットツールを閉じる",
	
    --Checkbox
    --Warning / Info / Tool Tip
	Warn_FileNotFound_CollabsFolder_Error = "Collabs フォルダーにファイルが見つかりません",
	Warn_ShowXYZ_Orientation_Info = "ターゲットを移動するときに方向を簡単に設定できるように、X、Y、Z 矢印を表示します。",
	Warn_LookAtCamera_OptionOff_Info = "この設定を変更した後、Look At Camera オプションを一度オフにします",
	Warn_DisableLookAtCamera_PhotoMode_Info = "有効にするには、写真モードの「カメラを見る」を一度無効にします",
	Warn_RequiresRestart_Info = "有効にするにはゲームを再起動する必要があります",
	Warn_SlowMotion_PhotoMode_Info = "フォト モードのスローモーションは、IGCS を使用して一時停止を解除した場合にのみ機能します",
	Warn_WeatherControl_RequireCodeware = "Weather Control には Codeware 1.4 以降が必要です",
	Warn_StopNpc_UnequipWeapon_Info = "これにより、NPC が指定された武器を装備解除できなくなります。注: NPC は戦闘中にも自由に装備を解除します。",
	Warn_OutOfCombat_NpcUnequip_Info = "注: 戦闘が終了すると、NPC は指定された武器をすぐに外します。",
	Warn_Photomode_UnfreezeSkipFrames_Info = "写真モードでは、Unfreeze Target はアニメーション化されたポーズのフレームをスキップします。フリーズ機能を完全に（解除）するには、Otis Camera Tools (IGCS) を使用する必要があります。",
	Warn_UserLocationsFolder_Info = "ユーザーの場所は、AppearanceMenuMod/User/Locations フォルダーに保存されます。",
	Warn_SeeMoreAction_Info = "V または NPC をターゲットにして、その他のアクションを表示します",
	Warn_SeeMoreActionProp_Info = "NPC または小道具をターゲットにして、より多くのアクションを表示します",
	Warn_SeamfixPiercingToggle_Info = "これにより、ゲームを閉じるまでメイクアップ、ピアス、シームフィックスのトグル状態が保存されます。",
	Warn_PassiveMode_Info = "戦闘を開始しても敵はあなたを攻撃します",
	Warn_TppCameraGameplay_Info = "TPP カメラは通常のゲームプレイには適していませんが、散歩には楽しいです ;)",
	Warn_AnimatedHead_PhotoMode_Info = "アニメーション ヘッドが有効になっている間は、フォト モードのエクスプレッションは機能しません。",
	Warn_ToolsOnly_WorksIngame = "ツールはゲーム内でのみ機能します",
	Warn_InvButtonMachineGun_Info = "見つけたんですね！装備品にヘビーマシンガンを追加しました。",
	Warn_InvButton_Info = "見つけたんですね！ファストモーションが利用可能になりました。",
	InvButtonTip = "ここをクリックするとどうなりますか?",
	InvButtonTip2 = "ここをクリックしても何も起こりません。",
	InvButtonTip3 = "警告が出たのでクリックしないでください。",
	
    --Text
	Facial_Expression = "表情",
	Expressions = "式",
	Look_At = "見てください",
	Look_At_Camera = "カメラ目線:",
	Target_Tools = "ターゲットツール",
	Rotation = "回転",
	Tilt_Rotation = "傾き/回転",
	Mode = "モード:",
	Precision = "精度",
	Relative = "相対的",
	Direct = "直接",
	AdvMovement = "上級動き",
	ForceGivenWeapon = "フォースギブン武器",
	Scale = "スケール",
	ProportionalMode = "比例モード",
	General_Actions = "一般的なアクション",
	DisablePassiveMode = "パッシブモードを無効にする",
	EnablePassiveMode = "パッシブモードを有効にする",
	EnableGodMode = "ゴッドモードを有効にする",
	DisableGodMode = "ゴッドモードを無効にする",
	Infinite_Oxygen = "無限の酸素",
	Select_Location = "場所の選択",
	Select_Expression = "式の選択",
	Select_Category = "カテゴリの選択",
	Teleport_Actions = "テレポートアクション",
	Use_Teleport_Animation = "テレポートアニメーションを使用する",
        Filter_Locations = "フィルターの場所",
        Locations = "所在地",
        Default_Locations = "デフォルトの場所",
        Collab_Locations = "コラボ場所",
        Button_AddTag = "タグの追加",
	Button_FilterByTags = "タグによるフィルター",
	Button_Close = "閉じる",
	Favorite_Selected_Location = "お気に入りの選択した場所",
	Unfavorite_Selected_Location = "選択した場所がお気に入りではありません",
	Edit_Selected_Location = "選択した場所を編集する",
	Locations_Favorites = "--------- お気に入り ----------",
	Locations_UserLocs = "------- ユーザーの所在地 -------",
	Locations_DefaultLocs = "----------- デフォルト ----------",
	Share_Location = "位置情報を共有する",
	Edit_Location = "場所の編集",
	TimeWeather_Actions = "時間と天気のアクション",
	TimeofDay = "時刻",
	Time_Actions = "時間アクション",
	Rain = "雨",
	Light_Rain = "小雨",
	Cloudy = "曇り",
	Fog = "霧",
	Heavy_Clouds = "重い雲",
	Light_Clouds = "軽い雲",
	Pollution = "汚染",
	Sandstorm = "砂嵐",
	Sunny = "晴れ",
	Toxic_Rain = "有毒な雨",
	Deep_Blue = "ディープブルー",
	Squat_Morning = "スクワットモーニング",
	Cloudy_Morning = "曇りの朝",
	Rainy_Night = "雨の夜",
	Courier_Clouds = "宅配便の雲",
	Cursor_LockState = "ロック状態",
	PhotoMode_NibblesReplacer = "フォトモードニブルリプレイサー",
	PhotoModeEnhancements = "フォトモードの強化",
	Button_ResetReplacerDatabase = "置換データベースをリセット",
	DisablePhotoModeCursor = "写真モードカーソルを無効にする",
	TPPCamera_Position = "TPP カメラの位置",
	AnimatedHeadin_PhotoMode = "フォトモードのアニメーションヘッド",
	LockLook_AtCamera = "ロックカメラ目線",
	UnlockLook_AtCamera = "カメラ目線のロックを解除する",
	Save_Toggles_State = "トグル状態の保存",
	Toggle_V_Head = "V ヘッドの切り替え",
	Toggle_TPP_Camera = "TPP カメラの切り替え",
	Target_Nibbles = "ターゲットニブル",
	Target_Replacer = "ターゲットリプレイサー",
	Left = "左",
	Left_Close = "左閉じ",
	Right = "右",
	Right_Close = "右クローズ",
	Center_Close = "センタークローズ",
	Center_Far = "センターファー",
	Front_Close = "フロントクローズ",
	Front_Far = "フロントファー",
	All = "すべて",
	Head_Only = "頭のみ",
	Eyes_Only = "目だけ",
	Movement = "動き",
	V_Actions = "V アクション",
	Invisible_V = "インビジブルV",
	LikeGTA_byGTATravel = "GTAトラベルによって",
	EnableSpawnedProps = "スポーンされたプロップを有効にする",
	LightControl = "ライトコントロール",
	Equipment = "設備",
	
	-- >> DIRECTOR TAB
	BeginItem_TabNameDirector = "ディレクター",
	BeginItem_TabNameTriggers = "トリガー",
	BeginCombo_StartAppearance = "開始外観",
	BeginCombo_EndAppearance = "エンドアピアランス",
	BeginCombo_Type = "タイプ",
	BeginCombo_GoToTarget = "ターゲットに移動",
	BeginCombo_PlayVoice = "音声を再生する",
	BeginCombo_Attack = "攻撃",
	BeginCombo_Triggers = "トリガー",
	BeginCombo_Scripts = "スクリプト",
	
	--Button
	Button_Yes = "はい",
	Button_No = "いいえ",
	Button_SaveChangesOnly = "変更のみを保存",
	Button_RemoveMark = "マークを削除",
	Button_EditMark = "編集マーク",
        Button_MoveMark = "マークを移動",
        Button_MoveUp = "上に移動",
        Button_MoveDown = "下に移動",
        Button_NewMark = "新しいマーク",
	Button_AddActor = "アクターの追加",
	Button_RemoveActor = "アクターの削除",
	Button_ChangeActor = "アクターの変更",
	Button_RadioOnlyOne = "オンリーワン",
	Button_RadioRandom = "ランダム",
	Button_RadioSequential = "シーケンシャル",
	Button_SaveTrigger = "保存トリガー",
	Button_NewCamera = "新しいカメラ",
	Button_NewScript = "新しいスクリプト",
	Button_DragSpeed = "速度",
	Button_ToggleMarker = "マーカーの切り替え",
	Button_TestPose = "テストポーズ",
	Button_StopPose = "ストップポーズ",
	
    --Button Label
	Button_Label_PlayScript = "スクリプトを再生する",
	Button_Label_StopScript = "スクリプトの停止",
	Button_Label_Stopping = "停止中...",
	Button_Label_Restarting = "再起動中...",
	Button_Label_AddMark = "マークを追加",
	Button_Label_SaveWNewPos = "新しい位置で保存",
	
    --Checkbox
    --Warning / Info / Tool Tip
	Warn_ActorSingleMark_Info = "俳優は単一のマークにとどまる",
	Warn_ActorRandomMark_Info = "アクターはマーク間をランダムに移動します",
	Warn_ActorSequentialMark_Info = "アクターは番号順にマーク間を移動します",
	Warn_DeleteScript_Info = "このスクリプトを削除してもよろしいですか?",
	Warn_CloseCamForMove_Info = "メニューを閉じるとカメラを移動できるようになります",
	Warn_CreateScriptsDesc_Info = "マシニマ、スクリーンショット、ロールプレイで実行するアクターを追加、服装、指示するためのスクリプトを作成します。",
	Warn_PremadeScriptsDesc_Info = "コンタクト時に事前に作成されたスクリプトをアクティブにするトリガーを作成します。",
	Warn_CreateCamera_FovZoomDesc_Info = "カメラを作成して自由に動き回ったり、さまざまな視野やズーム レベルを設定したりできます。",
	Warn_ShowMarksLocations_Info = "マークの位置に可視アイコンを表示します",
	Warn_AutoTalkNpc_Info = "これにより、NPC は範囲内にいる場合、1 分ごとに話すようになります (音声付き NPC のみ)",
	Warn_DirectActorPlayerPosition_Info = "現在のプレーヤーの位置にマークを作成してアクターを移動および指示します",
	Warn_InMenuDirectorDesc = "ディレクターはゲーム内でのみ機能します",
	
    --Text
	DirectorMode = "ディレクターモード",
	SelectActorToReplace = "置換するアクタを選択:",
	AddActorToCurrentScript = "現在のスクリプトにアクターを追加:",
	FacialExpression_WithColon = "表情:",
	FavoritePoses_WithColon = "好きなポーズ:",
	AddFavorites_Desc = "まずポーズタブのお気に入りにポーズを追加します",
	HoldDuration = "ホールド持続時間",
	Movement2 = "動き:",
	Actions = "アクション:",
	Actors = "俳優",
	Editing = "編集",
	AutoTalk = "オートトーク",
	ActorMarks = "俳優マークス",
	Current_Actors = "現在の俳優",
	Marks_Sequence = "マークシーケンス:",	
	ShowMarks = "マークを表示",
	Triggers = "トリガー",
	NewTrigger = "新しいトリガー",
	ShowTrigger = "トリガーを表示",
	Title = "タイトル",
	Select_Trigger = "トリガーの選択",
	Select_Script = "スクリプトの選択",
	Delete_Trigger = "トリガーの削除",
	Triggers_On_Off = "トリガーのオン/オフ",
	Running = "ランニング",
	Script_Running = "スクリプトを実行中...",
	Delete_Script = "スクリプトの削除",
	RepeatInLoop = "ループ内で繰り返す",
	ActivationRadius = "アクティベーション半径",
	Activate = "アクティブ化する",
	Deactivate = "非アクティブ化",
	FOV = "視野",
	Zoom = "ズーム",
	LockFrame = "ロックフレーム",
	Walk = "歩く",
	Sprint = "スプリント",
	Sequential = "シーケンシャル",
	Cameras = "カメラ",
	NodeView = "ノードビュー",
	TeamA = "チームA",
	TeamB = "チームB",
	
	
	
	-- >> SETTINGS TAB
	BeginItem_TabNameSettings = "設定",
	BeginItem_TabNameGeneral = "一般",
	BeginItem_TabNameCompanions = "仲間たち",
	BeginItem_TabNameUI = "ユーザーインターフェース",
	BeginItem_TabNameExperimental = "実験的",
	BeginItem_TabNamePhotoMode = "フォトモード",
	
	--Button
	Button_RevertAllModelSwaps = "すべてのモデルのスワップを元に戻す",
	Button_RespawnAll = "すべてリスポーン",
	Button_ForceDespawnAll = "すべて強制デスポーン",
	Button_ClearFavorites = "お気に入りをクリア",
	Button_ClearAllSavedAppearances = "保存されている外観をすべてクリア",
	Button_ClearAllBlacklistedAppearances = "ブラックリストに登録されたすべての出演をクリアする",
	Button_ClearAllAppearanceTriggers = "すべての出現トリガーをクリア",
	Button_ClearAllSavedDespawns = "保存されたデスポーンをすべてクリア",
	Button_SmallCreateTheme = "テーマの作成",
	Button_SmallDeleteTheme = "テーマの削除",
	Button_SmallSet = "セット",
	Button_ReloadAppearances = "カスタム外観を再ロードする",
	
    --Button Label
    --Checkbox
	Checkbox_SpawnAsCompanion = "コンパニオンとしてスポーンする",
	Checkbox_SpawnAsFriendly = "フレンドリーとしてスポーン",
	Checkbox_InvulnerableCompanion = "無敵の仲間",
	Checkbox_RespawnOnLaunch = "起動時にリスポーン",
	Checkbox_LockTargetAfterSpawn = "スポーン後にターゲットをロックする",
	Checkbox_OpenTargetToolsAfterSpawn = "スポーン後にターゲット ツールを開く",
	Checkbox_DisplayAxisIndicatorByDefault = "デフォルトで軸インジケーターを表示",
	Checkbox_PhotoModeEnhancements = "フォトモードの強化",
	Checkbox_GodModeOnLaunch = "起動時のゴッドモード",
	Checkbox_PassiveModeOnLaunch = "起動時のパッシブモード",
	Checkbox_StreamerMode = "ストリーマーモード",
	Checkbox_OpenWCETOverlay = "CET オーバーレイを使用して開く",
	Checkbox_AutoResizingWindow = "自動サイズ変更ウィンドウ",
	Checkbox_ScanningReticle = "スキャンレチクル",
	Checkbox_FloatingTargetTools = "フローティング ターゲット ツール",
	Checkbox_TabHeaderDescriptions = "タブヘッダーの説明",
	Checkbox_ExpandFavoritesByDefault = "デフォルトでお気に入りを展開",
	Checkbox_EnableScrollBars = "スクロールバーを有効にする",
	Checkbox_AlwaysDisablePhotoModeCursor = "写真モードカーソルを常に無効にする",
	Checkbox_Camera = "カメラ",
	Checkbox_DepthOfField = "自由度",
	Checkbox_Effect = "効果",
	Checkbox_Stickers = "ステッカー",
	Checkbox_LoadSave = "ロード/セーブ",
	Checkbox_ExperimentalFunstuff = "実験的/楽しいもの",
	Checkbox_EnableFreezeTargetInPhotoMode = "写真モードでフリーズターゲットを有効にする",
	Checkbox_WeaponizeCompanions = "コンパニオンを武器化する",
	Checkbox_AllowPlayerToBeTargetedinPosestab = "「ポーズ」タブでプレイヤーをターゲットにできるようにする",
	Checkbox_AllowPlayerAnimationsonNPCs = "NPC でのプレイヤー アニメーションを許可する",
	Checkbox_AllowExpressionOnNpcPM = "フォトモードでNPCの表情と視線を許可",
        Checkbox_ResetTargetPositionPM = "フォトモードNPCのターゲット位置をリセット",
        Checkbox_EnableRandomLocation = "[ランダム] ボタンを有効にする: プレイヤーをリストからランダムな場所にテレポートします。",
        Checkbox_RestoreOnLaunch = "起動時に復元",
        Radio_PrimarySlot = "プライマリスロット",
        Radio_SecondarySlot = "セカンダリスロット",
	
    --Warning / Info / Tool Tip
	Warn_RespawnOnLaunch_Info = "この設定は、ゲームのロード時に以前に保存された NPC の再出現を有効または無効にします。ゲームを終了すると、AMM はスポーンした NPC を自動的に保存します。",
	Warn_BannedWords_Info = "この設定は、裸、ヌード、xxx、シャワー、誕生日スーツ、pp、ペニスという単語を含む NPC の外観を有効または無効にします。",
	Warn_TargetNpcVehicleHotkey = "ホットキーを設定する対象の NPC または車両",
	Warn_FirstLaunchDecideTabsExpand_Info = "この設定により、AMM の初回起動時にデフォルトで [スポーン]、[スワップ]、[装飾] タブの [お気に入り] が展開されます。",
	Warn_ExperimentalTabDesc_Info = "実験的な機能はさらに多くの機能を追加しますが、うまく機能しない可能性があるため、実験的なラベルが付けられています。実際、ほとんどの AMM ユーザーは実験的機能を有効にしています。だからあまり心配しないで楽しんでください！",
	Warn_FreezeTargetPhotoMode_Info = "この設定は、フォト モードのポーズにカスタム アニメーションを追加する MOD からのアニメーション、または IGCS を使用して一時停止を解除するときにアニメーションをフリーズするのに役立つことを目的としています。",
	Warn_WeaponizeCompanions_Info = "これにより、すべての NPC に武器と戦闘能力が与えられます。 T ポーズや奇妙なアニメーションが期待されます。",
	Warn_PlayerAnimsOnNpc_Info = "NPC でプレイヤー アニメーションを使用できるようにする MOD を使用している場合は、これを有効にします。",
	Warn_UnpauseRequiresIGSC = "この設定では、IGCS が一時停止時間を解除する必要があります。",
	Warn_NotInstalled = "インストールされていません",
	Warn_DespawnAllProps = "すべてのプロップをデスポーンしてもよろしいですか?",
	
    --Text
	AMM_Version = "AMM バージョン:",
	CET_Version = "CET バージョン:",
	Codeware_Version = "コードウェアのバージョン:",
	Game_Version = "ゲームバージョン:",
	Companion_Damage = "仲間のダメージ:",
	Companion_Resistance = "仲間の耐性:",
	Companion_Distance = "コンパニオンの距離:",
	xDamage = "×ダメージ",
	xResistance = "×抵抗",
	SavedAppearancesHotkeys = "保存された外観のホットキー",
	Favorites = "お気に入り",
	Appearances = "出演",
	Blacklist = "ブラックリスト",
	AppearanceTriggers = "出現トリガー",
	SavedDespawns = "保存されたデスポーン",
	Interface_Language = "インターフェース言語:",
	Custom_Appearances = "カスタム外観",
	PhotoModeAdjustments = "写真モードの調整:",
	DisablePhotoModeTabs = "写真モードのタブを無効にする:",
	List_Height = "リストの高さ",
	Listbox_Themes = "テーマ",
	Weaponize = "武器化",
	NoAppearanceSet = "外観が設定されていません",
	
	
	
	-- >> EXTRA	
	--Texts, warns, tips, info's, buttons and labels etc.
	Seat_FrontRight = "フロント右",
	Seat_BackRight = "右奥",
	Seat_FrontLeft = "フロント左",
	Seat_BackLeft = "左奥",
	Label_Door = "ドア",
	Label_Window = "窓",

	Close = "閉じる",
	Far = "遠い",
	Moderate = "中等度",
	
	-- >> Archives Screen
	Warning_MissingRequiredArchives = "AMM に 1 つ以上の必要なアーカイブがありません。不足している必要なアーカイブを archive/pc/mod フォルダーにインストールしてください。",
	Warning_MissingOptionalArchives = "AMM に 1 つ以上のアーカイブがありません。これらはオプションですが、AMM に機能を追加します。これらの警告は無視しても構いませんが、AMM が正しく動作しない可能性があります。",
	
	
	-->> INIT.LUA
	AMMNeedsAttention = "AMMには注意が必要です",
	MISSING_ARCHIVES = "アーカイブが見つからない",
	VERSION_INFORMATION = "バージョン情報",
	CREDITS = "クレジット",
	UPDATE_HISTORY = "更新履歴",
	Updates = "アップデート",
	MISSING = "行方不明",
	REQUIRED = "必須",
	OPTIONAL = "オプション",
	WHATS_NEW = "最新情報", --Line 83 Function Error

	--Button
	Button_Ignorewarningsforthisversion = "このバージョンの警告を無視する",
	Button_Credits = "クレジット",
	Button_Cool = "かっこいい！",

	--Button Label
	Label_SpawnFavorites = "スポーンのお気に入り",
	Label_SwapFavorites = "お気に入りを交換する",
	Label_FavoriteAppearances = "お気に入りの出演作品",
	Label_Cancel = "キャンセル",

	--Text
	Hotkey_i = "ホットキー %i",

	--Node - Function Error(nil value) 
	Top = "トップへ", --Line 116
	Bottom = "下",
	Off = "オフ",
	
	--Voice Overs
	Label_GreetV = "グリーティングV",
	Label_FearFoll = "フィアーフォール",
	Label_FearToll = "恐怖の通行料",
	Label_FearBeg = "フィア・ベグ",
	Label_FearRun = "フィアーラン",
	Label_StealthSearch = "ステルス検索",
	Label_StealthDeath = "ステルスデス",
	Label_StealthRestore = "ステルス復元",
	Label_StealthEnd = "ステルスエンド",
	Label_CuriousGrunt = "好奇心旺盛なうなり声",
	Label_GrappleGrunt = "グラップルグラント",
	Label_Bump = "バンプ",
	Label_VehicleBump = "車両のバンプ",
	Label_TurretWarning = "タレット警告",
	Label_OctantWarning = "オクタント警告",
	Label_DroneWarning = "ドローン警報",
	Label_MechWarning = "メカ警告",
	Label_EliteWarning = "エリートの警告",
	Label_CameraWarning = "カメラ警告",
	Label_EnemyWarning = "敵の警告",
	Label_HeavyWarning = "厳重な警告",
	Label_SniperWarning = "狙撃兵の警告",
	Label_AnyDamage = "あらゆる損害",
	Label_Danger = "危険",
	Label_CombatStart = "戦闘開始",
	Label_CombatEnd = "戦闘終了",
	Label_CombatTargetHit = "戦闘目標の命中",
	Label_PedestrianHit = "歩行者衝突",
	Label_LightHit = "ライトヒット",
	Label_Curse = "呪い",
	Label_Irritated = "イライラした",
	Label_GrenadeThrow = "手榴弾の投擲",
	Label_Gotakill = "キルを獲得しました！",
	
	--Expressions
	Neutral = "ニュートラル",
	Joy = "ジョイ",
	Smile = "笑顔",
	Sad = "悲しい",
	Surprise = "サプライズ",
	Aggressive = "アグレッシブ",
	Anger = "怒り",
	Interested = "興味がある",
	Disinterested = "無関心",
	Disappointed = "がっかりした",
	Disgust = "嫌悪感",
	Exertion = "努力",
	Nervous = "緊張している",
	Fear = "恐怖",
	Terrified = "怖い",
	Pain = "痛み",
	Sleepy = "眠い",
	Unconscious = "無意識",
	Dead = "死んだ",

	-- Extra Expressions
	Frown = "しかめっ面",
	Shocked = "ショックを受けた",
	Annoyed_2 = "イライラ 2",
	Contempt = "軽蔑",
	Irritated = "イライラした",
	Sceptical_1 = "懐疑的 1",
	Sceptical_2 = "懐疑的2",
	Annoyed_1 = "イライラ 1",
	Offended = "気分を害した",
	Disgusted = "うんざりした",
	Disappointed_2 = "がっかりしました 2",
	Alert = "アラート",
	Crying = "泣いている",
	Embarrassed = "恥ずかしい",
	Humiliated = "屈辱的な",
	Impatient = "せっかち",
	Anguished = "苦悩する",
	Worried = "心配",
	Guilty = "有罪",
	Grieving = "悲しみ",
	RestrainedAnger = "抑制された怒り",
	Afraid = "怖い",
	LookingUpAnnoyed = "イライラして見上げる",
	Offended_2 = "気分を害した2",
	Resentful = "憤慨している",
	SadExtra = "悲しいおまけ",
	NervousBreath = "緊張した息",
	ScreamingLong = "スクリーミング・ロング",
	ScreamingShort = "スクリーミングショート",
	ScaredBreath = "怖い息",
	CryingPainful = "痛くて泣く",
	SelfReflectAnger = "怒りを反省する",
	IndulgentSmile = "贅沢な笑顔",
	Impressed = "感動した",
	LongSmile = "長い笑顔",
	ShortSmile = "短い笑顔",
	SimpleSmile = "シンプルスマイル",
	Confident = "自信を持って",
	Relief = "レリーフ",
	Impressed_2 = "感動2",
	Admiring = "感心する",
	Fascinated = "魅了された",
	RaisedBrows = "上げられた眉",
	LookingUpThinking = "見上げて考える",
	LeftGlanceProcessing = "左目処理",
	LeftGlanceCloseUp = "左目クローズアップ",
	LookingAround = "周りを見回す",
	LookingDownThinking = "見下ろして考える",
	LookingAroundAlt = "周りを見回す Alt",
	EyesDartFromLeft = "目は左から飛び出す",
	EyesDartFromRight = "目は右から飛び出す",
	EyesDartToRight = "目は右に飛びます",
	LookingLeft = "左を向いて",
	LookingUpThinking_2 = "見上げて考える 2",
	RightGlanceProcessing = "右目処理",
	LookingDown = "見下ろす",
	Left90GlanceClose = "左90ちらりと見る",
	LookingUp = "見上げる",
	Right90GlanceClose = "右90ちらりと見る",
	LookingLeftUp = "左上を見る",
	LookingRightUp = "真上を向いて",
	ReadingDown = "下から読む",
	ReadingUp = "読む",
	ReadingMiddle = "読書中",
	FrontCloseGlance = "正面から見る",
	WinkLeft = "左にウインク",
	EyeRoll = "アイロール",
	Squint = "斜視",
	FalseSmile_2 = "偽りの笑顔2",
	FalseSmile_1 = "偽りの笑顔1",
	ListeningNewInfo = "新しい情報を聞く",
	WhatDoYouWant = "何が欲しいですか",
	Maybe = "たぶん",
	SearchingForWords = "言葉を探す",
	What = "何",
	Where = "どこで",
	SureSure = "確かに確かに",
	ListenToMe = "聞いてください",
	StopThePolice = "警察を止めろ",
	HurryUp = "急いで",
	ShutUp = "黙ってろ",
	WinkRight = "右にウインク",
	MockingSmile = "嘲笑の笑み",
	AsymmetricalSmile = "非対称の笑顔",
	SarcasticSmile = "皮肉な笑顔",
	Sex = "セックス",
	LipBite_1 = "リップバイト 1",
	LipBite_2 = "リップバイト 2",
	Moan = "うめき声",
	LipBite_3 = "リップバイト 3",
	Pout = "ふくれっ面",
	SexySmile = "セクシーな笑顔",
	Swallow = "ツバメ",
	SensualSmile = "官能的な笑顔",
	SexScene_1 = "セックスシーン1",
	SexScene_2 = "セックスシーン2",
	Kiss = "キス",
	UsingInhaler = "吸入器の使用",
	ShortYawn = "短いあくび",
	Yawn = "あくび",
	Coughing = "咳",
	Bite = "噛む",	
	EatingFast = "早食い",
	ShortDrink = "ショートドリンク",
	Drinking = "飲酒",
	FastBite = "ファストバイト",
	LongDrink = "ロングドリンク",
	ShortSmoking = "短時間の喫煙",
	LongSmoking = "長時間の喫煙",
	Smoking = "喫煙",
	Eating_1 = "食べる1",
	Eating_2 = "食べる2",
	Eating_3 = "食べる3",
	Eating_4 = "食べる4",
	Vomit = "嘔吐物",
	BeingRevived = "復活する",
	MalwarePositive = "マルウェア陽性",
	MalwareNegative = "マルウェアネガティブ",
	MalwareInfected = "マルウェアに感染しました",
	FaceMorphActivate = "フェイスモーフアクティブ化",
	LieNetChairSleep = "嘘ネットチェアスリープ",
	LieNetChairBreathe = "嘘ネットチェア ブリーズ",
	NetrunnerDeathUnplugged = "ネットランナー デス アンプラグド",
	VeryItchyNose = "非常に鼻がかゆい",
	RollerCoasterNervous = "ジェットコースター緊張",
	Pfft = "ふふん",
	Hahaha = "ははは",
	Sniff = "匂いを嗅ぐ",
	Ahaaa = "ああああ",
	Heh = "へー",
	Huh = "ふーん",
	Haaa = "はぁ",
	Sigh_Lipsync = "ため息リップシンク",
	Hmm = "うーん",
	Whispering_1 = "ささやき1",
	Whispering_2 = "ささやき2",
	ApprovalYes = "承認はい",
	SubtleYes = "微妙にはい",
	QuickNoShake = "クイックノーシェイク",
	FirmYes = "しっかりはい",
	LongNo = "ロングノー",
	SubtleNo = "微妙なノー",
	NoContempt = "軽蔑の禁止",
	NoDisapproval = "反対しない",
	FirmNo = "会社番号",
	NoEnthusiastic = "熱心ではない",
	MockingYes = "嘲笑はい",
	EnthusiasticYes = "熱心なはい",
	AsymmetricalCornerUp = "非対称コーナーアップ",
	CornersUp = "コーナーアップ",
	SoftSigh = "柔らかなため息",
	BreathGasp = "あえぎ息",
	AssymetricalSneer = "非対称的な冷笑",
	CrimpingLips = "クリンピングリップ",
	BrowsDown = "ブラウズダウン",
	BrowsLeftUp = "眉を上げたまま",
	BrowsRightUp = "眉を真上に向ける",
	BrowsUp = "ブウズアップ",
	ClosedEyes_1 = "目を閉じて 1",
	ClosedEyes_2 = "目を閉じて 2",
	EyesClosed = "目を閉じた",
	LookRight = "右を向いて",
	FastBlink = "速い点滅",
	SlowBlink = "ゆっくり点滅",
	NormalBlink = "通常の点滅",
	TinyBlink = "小さなまばたき",
	HalfBlink = "半点滅",
	RegularSaccade = "定期的なサッカード",
	FrequentSaccade = "頻繁なサッカード",
	PhotoCloseupEyes = "写真クローズアップ目",
	PhotoCloseupLips = "唇のクローズアップ写真",
	PhotoCloseupHair = "写真クローズアップ髪",
	PhotoCloseupChin = "写真のクローズアップ あご",
	PhotoCloseupNose = "クローズアップ写真 鼻",
	PhotoCloseup = "写真のクローズアップ",
	PhotoCloseupPleased = "写真のクローズアップ",
	PhotoCloseupBody = "写真クローズアップボディ",
	PhotoCloseupTeeth = "歯のクローズアップ写真",
	PhotoCloseupIN = "インドのクローズアップ写真",
	PhotoCloseupOUT = "写真クローズアップアウト",
	Bored = "退屈",
	Charming = "魅力的",
	Furious = "激怒",
	Happy = "ハッピー",
	Pissed = "腹が立った",
	Pleased = "満足",
	Scared = "怖い",
	Surprised = "驚いた",
	Sadness = "悲しみ",
	Whistling = "口笛を吹く",
	Singing_1 = "歌う1",
	Singing_2 = "歌うこと2",
	Singing_3 = "歌うこと3",
	Alerted = "警戒済み",
	Hit_1 = "ヒット1",
	Hit_2 = "ヒット2",
	Wounded = "負傷者",
	Death = "死",

	-- Expressions Category
	Negative = "ネガティブ",
	Positive = "ポジティブ",
	Contemplative = "瞑想的な",
	Social = "ソーシャル",
	Sexual = "性的",
	Action = "アクション",
	Vocal = "ボーカル",
	Yes_N_No = "はい&いいえ",
	Nuance = "ニュアンス",
	Static = "静的",
	Combat = "戦闘",
	
	--Props
	AMM_Props_Desc = "小道具、キャラクター、乗り物を追加します。これがないと AMM は起動しません。",
	AMM_JohnnyCompanion_Desc = "Johnny Silverhand をスポーン可能なキャラクターとして追加します。",
	AMM_ScenesPack_Desc = "9358 シーンのアニメーションをポーズ システムに追加します。\nAMM の Nexus ページからダウンロードしてください。",
	AMM_SoundPack_Desc = "生成可能なサウンドエフェクトを追加します。",
	AMM_KerryPP_Desc = "新しい裸の外観を追加します。",
	AMM_BenjaminStonePP_Desc = "新しい裸の外観を追加します。",
	AMM_RiverPP_Desc = "新しい裸の外観を追加します。",
	AMM_YorinobuPP_Desc = "新しい裸の外観を追加します。",
	AMM_LizzyIncognito_Desc = "新しい外観を追加します。",
	AMM_MeredithXtra_Desc = "新しい外観を追加します。",
	AMM_DelamainFix_Desc = "デラメインにフルボディを追加。",
	AMM_HanakoNoMakeup_Desc = "カスタム外観を使用するときに、AMM が花子のメイクを除去できるようにします。",
	AMM_JudyBodyRevamp_Desc = "ジュディの体を改良された新しいものと交換します。",
	AMM_PanamBodyRevamp_Desc = "パナムのボディを改良型の新型ボディに交換。",
	AMM_MistyBodyRevamp_Desc = "ミスティのボディを改良型の新型ボディに交換。\nAMM の Nexus ページからダウンロードしてください。",
	AMM_1VesHanakoFixedBodyNaked_Desc = "花子の体を改良された新型のものと交換する。",
	AMM_PinkyDudeANIMFacialExpressionsFemV_Desc = "Female V で表情ツールを有効にします",
	AMM_PinkyDudeANIMFacialExpressionsMaleV_Desc = "男性 V で表情ツールを有効にします",
	AMM_DinoTattooFixArchive_Desc = "メッシュとテクスチャを置き換えます。",
	AMM_SongbirdBodyFixArchive_Desc = "灰色部分を修正するためにボディを交換します。まだ完璧ではありません。",
	AMM_RitaWheelerCombatEnablerArchive_Desc = "戦闘アニメーションを有効にするためにエンティティ ファイルを置き換えます。",
	AMM_CheriAppearances_Desc = "新しい外観を追加します。 AMM の Nexus ページからダウンロードしてください。",
	AMM_BryceNaked_Desc = "新しい裸の外観を追加します。 AMM の Nexus ページからダウンロードしてください。",
	AMM_EvelynNaked_Desc = "裸に見えるように体を固定する。 AMM の Nexus ページからダウンロードしてください。",
	AMM_SaburoAppearances_Desc = "新しい外観を追加します。 AMM の Nexus ページからダウンロードしてください。",
	AMM_TbugAppearances_Desc = "新しい外観を追加します。 AMM の Nexus ページからダウンロードしてください。",
	AMM_8ug8eagAppearances_Desc = "新しい外観を追加します。 AMM の Nexus ページからダウンロードしてください。",
	
	--Equipments (There is a Function Error(nil value) in this section, These are just labels that are not connected to any localizable strings in the file)
	Fists = "拳", --Line 2377 
	Katana = "カタナ",
	Mantis_Blades = "マンティスブレード",
	Machete = "マチェーテ",
	Hammer = "ハンマー",
	Baton = "バトン",
	Knife = "ナイフ",
	Crowbar = "バール",
	Baseball_Bat = "野球バット",
	Assault_Rifle = "アサルトライフル",
	Sidewinder = "サイドワインダー",
	Sniper_Rifle = "スナイパーライフル",
	Shotgun = "ショットガン",
	SMG = "SMG",
	Handgun = "ハンドガン", --Line 2391
	
	--Warning / Info / Tooltip
	Warn_CantSave_BlacklistedAppearance = "ブラックリストに登録された外観は保存できません。",
	Warn_ConfirmDeleteSavedAppearances = "保存した外観をすべて削除してもよろしいですか?",
	Warn_ConfirmDeleteBlacklistedAppearances = "ブラックリストに登録されている出演作をすべて削除してもよろしいですか?",
	Warn_ConfirmDeleteSavedDespawns = "保存したデスポーンをすべて削除してもよろしいですか?",
	Warn_ConfirmDeleteAppearanceTriggers = "すべての出現トリガーを削除してもよろしいですか?",
	Warn_ConfirmDeleteCurrentAppearance = "現在アクティブなプリセットを削除してもよろしいですか?",
	Warn_WeaponizeNpcAnimationIssues = "すべての NPC が、あらゆる種類の武器を使用するために必要なアニメーションを備えているわけではありません。 T ポーズや間違ったアニメーションが発生する可能性があります。\n有効にしてもよろしいですか?",
	Warn_ConfirmEnableExperimentalAndSave_Info = "実験的な機能を有効にしてもよろしいですか? AMM が期待どおりに機能しない可能性があります。ご自身の責任でご使用ください。",
	Warn_DeleteFavoritesAskWhichOne_Info = "お気に入りをすべて削除してもよい場合は、以下からどれかを選択してください:",
	Popup_Error_Title = "エラー",
	Button_Ok = "わかりました",
	Popup_FavoriteName = "好きな名前",
	Popup_RenamePreset = "プリセット名の変更",
	Popup_RenameProp = "プロップの名前を変更",
	Editor_Title = "テーマエディター",
	Editor_Field_ThemeName = "テーマ名",
	Editor_Hint_InsertThemeName = "新しいテーマ名を挿入",
	Error_ThemeNameExists = "テーマ名はすでに存在します",
}
