return {

    -- >> SCAN TAB
	BeginItem_TabNameScan = "스캔",
	
	--Button
	Button_CyclesAppearances = "사이클 외관",
	Button_SavesAppearance = "모양 저장",
	Button_ClearSavedAppearance = "저장된 모양 지우기",
	Button_UnlockDoor = "토글 도어 잠금 장치",
	Button_RestoreAccess = "액세스 복원",
	Button_UnlockVehicle = "차량 잠금 해제",
	Button_RepairVehicle = "수리 차량",
	Button_OpenCloseDoors = "문 열기/닫기",
	Button_OpenCloseWindows = "창 열기/닫기",
	Button_ToggleEngine = "토글 엔진",
	Button_ToggleAIDriver = "AI 드라이버 전환",
	Button_ToggleCamera = "카메라 전환",
	Button_ToggleRadio = "라디오 전환",
	Button_NextRadioStation = "다음 라디오 방송국",
	Button_TargetMountedVehicle = "타겟 탑재 차량",
	Button_AssignSeats = "좌석 배정",
	Button_Assign = "할당",
	Button_Reset = "재설정",
	Button_FakeDie = "페이크 다이",
	Button_SmallCopy = "복사",
	
    --Button Label
	Button_Label_Unfollower = "팔로우 해제",
	Button_Label_Follower = "추종자",
	Button_Label_SaveDespawn = "디스폰 저장",
	Button_Label_ClearSavedDespawn = "저장된 디스폰 지우기",
	Button_LabelLockTarget = "대상 잠금",
	Button_LabelUnlockTarget = "목표 잠금 해제",
	Label_AddToSpawnFavs = "생성 가능한 즐겨찾기에 추가",
	Label_RemoveFromSpawnFavs = "생성 가능한 즐겨찾기에서 제거",
	
    --Checkbox
	Checkbox_SavedDespawnsActive = "저장된 디스폰 활성화",
	Checkbox_KeepAssigned = "차량 변경 시 할당 상태 유지",
	
    --Warning / Info / Tool Tip
	WarnTextAI_FastTravel = "지도에서 빠른 이동 지점을 선택하여 이동하세요.",
	WarnText_DontReloadMods = "모든 모드 다시 로드를 사용하지 마세요.\n저장 게임을 다시 로드하거나 다른 지역으로 이동하세요.",
	Warning_NoTarget_Desc = "대상 없음! 시작하려면 NPC, 차량 또는 물체를 살펴보세요.",
	ToolTip_DisableCheckboxReloadSave_AbleTotargetClearSavedDespawns = "저장된 디스폰 삭제를 목표로 삼으려면 이 확인란을 비활성화하고 저장 내용을 다시 로드하세요.",
	
    --Text
	Build_Mode = "건축 모드",
	Speed = "속도:",
	Search = "검색",
	Clear = "지우기",
	Player = "플레이어",
	Saved = "저장됨",
	Saved_ = "저장됨_",
	Current = "현재",
	Current_ = "현재",
	Select_Seat = "좌석 선택",
	Target_Info = "대상 정보",
	Target_Actions = "타겟 액션",
	No_Appearances = "출연 없음",
	No_Target = "대상 없음",
	Favorite_Appearance = "좋아하는 외모",
	Unfavorite_Appearance = "마음에 들지 않는 외모",
	Blacklist_Appearance = "블랙리스트 등장",
	Unblacklist_Appearance = "블랙리스트 해제 모양",
	Saved_Appearance = "저장된 모습:",
	Current_Appearance = "현재 모습:",
	List_of_Appearances = "출연 목록",
	Appearance_Trigger = "출현 트리거",
	None = "없음",
	Default = "기본값",
	Zone = "구역",
	Area = "면적",
	Position = "위치",

	
	-- >> SPAWN TAB
	BeginItem_TabNameSpawn = "스폰",
	
	--Button
	Button_Refresh = "새로고침",
	Button_Save = "저장",
	Button_Confirm = "확인",
	Button_Cancel = "취소",
	Button_SmallSave = "저장",
	Button_SmallRespawn = "부활",
	Button_SmallDespawn = "디스폰",
	Button_SmallDespawn_WithSpace = "디스폰",
	Button_SmallTarget = "대상",
	Button_SmallEquipment = "장비",
	Button_LabelHostile = "적대적",
	Button_LabelFriendly = "우호적",
	
    --Button Label
	Label_Favorite = "즐겨찾기",
	Label_Unfavorite = "즐겨찾기 안함",
	
    --Checkbox
    --Warning / Info / Tool Tip
	Warn_PlayerInMenu = "플레이어 인 메뉴",
	Warn_AMMonlyfunctions_ingame = "AMM은 게임에서만 작동합니다.",
	Warn_SpawnWorksInGame = "스폰은 게임에서만 작동합니다.",
	Warn_InitError = "초기화 오류",
	Warn_InitError_Info = "자세한 내용은 AppearanceMenuMod.log를 확인하세요.",
	
    --Text
	Active_Spawns = "활성 스폰",
	NoActiveSpawns = "활성 스폰 없음",
	Select_To_Spawn = "생성하려면 선택",
	No_Results = "결과 없음",
	ItsEmpty = "비어있습니다 :(",
	Existing_Name = "기존 이름",
	Name = "이름",
	
	
	
	-- >> SWAP TAB
	BeginItem_TabNameSwap = "스왑",
	
	--Button
	Button_SmallRevert = "되돌리기",
	
    --Button Label
    --Checkbox
    --Warning / Info / Tool Tip
	Warn_ReloadSaveUpdateChanges = "변경 사항을 업데이트하려면 저장 게임을 다시 로드하세요!",
	Warn_NeedReloadSaveUpdateChanges = "변경 사항을 업데이트하려면 저장 내용을 다시 로드해야 합니다.",
	Warn_ReplacerSwap = "교체품을 교체할 수 없습니다! 사진 모드의 도구 탭을 사용하여 대상을 지정한 다음 생성 탭 또는 대상 도구에서 모양을 전환하세요.",
	Warning = "경고",
	Warning2 = "경고:",
	SaveSwap_Tooltip = "게임을 다시 로드한 후에도 유지하려면 스왑을 저장하세요.",
	
    --Text
	CantSwapReplacer = "교체품을 교체할 수 없습니다.",
	Active_Model_Swaps = "활성 모델 교환",
	Save = "저장",
	Restore = "복원",
	Current_Target = "현재 목표:",
	Target_ID = "대상 ID:",
	SelectSwap_CurrentTarget = "현재 대상으로 교체하려면 선택:",
	NoNPC_LookNPC = "NPC를 찾을 수 없습니다! NPC를 보고 시작하세요",
	
	-- Locations Categories
	Residences = "레지던스",
	ArasakaAndCorpo = "아라사카 & 코포",
	ClubsAndBars = "클럽 & 바",
	HotelsAndPleasure = "호텔 & 즐거움",
	UndergroundAndCrime = "지하 및 범죄",
	GovernmentAndSecurity = "정부 및 보안",
	StoryAndUnique = "스토리 & 유니크",
	Ripperdocs = "리퍼독스",
	LandmarksAndOpenWorld = "랜드마크 및 오픈 월드",
	SpoilersAndHidden = "스포일러 및 숨겨진 내용",
	UserLocations = "사용자 위치",
	
	
	-- >> DECOR TAB
	BeginItem_TabDecor = "장식",
	BeginItem_TabPresets = "사전 설정",
	Begin_ComboPresets = "사전 설정",
	
	--Button
	Button_SmallClone = "클론",
	Button_SmallRemove = "제거##",
	Button_SmallRename = "이름 바꾸기##",
	Button_SmallUpdate = "업데이트##",
	Button_SmallCancel = "취소",
	Button_Frame = "프레임",
	
    --Button Label
	Button_LabelHide = "숨기기",
	Button_LabelUnhide = "숨기기 해제",
	
    --Checkbox
    --Warning / Info / Tool Tip
	Warn_PersistPropSave = "집이나 원하는 곳 어디든 마음껏 장식할 소품을 생성하세요! 소품을 저장하여 지속되게 만드세요!",
	Warn_DespawnInProgress_PleaseWait = "디스폰이 진행 중입니다. 기다리세요.",
	Warn_PresetsFolder_Info = "사용자 사전 설정은 AppearanceMenuMod/User/Decor 폴더에 저장됩니다.",
	Warn_CustomPresets_Info = "이 사전 설정에는 사용자 정의 소품이 포함되어 있습니다.",
	Warn_CustomPropsModders_Info = "맞춤 제작 소품:",
	Warn_GamepadDirectMode_Info = "이를 통해 게임패드를 사용할 때 Direct 모드와 더 효과적으로 통합할 수 있습니다. 또한 고정된 작은 정보 창을 활성화합니다.",
	Warn_PresetTriggerDistanceFar = "Far로 설정하면 성능 문제가 발생할 수 있습니다.",
	
    --Text
	MovingAll_PropsTo_SavedProps = "모든 소품을 저장된 소품으로 이동",
	SelectPropSpawn = "생성할 소품 선택:",
	Spawned_Props = "생성된 소품",
	New_Preset = "새로운 사전 설정",
	No_Preset_Available = "사용 가능한 사전 설정 없음",
	Preset_TriggerDistance = "사전 설정된 트리거 거리",
	MovingSavedProps = "%s을(를) 저장된 속성으로 이동",
	UpdateTag = "태그 업데이트",
	Categories = "카테고리",
	Decorating = "꾸미기",
	Decor_Tabs = "장식 탭",
	Saved_Props = "저장된 소품",
	Show_Nearby_Only = "주변만 표시",
	Show_Lights_Only = "조명만 표시",
	Show_LockedTarget_Only = "잠긴 대상만 표시",
	Show_Customizable_Only = "사용자 정의 가능한 항목만 표시",
	Show_CustomProps_Only = "사용자 정의 소품만 표시",
	ShowOnMap = "지도에 표시",
	Rename = "이름 바꾸기",
	Delete = "삭제",
	Backup = "백업",
	Merge = "병합",
	Save_All = "모두 저장",
	Despawn_All = "모두 소멸",
	Save_ToSpecific_Tag = "특정 태그에 저장",
	Saved_Props2 = "저장된 소품:",
	Move_To_Tag = "태그로 이동",
	HideFromMap = "지도에서 숨기기",
	RemovingAllPropsFromTag = "태그에서 모든 Prop을 제거하는 중...",
	RemoveAllProps = "모든 소품 제거",
	RemoveHomeMarkerMap = "지도에서 홈 마커 제거",
	TeleportToLocation = "위치로 순간이동",
	TeleportToTrigger = "트리거로 순간이동",
	TeleportToMark = "마크로 순간이동",
	UpdateTagLocation = "태그 위치 업데이트",
	SharePresetWith_ThisTagOnly = "이 태그로만 사전 설정 공유",
	SavedPresetFolder_Info = "AppearanceMenuMod/User/Decor 폴더에 사전 설정이 저장되었습니다.",
	NoProps_WithThese_Conditions = "이 조건에는 소품이 없습니다",
	AddHomeMarkerMap = "지도에 홈 마커 추가",
	Distance = "거리",
	Total_Props = "총 소품:",
	Type_Tag_here = "여기에 태그를 입력하세요.",
	In_World = "세계에서",
	Tags = "태그",
	Tag = "태그",
	Both = "둘 다",	
	
	-- >> POSES TAB
	BeginItem_TabPoses = "포즈",
	
	--Button
	Button_SmallCopyClipboard = "클립보드에 복사",
	
    --Button Label
    --Checkbox
    --Warning / Info / Tool Tip
    --Text
	Active_Animations = "활성 애니메이션",
	ShowHistory = "기록 표시",
	ClearHistory = "기록 지우기",
	SelectPoseForCurrentTarget = "현재 대상의 포즈 선택:",
	LastUsedPoses = "마지막으로 사용한 포즈",
	
	
	
	-- >> TOOLS TAB
	BeginItem_TabTools = "도구",
	BeginItem_TabPhotoModeNibblesReplacer = "사진 모드 니블 교체기",
	BeginCombo_LookAt = "봐",
	BeginCombo_WeatherControl = "기상 제어",
	
	--Button
	Button_SkipFrame = "프레임 건너뛰기",
	Button_ToggleLight = "토글 라이트",
	Button_ResetScale = "스케일 재설정",
	Button_ShowAsLookAtTarget = "대상 보기로 표시",
	Button_ResetLookAtTarget = "대상 보기 재설정",
	Button_TogglePrimaryWeapon = "주 무기 장착",
	Button_ToggleSecondaryWeapon = "보조 무기 장착",
	Button_GiveCurrentEquippedWeapon = "현재 장착된 무기 부여",
	Button_SmallReset = "재설정",
	Button_ResetToPlayer = "플레이어로 재설정",
	Button_ClearSaved = "저장됨 지우기",
	Button_Cyberpsycho = "사이버사이코 전환",
	Button_ProtectNPCfromActions = "행동으로부터 NPC를 보호하세요",
	Button_AllFriendly = "모두 친절함",
	Button_AllHostile = "모두 적대적",
	Button_AllFollower = "모든 추종자",
	Button_AllFakeDie = "모든 페이크 다이",
	Button_AllDie = "모두 죽다",
	Button_AllDespawn = "모두 디스폰됨",
	Button_InvMachineGun = "기관총",
	Button_InvSpeed2 = "속도",
	Button_ToggleMakeup = "메이크업 전환",
	Button_TogglePiercings = "피어싱 전환",
	Button_ToggleSeamfix = "Seamfix 전환",
        Button_TargetV = "타겟 V",
        Button_Target = "대상",
        Button_TeleportToLocation = "위치로 순간이동",
        Button_TeleportToTrigger = "트리거로 순간이동",
        Button_TeleportToMark = "마크로 순간이동",
        Button_RandomLocation = "무작위",
        Button_ShareCurrentLocation = "현재 위치 공유",
	Button_GoBackToLastLocation = "마지막 위치로 돌아가기",
	Button_DeleteSelectedUserLocation = "선택한 사용자 위치 삭제",
	
	--Slider / Drag 
	Slider_HeadStiffness = "머리 뻣뻣함",
	Slider_HeadPoseOverride = "머리 포즈 재정의",
	Slider_ChestStiffness = "가슴이 뻣뻣함",
	Slider_ChestPoseOverride = "가슴 포즈 재정의",
	Slider_SlowMotion = "슬로우 모션",
	Slider_DefaultAperture = "기본 조리개",
	Slider_DefaultFieldofView = "기본 시야",
	Slider_MovementSpeed = "이동 속도",
	Drag_MovementSpeed = "이동 속도",
	
    --Button Label
	Button_Label_PauseTimeProgression = "일시정지 시간 진행",
	Button_Label_UnpauseTimeProgression = "시간 진행 일시정지 해제",
	Button_Label_UnfreezeTime = "동결 해제 시간",
	Button_Label_FreezeTime = "동결 시간",
	Button_Label_OpenLightSettings = "조명 설정 열기",
	Button_Label_UpdateLightTarget = "라이트 타겟 업데이트",
	Button_Label_Activate = "활성화",
	Button_Label_Deactivate = "비활성화",
	Button_Label_ChangeToCrouchStance = "웅크린 자세로 변경",
	Button_Label_ChangeToStandStance = "스탠스 자세로 변경",
	Button_Label_PickUpTarget = "픽업 대상",
	Button_Label_DropTarget = "드롭 타겟",
	Button_Label_FreezeTarget = "목표 동결",
	Button_Label_UnfreezeTarget = "대상 고정 해제",
	Button_Label_OpenTargetTools = "대상 도구 열기",
	Button_Label_CloseTargetTools = "타겟 도구 닫기",
	
    --Checkbox
    --Warning / Info / Tool Tip
	Warn_FileNotFound_CollabsFolder_Error = "Collabs 폴더에 파일이 없습니다.",
	Warn_ShowXYZ_Orientation_Info = "대상을 이동할 때 더 쉽게 방향을 잡을 수 있도록 X, Y 및 Z 화살표를 표시합니다.",
	Warn_LookAtCamera_OptionOff_Info = "이 설정을 변경한 후 카메라 보기 옵션을 한 번 끄세요.",
	Warn_DisableLookAtCamera_PhotoMode_Info = "사진 모드에서 '카메라 보기'를 한 번 비활성화하면 적용됩니다.",
	Warn_RequiresRestart_Info = "적용하려면 게임을 다시 시작해야 합니다.",
	Warn_SlowMotion_PhotoMode_Info = "사진 모드의 슬로우 모션은 IGCS를 사용하여 일시 중지를 해제한 경우에만 작동합니다.",
	Warn_WeatherControl_RequireCodeware = "날씨 제어에는 코드웨어 1.4 이상이 필요합니다.",
	Warn_StopNpc_UnequipWeapon_Info = "그러면 NPC가 주어진 무기를 장비 해제하는 것을 막을 수 있습니다. 참고: NPC는 전투 중에 마음대로 장비를 해제할 수 있습니다.",
	Warn_OutOfCombat_NpcUnequip_Info = "참고: 전투 중이 아닐 때 NPC는 해당 무기를 즉시 장착 해제합니다.",
	Warn_Photomode_UnfreezeSkipFrames_Info = "사진 모드에서 Unfreeze Target은 애니메이션 포즈의 프레임을 건너뜁니다. 전체 고정(비) 기능을 사용하려면 Otis Camera Tools(IGCS)를 사용해야 합니다.",
	Warn_UserLocationsFolder_Info = "사용자 위치는 AppearanceMenuMod/User/Locations 폴더에 저장됩니다.",
	Warn_SeeMoreAction_Info = "추가 작업을 보려면 V 또는 NPC를 타겟팅하세요.",
	Warn_SeeMoreActionProp_Info = "더 많은 액션을 보려면 NPC 또는 소품을 타겟팅하세요.",
	Warn_SeamfixPiercingToggle_Info = "이렇게 하면 게임을 닫을 때까지 메이크업, 피어싱 및 Seamfix 토글 상태가 저장됩니다.",
	Warn_PassiveMode_Info = "전투를 시작하면 적들은 계속해서 당신을 공격합니다.",
	Warn_TppCameraGameplay_Info = "TPP 카메라는 일반적인 게임 플레이에는 적합하지 않지만 산책에는 재미있습니다 ;)",
	Warn_AnimatedHead_PhotoMode_Info = "애니메이션 머리가 활성화된 동안에는 사진 모드 표현이 작동하지 않습니다.",
	Warn_ToolsOnly_WorksIngame = "도구는 게임에서만 작동합니다.",
	Warn_InvButtonMachineGun_Info = "찾았어요! 장비에 중기관총이 추가되었습니다.",
	Warn_InvButton_Info = "찾았어요! 이제 패스트 모션을 사용할 수 있습니다.",
	InvButtonTip = "여기를 클릭하면 어떻게 되나요?",
	InvButtonTip2 = "여기를 클릭해도 아무 일도 일어나지 않습니다!",
	InvButtonTip3 = "경고를 받았으니 클릭하지 마세요!",
	
    --Text
	Facial_Expression = "표정",
	Expressions = "표현식",
	Look_At = "봐",
	Look_At_Camera = "카메라를 봐:",
	Target_Tools = "대상 도구",
	Rotation = "회전",
	Tilt_Rotation = "기울이기/회전",
	Mode = "모드:",
	Precision = "정밀도",
	Relative = "친척",
	Direct = "직접",
	AdvMovement = "고급 운동",
	ForceGivenWeapon = "강제로 부여된 무기",
	Scale = "규모",
	ProportionalMode = "비례 모드",
	General_Actions = "일반 조치",
	DisablePassiveMode = "패시브 모드 비활성화",
	EnablePassiveMode = "패시브 모드 활성화",
	EnableGodMode = "신 모드 활성화",
	DisableGodMode = "신 모드 비활성화",
	Infinite_Oxygen = "무한 산소",
	Select_Location = "위치 선택",
	Select_Expression = "표현식 선택",
	Select_Category = "카테고리 선택",
	Teleport_Actions = "순간이동 작업",
	Use_Teleport_Animation = "텔레포트 애니메이션 사용",
        Filter_Locations = "위치 필터링",
        Locations = "위치",
        Default_Locations = "기본 위치",
        Collab_Locations = "협업 장소",
        Button_AddTag = "태그 추가",
	Button_FilterByTags = "태그로 필터링",
	Button_Close = "닫기",
	Favorite_Selected_Location = "즐겨찾는 선택 위치",
	Unfavorite_Selected_Location = "즐겨찾지 않는 선택 위치",
	Edit_Selected_Location = "선택한 위치 편집",
	Locations_Favorites = "--------- 즐겨찾기 ----------",
	Locations_UserLocs = "------- 사용자 위치 -------",
	Locations_DefaultLocs = "----------- 기본값 ----------",
	Share_Location = "위치 공유",
	Edit_Location = "위치 편집",
	TimeWeather_Actions = "시간 및 날씨 조치",
	TimeofDay = "하루 중 시간",
	Time_Actions = "시간 작업",
	Rain = "비",
	Light_Rain = "가벼운 비",
	Cloudy = "흐림",
	Fog = "안개",
	Heavy_Clouds = "무거운 구름",
	Light_Clouds = "가벼운 구름",
	Pollution = "오염",
	Sandstorm = "모래폭풍",
	Sunny = "써니",
	Toxic_Rain = "독성 비",
	Deep_Blue = "딥블루",
	Squat_Morning = "스쿼트 모닝",
	Cloudy_Morning = "흐린 아침",
	Rainy_Night = "비오는 밤",
	Courier_Clouds = "택배 구름",
	Cursor_LockState = "잠금 상태",
	PhotoMode_NibblesReplacer = "사진 모드 니블 교체기",
	PhotoModeEnhancements = "사진 모드 개선 사항",
	Button_ResetReplacerDatabase = "교체자 데이터베이스 재설정",
	DisablePhotoModeCursor = "사진 모드 커서 비활성화",
	TPPCamera_Position = "TPP 카메라 위치",
	AnimatedHeadin_PhotoMode = "사진 모드의 애니메이션 머리",
	LockLook_AtCamera = "카메라 보기 잠금",
	UnlockLook_AtCamera = "카메라 보기 잠금 해제",
	Save_Toggles_State = "저장 토글 상태",
	Toggle_V_Head = "V 헤드 전환",
	Toggle_TPP_Camera = "TPP 카메라 전환",
	Target_Nibbles = "타겟 니블",
	Target_Replacer = "대상 대체자",
	Left = "왼쪽",
	Left_Close = "왼쪽 닫기",
	Right = "오른쪽",
	Right_Close = "오른쪽 닫기",
	Center_Close = "센터 클로즈",
	Center_Far = "센터 파",
	Front_Close = "프론트 클로즈",
	Front_Far = "전방 원거리",
	All = "모두",
	Head_Only = "머리만",
	Eyes_Only = "눈만",
	Movement = "운동",
	V_Actions = "V 액션",
	Invisible_V = "보이지 않는 V",
	LikeGTA_byGTATravel = "GTA 여행으로",
	EnableSpawnedProps = "생성된 소품 활성화",
	LightControl = "조명 제어",
	Equipment = "장비",
	
	-- >> DIRECTOR TAB
	BeginItem_TabNameDirector = "이사",
	BeginItem_TabNameTriggers = "트리거",
	BeginCombo_StartAppearance = "시작 모양",
	BeginCombo_EndAppearance = "최종 외관",
	BeginCombo_Type = "유형",
	BeginCombo_GoToTarget = "대상으로 이동",
	BeginCombo_PlayVoice = "음성 재생",
	BeginCombo_Attack = "공격",
	BeginCombo_Triggers = "트리거",
	BeginCombo_Scripts = "스크립트",
	
	--Button
	Button_Yes = "예",
	Button_No = "아니요",
	Button_SaveChangesOnly = "변경 사항만 저장",
	Button_RemoveMark = "표시 제거",
	Button_EditMark = "마크 편집",
        Button_MoveMark = "마크 이동",
        Button_MoveUp = "위로 이동",
        Button_MoveDown = "아래로 이동",
        Button_NewMark = "뉴마크",
	Button_AddActor = "배우 추가",
	Button_RemoveActor = "배우 제거",
	Button_ChangeActor = "배우 변경",
	Button_RadioOnlyOne = "온리원",
	Button_RadioRandom = "무작위",
	Button_RadioSequential = "순차",
	Button_SaveTrigger = "트리거 저장",
	Button_NewCamera = "새 카메라",
	Button_NewScript = "새 스크립트",
	Button_DragSpeed = "속도",
	Button_ToggleMarker = "토글 마커",
	Button_TestPose = "테스트 포즈",
	Button_StopPose = "포즈 중지",
	
    --Button Label
	Button_Label_PlayScript = "스크립트 재생",
	Button_Label_StopScript = "스크립트 중지",
	Button_Label_Stopping = "중지 중...",
	Button_Label_Restarting = "다시 시작하는 중...",
	Button_Label_AddMark = "마크 추가",
	Button_Label_SaveWNewPos = "새 위치로 저장",
	
    --Checkbox
    --Warning / Info / Tool Tip
	Warn_ActorSingleMark_Info = "액터는 단일 마크에 유지됩니다.",
	Warn_ActorRandomMark_Info = "액터가 마크 사이를 무작위로 이동합니다.",
	Warn_ActorSequentialMark_Info = "액터는 숫자 순서대로 마크 사이를 이동합니다.",
	Warn_DeleteScript_Info = "이 스크립트를 삭제하시겠습니까?",
	Warn_CloseCamForMove_Info = "카메라를 이동하려면 메뉴를 닫으세요.",
	Warn_CreateScriptsDesc_Info = "머시니마, 스크린샷, 역할극을 위해 연기할 배우를 추가하고, 옷을 입히고, 지시하는 스크립트를 만듭니다.",
	Warn_PremadeScriptsDesc_Info = "접촉 시 미리 만들어진 스크립트를 활성화하는 트리거를 만듭니다.",
	Warn_CreateCamera_FovZoomDesc_Info = "자유롭게 이동할 수 있는 카메라를 만들고 다양한 시야와 확대/축소 수준을 설정하세요.",
	Warn_ShowMarksLocations_Info = "표시 위치에 눈에 보이는 아이콘을 표시합니다.",
	Warn_AutoTalkNpc_Info = "이렇게 하면 NPC가 범위 내에 있을 때 1분마다 한 번씩 대화하게 됩니다(음성 NPC만 해당).",
	Warn_DirectActorPlayerPosition_Info = "현재 플레이어 위치에 마크를 생성하여 액터를 이동하고 지시합니다.",
	Warn_InMenuDirectorDesc = "디렉터는 게임 내에서만 작동합니다.",
	
    --Text
	DirectorMode = "디렉터 모드",
	SelectActorToReplace = "교체할 액터 선택:",
	AddActorToCurrentScript = "현재 스크립트에 액터 추가:",
	FacialExpression_WithColon = "표정:",
	FavoritePoses_WithColon = "좋아하는 포즈:",
	AddFavorites_Desc = "먼저 포즈 탭에서 즐겨찾기에 포즈를 추가하세요.",
	HoldDuration = "보유 기간",
	Movement2 = "운동:",
	Actions = "작업:",
	Actors = "배우",
	Editing = "편집",
	AutoTalk = "자동통화",
	ActorMarks = "배우 마크",
	Current_Actors = "현재 배우",
	Marks_Sequence = "마크 순서:",	
	ShowMarks = "표시 표시",
	Triggers = "트리거",
	NewTrigger = "새로운 트리거",
	ShowTrigger = "트리거 표시",
	Title = "제목",
	Select_Trigger = "트리거 선택",
	Select_Script = "스크립트 선택",
	Delete_Trigger = "트리거 삭제",
	Triggers_On_Off = "트리거 켜기/끄기",
	Running = "달리기",
	Script_Running = "스크립트 실행 중...",
	Delete_Script = "스크립트 삭제",
	RepeatInLoop = "루프 내에서 반복",
	ActivationRadius = "활성화 반경",
	Activate = "활성화",
	Deactivate = "비활성화",
	FOV = "시야",
	Zoom = "줌",
	LockFrame = "잠금 프레임",
	Walk = "걷기",
	Sprint = "스프린트",
	Sequential = "순차",
	Cameras = "카메라",
	NodeView = "노드 보기",
	TeamA = "A팀",
	TeamB = "B팀",
	
	
	
	-- >> SETTINGS TAB
	BeginItem_TabNameSettings = "설정",
	BeginItem_TabNameGeneral = "일반",
	BeginItem_TabNameCompanions = "동반자",
	BeginItem_TabNameUI = "사용자 인터페이스",
	BeginItem_TabNameExperimental = "실험적",
	BeginItem_TabNamePhotoMode = "사진 모드",
	
	--Button
	Button_RevertAllModelSwaps = "모든 모델 교체 되돌리기",
	Button_RespawnAll = "모두 리스폰",
	Button_ForceDespawnAll = "강제 소멸 모두",
	Button_ClearFavorites = "즐겨찾기 지우기",
	Button_ClearAllSavedAppearances = "저장된 표현 모두 지우기",
	Button_ClearAllBlacklistedAppearances = "블랙리스트에 등록된 모든 모습 지우기",
	Button_ClearAllAppearanceTriggers = "모든 모양 트리거 지우기",
	Button_ClearAllSavedDespawns = "저장된 모든 디스폰 지우기",
	Button_SmallCreateTheme = "테마 만들기",
	Button_SmallDeleteTheme = "테마 삭제",
	Button_SmallSet = "세트",
	Button_ReloadAppearances = "사용자 정의 표현 다시 로드",
	
    --Button Label
    --Checkbox
	Checkbox_SpawnAsCompanion = "동반자로 생성",
	Checkbox_SpawnAsFriendly = "우호적으로 생성",
	Checkbox_InvulnerableCompanion = "무적의 동반자",
	Checkbox_RespawnOnLaunch = "실행 시 리스폰",
	Checkbox_LockTargetAfterSpawn = "생성 후 대상 고정",
	Checkbox_OpenTargetToolsAfterSpawn = "생성 후 대상 도구 열기",
	Checkbox_DisplayAxisIndicatorByDefault = "기본적으로 축 표시기 표시",
	Checkbox_PhotoModeEnhancements = "사진 모드 개선 사항",
	Checkbox_GodModeOnLaunch = "신 모드 출시 중",
	Checkbox_PassiveModeOnLaunch = "실행 시 패시브 모드",
	Checkbox_StreamerMode = "스트리머 모드",
	Checkbox_OpenWCETOverlay = "CET 오버레이로 열기",
	Checkbox_AutoResizingWindow = "자동 크기 조정 창",
	Checkbox_ScanningReticle = "스캐닝 레티클",
	Checkbox_FloatingTargetTools = "플로팅 타겟 도구",
	Checkbox_TabHeaderDescriptions = "탭 헤더 설명",
	Checkbox_ExpandFavoritesByDefault = "기본적으로 즐겨찾기 확장",
	Checkbox_EnableScrollBars = "스크롤 막대 활성화",
	Checkbox_AlwaysDisablePhotoModeCursor = "항상 사진 모드 커서 비활성화",
	Checkbox_Camera = "카메라",
	Checkbox_DepthOfField = "자유도",
	Checkbox_Effect = "효과",
	Checkbox_Stickers = "스티커",
	Checkbox_LoadSave = "로드/저장",
	Checkbox_ExperimentalFunstuff = "실험적/재미있는 것들",
	Checkbox_EnableFreezeTargetInPhotoMode = "사진 모드에서 대상 고정 활성화",
	Checkbox_WeaponizeCompanions = "동료를 무기화하다",
	Checkbox_AllowPlayerToBeTargetedinPosestab = "포즈 탭에서 플레이어의 타겟 지정 허용",
	Checkbox_AllowPlayerAnimationsonNPCs = "NPC에서 플레이어 애니메이션 허용",
	Checkbox_AllowExpressionOnNpcPM = "사진 모드에서 표정 허용 및 NPC 살펴보기",
        Checkbox_ResetTargetPositionPM = "사진 모드 NPC의 대상 위치 재설정",
        Checkbox_EnableRandomLocation = "무작위 버튼 활성화: 플레이어를 목록에서 무작위 위치로 순간이동시킵니다.",
        Checkbox_RestoreOnLaunch = "실행 시 복원",
        Radio_PrimarySlot = "기본 슬롯",
        Radio_SecondarySlot = "보조 슬롯",
	
    --Warning / Info / Tool Tip
	Warn_RespawnOnLaunch_Info = "이 설정은 게임 로드 시 이전에 저장한 NPC의 부활을 활성화/비활성화합니다. AMM은 게임을 종료할 때 생성된 NPC를 자동으로 저장합니다.",
	Warn_BannedWords_Info = "이 설정은 naked, naked, xxx, 샤워, birthday_suit, pp 및 음경 단어가 포함된 NPC 모양을 활성화/비활성화합니다.",
	Warn_TargetNpcVehicleHotkey = "단축키를 설정할 대상 NPC 또는 차량",
	Warn_FirstLaunchDecideTabsExpand_Info = "이 설정은 AMM이 처음 실행될 때 기본적으로 생성, 교체 및 장식 탭의 즐겨찾기를 확장합니다.",
	Warn_ExperimentalTabDesc_Info = "실험적 기능은 더 많은 기능을 추가하지만 실험적 라벨에서는 제대로 작동하지 않을 수 있습니다. 실제로 대부분의 AMM 사용자는 실험적 기능을 활성화했습니다. 그러니 너무 걱정하지 마시고 재미있게 보내세요!",
	Warn_FreezeTargetPhotoMode_Info = "이 설정은 사진 모드 포즈에 사용자 지정 애니메이션을 추가하는 모드에서 또는 IGCS를 사용하여 일시 중지를 해제할 때 애니메이션을 고정하는 데 도움이 됩니다.",
	Warn_WeaponizeCompanions_Info = "그러면 모든 NPC에게 무기와 전투 능력이 부여됩니다. T-포즈와 이상한 애니메이션이 예상됩니다.",
	Warn_PlayerAnimsOnNpc_Info = "NPC에서 플레이어 애니메이션을 사용할 수 있는 모드를 사용하는 경우 이 옵션을 활성화하세요.",
	Warn_UnpauseRequiresIGSC = "이 설정을 사용하려면 IGCS가 시간 일시중지를 해제해야 합니다.",
	Warn_NotInstalled = "설치되지 않음",
	Warn_DespawnAllProps = "모든 사물을 디스폰하시겠습니까?",
	
    --Text
	AMM_Version = "AMM 버전:",
	CET_Version = "CET 버전:",
	Codeware_Version = "코드웨어 버전:",
	Game_Version = "게임 버전:",
	Companion_Damage = "동반자 피해:",
	Companion_Resistance = "동료 저항:",
	Companion_Distance = "동반자 거리:",
	xDamage = "x 손상",
	xResistance = "x 저항",
	SavedAppearancesHotkeys = "저장된 표현 단축키",
	Favorites = "즐겨찾기",
	Appearances = "외관",
	Blacklist = "블랙리스트",
	AppearanceTriggers = "외관 트리거",
	SavedDespawns = "저장된 디스폰",
	Interface_Language = "인터페이스 언어:",
	Custom_Appearances = "맞춤형 표현",
	PhotoModeAdjustments = "사진 모드 조정:",
	DisablePhotoModeTabs = "사진 모드 탭 비활성화:",
	List_Height = "목록 높이",
	Listbox_Themes = "테마",
	Weaponize = "무기화",
	NoAppearanceSet = "외형 세트 없음",
	
	
	
	-- >> EXTRA	
	--Texts, warns, tips, info's, buttons and labels etc.
	Seat_FrontRight = "앞 오른쪽",
	Seat_BackRight = "뒤로 오른쪽",
	Seat_FrontLeft = "앞 좌측",
	Seat_BackLeft = "뒤 왼쪽",
	Label_Door = "문",
	Label_Window = "창",

	Close = "닫기",
	Far = "멀리",
	Moderate = "보통",
	
	-- >> Archives Screen
	Warning_MissingRequiredArchives = "AMM에 하나 이상의 필수 아카이브가 없습니다. archive/pc/mod 폴더에 누락된 필수 아카이브를 설치하십시오.",
	Warning_MissingOptionalArchives = "AMM에 하나 이상의 아카이브가 없습니다. 이는 선택 사항이지만 AMM에 기능을 추가합니다. 이러한 경고는 무시해도 되지만 AMM이 제대로 작동하지 않을 수 있습니다.",
	
	
	-->> INIT.LUA
	AMMNeedsAttention = "AMM에 주의가 필요합니다",
	MISSING_ARCHIVES = "누락된 아카이브",
	VERSION_INFORMATION = "버전 정보",
	CREDITS = "크레딧",
	UPDATE_HISTORY = "업데이트 내역",
	Updates = "업데이트",
	MISSING = "누락",
	REQUIRED = "필수",
	OPTIONAL = "선택사항",
	WHATS_NEW = "새로운 소식", --Line 83 Function Error

	--Button
	Button_Ignorewarningsforthisversion = "이 버전에 대한 경고 무시",
	Button_Credits = "크레딧",
	Button_Cool = "멋지다!",

	--Button Label
	Label_SpawnFavorites = "즐겨찾기 생성",
	Label_SwapFavorites = "즐겨찾기 교환",
	Label_FavoriteAppearances = "좋아하는 외모",
	Label_Cancel = "취소",

	--Text
	Hotkey_i = "단축키 %i",

	--Node - Function Error(nil value) 
	Top = "탑", --Line 116
	Bottom = "바닥",
	Off = "끄기",
	
	--Voice Overs
	Label_GreetV = "V에게 인사하세요",
	Label_FearFoll = "두려움",
	Label_FearToll = "공포의 통행료",
	Label_FearBeg = "두려워서 구걸하다",
	Label_FearRun = "공포 실행",
	Label_StealthSearch = "스텔스 검색",
	Label_StealthDeath = "스텔스 데스",
	Label_StealthRestore = "스텔스 복원",
	Label_StealthEnd = "스텔스엔드",
	Label_CuriousGrunt = "호기심 많은 그런트",
	Label_GrappleGrunt = "그래플 그런트",
	Label_Bump = "범프",
	Label_VehicleBump = "차량 범프",
	Label_TurretWarning = "포탑 경고",
	Label_OctantWarning = "8분원 경고",
	Label_DroneWarning = "드론 경고",
	Label_MechWarning = "기계 경고",
	Label_EliteWarning = "엘리트 경고",
	Label_CameraWarning = "카메라 경고",
	Label_EnemyWarning = "적 경고",
	Label_HeavyWarning = "무거운 경고",
	Label_SniperWarning = "저격수 경고",
	Label_AnyDamage = "모든 손상",
	Label_Danger = "위험",
	Label_CombatStart = "전투 시작",
	Label_CombatEnd = "전투 종료",
	Label_CombatTargetHit = "전투 목표물 명중",
	Label_PedestrianHit = "보행자 충돌",
	Label_LightHit = "가벼운 타격",
	Label_Curse = "저주",
	Label_Irritated = "짜증나다",
	Label_GrenadeThrow = "수류탄 던지기",
	Label_Gotakill = "죽였어!",
	
	--Expressions
	Neutral = "중립",
	Joy = "기쁨",
	Smile = "미소",
	Sad = "슬픈",
	Surprise = "놀라움",
	Aggressive = "공격적",
	Anger = "분노",
	Interested = "관심",
	Disinterested = "무관심",
	Disappointed = "실망하다",
	Disgust = "혐오감",
	Exertion = "노력",
	Nervous = "긴장하다",
	Fear = "두려움",
	Terrified = "겁에 질린",
	Pain = "고통",
	Sleepy = "졸려",
	Unconscious = "무의식",
	Dead = "죽은",

	-- Extra Expressions
	Frown = "찌푸린 얼굴",
	Shocked = "충격을 받음",
	Annoyed_2 = "짜증나 2",
	Contempt = "경멸",
	Irritated = "짜증나다",
	Sceptical_1 = "회의적 1",
	Sceptical_2 = "회의적 2",
	Annoyed_1 = "짜증나 1",
	Offended = "불쾌한",
	Disgusted = "역겹다",
	Disappointed_2 = "실망 2",
	Alert = "경고",
	Crying = "울고",
	Embarrassed = "당황하다",
	Humiliated = "굴욕을 당하다",
	Impatient = "참을성이 없는",
	Anguished = "고뇌",
	Worried = "걱정",
	Guilty = "유죄",
	Grieving = "슬픔",
	RestrainedAnger = "억제된 분노",
	Afraid = "두려워",
	LookingUpAnnoyed = "짜증이 나서 올려다보다",
	Offended_2 = "불쾌한 2",
	Resentful = "분개하다",
	SadExtra = "슬픈 엑스트라",
	NervousBreath = "긴장된 호흡",
	ScreamingLong = "오랫동안 비명을 지르다",
	ScreamingShort = "스크리밍 쇼트",
	ScaredBreath = "겁먹은 숨결",
	CryingPainful = "고통스럽게 울다",
	SelfReflectAnger = "자기반성 분노",
	IndulgentSmile = "관대한 미소",
	Impressed = "감동",
	LongSmile = "긴 미소",
	ShortSmile = "짧은 미소",
	SimpleSmile = "단순한 미소",
	Confident = "자신감",
	Relief = "구호",
	Impressed_2 = "감동 2",
	Admiring = "감탄하다",
	Fascinated = "매료되다",
	RaisedBrows = "올려진 눈썹",
	LookingUpThinking = "생각을 찾고",
	LeftGlanceProcessing = "왼쪽 시선 처리",
	LeftGlanceCloseUp = "왼쪽 눈을 가까이",
	LookingAround = "둘러보기",
	LookingDownThinking = "아래를 내려다 보면서 생각",
	LookingAroundAlt = "Alt 둘러보기",
	EyesDartFromLeft = "눈은 왼쪽에서 다트",
	EyesDartFromRight = "눈은 오른쪽에서 다트",
	EyesDartToRight = "눈이 오른쪽으로 향함",
	LookingLeft = "왼쪽을 바라보며",
	LookingUpThinking_2 = "생각 2를 찾고",
	RightGlanceProcessing = "직시 가공",
	LookingDown = "아래를 내려다 보면서",
	Left90GlanceClose = "왼쪽90눈짓 닫기",
	LookingUp = "올려다보기",
	Right90GlanceClose = "오른쪽90눈짓 닫기",
	LookingLeftUp = "왼쪽 위로 바라보기",
	LookingRightUp = "바로 위를 바라보며",
	ReadingDown = "아래로 읽기",
	ReadingUp = "읽기",
	ReadingMiddle = "독서중",
	FrontCloseGlance = "정면 가까이서 살펴보기",
	WinkLeft = "윙크 왼쪽",
	EyeRoll = "아이롤",
	Squint = "곁눈질",
	FalseSmile_2 = "거짓 미소 2",
	FalseSmile_1 = "거짓 미소 1",
	ListeningNewInfo = "새로운 정보 듣기",
	WhatDoYouWant = "당신은 무엇을 원하십니까",
	Maybe = "어쩌면",
	SearchingForWords = "단어 검색",
	What = "무엇",
	Where = "어디에",
	SureSure = "물론이죠",
	ListenToMe = "내 말을 들어보세요",
	StopThePolice = "경찰을 멈춰라",
	HurryUp = "서둘러",
	ShutUp = "닥쳐",
	WinkRight = "윙크 오른쪽",
	MockingSmile = "조롱하는 미소",
	AsymmetricalSmile = "비대칭 미소",
	SarcasticSmile = "냉소적인 미소",
	Sex = "섹스",
	LipBite_1 = "입술 물린 1",
	LipBite_2 = "입술 물린 2",
	Moan = "신음",
	LipBite_3 = "입술 물린 3",
	Pout = "삐죽",
	SexySmile = "섹시한 미소",
	Swallow = "제비",
	SensualSmile = "관능적인 미소",
	SexScene_1 = "섹스 장면 1",
	SexScene_2 = "섹스 장면 2",
	Kiss = "키스",
	UsingInhaler = "흡입기 사용",
	ShortYawn = "짧은 하품",
	Yawn = "하품",
	Coughing = "기침",
	Bite = "물린",	
	EatingFast = "빨리 먹기",
	ShortDrink = "쇼트 드링크",
	Drinking = "음주",
	FastBite = "패스트 바이트",
	LongDrink = "롱 드링크",
	ShortSmoking = "짧은 흡연",
	LongSmoking = "장시간 흡연",
	Smoking = "흡연",
	Eating_1 = "1을 먹고",
	Eating_2 = "먹는 2",
	Eating_3 = "3을 먹고",
	Eating_4 = "먹는 4",
	Vomit = "구토",
	BeingRevived = "부활하는 중",
	MalwarePositive = "악성코드 양성",
	MalwareNegative = "악성코드 네거티브",
	MalwareInfected = "악성코드 감염",
	FaceMorphActivate = "얼굴 변형 활성화",
	LieNetChairSleep = "거짓말 그물 의자 수면",
	LieNetChairBreathe = "거짓말 그물 의자 호흡",
	NetrunnerDeathUnplugged = "넷러너 데스 언플러그드",
	VeryItchyNose = "매우 가려운 코",
	RollerCoasterNervous = "롤러코스터 긴장",
	Pfft = "Pfft",
	Hahaha = "하하하",
	Sniff = "냄새맡다",
	Ahaaa = "아하아아",
	Heh = "ㅎ",
	Huh = "허",
	Haaa = "하아아",
	Sigh_Lipsync = "한숨 립싱크",
	Hmm = "흠",
	Whispering_1 = "속삭임 1",
	Whispering_2 = "속삭임 2",
	ApprovalYes = "승인 예",
	SubtleYes = "미묘한 예",
	QuickNoShake = "빠른 흔들림 없음",
	FirmYes = "확정 예",
	LongNo = "롱 노",
	SubtleNo = "미묘한 아니요",
	NoContempt = "경멸 없음",
	NoDisapproval = "비승인 없음",
	FirmNo = "회사 번호",
	NoEnthusiastic = "열정적이지 않음",
	MockingYes = "조롱 예",
	EnthusiasticYes = "열정적임 예",
	AsymmetricalCornerUp = "비대칭 코너 업",
	CornersUp = "코너 업",
	SoftSigh = "부드러운 한숨",
	BreathGasp = "숨 헐떡임",
	AssymetricalSneer = "비대칭 비웃음",
	CrimpingLips = "크림핑 입술",
	BrowsDown = "아래로 눈썹",
	BrowsLeftUp = "눈썹은 왼쪽 위로",
	BrowsRightUp = "눈썹이 위로 올라간다",
	BrowsUp = "브라우즈 업",
	ClosedEyes_1 = "닫힌 눈 1",
	ClosedEyes_2 = "닫힌 눈 2",
	EyesClosed = "눈을 감고",
	LookRight = "오른쪽 봐",
	FastBlink = "빠르게 깜박임",
	SlowBlink = "느린 깜박임",
	NormalBlink = "일반 깜박임",
	TinyBlink = "작은 깜박임",
	HalfBlink = "반쯤 깜박임",
	RegularSaccade = "규칙적인 단속운동",
	FrequentSaccade = "빈번한 단속운동",
	PhotoCloseupEyes = "사진 근접 촬영 눈",
	PhotoCloseupLips = "사진 근접 촬영 입술",
	PhotoCloseupHair = "사진 근접 촬영 머리",
	PhotoCloseupChin = "사진 근접 촬영 턱",
	PhotoCloseupNose = "사진 근접 촬영 코",
	PhotoCloseup = "사진 근접 촬영",
	PhotoCloseupPleased = "사진 근접 촬영 기쁘게 생각합니다",
	PhotoCloseupBody = "사진 근접 촬영 본문",
	PhotoCloseupTeeth = "사진 근접 촬영 치아",
	PhotoCloseupIN = "사진 근접 촬영 IN",
	PhotoCloseupOUT = "사진 근접 촬영 OUT",
	Bored = "지루하다",
	Charming = "매력적인",
	Furious = "퓨리어스",
	Happy = "행복하다",
	Pissed = "화났어",
	Pleased = "기쁘게 생각합니다",
	Scared = "무서워",
	Surprised = "놀랐다",
	Sadness = "슬픔",
	Whistling = "휘파람소리",
	Singing_1 = "노래 1",
	Singing_2 = "노래 2",
	Singing_3 = "노래 3",
	Alerted = "경고됨",
	Hit_1 = "히트 1",
	Hit_2 = "히트 2",
	Wounded = "부상",
	Death = "죽음",

	-- Expressions Category
	Negative = "네거티브",
	Positive = "긍정적",
	Contemplative = "명상적",
	Social = "소셜",
	Sexual = "성적",
	Action = "액션",
	Vocal = "보컬",
	Yes_N_No = "예 & 아니오",
	Nuance = "뉘앙스",
	Static = "정적",
	Combat = "전투",
	
	--Props
	AMM_Props_Desc = "소품, 캐릭터, 차량을 추가합니다. 이것이 없으면 AMM이 실행되지 않습니다.",
	AMM_JohnnyCompanion_Desc = "생성 가능한 캐릭터로 Johnny Silverhand를 추가합니다.",
	AMM_ScenesPack_Desc = "포즈 시스템에 9358 장면 애니메이션을 추가합니다.\nAMM의 Nexus 페이지에서 다운로드하세요.",
	AMM_SoundPack_Desc = "생성 가능한 음향 효과를 추가합니다.",
	AMM_KerryPP_Desc = "새로운 벌거벗은 모습을 추가합니다.",
	AMM_BenjaminStonePP_Desc = "새로운 벌거벗은 모습을 추가합니다.",
	AMM_RiverPP_Desc = "새로운 벌거벗은 모습을 추가합니다.",
	AMM_YorinobuPP_Desc = "새로운 벌거벗은 모습을 추가합니다.",
	AMM_LizzyIncognito_Desc = "새로운 모습을 추가합니다.",
	AMM_MeredithXtra_Desc = "새로운 모습을 추가합니다.",
	AMM_DelamainFix_Desc = "델라마인에 전신을 추가합니다.",
	AMM_HanakoNoMakeup_Desc = "Custom Appearance를 사용할 때 AMM이 Hanako의 메이크업을 제거할 수 있습니다.",
	AMM_JudyBodyRevamp_Desc = "주디의 몸을 새롭게 개선된 몸으로 교체합니다.",
	AMM_PanamBodyRevamp_Desc = "파남의 신체를 새롭게 개선된 신체로 교체합니다.",
	AMM_MistyBodyRevamp_Desc = "미스티의 몸을 새롭게 개선된 몸으로 교체합니다.\nAMM의 Nexus 페이지에서 다운로드하세요.",
	AMM_1VesHanakoFixedBodyNaked_Desc = "하나코의 몸을 새롭게 개선된 몸으로 교체합니다.",
	AMM_PinkyDudeANIMFacialExpressionsFemV_Desc = "Female V의 표정 도구를 활성화합니다.",
	AMM_PinkyDudeANIMFacialExpressionsMaleV_Desc = "Male V의 표정 도구를 활성화합니다.",
	AMM_DinoTattooFixArchive_Desc = "메쉬와 텍스처를 대체합니다.",
	AMM_SongbirdBodyFixArchive_Desc = "회색 영역을 수정하기 위해 본체를 교체합니다. 아직 완벽하지 않습니다.",
	AMM_RitaWheelerCombatEnablerArchive_Desc = "전투 애니메이션을 활성화하기 위해 엔터티 파일을 대체합니다.",
	AMM_CheriAppearances_Desc = "새로운 모습을 추가합니다. AMM의 Nexus 페이지에서 다운로드하세요.",
	AMM_BryceNaked_Desc = "새로운 벌거벗은 모습을 추가합니다. AMM의 Nexus 페이지에서 다운로드하세요.",
	AMM_EvelynNaked_Desc = "벌거벗은 모습이 가능하도록 몸을 고정합니다. AMM의 Nexus 페이지에서 다운로드하세요.",
	AMM_SaburoAppearances_Desc = "새로운 모습을 추가합니다. AMM의 Nexus 페이지에서 다운로드하세요.",
	AMM_TbugAppearances_Desc = "새로운 모습을 추가합니다. AMM의 Nexus 페이지에서 다운로드하세요.",
	AMM_8ug8eagAppearances_Desc = "새로운 모습을 추가합니다. AMM의 Nexus 페이지에서 다운로드하세요.",
	
	--Equipments (There is a Function Error(nil value) in this section, These are just labels that are not connected to any localizable strings in the file)
	Fists = "주먹", --Line 2377 
	Katana = "카타나",
	Mantis_Blades = "맨티스 블레이드",
	Machete = "마체테",
	Hammer = "망치",
	Baton = "배턴",
	Knife = "칼",
	Crowbar = "크로우바",
	Baseball_Bat = "야구배트",
	Assault_Rifle = "돌격소총",
	Sidewinder = "사이드와인더",
	Sniper_Rifle = "저격소총",
	Shotgun = "산탄총",
	SMG = "기관단총",
	Handgun = "권총", --Line 2391
	
	--Warning / Info / Tooltip
	Warn_CantSave_BlacklistedAppearance = "블랙리스트에 등록된 외모는 저장할 수 없습니다!",
	Warn_ConfirmDeleteSavedAppearances = "저장된 모든 모습을 삭제하시겠습니까?",
	Warn_ConfirmDeleteBlacklistedAppearances = "블랙리스트에 등록된 모든 출연을 삭제하시겠습니까?",
	Warn_ConfirmDeleteSavedDespawns = "저장된 모든 디스폰을 삭제하시겠습니까?",
	Warn_ConfirmDeleteAppearanceTriggers = "모든 출현 트리거를 삭제하시겠습니까?",
	Warn_ConfirmDeleteCurrentAppearance = "현재 활성 사전 설정을 삭제하시겠습니까?",
	Warn_WeaponizeNpcAnimationIssues = "모든 NPC가 모든 유형의 무기를 사용하는 데 필요한 애니메이션을 갖고 있는 것은 아닙니다. T 포즈 및 잘못된 애니메이션이 발생할 수 있습니다.\n정말로 활성화하시겠습니까?",
	Warn_ConfirmEnableExperimentalAndSave_Info = "실험적 기능을 활성화하시겠습니까? AMM이 예상대로 작동하지 않을 수 있습니다. 자신의 책임하에 사용하십시오!",
	Warn_DeleteFavoritesAskWhichOne_Info = "즐겨찾기를 모두 삭제하려면 아래에서 원하는 항목을 선택하세요.",
	Popup_Error_Title = "오류",
	Button_Ok = "알았어",
	Popup_FavoriteName = "좋아하는 이름",
	Popup_RenamePreset = "사전 설정 이름 바꾸기",
	Popup_RenameProp = "소품 이름 바꾸기",
	Editor_Title = "테마 편집기",
	Editor_Field_ThemeName = "테마 이름",
	Editor_Hint_InsertThemeName = "새 테마 이름 삽입",
	Error_ThemeNameExists = "테마 이름이 이미 존재합니다.",
}
