return {

    -- >> SCAN TAB
	BeginItem_TabNameScan = "Skanuj",
	
	--Button
	Button_CyclesAppearances = "Wygląd cyklu",
	Button_SavesAppearance = "Zapisz wygląd",
	Button_ClearSavedAppearance = "Wyczyść zapisany wygląd",
	Button_UnlockDoor = "Przełącz blokadę drzwi",
	Button_RestoreAccess = "Przywróć dostęp",
	Button_UnlockVehicle = "Odblokuj pojazd",
	Button_RepairVehicle = "Napraw pojazd",
	Button_OpenCloseDoors = "Otwórz/zamknij drzwi",
	Button_OpenCloseWindows = "Otwórz/zamknij okna",
	Button_ToggleEngine = "Przełącz silnik",
	Button_ToggleAIDriver = "Przełącz sterownik AI",
	Button_ToggleCamera = "Przełącz kamerę",
	Button_ToggleRadio = "Przełącz radio",
	Button_NextRadioStation = "Następna stacja radiowa",
	Button_TargetMountedVehicle = "Pojazd montowany na celu",
	Button_AssignSeats = "Przypisz miejsca",
	Button_Assign = "Przypisz",
	Button_Reset = "Zresetuj",
	Button_FakeDie = "Fałszywa śmierć",
	Button_SmallCopy = "Kopiuj",
	
    --Button Label
	Button_Label_Unfollower = "Przestań obserwować",
	Button_Label_Follower = "Obserwujący",
	Button_Label_SaveDespawn = "Uratuj Desspawna",
	Button_Label_ClearSavedDespawn = "Wyczyść zapisany Desspawn",
	Button_LabelLockTarget = "Zablokuj cel",
	Button_LabelUnlockTarget = "Odblokuj cel",
	Label_AddToSpawnFavs = "Dodaj do ulubionych, które można spawnować",
	Label_RemoveFromSpawnFavs = "Usuń z ulubionych, które można spawnować",
	
    --Checkbox
	Checkbox_SavedDespawnsActive = "Zapisane znikają aktywne",
	Checkbox_KeepAssigned = "Zachowaj przypisane przy zmianie samochodu",
	
    --Warning / Info / Tool Tip
	WarnTextAI_FastTravel = "Wybierz punkt szybkiej podróży na mapie, aby wyruszyć w podróż",
	WarnText_DontReloadMods = "Nie używaj opcji Wczytaj ponownie wszystkie mody.\nWczytaj ponownie zapisaną grę lub przejdź do innego obszaru.",
	Warning_NoTarget_Desc = "Brak celu! Aby rozpocząć, spójrz na NPC, pojazd lub obiekt",
	ToolTip_DisableCheckboxReloadSave_AbleTotargetClearSavedDespawns = "Wyłącz to pole wyboru i wczytaj ponownie swój zapis, aby móc celować w Wyczyść zapisane zniknięcia",
	
    --Text
	Build_Mode = "Tryb budowania",
	Speed = "Prędkość:",
	Search = "Szukaj",
	Clear = "Jasne",
	Player = "Gracz",
	Saved = "Zapisano",
	Saved_ = "Zapisano_",
	Current = "Aktualny",
	Current_ = "Aktualny",
	Select_Seat = "Wybierz Miejsce",
	Target_Info = "Informacje o celu",
	Target_Actions = "Działania docelowe",
	No_Appearances = "Żadnych występów",
	No_Target = "Brak celu",
	Favorite_Appearance = "Ulubiony wygląd",
	Unfavorite_Appearance = "Nieulubiony wygląd",
	Blacklist_Appearance = "Wygląd czarnej listy",
	Unblacklist_Appearance = "Usuń wygląd z czarnej listy",
	Saved_Appearance = "Zapisany wygląd:",
	Current_Appearance = "Obecny wygląd:",
	List_of_Appearances = "Lista występów",
	Appearance_Trigger = "Wyzwalacz wyglądu",
	None = "Żadne",
	Default = "Domyślne",
	Zone = "Strefa",
	Area = "Obszar",
	Position = "Pozycja",

	
	-- >> SPAWN TAB
	BeginItem_TabNameSpawn = "Spawnować",
	
	--Button
	Button_Refresh = "Odśwież",
	Button_Save = "Zapisz",
	Button_Confirm = "Potwierdź",
	Button_Cancel = "Anuluj",
	Button_SmallSave = "Zapisz",
	Button_SmallRespawn = "Odrodzenie",
	Button_SmallDespawn = "Zniknięcie",
	Button_SmallDespawn_WithSpace = "Zniknięcie",
	Button_SmallTarget = "Cel",
	Button_SmallEquipment = "Sprzęt",
	Button_LabelHostile = "Wrogi",
	Button_LabelFriendly = "Przyjazny",
	
    --Button Label
	Label_Favorite = "Ulubiony",
	Label_Unfavorite = "Nieulubiony",
	
    --Checkbox
    --Warning / Info / Tool Tip
	Warn_PlayerInMenu = "Gracz W Menu",
	Warn_AMMonlyfunctions_ingame = "AMM działa tylko w grze",
	Warn_SpawnWorksInGame = "Spawnowanie działa tylko w grze",
	Warn_InitError = "Błąd inicjalizacji",
	Warn_InitError_Info = "Aby uzyskać więcej informacji, sprawdź plik AppearanceMenuMod.log.",
	
    --Text
	Active_Spawns = "Aktywne spawnowanie",
	NoActiveSpawns = "Brak aktywnych spawnów",
	Select_To_Spawn = "Wybierz opcję Spawn",
	No_Results = "Brak wyników",
	ItsEmpty = "Jest pusty :(",
	Existing_Name = "Istniejąca nazwa",
	Name = "Imię",
	
	
	
	-- >> SWAP TAB
	BeginItem_TabNameSwap = "Zamień",
	
	--Button
	Button_SmallRevert = "Przywróć",
	
    --Button Label
    --Checkbox
    --Warning / Info / Tool Tip
	Warn_ReloadSaveUpdateChanges = "Załaduj ponownie zapisaną grę, aby zaktualizować zmiany!",
	Warn_NeedReloadSaveUpdateChanges = "Aby zaktualizować zmiany, konieczne będzie ponowne wczytanie zapisu.",
	Warn_ReplacerSwap = "Zamiennika nie można wymienić! Użyj zakładki narzędzi w trybie fotograficznym, aby namierzyć je, a następnie zmień ich wygląd z zakładki Spawn lub narzędzi docelowych.",
	Warning = "OSTRZEŻENIE",
	Warning2 = "OSTRZEŻENIE:",
	SaveSwap_Tooltip = "Zapisz swoje wymiany, aby zachować je po ponownym załadowaniu gry.",
	
    --Text
	CantSwapReplacer = "Nie można wymienić zamiennika",
	Active_Model_Swaps = "Aktywne zamiany modeli",
	Save = "Zapisz",
	Restore = "Przywróć",
	Current_Target = "Aktualny cel:",
	Target_ID = "Identyfikator celu:",
	SelectSwap_CurrentTarget = "Wybierz, aby zamienić z bieżącym celem:",
	NoNPC_LookNPC = "Nie znaleziono NPC! Na początek spójrz na NPC",
	
	-- Locations Categories
	Residences = "Rezydencje",
	ArasakaAndCorpo = "Arasaka i Corpo",
	ClubsAndBars = "Kluby i bary",
	HotelsAndPleasure = "Hotele i rozrywka",
	UndergroundAndCrime = "Podziemie i przestępczość",
	GovernmentAndSecurity = "Rząd i bezpieczeństwo",
	StoryAndUnique = "Historia i wyjątkowa",
	Ripperdocs = "Ripperdocs",
	LandmarksAndOpenWorld = "Zabytki i otwarty świat",
	SpoilersAndHidden = "Spoilery i ukryte",
	UserLocations = "Lokalizacje użytkowników",
	
	
	-- >> DECOR TAB
	BeginItem_TabDecor = "Wystrój",
	BeginItem_TabPresets = "Ustawienia wstępne",
	Begin_ComboPresets = "Ustawienia wstępne",
	
	--Button
	Button_SmallClone = "Klon",
	Button_SmallRemove = "Usuń##",
	Button_SmallRename = "Zmień nazwę##",
	Button_SmallUpdate = "Aktualizacja##",
	Button_SmallCancel = "Anuluj",
	Button_Frame = "Rama",
	
    --Button Label
	Button_LabelHide = "Ukryj",
	Button_LabelUnhide = "Odkryj",
	
    --Checkbox
    --Warning / Info / Tool Tip
	Warn_PersistPropSave = "Rekwizyty do spawnowania, które udekorują Twój dom lub gdziekolwiek chcesz, według własnego uznania! Zapisz rekwizyty, aby je zachować!",
	Warn_DespawnInProgress_PleaseWait = "Despawn w toku. Proszę czekać.",
	Warn_PresetsFolder_Info = "Ustawienia użytkownika są zapisywane w folderze AppearanceMenuMod/User/Decor",
	Warn_CustomPresets_Info = "To ustawienie wstępne zawiera niestandardowe rekwizyty",
	Warn_CustomPropsModders_Info = "Niestandardowe rekwizyty wykonane przez:",
	Warn_GamepadDirectMode_Info = "Umożliwia to lepszą integrację z trybem Direct podczas korzystania z gamepada. Umożliwia także wyświetlanie małego okna informacyjnego, które będzie się trzymać.",
	Warn_PresetTriggerDistanceFar = "Ustawienie opcji Daleko może powodować problemy z wydajnością.",
	
    --Text
	MovingAll_PropsTo_SavedProps = "Przenoszenie wszystkich rekwizytów do zapisanych rekwizytów",
	SelectPropSpawn = "Wybierz rekwizyt do odrodzenia:",
	Spawned_Props = "Zrodzone rekwizyty",
	New_Preset = "Nowe ustawienie wstępne",
	No_Preset_Available = "Brak dostępnych ustawień wstępnych",
	Preset_TriggerDistance = "Zaprogramowana odległość wyzwalania",
	MovingSavedProps = "Przenoszę %s do zapisanych rekwizytów",
	UpdateTag = "Aktualizuj tag",
	Categories = "Kategorie",
	Decorating = "Dekorowanie",
	Decor_Tabs = "Zakładki dekoracyjne",
	Saved_Props = "Zapisane rekwizyty",
	Show_Nearby_Only = "Pokaż tylko w pobliżu",
	Show_Lights_Only = "Pokaż tylko światła",
	Show_LockedTarget_Only = "Pokaż tylko zablokowany cel",
	Show_Customizable_Only = "Pokaż tylko konfigurowalne",
	Show_CustomProps_Only = "Pokaż tylko niestandardowe rekwizyty",
	ShowOnMap = "Pokaż na mapie",
	Rename = "Zmień nazwę",
	Delete = "Usuń",
	Backup = "Kopia zapasowa",
	Merge = "Połącz",
	Save_All = "Zapisz wszystko",
	Despawn_All = "Zniszcz wszystko",
	Save_ToSpecific_Tag = "Zapisz w określonym tagu",
	Saved_Props2 = "Zapisane rekwizyty:",
	Move_To_Tag = "Przenieś do tagu",
	HideFromMap = "Ukryj na mapie",
	RemovingAllPropsFromTag = "Usuwanie wszystkich rekwizytów z tagu...",
	RemoveAllProps = "Usuń wszystkie rekwizyty",
	RemoveHomeMarkerMap = "Usuń znacznik domu z mapy",
	TeleportToLocation = "Teleportuj się do lokalizacji",
	TeleportToTrigger = "Teleportacja do wyzwalacza",
	TeleportToMark = "Teleportuj się do Marka",
	UpdateTagLocation = "Zaktualizuj lokalizację znacznika",
	SharePresetWith_ThisTagOnly = "Udostępnij ustawienie wstępne tylko za pomocą tego tagu",
	SavedPresetFolder_Info = "Zapisano ustawienie wstępne w folderze AppearanceMenuMod/User/Decor",
	NoProps_WithThese_Conditions = "Żadnych rekwizytów w tych warunkach",
	AddHomeMarkerMap = "Dodaj znacznik domu do mapy",
	Distance = "Odległość",
	Total_Props = "Razem rekwizyty:",
	Type_Tag_here = "Wpisz tutaj Tag",
	In_World = "W świecie",
	Tags = "Tagi",
	Tag = "Oznacz",
	Both = "Obydwa",	
	
	-- >> POSES TAB
	BeginItem_TabPoses = "Pozy",
	
	--Button
	Button_SmallCopyClipboard = "Skopiuj do schowka",
	
    --Button Label
    --Checkbox
    --Warning / Info / Tool Tip
    --Text
	Active_Animations = "Aktywne animacje",
	ShowHistory = "Pokaż historię",
	ClearHistory = "Wyczyść historię",
	SelectPoseForCurrentTarget = "Wybierz pozę dla bieżącego celu:",
	LastUsedPoses = "Ostatnio używane pozy",
	
	
	
	-- >> TOOLS TAB
	BeginItem_TabTools = "Narzędzia",
	BeginItem_TabPhotoModeNibblesReplacer = "Zamiennik przekąsek w trybie fotograficznym",
	BeginCombo_LookAt = "Spójrz",
	BeginCombo_WeatherControl = "Kontrola pogody",
	
	--Button
	Button_SkipFrame = "Pomiń ramkę",
	Button_ToggleLight = "Przełącz światło",
	Button_ResetScale = "Zresetuj skalę",
	Button_ShowAsLookAtTarget = "Pokaż jako spojrzenie na cel",
	Button_ResetLookAtTarget = "Zresetuj spojrzenie na cel",
	Button_TogglePrimaryWeapon = "Wyposaż się w broń główną",
	Button_ToggleSecondaryWeapon = "Wyposaż się w broń dodatkową",
	Button_GiveCurrentEquippedWeapon = "Podaj aktualnie wyposażoną broń",
	Button_SmallReset = "Zresetuj",
	Button_ResetToPlayer = "Zresetuj do odtwarzacza",
	Button_ClearSaved = "Wyczyść Zapisane",
	Button_Cyberpsycho = "Przełącz Cyberpsycho",
	Button_ProtectNPCfromActions = "Chroń NPC przed akcjami",
	Button_AllFriendly = "Wszystko Przyjazne",
	Button_AllHostile = "Wszyscy wrodzy",
	Button_AllFollower = "Wszyscy obserwujący",
	Button_AllFakeDie = "Wszystko fałszywe",
	Button_AllDie = "Wszyscy umierają",
	Button_AllDespawn = "Cały Desspawn",
	Button_InvMachineGun = "Karabin Maszynowy",
	Button_InvSpeed2 = "Prędkość",
	Button_ToggleMakeup = "Przełącz makijaż",
	Button_TogglePiercings = "Przełącz piercing",
	Button_ToggleSeamfix = "Przełącz Seamfix",
        Button_TargetV = "Cel V",
        Button_Target = "Cel",
        Button_TeleportToLocation = "Teleportuj się do lokalizacji",
        Button_TeleportToTrigger = "Teleportacja do wyzwalacza",
        Button_TeleportToMark = "Teleportuj się do Marka",
        Button_RandomLocation = "Losowe",
        Button_ShareCurrentLocation = "Udostępnij bieżącą lokalizację",
	Button_GoBackToLastLocation = "Wróć do ostatniej lokalizacji",
	Button_DeleteSelectedUserLocation = "Usuń wybraną lokalizację użytkownika",
	
	--Slider / Drag 
	Slider_HeadStiffness = "Sztywność głowy",
	Slider_HeadPoseOverride = "Zmiana pozycji głowy",
	Slider_ChestStiffness = "Sztywność klatki piersiowej",
	Slider_ChestPoseOverride = "Zmiana pozycji klatki piersiowej",
	Slider_SlowMotion = "Powolny ruch",
	Slider_DefaultAperture = "Domyślna przysłona",
	Slider_DefaultFieldofView = "Domyślne pole widzenia",
	Slider_MovementSpeed = "Szybkość ruchu",
	Drag_MovementSpeed = "Szybkość ruchu",
	
    --Button Label
	Button_Label_PauseTimeProgression = "Wstrzymaj postęp czasu",
	Button_Label_UnpauseTimeProgression = "Wstrzymaj postęp czasu",
	Button_Label_UnfreezeTime = "Odblokuj czas",
	Button_Label_FreezeTime = "Zamrożenie czasu",
	Button_Label_OpenLightSettings = "Otwórz Ustawienia światła",
	Button_Label_UpdateLightTarget = "Zaktualizuj cel świetlny",
	Button_Label_Activate = "Aktywuj",
	Button_Label_Deactivate = "Dezaktywuj",
	Button_Label_ChangeToCrouchStance = "Zmień pozycję na kucającą",
	Button_Label_ChangeToStandStance = "Zmień postawę na stojącą",
	Button_Label_PickUpTarget = "Podnieś cel",
	Button_Label_DropTarget = "Upuść cel",
	Button_Label_FreezeTarget = "Zamroź cel",
	Button_Label_UnfreezeTarget = "Odblokuj cel",
	Button_Label_OpenTargetTools = "Otwórz Narzędzia docelowe",
	Button_Label_CloseTargetTools = "Zamknij narzędzia docelowe",
	
    --Checkbox
    --Warning / Info / Tool Tip
	Warn_FileNotFound_CollabsFolder_Error = "Nie znaleziono pliku w folderze Collabs",
	Warn_ShowXYZ_Orientation_Info = "Pokaż strzałki X, Y i Z, aby ułatwić orientację podczas przesuwania celu.",
	Warn_LookAtCamera_OptionOff_Info = "Po zmianie tego ustawienia wyłącz raz opcję Spójrz na kamerę",
	Warn_DisableLookAtCamera_PhotoMode_Info = "Aby zastosować tę funkcję, wyłącz raz funkcję „Spójrz na aparat” w trybie fotograficznym",
	Warn_RequiresRestart_Info = "Wymaga ponownego uruchomienia gry, aby zadziałało",
	Warn_SlowMotion_PhotoMode_Info = "Zwolnione tempo w trybie fotograficznym działa tylko po wznowieniu pauzy przy użyciu IGCS",
	Warn_WeatherControl_RequireCodeware = "Kontrola pogody wymaga oprogramowania Codeware 1.4+",
	Warn_StopNpc_UnequipWeapon_Info = "Powstrzyma to NPC od zdjęcia danej broni. Uwaga: NPC nadal będzie mógł zdejmować wyposażenie podczas walki.",
	Warn_OutOfCombat_NpcUnequip_Info = "Uwaga: Poza walką NPC natychmiast zdejmie daną broń.",
	Warn_Photomode_UnfreezeSkipFrames_Info = "W trybie fotograficznym Unfreeze Target pomija klatki w animowanych pozach. Aby móc w pełni (od)zamrażać, należy użyć oprogramowania Otis Camera Tools (IGCS).",
	Warn_UserLocationsFolder_Info = "Lokalizacje użytkowników są zapisywane w folderze AppearanceMenuMod/User/Locations",
	Warn_SeeMoreAction_Info = "Wybierz V lub NPC, aby zobaczyć więcej akcji",
	Warn_SeeMoreActionProp_Info = "Wybierz NPC lub rekwizyt, aby zobaczyć więcej akcji",
	Warn_SeamfixPiercingToggle_Info = "Spowoduje to zapisanie stanu przełączania makijażu, piercingu i Seamfix do czasu zamknięcia gry.",
	Warn_PassiveMode_Info = "Wrogowie nadal będą cię atakować, jeśli rozpoczniesz walkę",
	Warn_TppCameraGameplay_Info = "Kamera TPP nie nadaje się do zwykłej rozgrywki, ale na spacer jest fajna ;)",
	Warn_AnimatedHead_PhotoMode_Info = "Wyrażenia w trybie fotograficznym nie będą działać, gdy włączona jest funkcja Animowana głowa.",
	Warn_ToolsOnly_WorksIngame = "Narzędzia działają tylko w grze",
	Warn_InvButtonMachineGun_Info = "Znalazłeś to! Do wyposażenia dodano ciężki karabin maszynowy.",
	Warn_InvButton_Info = "Znalazłeś to! Szybki ruch jest już dostępny.",
	InvButtonTip = "A co jeśli kliknę tutaj?",
	InvButtonTip2 = "Kliknięcie tutaj nic nie daje!",
	InvButtonTip3 = "NIE KLIKAJ, ZOSTAŁEŚ OSTRZEŻONY!",
	
    --Text
	Facial_Expression = "Wyraz twarzy",
	Expressions = "Wyrażenia",
	Look_At = "Spójrz",
	Look_At_Camera = "Spójrz na kamerę:",
	Target_Tools = "Narzędzia docelowe",
	Rotation = "Obrót",
	Tilt_Rotation = "Pochylenie/obrót",
	Mode = "Tryb:",
	Precision = "Precyzja",
	Relative = "Względny",
	Direct = "Bezpośrednie",
	AdvMovement = "Adw. Ruch",
	ForceGivenWeapon = "Broń nadana siłą",
	Scale = "Skala",
	ProportionalMode = "Tryb proporcjonalny",
	General_Actions = "Działania ogólne",
	DisablePassiveMode = "Wyłącz tryb pasywny",
	EnablePassiveMode = "Włącz tryb pasywny",
	EnableGodMode = "Włącz tryb Boga",
	DisableGodMode = "Wyłącz tryb Boga",
	Infinite_Oxygen = "Nieskończony tlen",
	Select_Location = "Wybierz opcję Lokalizacja",
	Select_Expression = "Wybierz Wyrażenie",
	Select_Category = "Wybierz kategorię",
	Teleport_Actions = "Akcje teleportacji",
	Use_Teleport_Animation = "Użyj animacji teleportacji",
        Filter_Locations = "Filtruj lokalizacje",
        Locations = "Lokalizacje",
        Default_Locations = "Domyślne lokalizacje",
        Collab_Locations = "Lokalizacje współpracy",
        Button_AddTag = "Dodaj znacznik",
	Button_FilterByTags = "Filtruj według tagów",
	Button_Close = "Zamknij",
	Favorite_Selected_Location = "Ulubiona wybrana lokalizacja",
	Unfavorite_Selected_Location = "Usuń z ulubionych wybraną lokalizację",
	Edit_Selected_Location = "Edytuj wybraną lokalizację",
	Locations_Favorites = "--------- Ulubione ---------------",
	Locations_UserLocs = "-------- Lokalizacje użytkowników --------",
	Locations_DefaultLocs = "----------- Domyślne ----------",
	Share_Location = "Udostępnij lokalizację",
	Edit_Location = "Edytuj lokalizację",
	TimeWeather_Actions = "Działania związane z czasem i pogodą",
	TimeofDay = "Pora dnia",
	Time_Actions = "Działania czasowe",
	Rain = "Deszcz",
	Light_Rain = "Lekki deszcz",
	Cloudy = "Pochmurno",
	Fog = "Mgła",
	Heavy_Clouds = "Ciężkie chmury",
	Light_Clouds = "Lekkie chmury",
	Pollution = "Zanieczyszczenie",
	Sandstorm = "Burza Piaskowa",
	Sunny = "Słoneczny",
	Toxic_Rain = "Toksyczny deszcz",
	Deep_Blue = "Głęboki błękit",
	Squat_Morning = "Przysiadowy poranek",
	Cloudy_Morning = "Pochmurny poranek",
	Rainy_Night = "Deszczowa noc",
	Courier_Clouds = "Chmury Kurierskie",
	Cursor_LockState = "Stan blokady",
	PhotoMode_NibblesReplacer = "Zamiennik przekąsek w trybie fotograficznym",
	PhotoModeEnhancements = "Ulepszenia trybu fotograficznego",
	Button_ResetReplacerDatabase = "Zresetuj bazę danych zamienników",
	DisablePhotoModeCursor = "Wyłącz kursor trybu fotograficznego",
	TPPCamera_Position = "Pozycja kamery TPP",
	AnimatedHeadin_PhotoMode = "Animowana głowa w trybie fotograficznym",
	LockLook_AtCamera = "Zablokuj spojrzenie na kamerę",
	UnlockLook_AtCamera = "Odblokuj Spójrz na kamerę",
	Save_Toggles_State = "Zapisz Przełącza stan",
	Toggle_V_Head = "Przełącz głowicę V",
	Toggle_TPP_Camera = "Przełącz kamerę TPP",
	Target_Nibbles = "Celuj w Nibbles",
	Target_Replacer = "Zamiennik celu",
	Left = "Lewy",
	Left_Close = "Lewy Zamknij",
	Right = "Jasne",
	Right_Close = "Zaraz blisko",
	Center_Close = "Centrum blisko",
	Center_Far = "Centrum Daleko",
	Front_Close = "Zamknięcie z przodu",
	Front_Far = "Przód Daleko",
	All = "Wszystko",
	Head_Only = "Tylko głowa",
	Eyes_Only = "Tylko oczy",
	Movement = "Ruch",
	V_Actions = "Działania V",
	Invisible_V = "Niewidzialny W",
	LikeGTA_byGTATravel = "przez GTA Travel",
	EnableSpawnedProps = "Włącz generowane rekwizyty",
	LightControl = "Kontrola światła",
	Equipment = "Sprzęt",
	
	-- >> DIRECTOR TAB
	BeginItem_TabNameDirector = "Dyrektor",
	BeginItem_TabNameTriggers = "Wyzwalacze",
	BeginCombo_StartAppearance = "Rozpocznij wygląd",
	BeginCombo_EndAppearance = "Wygląd końcowy",
	BeginCombo_Type = "Wpisz",
	BeginCombo_GoToTarget = "Idź do celu",
	BeginCombo_PlayVoice = "Odtwórz głos",
	BeginCombo_Attack = "Atak",
	BeginCombo_Triggers = "Wyzwalacze",
	BeginCombo_Scripts = "Skrypty",
	
	--Button
	Button_Yes = "Tak",
	Button_No = "Nie",
	Button_SaveChangesOnly = "Zapisz tylko zmiany",
	Button_RemoveMark = "Usuń Marka",
	Button_EditMark = "Edytuj Marka",
        Button_MoveMark = "Przesuń Marka",
        Button_MoveUp = "Przesuń w górę",
        Button_MoveDown = "Przesuń w dół",
        Button_NewMark = "Nowy Marek",
	Button_AddActor = "Dodaj aktora",
	Button_RemoveActor = "Usuń aktora",
	Button_ChangeActor = "Zmień aktora",
	Button_RadioOnlyOne = "Tylko Jeden",
	Button_RadioRandom = "Losowe",
	Button_RadioSequential = "Sekwencyjny",
	Button_SaveTrigger = "Zapisz wyzwalacz",
	Button_NewCamera = "Nowy aparat",
	Button_NewScript = "Nowy skrypt",
	Button_DragSpeed = "Prędkość",
	Button_ToggleMarker = "Przełącz znacznik",
	Button_TestPose = "Pozycja testowa",
	Button_StopPose = "Zatrzymaj pozycję",
	
    --Button Label
	Button_Label_PlayScript = "Zagraj w skrypt",
	Button_Label_StopScript = "Zatrzymaj skrypt",
	Button_Label_Stopping = "Zatrzymywanie...",
	Button_Label_Restarting = "Ponowne uruchamianie...",
	Button_Label_AddMark = "Dodaj Marka",
	Button_Label_SaveWNewPos = "Zapisz z nową pozycją",
	
    --Checkbox
    --Warning / Info / Tool Tip
	Warn_ActorSingleMark_Info = "Aktor pozostanie przy jednym Marku",
	Warn_ActorRandomMark_Info = "Aktor będzie losowo przemieszczał się pomiędzy Znakami",
	Warn_ActorSequentialMark_Info = "Aktor będzie poruszał się pomiędzy Znakami w kolejności numerycznej",
	Warn_DeleteScript_Info = "Czy na pewno chcesz usunąć ten skrypt?",
	Warn_CloseCamForMove_Info = "Zamknij menu, aby móc poruszać kamerą",
	Warn_CreateScriptsDesc_Info = "Twórz skrypty, aby dodawać, ubierać i kierować aktorami do występów w Machinima, zrzutach ekranu i odgrywaniu ról.",
	Warn_PremadeScriptsDesc_Info = "Utwórz wyzwalacze, aby aktywować gotowe skrypty podczas kontaktu.",
	Warn_CreateCamera_FovZoomDesc_Info = "Twórz kamery, aby swobodnie się poruszać, ustawiaj różne pola widzenia i poziomy powiększenia.",
	Warn_ShowMarksLocations_Info = "Wyświetla widoczną ikonę w miejscach zaznaczenia",
	Warn_AutoTalkNpc_Info = "Spowoduje to, że NPC będą rozmawiać raz na minutę, gdy znajdą się w zasięgu (tylko dźwięczni NPC)",
	Warn_DirectActorPlayerPosition_Info = "Utwórz Znak na bieżącej pozycji Gracza, aby poruszać i kierować Aktorami",
	Warn_InMenuDirectorDesc = "Dyrektor działa tylko w grze",
	
    --Text
	DirectorMode = "Tryb reżyserski",
	SelectActorToReplace = "Wybierz aktora do zastąpienia:",
	AddActorToCurrentScript = "Dodaj aktora do bieżącego scenariusza:",
	FacialExpression_WithColon = "Wyraz twarzy:",
	FavoritePoses_WithColon = "Ulubione pozy:",
	AddFavorites_Desc = "Najpierw dodaj pozy do ulubionych w zakładce pozy",
	HoldDuration = "Przytrzymaj czas trwania",
	Movement2 = "Ruch:",
	Actions = "Działania:",
	Actors = "Aktorzy",
	Editing = "Edytowanie",
	AutoTalk = "Automatyczna rozmowa",
	ActorMarks = "Aktor Marek",
	Current_Actors = "Obecni aktorzy",
	Marks_Sequence = "Sekwencja znaków:",	
	ShowMarks = "Pokaż znaki",
	Triggers = "Wyzwalacze",
	NewTrigger = "Nowy wyzwalacz",
	ShowTrigger = "Pokaż wyzwalacz",
	Title = "Tytuł",
	Select_Trigger = "Wybierz opcję Wyzwalacz",
	Select_Script = "Wybierz Skrypt",
	Delete_Trigger = "Usuń wyzwalacz",
	Triggers_On_Off = "Wyzwala wł./wył",
	Running = "Bieganie",
	Script_Running = "Uruchamianie skryptu...",
	Delete_Script = "Usuń skrypt",
	RepeatInLoop = "Powtórz w pętli",
	ActivationRadius = "Promień aktywacji",
	Activate = "Aktywuj",
	Deactivate = "Dezaktywuj",
	FOV = "Pole widzenia",
	Zoom = "Powiększ",
	LockFrame = "Zablokuj ramkę",
	Walk = "Spacer",
	Sprint = "Sprint",
	Sequential = "Sekwencyjny",
	Cameras = "Kamery",
	NodeView = "Widok węzła",
	TeamA = "Zespół A",
	TeamB = "Zespół B",
	
	
	
	-- >> SETTINGS TAB
	BeginItem_TabNameSettings = "Ustawienia",
	BeginItem_TabNameGeneral = "Generał",
	BeginItem_TabNameCompanions = "Towarzysze",
	BeginItem_TabNameUI = "Interfejs użytkownika",
	BeginItem_TabNameExperimental = "Eksperymentalny",
	BeginItem_TabNamePhotoMode = "Tryb fotograficzny",
	
	--Button
	Button_RevertAllModelSwaps = "Cofnij wszystkie zamiany modeli",
	Button_RespawnAll = "Odrodzić wszystkich",
	Button_ForceDespawnAll = "Wymuś zniszczenie wszystkich",
	Button_ClearFavorites = "Wyczyść ulubione",
	Button_ClearAllSavedAppearances = "Wyczyść wszystkie zapisane wyglądy",
	Button_ClearAllBlacklistedAppearances = "Usuń wszystkie występy z czarnej listy",
	Button_ClearAllAppearanceTriggers = "Wyczyść wszystkie wyzwalacze wyglądu",
	Button_ClearAllSavedDespawns = "Wyczyść wszystkie zapisane zniknięcia",
	Button_SmallCreateTheme = "Utwórz motyw",
	Button_SmallDeleteTheme = "Usuń motyw",
	Button_SmallSet = "Zestaw",
	Button_ReloadAppearances = "Załaduj ponownie wyglądy niestandardowe",
	
    --Button Label
    --Checkbox
	Checkbox_SpawnAsCompanion = "Spawnuj się jako towarzysz",
	Checkbox_SpawnAsFriendly = "Spawnuj jako przyjazny",
	Checkbox_InvulnerableCompanion = "Niezniszczalny towarzysz",
	Checkbox_RespawnOnLaunch = "Odrodzenie po uruchomieniu",
	Checkbox_LockTargetAfterSpawn = "Zablokuj cel po odrodzeniu",
	Checkbox_OpenTargetToolsAfterSpawn = "Otwórz narzędzia docelowe po odrodzeniu",
	Checkbox_DisplayAxisIndicatorByDefault = "Domyślnie wyświetlaj wskaźnik osi",
	Checkbox_PhotoModeEnhancements = "Ulepszenia trybu fotograficznego",
	Checkbox_GodModeOnLaunch = "Tryb Boga po uruchomieniu",
	Checkbox_PassiveModeOnLaunch = "Tryb pasywny po uruchomieniu",
	Checkbox_StreamerMode = "Tryb streamera",
	Checkbox_OpenWCETOverlay = "Otwórz z nakładką CET",
	Checkbox_AutoResizingWindow = "Okno automatycznej zmiany rozmiaru",
	Checkbox_ScanningReticle = "Siatka skanująca",
	Checkbox_FloatingTargetTools = "Narzędzia pływającego celu",
	Checkbox_TabHeaderDescriptions = "Opisy nagłówków zakładek",
	Checkbox_ExpandFavoritesByDefault = "Domyślnie rozwiń Ulubione",
	Checkbox_EnableScrollBars = "Włącz paski przewijania",
	Checkbox_AlwaysDisablePhotoModeCursor = "Zawsze wyłączaj kursor trybu fotograficznego",
	Checkbox_Camera = "Kamera",
	Checkbox_DepthOfField = "DOF",
	Checkbox_Effect = "Efekt",
	Checkbox_Stickers = "Naklejki",
	Checkbox_LoadSave = "Załaduj/Zapisz",
	Checkbox_ExperimentalFunstuff = "Rzeczy eksperymentalne/zabawne",
	Checkbox_EnableFreezeTargetInPhotoMode = "Włącz opcję Zamroź cel w trybie fotograficznym",
	Checkbox_WeaponizeCompanions = "Uzbrojenie towarzyszy",
	Checkbox_AllowPlayerToBeTargetedinPosestab = "Zezwalaj na celowanie w gracza w zakładce Pozy",
	Checkbox_AllowPlayerAnimationsonNPCs = "Zezwalaj na animacje graczy u NPC",
	Checkbox_AllowExpressionOnNpcPM = "Zezwalaj na wyrażenia i przyglądaj się NPC-om w trybie fotograficznym",
        Checkbox_ResetTargetPositionPM = "Zresetuj pozycję docelową dla NPC w trybie fotograficznym",
        Checkbox_EnableRandomLocation = "Włącz przycisk Losowy: teleportuj gracza do losowej lokalizacji z listy",
        Checkbox_RestoreOnLaunch = "Przywróć po uruchomieniu",
        Radio_PrimarySlot = "Gniazdo podstawowe",
        Radio_SecondarySlot = "Dodatkowe gniazdo",
	
    --Warning / Info / Tool Tip
	Warn_RespawnOnLaunch_Info = "To ustawienie włącza/wyłącza odradzanie wcześniej zapisanych NPCów podczas ładowania gry. AMM automatycznie zapisuje odrodzonych NPC po wyjściu z gry.",
	Warn_BannedWords_Info = "To ustawienie włącza/wyłącza pojawianie się NPCów zawierających słowa: naked, nude, xxx, shower, Birthday_suit, pp i penis.",
	Warn_TargetNpcVehicleHotkey = "Wybierz NPC lub pojazd, aby ustawić klawisze skrótu",
	Warn_FirstLaunchDecideTabsExpand_Info = "To ustawienie domyślnie rozwinie Ulubione w zakładkach Odradzanie, Zamiana i Wystrój, gdy AMM zostanie uruchomione po raz pierwszy.",
	Warn_ExperimentalTabDesc_Info = "Funkcje eksperymentalne dodają więcej funkcjonalności, ale mogą nie działać tak dobrze, stąd etykieta eksperymentalna. W rzeczywistości większość użytkowników AMM ma włączone funkcje eksperymentalne. Więc nie martw się zbytnio i baw się dobrze!",
	Warn_FreezeTargetPhotoMode_Info = "To ustawienie ma na celu pomóc w zamrożeniu animacji z modów, które dodają niestandardową animację do póz w trybie fotograficznym lub gdy wznawiasz pauzę przy użyciu IGCS.",
	Warn_WeaponizeCompanions_Info = "To da broń i zdolności bojowe wszystkim NPC-om. Oczekiwane są pozy T i dziwne animacje.",
	Warn_PlayerAnimsOnNpc_Info = "Włącz tę opcję, jeśli używasz moda, który pozwala na używanie animacji gracza na NPC-ach.",
	Warn_UnpauseRequiresIGSC = "To ustawienie wymaga, aby IGCS wstrzymywał czas.",
	Warn_NotInstalled = "NIE ZAINSTALOWANE",
	Warn_DespawnAllProps = "Czy na pewno chcesz usunąć wszystkie rekwizyty?",
	
    --Text
	AMM_Version = "Wersja AMM:",
	CET_Version = "Wersja CET:",
	Codeware_Version = "Wersja oprogramowania:",
	Game_Version = "Wersja gry:",
	Companion_Damage = "Obrażenia Towarzysza:",
	Companion_Resistance = "Odporność towarzysza:",
	Companion_Distance = "Odległość towarzysza:",
	xDamage = "x Uszkodzenie",
	xResistance = "x Opór",
	SavedAppearancesHotkeys = "Skróty klawiszowe zapisanych wyglądów",
	Favorites = "Ulubione",
	Appearances = "Występy",
	Blacklist = "Czarna lista",
	AppearanceTriggers = "Wyzwalacze wyglądu",
	SavedDespawns = "Uratowano Desspawn",
	Interface_Language = "Język interfejsu:",
	Custom_Appearances = "Wyglądy niestandardowe",
	PhotoModeAdjustments = "Regulacja trybu fotograficznego:",
	DisablePhotoModeTabs = "Wyłącz karty trybu fotograficznego:",
	List_Height = "Wysokość listy",
	Listbox_Themes = "Motywy",
	Weaponize = "Zbroić",
	NoAppearanceSet = "Brak zestawu wyglądu",
	
	
	
	-- >> EXTRA	
	--Texts, warns, tips, info's, buttons and labels etc.
	Seat_FrontRight = "Przód, prawy",
	Seat_BackRight = "Powrót w prawo",
	Seat_FrontLeft = "Lewy przód",
	Seat_BackLeft = "Powrót w lewo",
	Label_Door = "Drzwi",
	Label_Window = "Okno",

	Close = "Zamknij",
	Far = "Daleko",
	Moderate = "Umiarkowane",
	
	-- >> Archives Screen
	Warning_MissingRequiredArchives = "W AMM brakuje jednego lub więcej wymaganych archiwów. Zainstaluj brakujące wymagane archiwum w folderze Archive/pc/mod.",
	Warning_MissingOptionalArchives = "W AMM brakuje jednego lub więcej archiwów. Są one opcjonalne, ale dodają funkcjonalność do AMM. Możesz zignorować te ostrzeżenia, ale AMM może nie działać poprawnie.",
	
	
	-->> INIT.LUA
	AMMNeedsAttention = "AMM wymaga uwagi",
	MISSING_ARCHIVES = "BRAKUJĄCE ARCHIWUM",
	VERSION_INFORMATION = "INFORMACJE O WERSJI",
	CREDITS = "KREDYTY",
	UPDATE_HISTORY = "AKTUALIZUJ HISTORIĘ",
	Updates = "Aktualizacje",
	MISSING = "BRAK",
	REQUIRED = "WYMAGANE",
	OPTIONAL = "OPCJONALNIE",
	WHATS_NEW = "CO NOWEGO", --Line 83 Function Error

	--Button
	Button_Ignorewarningsforthisversion = "Zignoruj ostrzeżenia dotyczące tej wersji",
	Button_Credits = "Kredyty",
	Button_Cool = "Super!",

	--Button Label
	Label_SpawnFavorites = "Spawnuj ulubione",
	Label_SwapFavorites = "Zamień ulubione",
	Label_FavoriteAppearances = "Ulubione występy",
	Label_Cancel = "Anuluj",

	--Text
	Hotkey_i = "Klawisz skrótu %i",

	--Node - Function Error(nil value) 
	Top = "Góra", --Line 116
	Bottom = "Dół",
	Off = "Wyłączone",
	
	--Voice Overs
	Label_GreetV = "Powitaj V",
	Label_FearFoll = "Strach Foll",
	Label_FearToll = "Strach Toll",
	Label_FearBeg = "Strach błagać",
	Label_FearRun = "Bieg strachu",
	Label_StealthSearch = "Ukryte wyszukiwanie",
	Label_StealthDeath = "Ukryta śmierć",
	Label_StealthRestore = "Ukryte przywracanie",
	Label_StealthEnd = "Koniec ukrycia",
	Label_CuriousGrunt = "Ciekawy Grunt",
	Label_GrappleGrunt = "Chwytak Chrząknięcie",
	Label_Bump = "Uderzenie",
	Label_VehicleBump = "Zderzenie pojazdu",
	Label_TurretWarning = "Ostrzeżenie dotyczące wieży",
	Label_OctantWarning = "Ostrzeżenie oktanowe",
	Label_DroneWarning = "Ostrzeżenie dotyczące dronów",
	Label_MechWarning = "Mech, ostrzeżenie",
	Label_EliteWarning = "Elitarne ostrzeżenie",
	Label_CameraWarning = "Ostrzeżenie o kamerze",
	Label_EnemyWarning = "Ostrzeżenie wroga",
	Label_HeavyWarning = "Ciężkie ostrzeżenie",
	Label_SniperWarning = "Ostrzeżenie snajperskie",
	Label_AnyDamage = "Wszelkie uszkodzenia",
	Label_Danger = "Niebezpieczeństwo",
	Label_CombatStart = "Rozpoczęcie walki",
	Label_CombatEnd = "Koniec walki",
	Label_CombatTargetHit = "Trafienie w cel bojowy",
	Label_PedestrianHit = "Potrącenie pieszego",
	Label_LightHit = "Lekkie uderzenie",
	Label_Curse = "Klątwa",
	Label_Irritated = "Zirytowany",
	Label_GrenadeThrow = "Rzut granatem",
	Label_Gotakill = "Mam zabójstwo!",
	
	--Expressions
	Neutral = "Neutralny",
	Joy = "Radość",
	Smile = "Uśmiechnij się",
	Sad = "Smutny",
	Surprise = "Niespodzianka",
	Aggressive = "Agresywny",
	Anger = "Gniew",
	Interested = "Zainteresowany",
	Disinterested = "Bezinteresowny",
	Disappointed = "Rozczarowany",
	Disgust = "Wstręt",
	Exertion = "Wysiłek",
	Nervous = "Nerwowy",
	Fear = "Strach",
	Terrified = "Przerażony",
	Pain = "Ból",
	Sleepy = "Śpiący",
	Unconscious = "Nieprzytomny",
	Dead = "Martwy",

	-- Extra Expressions
	Frown = "Zmarszcz brwi",
	Shocked = "Zszokowany",
	Annoyed_2 = "Zirytowany 2",
	Contempt = "Pogarda",
	Irritated = "Zirytowany",
	Sceptical_1 = "Sceptyczny 1",
	Sceptical_2 = "Sceptyczny 2",
	Annoyed_1 = "Zirytowany 1",
	Offended = "Obrażony",
	Disgusted = "Zniesmaczony",
	Disappointed_2 = "Rozczarowany 2",
	Alert = "Alarm",
	Crying = "Płacz",
	Embarrassed = "Zawstydzony",
	Humiliated = "Upokorzony",
	Impatient = "Niecierpliwy",
	Anguished = "Udręczony",
	Worried = "Zmartwiony",
	Guilty = "Winny",
	Grieving = "Smutek",
	RestrainedAnger = "Powstrzymana złość",
	Afraid = "Boję się",
	LookingUpAnnoyed = "Patrząc w górę zirytowany",
	Offended_2 = "Obrażony 2",
	Resentful = "Urażony",
	SadExtra = "Smutny dodatek",
	NervousBreath = "Nerwowy oddech",
	ScreamingLong = "Krzyczy długo",
	ScreamingShort = "Krzyczący Krótki",
	ScaredBreath = "Przestraszony oddech",
	CryingPainful = "Płacz Bolesny",
	SelfReflectAnger = "Autorefleksja w gniewie",
	IndulgentSmile = "Pobłażliwy uśmiech",
	Impressed = "Pod wrażeniem",
	LongSmile = "Długi uśmiech",
	ShortSmile = "Krótki uśmiech",
	SimpleSmile = "Prosty uśmiech",
	Confident = "Pewny siebie",
	Relief = "Ulga",
	Impressed_2 = "Pod wrażeniem 2",
	Admiring = "Podziwiać",
	Fascinated = "Zafascynowany",
	RaisedBrows = "Podniesione brwi",
	LookingUpThinking = "Patrząc w górę i myśląc",
	LeftGlanceProcessing = "Przetwarzanie lewego spojrzenia",
	LeftGlanceCloseUp = "Lewe spojrzenie z bliska",
	LookingAround = "Rozglądając się",
	LookingDownThinking = "Patrząc w dół i myśląc",
	LookingAroundAlt = "Rozglądanie się Alt",
	EyesDartFromLeft = "Oczy rzucają się z lewej strony",
	EyesDartFromRight = "Oczy rzucają się z prawej strony",
	EyesDartToRight = "Oczy kierują się w prawo",
	LookingLeft = "Patrząc w lewo",
	LookingUpThinking_2 = "Patrząc w górę i myśląc 2",
	RightGlanceProcessing = "Przetwarzanie prawego spojrzenia",
	LookingDown = "Patrząc w dół",
	Left90GlanceClose = "W lewo90Spojrzenie blisko",
	LookingUp = "Patrząc w górę",
	Right90GlanceClose = "Prawo90Spojrzenie blisko",
	LookingLeftUp = "Patrząc w lewo w górę",
	LookingRightUp = "Patrząc prosto w górę",
	ReadingDown = "Czytanie",
	ReadingUp = "Czytanie",
	ReadingMiddle = "Czytanie środka",
	FrontCloseGlance = "Spojrzenie z przodu z bliska",
	WinkLeft = "Mrugnij w lewo",
	EyeRoll = "Przewrót oczami",
	Squint = "Zez",
	FalseSmile_2 = "Fałszywy uśmiech 2",
	FalseSmile_1 = "Fałszywy uśmiech 1",
	ListeningNewInfo = "Słuchanie nowych informacji",
	WhatDoYouWant = "Czego chcesz",
	Maybe = "Może",
	SearchingForWords = "Szukanie słów",
	What = "Co",
	Where = "Gdzie",
	SureSure = "Jasne Jasne",
	ListenToMe = "Posłuchaj mnie",
	StopThePolice = "Zatrzymaj policję",
	HurryUp = "Pospiesz się",
	ShutUp = "Zamknij się",
	WinkRight = "Mrugnij Dobrze",
	MockingSmile = "Szyderczy uśmiech",
	AsymmetricalSmile = "Asymetryczny uśmiech",
	SarcasticSmile = "Sarkastyczny uśmiech",
	Sex = "Seks",
	LipBite_1 = "Ugryzienie wargi 1",
	LipBite_2 = "Ugryzienie wargi 2",
	Moan = "Jęk",
	LipBite_3 = "Ugryzienie wargi 3",
	Pout = "Dąsać się",
	SexySmile = "Seksowny uśmiech",
	Swallow = "Połknij",
	SensualSmile = "Zmysłowy uśmiech",
	SexScene_1 = "Scena seksu 1",
	SexScene_2 = "Scena seksu 2",
	Kiss = "Pocałunek",
	UsingInhaler = "Korzystanie z inhalatora",
	ShortYawn = "Krótkie ziewanie",
	Yawn = "Ziewam",
	Coughing = "Kaszel",
	Bite = "Ugryźć",	
	EatingFast = "Szybkie jedzenie",
	ShortDrink = "Krótki napój",
	Drinking = "Picie",
	FastBite = "Szybki kęs",
	LongDrink = "Długi napój",
	ShortSmoking = "Krótkie palenie",
	LongSmoking = "Długie palenie",
	Smoking = "Palenie",
	Eating_1 = "Jedzenie 1",
	Eating_2 = "Jedzenie 2",
	Eating_3 = "Jedzenie 3",
	Eating_4 = "Jedzenie 4",
	Vomit = "Wymiotować",
	BeingRevived = "Będąc odrodzonym",
	MalwarePositive = "Pozytywny wynik złośliwego oprogramowania",
	MalwareNegative = "Złośliwe oprogramowanie negatywne",
	MalwareInfected = "Zainfekowany złośliwym oprogramowaniem",
	FaceMorphActivate = "Aktywacja zmiany twarzy",
	LieNetChairSleep = "Kłamstwo na krześle Net",
	LieNetChairBreathe = "Oddychaj na krześle leżącym w siatce",
	NetrunnerDeathUnplugged = "Netrunner Death odłączony",
	VeryItchyNose = "Bardzo swędzący nos",
	RollerCoasterNervous = "Nerwowy rollercoaster",
	Pfft = "Pff",
	Hahaha = "Hahaha",
	Sniff = "Powąchaj",
	Ahaaa = "Ahaaa",
	Heh = "Heh",
	Huh = "huh",
	Haaa = "Haaa",
	Sigh_Lipsync = "Westchnienie Lipsync",
	Hmm = "Hmm",
	Whispering_1 = "Szeptanie 1",
	Whispering_2 = "Szeptanie 2",
	ApprovalYes = "Zatwierdzenie Tak",
	SubtleYes = "Subtelne Tak",
	QuickNoShake = "Szybki, bez wstrząsów",
	FirmYes = "Firma Tak",
	LongNo = "Długi nr",
	SubtleNo = "Subtelny nr",
	NoContempt = "Żadnej pogardy",
	NoDisapproval = "Żadnej dezaprobaty",
	FirmNo = "Firma nr",
	NoEnthusiastic = "Żaden entuzjasta",
	MockingYes = "Kpiąco Tak",
	EnthusiasticYes = "Entuzjastyczny Tak",
	AsymmetricalCornerUp = "Asymetryczny narożnik w górę",
	CornersUp = "Narożniki w górę",
	SoftSigh = "Miękkie westchnienie",
	BreathGasp = "Oddech",
	AssymetricalSneer = "Asymetryczny szyderstwo",
	CrimpingLips = "Zaciskanie ust",
	BrowsDown = "Przegląda w dół",
	BrowsLeftUp = "Brwi lewe w górę",
	BrowsRightUp = "Brwi w górę",
	BrowsUp = "Przegląda w górę",
	ClosedEyes_1 = "Zamknięte oczy 1",
	ClosedEyes_2 = "Zamknięte oczy 2",
	EyesClosed = "Oczy zamknięte",
	LookRight = "Spójrz dobrze",
	FastBlink = "Szybkie mrugnięcie",
	SlowBlink = "Powolne mrugnięcie",
	NormalBlink = "Normalne mrugnięcie",
	TinyBlink = "Małe Mrugnięcie",
	HalfBlink = "Półmrugnięcie",
	RegularSaccade = "Zwykła Sakada",
	FrequentSaccade = "Częsta sakada",
	PhotoCloseupEyes = "Zdjęcie Zbliżenie Oczy",
	PhotoCloseupLips = "Zdjęcie Zbliżenie Usta",
	PhotoCloseupHair = "Zdjęcie Zbliżenie Włosy",
	PhotoCloseupChin = "Zdjęcie Zbliżenie Podbródek",
	PhotoCloseupNose = "Zdjęcie Zbliżenie Nos",
	PhotoCloseup = "Zdjęcie Zbliżenie",
	PhotoCloseupPleased = "Zdjęcie Zbliżenie Zadowolony",
	PhotoCloseupBody = "Zdjęcie Zbliżenie Ciała",
	PhotoCloseupTeeth = "Zdjęcie Zbliżenie zębów",
	PhotoCloseupIN = "Zdjęcie Zbliżenie W",
	PhotoCloseupOUT = "Zdjęcie Zbliżenie OUT",
	Bored = "Znudzony",
	Charming = "Urocze",
	Furious = "Wściekły",
	Happy = "Szczęśliwy",
	Pissed = "Wkurzony",
	Pleased = "Zadowolony",
	Scared = "Przestraszony",
	Surprised = "Zaskoczony",
	Sadness = "Smutek",
	Whistling = "Gwizdanie",
	Singing_1 = "Śpiew 1",
	Singing_2 = "Śpiew 2",
	Singing_3 = "Śpiew 3",
	Alerted = "Zaalarmowany",
	Hit_1 = "Uderz 1",
	Hit_2 = "Uderz 2",
	Wounded = "Ranny",
	Death = "Śmierć",

	-- Expressions Category
	Negative = "Negatywne",
	Positive = "Pozytywny",
	Contemplative = "Kontemplacyjny",
	Social = "Społeczny",
	Sexual = "Seksualny",
	Action = "Akcja",
	Vocal = "Wokal",
	Yes_N_No = "Tak i Nie",
	Nuance = "Niuans",
	Static = "Statyczny",
	Combat = "Walka",
	
	--Props
	AMM_Props_Desc = "Dodaje rekwizyty, postacie i pojazdy. Bez tego AMM nie uruchomi się.",
	AMM_JohnnyCompanion_Desc = "Dodaje Johnny'ego Silverhanda jako postać możliwą do odrodzenia.",
	AMM_ScenesPack_Desc = "Dodaje 9358 animacji scen do systemu pozycji.\nPobierz go ze strony Nexusa AMM.",
	AMM_SoundPack_Desc = "Dodaje możliwe do odtworzenia efekty dźwiękowe.",
	AMM_KerryPP_Desc = "Dodaje nowy, nagi wygląd.",
	AMM_BenjaminStonePP_Desc = "Dodaje nowy, nagi wygląd.",
	AMM_RiverPP_Desc = "Dodaje nowy, nagi wygląd.",
	AMM_YorinobuPP_Desc = "Dodaje nowy, nagi wygląd.",
	AMM_LizzyIncognito_Desc = "Dodaje nowy wygląd.",
	AMM_MeredithXtra_Desc = "Dodaje nowy wygląd.",
	AMM_DelamainFix_Desc = "Dodaje pełne ciało Delamainowi.",
	AMM_HanakoNoMakeup_Desc = "Umożliwia AMM usunięcie makijażu Hanako podczas korzystania z niestandardowego wyglądu.",
	AMM_JudyBodyRevamp_Desc = "Zastępuje ciało Judy nowym, ulepszonym.",
	AMM_PanamBodyRevamp_Desc = "Zastępuje nadwozie Panama nowym, ulepszonym.",
	AMM_MistyBodyRevamp_Desc = "Zastępuje ciało Misty nowym, ulepszonym.\nPobierz go ze strony Nexusa AMM.",
	AMM_1VesHanakoFixedBodyNaked_Desc = "Zastępuje ciało Hanako nowym, ulepszonym.",
	AMM_PinkyDudeANIMFacialExpressionsFemV_Desc = "Włącza narzędzia mimiki twarzy w wersji Female V",
	AMM_PinkyDudeANIMFacialExpressionsMaleV_Desc = "Włącza narzędzia mimiki twarzy w Male V",
	AMM_DinoTattooFixArchive_Desc = "Zastępuje siatkę i teksturę.",
	AMM_SongbirdBodyFixArchive_Desc = "Zastępuje korpus, aby naprawić szary obszar. Jeszcze nie idealnie.",
	AMM_RitaWheelerCombatEnablerArchive_Desc = "Zastępuje plik jednostki, aby włączyć animacje walki.",
	AMM_CheriAppearances_Desc = "Dodaje nowe wyglądy. Pobierz go ze strony Nexusa AMM.",
	AMM_BryceNaked_Desc = "Dodaje nowy, nagi wygląd. Pobierz go ze strony Nexusa AMM.",
	AMM_EvelynNaked_Desc = "Naprawia swoje ciało, aby pozwolić na nagi wygląd. Pobierz go ze strony Nexusa AMM.",
	AMM_SaburoAppearances_Desc = "Dodaje nowe wyglądy. Pobierz go ze strony Nexusa AMM.",
	AMM_TbugAppearances_Desc = "Dodaje nowe wyglądy. Pobierz go ze strony Nexusa AMM.",
	AMM_8ug8eagAppearances_Desc = "Dodaje nowe wyglądy. Pobierz go ze strony Nexusa AMM.",
	
	--Equipments (There is a Function Error(nil value) in this section, These are just labels that are not connected to any localizable strings in the file)
	Fists = "Pięści", --Line 2377 
	Katana = "Katana",
	Mantis_Blades = "Ostrza Modliszki",
	Machete = "Maczeta",
	Hammer = "Młotek",
	Baton = "Pałka",
	Knife = "Nóż",
	Crowbar = "Łom",
	Baseball_Bat = "Kij baseballowy",
	Assault_Rifle = "Karabin szturmowy",
	Sidewinder = "Sidewinder",
	Sniper_Rifle = "Karabin snajperski",
	Shotgun = "Strzelba",
	SMG = "SMG",
	Handgun = "Pistolet", --Line 2391
	
	--Warning / Info / Tooltip
	Warn_CantSave_BlacklistedAppearance = "Nie możesz zapisać wyglądu na czarnej liście!",
	Warn_ConfirmDeleteSavedAppearances = "Czy na pewno chcesz usunąć wszystkie zapisane występy?",
	Warn_ConfirmDeleteBlacklistedAppearances = "Czy na pewno chcesz usunąć wszystkie występy z czarnej listy?",
	Warn_ConfirmDeleteSavedDespawns = "Czy na pewno chcesz usunąć wszystkie zapisane odrodzenia?",
	Warn_ConfirmDeleteAppearanceTriggers = "Czy na pewno chcesz usunąć wszystkie wyzwalacze wyglądu?",
	Warn_ConfirmDeleteCurrentAppearance = "Czy na pewno chcesz usunąć aktualnie aktywne ustawienie wstępne?",
	Warn_WeaponizeNpcAnimationIssues = "Nie każdy NPC będzie miał niezbędne animacje do używania każdego rodzaju broni. Mogą wystąpić pozy T i nieprawidłowe animacje.\nCzy na pewno chcesz to włączyć?",
	Warn_ConfirmEnableExperimentalAndSave_Info = "Czy na pewno chcesz włączyć funkcje eksperymentalne? AMM może nie działać zgodnie z oczekiwaniami. Używaj go na własne ryzyko!",
	Warn_DeleteFavoritesAskWhichOne_Info = "Jeśli jesteś pewien, że chcesz usunąć wszystkie swoje ulubione, wybierz które z nich poniżej:",
	Popup_Error_Title = "Błąd",
	Button_Ok = "OK",
	Popup_FavoriteName = "Ulubione imię",
	Popup_RenamePreset = "Zmień nazwę ustawienia wstępnego",
	Popup_RenameProp = "Zmień nazwę prop",
	Editor_Title = "Edytor motywów",
	Editor_Field_ThemeName = "Nazwa motywu",
	Editor_Hint_InsertThemeName = "Wstaw nową nazwę motywu",
	Error_ThemeNameExists = "Nazwa motywu już istnieje",
}
