return {

    -- >> SCAN TAB
	BeginItem_TabNameScan = "Escanear",
	
	--Button
	Button_CyclesAppearances = "Aparência do Ciclo",
	Button_SavesAppearance = "Salvar aparência",
	Button_ClearSavedAppearance = "Limpar aparência salva",
	Button_UnlockDoor = "Alternar fechadura da porta",
	Button_RestoreAccess = "Restaurar acesso",
	Button_UnlockVehicle = "Desbloquear veículo",
	Button_RepairVehicle = "Reparar veículo",
	Button_OpenCloseDoors = "Abrir/fechar portas",
	Button_OpenCloseWindows = "Abrir/fechar janelas",
	Button_ToggleEngine = "Alternar mecanismo",
	Button_ToggleAIDriver = "Alternar driver AI",
	Button_ToggleCamera = "Alternar câmera",
	Button_ToggleRadio = "Alternar rádio",
	Button_NextRadioStation = "Próxima estação de rádio",
	Button_TargetMountedVehicle = "Veículo Montado Alvo",
	Button_AssignSeats = "Atribuir assentos",
	Button_Assign = "Atribuir",
	Button_Reset = "Redefinir",
	Button_FakeDie = "Dado falso",
	Button_SmallCopy = "Copiar",
	
    --Button Label
	Button_Label_Unfollower = "Deixar de seguir",
	Button_Label_Follower = "Seguidor",
	Button_Label_SaveDespawn = "Salvar Despawn",
	Button_Label_ClearSavedDespawn = "Limpar Despawn Salvo",
	Button_LabelLockTarget = "Bloquear alvo",
	Button_LabelUnlockTarget = "Desbloquear alvo",
	Label_AddToSpawnFavs = "Adicionar aos favoritos que podem ser gerados",
	Label_RemoveFromSpawnFavs = "Remover dos favoritos que podem ser gerados",
	
    --Checkbox
	Checkbox_SavedDespawnsActive = "Despawns salvos ativos",
	Checkbox_KeepAssigned = "Mantenha-se atribuído ao trocar de carro",
	
    --Warning / Info / Tool Tip
	WarnTextAI_FastTravel = "Selecione um ponto de viagem rápida no seu mapa para prosseguir",
	WarnText_DontReloadMods = "Não use Recarregar todos os mods.\nPor favor, recarregue seu jogo salvo ou vá para uma área diferente.",
	Warning_NoTarget_Desc = "Sem alvo! Olhe para NPC, Veículo ou Objeto para começar",
	ToolTip_DisableCheckboxReloadSave_AbleTotargetClearSavedDespawns = "Desative esta caixa de seleção e recarregue seu save para poder direcionar Clear Saved Despawns",
	
    --Text
	Build_Mode = "Modo de construção",
	Speed = "Velocidade:",
	Search = "Pesquisar",
	Clear = "Limpar",
	Player = "Jogador",
	Saved = "Salvo",
	Saved_ = "Salvo_",
	Current = "Atual",
	Current_ = "Atual",
	Select_Seat = "Selecione o assento",
	Target_Info = "Informações do alvo",
	Target_Actions = "Ações alvo",
	No_Appearances = "Sem aparências",
	No_Target = "Sem alvo",
	Favorite_Appearance = "Aparência Favorita",
	Unfavorite_Appearance = "Aparência não favorita",
	Blacklist_Appearance = "Aparência na lista negra",
	Unblacklist_Appearance = "Aparência de remoção da lista negra",
	Saved_Appearance = "Aparência salva:",
	Current_Appearance = "Aparência atual:",
	List_of_Appearances = "Lista de Aparições",
	Appearance_Trigger = "Gatilho de aparência",
	None = "Nenhum",
	Default = "Padrão",
	Zone = "Zona",
	Area = "Área",
	Position = "Posição",

	
	-- >> SPAWN TAB
	BeginItem_TabNameSpawn = "Gerar",
	
	--Button
	Button_Refresh = "Atualizar",
	Button_Save = "Salvar",
	Button_Confirm = "Confirmar",
	Button_Cancel = "Cancelar",
	Button_SmallSave = "Salvar",
	Button_SmallRespawn = "Reaparecer",
	Button_SmallDespawn = "Despawn",
	Button_SmallDespawn_WithSpace = "Despawn",
	Button_SmallTarget = "Alvo",
	Button_SmallEquipment = "Equipamento",
	Button_LabelHostile = "Hostil",
	Button_LabelFriendly = "Amigável",
	
    --Button Label
	Label_Favorite = "Favorito",
	Label_Unfavorite = "Não favorito",
	
    --Checkbox
    --Warning / Info / Tool Tip
	Warn_PlayerInMenu = "Jogador no menu",
	Warn_AMMonlyfunctions_ingame = "AMM funciona apenas no jogo",
	Warn_SpawnWorksInGame = "A desova só funciona no jogo",
	Warn_InitError = "Erro de inicialização",
	Warn_InitError_Info = "Por favor, verifique AppearanceMenuMod.log para obter mais informações.",
	
    --Text
	Active_Spawns = "Spawns Ativos",
	NoActiveSpawns = "Sem Spawns Ativos",
	Select_To_Spawn = "Selecione para gerar",
	No_Results = "Sem resultados",
	ItsEmpty = "Está vazio :(",
	Existing_Name = "Nome Existente",
	Name = "Nome",
	
	
	
	-- >> SWAP TAB
	BeginItem_TabNameSwap = "Trocar",
	
	--Button
	Button_SmallRevert = "Reverter",
	
    --Button Label
    --Checkbox
    --Warning / Info / Tool Tip
	Warn_ReloadSaveUpdateChanges = "Recarregue seu jogo salvo para atualizar as alterações!",
	Warn_NeedReloadSaveUpdateChanges = "Você precisará recarregar seu save para atualizar as alterações.",
	Warn_ReplacerSwap = "Você não pode trocar o substituto! Use a guia de ferramentas no modo foto para direcioná-los e, em seguida, altere sua aparência na guia Spawn ou nas ferramentas de alvo.",
	Warning = "AVISO",
	Warning2 = "AVISO:",
	SaveSwap_Tooltip = "Salve suas trocas para mantê-las após recarregar o jogo.",
	
    --Text
	CantSwapReplacer = "Não é possível trocar o Substituto",
	Active_Model_Swaps = "Trocas de modelos ativos",
	Save = "Salvar",
	Restore = "Restaurar",
	Current_Target = "Alvo atual:",
	Target_ID = "ID de destino:",
	SelectSwap_CurrentTarget = "Selecione para trocar com o alvo atual:",
	NoNPC_LookNPC = "Nenhum NPC encontrado! Olhe para o NPC para começar",
	
	-- Locations Categories
	Residences = "Residências",
	ArasakaAndCorpo = "Arasaka & Corpo",
	ClubsAndBars = "Clubes e bares",
	HotelsAndPleasure = "Hotéis e lazer",
	UndergroundAndCrime = "Subterrâneo e crime",
	GovernmentAndSecurity = "Governo e Segurança",
	StoryAndUnique = "História e Único",
	Ripperdocs = "Ripperdocs",
	LandmarksAndOpenWorld = "Marcos e mundo aberto",
	SpoilersAndHidden = "Spoilers e Ocultos",
	UserLocations = "Locais de usuários",
	
	
	-- >> DECOR TAB
	BeginItem_TabDecor = "Decoração",
	BeginItem_TabPresets = "Predefinições",
	Begin_ComboPresets = "Predefinições",
	
	--Button
	Button_SmallClone = "Clonar",
	Button_SmallRemove = "Remover##",
	Button_SmallRename = "Renomear##",
	Button_SmallUpdate = "Atualização##",
	Button_SmallCancel = "Cancelar",
	Button_Frame = "Quadro",
	
    --Button Label
	Button_LabelHide = "Esconder",
	Button_LabelUnhide = "Mostrar",
	
    --Checkbox
    --Warning / Info / Tool Tip
	Warn_PersistPropSave = "Crie adereços para decorar sua casa ou qualquer lugar que você quiser! Salve os adereços para fazê-los persistir!",
	Warn_DespawnInProgress_PleaseWait = "Despawn em andamento. Por favor, aguarde.",
	Warn_PresetsFolder_Info = "As predefinições do usuário são salvas na pasta AppearanceMenuMod/User/Decor",
	Warn_CustomPresets_Info = "Esta predefinição inclui acessórios personalizados",
	Warn_CustomPropsModders_Info = "Adereços personalizados feitos por:",
	Warn_GamepadDirectMode_Info = "Isso permite uma melhor integração com o modo Direto ao usar o gamepad. Ele também permite uma pequena janela de informações que fica por perto.",
	Warn_PresetTriggerDistanceFar = "Definir como Far pode causar problemas de desempenho.",
	
    --Text
	MovingAll_PropsTo_SavedProps = "Movendo todos os adereços para adereços salvos",
	SelectPropSpawn = "Selecione o acessório para gerar:",
	Spawned_Props = "Adereços gerados",
	New_Preset = "Nova predefinição",
	No_Preset_Available = "Nenhuma predefinição disponível",
	Preset_TriggerDistance = "Distância de disparo predefinida",
	MovingSavedProps = "Movendo %s para objetos salvos",
	UpdateTag = "Atualizar etiqueta",
	Categories = "Categorias",
	Decorating = "Decoração",
	Decor_Tabs = "Abas de decoração",
	Saved_Props = "Adereços salvos",
	Show_Nearby_Only = "Mostrar apenas nas proximidades",
	Show_Lights_Only = "Mostrar apenas luzes",
	Show_LockedTarget_Only = "Mostrar apenas alvo bloqueado",
	Show_Customizable_Only = "Mostrar apenas personalizável",
	Show_CustomProps_Only = "Mostrar apenas acessórios personalizados",
	ShowOnMap = "Mostrar no mapa",
	Rename = "Renomear",
	Delete = "Excluir",
	Backup = "Cópia de segurança",
	Merge = "Mesclar",
	Save_All = "Salvar tudo",
	Despawn_All = "Desaparecer tudo",
	Save_ToSpecific_Tag = "Salvar em tag específica",
	Saved_Props2 = "Adereços salvos:",
	Move_To_Tag = "Mover para etiqueta",
	HideFromMap = "Ocultar do mapa",
	RemovingAllPropsFromTag = "Removendo todos os adereços da tag...",
	RemoveAllProps = "Remover todos os adereços",
	RemoveHomeMarkerMap = "Remover marcador inicial do mapa",
	TeleportToLocation = "Teleporte para local",
	TeleportToTrigger = "Teleporte para o gatilho",
	TeleportToMark = "Teleporte para marcar",
	UpdateTagLocation = "Atualizar localização da tag",
	SharePresetWith_ThisTagOnly = "Compartilhe predefinições apenas com esta tag",
	SavedPresetFolder_Info = "Predefinição salva na pasta AppearanceMenuMod/User/Decor",
	NoProps_WithThese_Conditions = "Sem acessórios com essas condições",
	AddHomeMarkerMap = "Adicionar marcador inicial ao mapa",
	Distance = "Distância",
	Total_Props = "Adereços totais:",
	Type_Tag_here = "Digite a etiqueta aqui",
	In_World = "No mundo",
	Tags = "Etiquetas",
	Tag = "Etiqueta",
	Both = "Ambos",	
	
	-- >> POSES TAB
	BeginItem_TabPoses = "Poses",
	
	--Button
	Button_SmallCopyClipboard = "Copiar para a área de transferência",
	
    --Button Label
    --Checkbox
    --Warning / Info / Tool Tip
    --Text
	Active_Animations = "Animações ativas",
	ShowHistory = "Mostrar histórico",
	ClearHistory = "Limpar histórico",
	SelectPoseForCurrentTarget = "Selecione Pose para alvo atual:",
	LastUsedPoses = "Últimas poses usadas",
	
	
	
	-- >> TOOLS TAB
	BeginItem_TabTools = "Ferramentas",
	BeginItem_TabPhotoModeNibblesReplacer = "Substituidor de mordidelas do modo foto",
	BeginCombo_LookAt = "Olhe para",
	BeginCombo_WeatherControl = "Controle climático",
	
	--Button
	Button_SkipFrame = "Pular quadro",
	Button_ToggleLight = "Alternar luz",
	Button_ResetScale = "Redefinir escala",
	Button_ShowAsLookAtTarget = "Mostrar como olhar para o alvo",
	Button_ResetLookAtTarget = "Redefinir olhar para o alvo",
	Button_TogglePrimaryWeapon = "Equipar Arma Primária",
	Button_ToggleSecondaryWeapon = "Equipar Arma Secundária",
	Button_GiveCurrentEquippedWeapon = "Dê a arma equipada atual",
	Button_SmallReset = "Redefinir",
	Button_ResetToPlayer = "Redefinir para jogador",
	Button_ClearSaved = "Limpar salvo",
	Button_Cyberpsycho = "Alternar ciberpsicopata",
	Button_ProtectNPCfromActions = "Proteja o NPC de ações",
	Button_AllFriendly = "Todos amigáveis",
	Button_AllHostile = "Todos hostis",
	Button_AllFollower = "Todos os seguidores",
	Button_AllFakeDie = "Todos os dados falsos",
	Button_AllDie = "Todos morrem",
	Button_AllDespawn = "Todos Despawn",
	Button_InvMachineGun = "Metralhadora",
	Button_InvSpeed2 = "Velocidade",
	Button_ToggleMakeup = "Alternar maquiagem",
	Button_TogglePiercings = "Alternar piercings",
	Button_ToggleSeamfix = "Alternar Seamfix",
        Button_TargetV = "Alvo V",
        Button_Target = "Alvo",
        Button_TeleportToLocation = "Teleporte para local",
        Button_TeleportToTrigger = "Teleporte para o gatilho",
        Button_TeleportToMark = "Teleporte para marcar",
        Button_RandomLocation = "Aleatório",
        Button_ShareCurrentLocation = "Compartilhar localização atual",
	Button_GoBackToLastLocation = "Volte para o último local",
	Button_DeleteSelectedUserLocation = "Excluir local do usuário selecionado",
	
	--Slider / Drag 
	Slider_HeadStiffness = "Rigidez de cabeça",
	Slider_HeadPoseOverride = "Substituição da pose da cabeça",
	Slider_ChestStiffness = "Rigidez no peito",
	Slider_ChestPoseOverride = "Substituição da postura do peito",
	Slider_SlowMotion = "Câmera lenta",
	Slider_DefaultAperture = "Abertura padrão",
	Slider_DefaultFieldofView = "Campo de visão padrão",
	Slider_MovementSpeed = "Velocidade de movimento",
	Drag_MovementSpeed = "Velocidade de movimento",
	
    --Button Label
	Button_Label_PauseTimeProgression = "Pausar a progressão do tempo",
	Button_Label_UnpauseTimeProgression = "Retomar a progressão do tempo",
	Button_Label_UnfreezeTime = "Tempo de descongelamento",
	Button_Label_FreezeTime = "Tempo de congelamento",
	Button_Label_OpenLightSettings = "Abra as configurações de luz",
	Button_Label_UpdateLightTarget = "Atualizar alvo claro",
	Button_Label_Activate = "Ativar",
	Button_Label_Deactivate = "Desativar",
	Button_Label_ChangeToCrouchStance = "Mudar para postura agachada",
	Button_Label_ChangeToStandStance = "Mude para a posição de pé",
	Button_Label_PickUpTarget = "Pegar alvo",
	Button_Label_DropTarget = "Soltar alvo",
	Button_Label_FreezeTarget = "Alvo Congelado",
	Button_Label_UnfreezeTarget = "Descongelar alvo",
	Button_Label_OpenTargetTools = "Abrir ferramentas de destino",
	Button_Label_CloseTargetTools = "Fechar ferramentas de destino",
	
    --Checkbox
    --Warning / Info / Tool Tip
	Warn_FileNotFound_CollabsFolder_Error = "arquivo não encontrado na pasta Collabs",
	Warn_ShowXYZ_Orientation_Info = "Mostre as setas X, Y e Z para facilitar a orientação ao mover o alvo.",
	Warn_LookAtCamera_OptionOff_Info = "DESLIGUE a opção Olhar para a câmera uma vez após alterar esta configuração",
	Warn_DisableLookAtCamera_PhotoMode_Info = "Desative 'Olhar para a câmera' no modo Foto uma vez para ter efeito",
	Warn_RequiresRestart_Info = "Requer reinicialização do jogo para entrar em vigor",
	Warn_SlowMotion_PhotoMode_Info = "A câmera lenta no modo foto só funciona se você retomar o uso do IGCS",
	Warn_WeatherControl_RequireCodeware = "O controle climático requer Codeware 1.4+",
	Warn_StopNpc_UnequipWeapon_Info = "Isso impedirá o NPC de desequipar sua arma. Nota: o NPC ainda irá desequipar à vontade durante o combate.",
	Warn_OutOfCombat_NpcUnequip_Info = "Nota: Fora de combate, o NPC irá desequipar a arma fornecida imediatamente.",
	Warn_Photomode_UnfreezeSkipFrames_Info = "No modo Foto, o Unfreeze Target pulará quadros em poses animadas. Para obter a funcionalidade completa de (des)congelamento, você precisa usar o Otis Camera Tools (IGCS).",
	Warn_UserLocationsFolder_Info = "As localizações dos usuários são salvas na pasta AppearanceMenuMod/User/Locations",
	Warn_SeeMoreAction_Info = "Alvo V ou NPC para ver mais ações",
	Warn_SeeMoreActionProp_Info = "Alvo NPC ou Prop para ver mais ações",
	Warn_SeamfixPiercingToggle_Info = "Isso salvará o estado de alternância de Maquiagem, Piercing e Seamfix até você fechar o jogo.",
	Warn_PassiveMode_Info = "Os inimigos ainda irão atacar você se você iniciar o combate",
	Warn_TppCameraGameplay_Info = "A câmera TPP não é adequada para jogos normais, mas é divertida para passear ;)",
	Warn_AnimatedHead_PhotoMode_Info = "As expressões do modo Foto não funcionarão enquanto a Cabeça Animada estiver ativada.",
	Warn_ToolsOnly_WorksIngame = "Ferramentas só funcionam no jogo",
	Warn_InvButtonMachineGun_Info = "Você encontrou! Metralhadora Pesada foi adicionada aos Equipamentos.",
	Warn_InvButton_Info = "Você encontrou! O movimento rápido já está disponível.",
	InvButtonTip = "E se eu clicar aqui?",
	InvButtonTip2 = "Clicar aqui não adianta nada!",
	InvButtonTip3 = "NÃO CLIQUE VOCÊ FOI AVISADO!",
	
    --Text
	Facial_Expression = "Expressão Facial",
	Expressions = "Expressões",
	Look_At = "Olhe para",
	Look_At_Camera = "Olhe para a câmera:",
	Target_Tools = "Ferramentas de destino",
	Rotation = "Rotação",
	Tilt_Rotation = "Inclinação/Rotação",
	Mode = "Modo:",
	Precision = "Precisão",
	Relative = "Relativo",
	Direct = "Direto",
	AdvMovement = "Av. Movimento",
	ForceGivenWeapon = "Força Dada Arma",
	Scale = "Escala",
	ProportionalMode = "Modo Proporcional",
	General_Actions = "Ações Gerais",
	DisablePassiveMode = "Desative o modo passivo",
	EnablePassiveMode = "Habilitar modo passivo",
	EnableGodMode = "Habilite o modo Deus",
	DisableGodMode = "Desative o modo Deus",
	Infinite_Oxygen = "Oxigênio Infinito",
	Select_Location = "Selecione o local",
	Select_Expression = "Selecione Expressão",
	Select_Category = "Selecione a categoria",
	Teleport_Actions = "Ações de teletransporte",
	Use_Teleport_Animation = "Use animação de teletransporte",
        Filter_Locations = "Filtrar locais",
        Locations = "Locais",
        Default_Locations = "Locais padrão",
        Collab_Locations = "Locais de colaboração",
        Button_AddTag = "Adicionar etiqueta",
	Button_FilterByTags = "Filtrar por tags",
	Button_Close = "Fechar",
	Favorite_Selected_Location = "Local selecionado favorito",
	Unfavorite_Selected_Location = "Local selecionado não favorito",
	Edit_Selected_Location = "Editar local selecionado",
	Locations_Favorites = "--------- Favoritos ----------",
	Locations_UserLocs = "------- Locais de usuários -------",
	Locations_DefaultLocs = "----------- Padrão ----------",
	Share_Location = "Compartilhar localização",
	Edit_Location = "Editar local",
	TimeWeather_Actions = "Ações de tempo e clima",
	TimeofDay = "Hora do dia",
	Time_Actions = "Ações de tempo",
	Rain = "Chuva",
	Light_Rain = "Chuva fraca",
	Cloudy = "Nublado",
	Fog = "Nevoeiro",
	Heavy_Clouds = "Nuvens Pesadas",
	Light_Clouds = "Nuvens claras",
	Pollution = "Poluição",
	Sandstorm = "Tempestade de areia",
	Sunny = "Ensolarado",
	Toxic_Rain = "Chuva Tóxica",
	Deep_Blue = "Azul Profundo",
	Squat_Morning = "Agachamento Manhã",
	Cloudy_Morning = "Manhã nublada",
	Rainy_Night = "Noite chuvosa",
	Courier_Clouds = "Nuvens de correio",
	Cursor_LockState = "Estado de bloqueio",
	PhotoMode_NibblesReplacer = "Substituidor de mordidelas do modo foto",
	PhotoModeEnhancements = "Aprimoramentos no modo foto",
	Button_ResetReplacerDatabase = "Redefinir banco de dados substituto",
	DisablePhotoModeCursor = "Desativar cursor do modo foto",
	TPPCamera_Position = "Posição da câmera TPP",
	AnimatedHeadin_PhotoMode = "Cabeça animada no modo foto",
	LockLook_AtCamera = "Bloquear olhar para a câmera",
	UnlockLook_AtCamera = "Desbloquear olhar para a câmera",
	Save_Toggles_State = "Salvar estado de alternância",
	Toggle_V_Head = "Alternar cabeça V",
	Toggle_TPP_Camera = "Alternar câmera TPP",
	Target_Nibbles = "Mordidelas alvo",
	Target_Replacer = "Substituto de Alvo",
	Left = "Esquerda",
	Left_Close = "Fechar à esquerda",
	Right = "Certo",
	Right_Close = "Fechar à direita",
	Center_Close = "Fechar Centro",
	Center_Far = "Centro Distante",
	Front_Close = "Fechamento frontal",
	Front_Far = "Frente Distante",
	All = "Todos",
	Head_Only = "Somente cabeça",
	Eyes_Only = "Somente olhos",
	Movement = "Movimento",
	V_Actions = "V Ações",
	Invisible_V = "V invisível",
	LikeGTA_byGTATravel = "por GTA Travel",
	EnableSpawnedProps = "Habilitar adereços gerados",
	LightControl = "Controle de luz",
	Equipment = "Equipamento",
	
	-- >> DIRECTOR TAB
	BeginItem_TabNameDirector = "Diretor",
	BeginItem_TabNameTriggers = "Gatilhos",
	BeginCombo_StartAppearance = "Iniciar aparência",
	BeginCombo_EndAppearance = "Aparência final",
	BeginCombo_Type = "Tipo",
	BeginCombo_GoToTarget = "Vá para o alvo",
	BeginCombo_PlayVoice = "Tocar voz",
	BeginCombo_Attack = "Ataque",
	BeginCombo_Triggers = "Gatilhos",
	BeginCombo_Scripts = "Roteiros",
	
	--Button
	Button_Yes = "Sim",
	Button_No = "Não",
	Button_SaveChangesOnly = "Salvar apenas alterações",
	Button_RemoveMark = "Remover marca",
	Button_EditMark = "Editar marca",
        Button_MoveMark = "Mover marca",
        Button_MoveUp = "Subir",
        Button_MoveDown = "Mover para baixo",
        Button_NewMark = "Nova marca",
	Button_AddActor = "Adicionar ator",
	Button_RemoveActor = "Remover ator",
	Button_ChangeActor = "Mudar ator",
	Button_RadioOnlyOne = "Apenas um",
	Button_RadioRandom = "Aleatório",
	Button_RadioSequential = "Sequencial",
	Button_SaveTrigger = "Salvar gatilho",
	Button_NewCamera = "Nova câmera",
	Button_NewScript = "Novo roteiro",
	Button_DragSpeed = "Velocidade",
	Button_ToggleMarker = "Alternar marcador",
	Button_TestPose = "Pose de teste",
	Button_StopPose = "Pare de postura",
	
    --Button Label
	Button_Label_PlayScript = "Jogar roteiro",
	Button_Label_StopScript = "Parar script",
	Button_Label_Stopping = "Parando...",
	Button_Label_Restarting = "Reiniciando...",
	Button_Label_AddMark = "Adicionar marca",
	Button_Label_SaveWNewPos = "Salvar com nova posição",
	
    --Checkbox
    --Warning / Info / Tool Tip
	Warn_ActorSingleMark_Info = "Ator permanecerá em uma única marca",
	Warn_ActorRandomMark_Info = "O ator se moverá aleatoriamente entre as marcas",
	Warn_ActorSequentialMark_Info = "O ator se moverá entre as marcas em ordem numérica",
	Warn_DeleteScript_Info = "Tem certeza de que deseja excluir este script?",
	Warn_CloseCamForMove_Info = "Feche o menu para poder mover a câmera",
	Warn_CreateScriptsDesc_Info = "Crie scripts para adicionar, vestir e direcionar atores para atuar em machinima, capturas de tela e roleplay.",
	Warn_PremadeScriptsDesc_Info = "Crie Triggers para ativar Scripts pré-fabricados no contato.",
	Warn_CreateCamera_FovZoomDesc_Info = "Crie câmeras para se movimentar livremente, defina diferentes campos de visão e níveis de zoom.",
	Warn_ShowMarksLocations_Info = "Exibe um ícone visível nos locais de marcação",
	Warn_AutoTalkNpc_Info = "Isso fará com que os NPCs falem uma vez a cada minuto quando estiverem dentro do alcance (somente NPCs com voz)",
	Warn_DirectActorPlayerPosition_Info = "Crie uma marca na posição atual do jogador para mover e direcionar os atores",
	Warn_InMenuDirectorDesc = "Diretor só trabalha no jogo",
	
    --Text
	DirectorMode = "Modo Diretor",
	SelectActorToReplace = "Selecione o ator a ser substituído:",
	AddActorToCurrentScript = "Adicionar ator ao script atual:",
	FacialExpression_WithColon = "Expressão Facial:",
	FavoritePoses_WithColon = "Poses favoritas:",
	AddFavorites_Desc = "Adicione Poses aos Favoritos na guia Poses primeiro",
	HoldDuration = "Duração da retenção",
	Movement2 = "Movimento:",
	Actions = "Ações:",
	Actors = "Atores",
	Editing = "Edição",
	AutoTalk = "Conversa automática",
	ActorMarks = "Marcas do ator",
	Current_Actors = "Atores Atuais",
	Marks_Sequence = "Sequência de Marcas:",	
	ShowMarks = "Mostrar marcas",
	Triggers = "Gatilhos",
	NewTrigger = "Novo gatilho",
	ShowTrigger = "Mostrar gatilho",
	Title = "Título",
	Select_Trigger = "Selecione o gatilho",
	Select_Script = "Selecione o roteiro",
	Delete_Trigger = "Excluir gatilho",
	Triggers_On_Off = "Ativadores ativados/desativados",
	Running = "Correndo",
	Script_Running = "Script em execução...",
	Delete_Script = "Excluir script",
	RepeatInLoop = "Repita em loop",
	ActivationRadius = "Raio de ativação",
	Activate = "Ativar",
	Deactivate = "Desativar",
	FOV = "campo de visão",
	Zoom = "Zoom",
	LockFrame = "Quadro de bloqueio",
	Walk = "Caminhar",
	Sprint = "Corrida",
	Sequential = "Sequencial",
	Cameras = "Câmeras",
	NodeView = "Visualização de nós",
	TeamA = "Equipe A",
	TeamB = "Equipe B",
	
	
	
	-- >> SETTINGS TAB
	BeginItem_TabNameSettings = "Configurações",
	BeginItem_TabNameGeneral = "Geral",
	BeginItem_TabNameCompanions = "Companheiros",
	BeginItem_TabNameUI = "Interface",
	BeginItem_TabNameExperimental = "Experimental",
	BeginItem_TabNamePhotoMode = "Modo foto",
	
	--Button
	Button_RevertAllModelSwaps = "Reverter todas as trocas de modelo",
	Button_RespawnAll = "Reaparecer tudo",
	Button_ForceDespawnAll = "Forçar o desaparecimento de todos",
	Button_ClearFavorites = "Limpar favoritos",
	Button_ClearAllSavedAppearances = "Limpar todas as aparências salvas",
	Button_ClearAllBlacklistedAppearances = "Limpar todas as aparências da lista negra",
	Button_ClearAllAppearanceTriggers = "Limpar todos os gatilhos de aparência",
	Button_ClearAllSavedDespawns = "Limpar todos os despawns salvos",
	Button_SmallCreateTheme = "Criar tema",
	Button_SmallDeleteTheme = "Excluir tema",
	Button_SmallSet = "Definir",
	Button_ReloadAppearances = "Recarregar aparências personalizadas",
	
    --Button Label
    --Checkbox
	Checkbox_SpawnAsCompanion = "Spawn como companheiro",
	Checkbox_SpawnAsFriendly = "Gerar como amigável",
	Checkbox_InvulnerableCompanion = "Companheiro Invulnerável",
	Checkbox_RespawnOnLaunch = "Reaparecer no lançamento",
	Checkbox_LockTargetAfterSpawn = "Bloquear alvo após o surgimento",
	Checkbox_OpenTargetToolsAfterSpawn = "Abra as ferramentas de destino após o spawn",
	Checkbox_DisplayAxisIndicatorByDefault = "Exibir indicador de eixo por padrão",
	Checkbox_PhotoModeEnhancements = "Aprimoramentos no modo foto",
	Checkbox_GodModeOnLaunch = "Modo Deus no lançamento",
	Checkbox_PassiveModeOnLaunch = "Modo passivo no lançamento",
	Checkbox_StreamerMode = "Modo Streamer",
	Checkbox_OpenWCETOverlay = "Abrir com sobreposição CET",
	Checkbox_AutoResizingWindow = "Janela de redimensionamento automático",
	Checkbox_ScanningReticle = "Retículo de digitalização",
	Checkbox_FloatingTargetTools = "Ferramentas de alvo flutuante",
	Checkbox_TabHeaderDescriptions = "Descrições do cabeçalho da guia",
	Checkbox_ExpandFavoritesByDefault = "Expandir favoritos por padrão",
	Checkbox_EnableScrollBars = "Habilitar barras de rolagem",
	Checkbox_AlwaysDisablePhotoModeCursor = "Sempre desative o cursor do modo foto",
	Checkbox_Camera = "Câmera",
	Checkbox_DepthOfField = "DOF",
	Checkbox_Effect = "Efeito",
	Checkbox_Stickers = "Adesivos",
	Checkbox_LoadSave = "Carregar/Salvar",
	Checkbox_ExperimentalFunstuff = "Coisas experimentais/divertidas",
	Checkbox_EnableFreezeTargetInPhotoMode = "Ativar congelamento de alvo no modo foto",
	Checkbox_WeaponizeCompanions = "Armar Companheiros",
	Checkbox_AllowPlayerToBeTargetedinPosestab = "Permitir que o jogador seja direcionado na guia Poses",
	Checkbox_AllowPlayerAnimationsonNPCs = "Permitir animações de jogadores em NPCs",
	Checkbox_AllowExpressionOnNpcPM = "Habilite expressões e procure NPCs no modo foto",
        Checkbox_ResetTargetPositionPM = "Redefinir a posição alvo para NPCs do modo foto",
        Checkbox_EnableRandomLocation = "Habilitar botão Aleatório: teletransporta o jogador para um local aleatório da lista",
        Checkbox_RestoreOnLaunch = "Restaurar no lançamento",
        Radio_PrimarySlot = "Slot Primário",
        Radio_SecondarySlot = "Slot Secundário",
	
    --Warning / Info / Tool Tip
	Warn_RespawnOnLaunch_Info = "Esta configuração ativará/desativará o reaparecimento de NPCs salvos anteriormente no carregamento do jogo. AMM salva automaticamente seus NPCs gerados quando você sai do jogo.",
	Warn_BannedWords_Info = "Esta configuração ativará/desativará as aparências de NPCs que contenham as palavras: nu, nu, xxx, chuveiro, roupa de aniversário, pp e pênis.",
	Warn_TargetNpcVehicleHotkey = "NPC ou veículo alvo para definir teclas de atalho",
	Warn_FirstLaunchDecideTabsExpand_Info = "Esta configuração expandirá os Favoritos nas guias Spawn, Swap e Decor por padrão quando o AMM for iniciado pela primeira vez.",
	Warn_ExperimentalTabDesc_Info = "Os recursos experimentais adicionam mais funcionalidades, mas podem não funcionar tão bem, daí o rótulo experimental. Na verdade, a maioria dos usuários de AMM tem recursos experimentais habilitados. Então não se preocupe muito e divirta-se!",
	Warn_FreezeTargetPhotoMode_Info = "Esta configuração tem como objetivo ajudar a congelar animações de mods que adicionam animações personalizadas às poses do Modo Foto ou quando você retoma o uso do IGCS.",
	Warn_WeaponizeCompanions_Info = "Isto dará armas e habilidades de combate a todos os NPCs. Esperam-se poses em T e animações estranhas.",
	Warn_PlayerAnimsOnNpc_Info = "Habilite isto se você estiver usando um mod que permite que animações do jogador sejam usadas em NPCs.",
	Warn_UnpauseRequiresIGSC = "Esta configuração exige que o IGCS retome o tempo.",
	Warn_NotInstalled = "NÃO INSTALADO",
	Warn_DespawnAllProps = "Tem certeza de que deseja Despawn Todos os Adereços?",
	
    --Text
	AMM_Version = "Versão AMM:",
	CET_Version = "Versão CET:",
	Codeware_Version = "Versão do Codeware:",
	Game_Version = "Versão do jogo:",
	Companion_Damage = "Dano ao Companheiro:",
	Companion_Resistance = "Resistência do companheiro:",
	Companion_Distance = "Distância do companheiro:",
	xDamage = "x Dano",
	xResistance = "x Resistência",
	SavedAppearancesHotkeys = "Teclas de atalho de aparências salvas",
	Favorites = "Favoritos",
	Appearances = "Aparências",
	Blacklist = "Lista negra",
	AppearanceTriggers = "Gatilhos de aparência",
	SavedDespawns = "Despawns salvos",
	Interface_Language = "Idioma da interface:",
	Custom_Appearances = "Aparências personalizadas",
	PhotoModeAdjustments = "Ajustes no modo foto:",
	DisablePhotoModeTabs = "Desative as guias do modo foto:",
	List_Height = "Altura da lista",
	Listbox_Themes = "Temas",
	Weaponize = "Armar",
	NoAppearanceSet = "Nenhuma aparência definida",
	
	
	
	-- >> EXTRA	
	--Texts, warns, tips, info's, buttons and labels etc.
	Seat_FrontRight = "Frente Direita",
	Seat_BackRight = "Atrás à Direita",
	Seat_FrontLeft = "Frente Esquerda",
	Seat_BackLeft = "Atrás à esquerda",
	Label_Door = "Porta",
	Label_Window = "Janela",

	Close = "Fechar",
	Far = "Longe",
	Moderate = "Moderado",
	
	-- >> Archives Screen
	Warning_MissingRequiredArchives = "AMM está faltando um ou mais arquivos necessários. Por favor, instale qualquer arquivo necessário ausente em sua pasta archive/pc/mod.",
	Warning_MissingOptionalArchives = "AMM está faltando um ou mais arquivos. Eles são opcionais, mas adicionam funcionalidade ao AMM. Você pode ignorar esses avisos, mas o AMM pode não funcionar corretamente.",
	
	
	-->> INIT.LUA
	AMMNeedsAttention = "AMM precisa de atenção",
	MISSING_ARCHIVES = "ARQUIVOS FALTANDO",
	VERSION_INFORMATION = "INFORMAÇÕES DA VERSÃO",
	CREDITS = "CRÉDITOS",
	UPDATE_HISTORY = "HISTÓRICO DE ATUALIZAÇÕES",
	Updates = "Atualizações",
	MISSING = "FALTANDO",
	REQUIRED = "OBRIGATÓRIO",
	OPTIONAL = "OPCIONAL",
	WHATS_NEW = "O QUE HÁ DE NOVO", --Line 83 Function Error

	--Button
	Button_Ignorewarningsforthisversion = "Ignorar avisos para esta versão",
	Button_Credits = "Créditos",
	Button_Cool = "Legal!",

	--Button Label
	Label_SpawnFavorites = "Gerar Favoritos",
	Label_SwapFavorites = "Trocar favoritos",
	Label_FavoriteAppearances = "Aparições favoritas",
	Label_Cancel = "Cancelar",

	--Text
	Hotkey_i = "Tecla de atalho %i",

	--Node - Function Error(nil value) 
	Top = "Superior", --Line 116
	Bottom = "Inferior",
	Off = "Desligado",
	
	--Voice Overs
	Label_GreetV = "Cumprimente V.",
	Label_FearFoll = "Medo Seguir",
	Label_FearToll = "Taxa de medo",
	Label_FearBeg = "Medo implora",
	Label_FearRun = "Medo Correr",
	Label_StealthSearch = "Pesquisa furtiva",
	Label_StealthDeath = "Morte furtiva",
	Label_StealthRestore = "Restauração furtiva",
	Label_StealthEnd = "Fim Furtivo",
	Label_CuriousGrunt = "Grunhido Curioso",
	Label_GrappleGrunt = "Grunhido",
	Label_Bump = "Colisão",
	Label_VehicleBump = "Colisão do veículo",
	Label_TurretWarning = "Aviso de torre",
	Label_OctantWarning = "Aviso de octante",
	Label_DroneWarning = "Aviso de drone",
	Label_MechWarning = "Aviso mecânico",
	Label_EliteWarning = "Aviso Elite",
	Label_CameraWarning = "Aviso de câmera",
	Label_EnemyWarning = "Aviso Inimigo",
	Label_HeavyWarning = "Aviso Pesado",
	Label_SniperWarning = "Aviso de atirador",
	Label_AnyDamage = "Qualquer dano",
	Label_Danger = "Perigo",
	Label_CombatStart = "Início do Combate",
	Label_CombatEnd = "Fim do Combate",
	Label_CombatTargetHit = "Acerto no Alvo de Combate",
	Label_PedestrianHit = "Atropelamento de pedestres",
	Label_LightHit = "Golpe leve",
	Label_Curse = "Maldição",
	Label_Irritated = "Irritado",
	Label_GrenadeThrow = "Lançamento de granada",
	Label_Gotakill = "Matei!",
	
	--Expressions
	Neutral = "Neutro",
	Joy = "Alegria",
	Smile = "Sorria",
	Sad = "Triste",
	Surprise = "Surpresa",
	Aggressive = "Agressivo",
	Anger = "Raiva",
	Interested = "Interessado",
	Disinterested = "Desinteressado",
	Disappointed = "Decepcionado",
	Disgust = "Nojo",
	Exertion = "Esforço",
	Nervous = "Nervoso",
	Fear = "Medo",
	Terrified = "Aterrorizado",
	Pain = "Dor",
	Sleepy = "Com sono",
	Unconscious = "Inconsciente",
	Dead = "Morto",

	-- Extra Expressions
	Frown = "Franzir a testa",
	Shocked = "Chocado",
	Annoyed_2 = "Irritado 2",
	Contempt = "Desprezo",
	Irritated = "Irritado",
	Sceptical_1 = "Cético 1",
	Sceptical_2 = "Cético 2",
	Annoyed_1 = "Irritado 1",
	Offended = "Ofendido",
	Disgusted = "Enojado",
	Disappointed_2 = "Decepcionado 2",
	Alert = "Alerta",
	Crying = "Chorando",
	Embarrassed = "Envergonhado",
	Humiliated = "Humilhado",
	Impatient = "Impaciente",
	Anguished = "Angustiado",
	Worried = "Preocupado",
	Guilty = "Culpado",
	Grieving = "Luto",
	RestrainedAnger = "Raiva contida",
	Afraid = "Com medo",
	LookingUpAnnoyed = "Olhando para cima irritado",
	Offended_2 = "Ofendido 2",
	Resentful = "Ressentido",
	SadExtra = "Mais triste",
	NervousBreath = "Respiração Nervosa",
	ScreamingLong = "Gritando muito",
	ScreamingShort = "Gritando Curto",
	ScaredBreath = "Respiração assustada",
	CryingPainful = "Chorando Doloroso",
	SelfReflectAnger = "Auto-reflexão da raiva",
	IndulgentSmile = "Sorriso Indulgente",
	Impressed = "Impressionado",
	LongSmile = "Sorriso Longo",
	ShortSmile = "Sorriso curto",
	SimpleSmile = "Sorriso Simples",
	Confident = "Confiante",
	Relief = "Alívio",
	Impressed_2 = "Impressionado 2",
	Admiring = "Admirando",
	Fascinated = "Fascinado",
	RaisedBrows = "Sobrancelhas levantadas",
	LookingUpThinking = "Olhando para cima pensando",
	LeftGlanceProcessing = "Processamento de olhar esquerdo",
	LeftGlanceCloseUp = "Vista esquerda de perto",
	LookingAround = "Olhando ao redor",
	LookingDownThinking = "Olhando para baixo pensando",
	LookingAroundAlt = "Olhando ao redor Alt",
	EyesDartFromLeft = "Olhos disparados da esquerda",
	EyesDartFromRight = "Olhos disparados da direita",
	EyesDartToRight = "Olhos disparados para a direita",
	LookingLeft = "Olhando para a esquerda",
	LookingUpThinking_2 = "Olhando para cima pensando 2",
	RightGlanceProcessing = "Processamento do olhar direito",
	LookingDown = "Olhando para baixo",
	Left90GlanceClose = "Esquerda90Glance Fechar",
	LookingUp = "Olhando para cima",
	Right90GlanceClose = "Direita90Olhar Fechar",
	LookingLeftUp = "Olhando para a esquerda",
	LookingRightUp = "Olhando para cima",
	ReadingDown = "Lendo para baixo",
	ReadingUp = "Lendo",
	ReadingMiddle = "Leitura do meio",
	FrontCloseGlance = "Olhar frontal próximo",
	WinkLeft = "Piscadela para a esquerda",
	EyeRoll = "Revirar os olhos",
	Squint = "Apertar os olhos",
	FalseSmile_2 = "Sorriso Falso 2",
	FalseSmile_1 = "Sorriso Falso 1",
	ListeningNewInfo = "Ouvindo novas informações",
	WhatDoYouWant = "O que você quer",
	Maybe = "Talvez",
	SearchingForWords = "Procurando por palavras",
	What = "O que",
	Where = "Onde",
	SureSure = "Claro Claro",
	ListenToMe = "Ouça-me",
	StopThePolice = "Pare a polícia",
	HurryUp = "Apresse-se",
	ShutUp = "Cale a boca",
	WinkRight = "Pisque para a direita",
	MockingSmile = "Sorriso zombeteiro",
	AsymmetricalSmile = "Sorriso Assimétrico",
	SarcasticSmile = "Sorriso Sarcástico",
	Sex = "Sexo",
	LipBite_1 = "Mordida de lábio 1",
	LipBite_2 = "Mordida labial 2",
	Moan = "Gemer",
	LipBite_3 = "Mordida labial 3",
	Pout = "Beicinho",
	SexySmile = "Sorriso sexy",
	Swallow = "Engolir",
	SensualSmile = "Sorriso Sensual",
	SexScene_1 = "Cena de sexo 1",
	SexScene_2 = "Cena de sexo 2",
	Kiss = "Beijo",
	UsingInhaler = "Usando o inalador",
	ShortYawn = "Bocejo curto",
	Yawn = "Bocejo",
	Coughing = "Tosse",
	Bite = "Mordida",	
	EatingFast = "Comer rápido",
	ShortDrink = "Bebida Curta",
	Drinking = "Beber",
	FastBite = "Mordida rápida",
	LongDrink = "Bebida longa",
	ShortSmoking = "Fumar Curto",
	LongSmoking = "Fumar muito tempo",
	Smoking = "Fumar",
	Eating_1 = "Comer 1",
	Eating_2 = "Comer 2",
	Eating_3 = "Comer 3",
	Eating_4 = "Comer 4",
	Vomit = "Vômito",
	BeingRevived = "Sendo revivido",
	MalwarePositive = "Malware Positivo",
	MalwareNegative = "Malware negativo",
	MalwareInfected = "Malware infectado",
	FaceMorphActivate = "Ativação de transformação facial",
	LieNetChairSleep = "Lie Net Cadeira Sono",
	LieNetChairBreathe = "Lie Net Cadeira Respire",
	NetrunnerDeathUnplugged = "Morte de Netrunner desconectada",
	VeryItchyNose = "Nariz com muita coceira",
	RollerCoasterNervous = "Montanha Russa Nervosa",
	Pfft = "Pfft",
	Hahaha = "Hahaha",
	Sniff = "Cheirar",
	Ahaaa = "Ahaaa",
	Heh = "Ei",
	Huh = "Hã",
	Haaa = "Haaa",
	Sigh_Lipsync = "Suspiro Lipsync",
	Hmm = "Hum",
	Whispering_1 = "Sussurrando 1",
	Whispering_2 = "Sussurrando 2",
	ApprovalYes = "Aprovação Sim",
	SubtleYes = "Sutil sim",
	QuickNoShake = "Rápido sem agitação",
	FirmYes = "Firme Sim",
	LongNo = "Longo Não",
	SubtleNo = "Sutil não",
	NoContempt = "Sem desprezo",
	NoDisapproval = "Sem desaprovação",
	FirmNo = "Empresa Não",
	NoEnthusiastic = "Não entusiasmado",
	MockingYes = "Zombando sim",
	EnthusiasticYes = "Entusiasmado Sim",
	AsymmetricalCornerUp = "Canto assimétrico para cima",
	CornersUp = "Cantos para cima",
	SoftSigh = "Suspiro Suave",
	BreathGasp = "Suspiro",
	AssymetricalSneer = "Zombaria Assimétrica",
	CrimpingLips = "Crimpagem de Lábios",
	BrowsDown = "Sobrancelhas para baixo",
	BrowsLeftUp = "Sobrancelhas para cima",
	BrowsRightUp = "Sobrancelhas para cima",
	BrowsUp = "Navega para cima",
	ClosedEyes_1 = "Olhos Fechados 1",
	ClosedEyes_2 = "Olhos Fechados 2",
	EyesClosed = "Olhos Fechados",
	LookRight = "Olhe certo",
	FastBlink = "Piscar rápido",
	SlowBlink = "Piscar lento",
	NormalBlink = "Piscar normal",
	TinyBlink = "Pequeno piscar",
	HalfBlink = "Meio piscar",
	RegularSaccade = "Sacada Regular",
	FrequentSaccade = "Sacada frequente",
	PhotoCloseupEyes = "Foto closeup olhos",
	PhotoCloseupLips = "Foto closeup lábios",
	PhotoCloseupHair = "Cabelo closeup de foto",
	PhotoCloseupChin = "Foto close do queixo",
	PhotoCloseupNose = "Foto closeup nariz",
	PhotoCloseup = "Close da foto",
	PhotoCloseupPleased = "Close da foto satisfeito",
	PhotoCloseupBody = "Corpo em close da foto",
	PhotoCloseupTeeth = "Dentes em close de foto",
	PhotoCloseupIN = "Close da foto IN",
	PhotoCloseupOUT = "Close da foto FORA",
	Bored = "Entediado",
	Charming = "Encantador",
	Furious = "Furioso",
	Happy = "Feliz",
	Pissed = "Irritado",
	Pleased = "Satisfeito",
	Scared = "Assustado",
	Surprised = "Surpreso",
	Sadness = "Tristeza",
	Whistling = "Assobiando",
	Singing_1 = "Cantando 1",
	Singing_2 = "Cantando 2",
	Singing_3 = "Cantando 3",
	Alerted = "Alertado",
	Hit_1 = "Acerto 1",
	Hit_2 = "Acerte 2",
	Wounded = "Ferido",
	Death = "Morte",

	-- Expressions Category
	Negative = "Negativo",
	Positive = "Positivo",
	Contemplative = "Contemplativo",
	Social = "Sociais",
	Sexual = "Sexuais",
	Action = "Ação",
	Vocal = "Vocal",
	Yes_N_No = "Sim e Não",
	Nuance = "Nuance",
	Static = "Estático",
	Combat = "Combate",
	
	--Props
	AMM_Props_Desc = "Adiciona adereços, personagens e veículos. AMM não será lançado sem isso.",
	AMM_JohnnyCompanion_Desc = "Adiciona Johnny Silverhand como personagem que pode ser gerado.",
	AMM_ScenesPack_Desc = "Adiciona 9358 animações de cena ao sistema Poses.\nBaixe-o na página Nexus da AMM.",
	AMM_SoundPack_Desc = "Adiciona efeitos sonoros que podem ser gerados.",
	AMM_KerryPP_Desc = "Adiciona uma nova aparência nua.",
	AMM_BenjaminStonePP_Desc = "Adiciona uma nova aparência nua.",
	AMM_RiverPP_Desc = "Adiciona uma nova aparência nua.",
	AMM_YorinobuPP_Desc = "Adiciona uma nova aparência nua.",
	AMM_LizzyIncognito_Desc = "Adiciona uma nova aparência.",
	AMM_MeredithXtra_Desc = "Adiciona uma nova aparência.",
	AMM_DelamainFix_Desc = "Adiciona corpo inteiro ao Delamain.",
	AMM_HanakoNoMakeup_Desc = "Permite que AMM remova a maquiagem de Hanako ao usar Aparência Personalizada.",
	AMM_JudyBodyRevamp_Desc = "Substitui o corpo de Judy por um novo e melhorado.",
	AMM_PanamBodyRevamp_Desc = "Substitui o corpo do Panam por um novo e melhorado.",
	AMM_MistyBodyRevamp_Desc = "Substitui o corpo de Misty por um novo e melhorado.\nBaixe-o na página Nexus da AMM.",
	AMM_1VesHanakoFixedBodyNaked_Desc = "Substitui o corpo de Hanako por um novo e melhorado.",
	AMM_PinkyDudeANIMFacialExpressionsFemV_Desc = "Ativa ferramentas de expressões faciais no Female V",
	AMM_PinkyDudeANIMFacialExpressionsMaleV_Desc = "Ativa ferramentas de expressões faciais no Male V",
	AMM_DinoTattooFixArchive_Desc = "Substitui malha e textura.",
	AMM_SongbirdBodyFixArchive_Desc = "Substitui o corpo para corrigir a área cinzenta. Ainda não é perfeito.",
	AMM_RitaWheelerCombatEnablerArchive_Desc = "Substitui o arquivo de entidade para permitir animações de combate.",
	AMM_CheriAppearances_Desc = "Adiciona novas aparências. Baixe-o na página Nexus da AMM.",
	AMM_BryceNaked_Desc = "Adiciona uma nova aparência nua. Baixe-o na página Nexus da AMM.",
	AMM_EvelynNaked_Desc = "Corrige seu corpo para permitir a aparência nua. Baixe-o na página Nexus da AMM.",
	AMM_SaburoAppearances_Desc = "Adiciona novas aparências. Baixe-o na página Nexus da AMM.",
	AMM_TbugAppearances_Desc = "Adiciona novas aparências. Baixe-o na página Nexus da AMM.",
	AMM_8ug8eagAppearances_Desc = "Adiciona novas aparências. Baixe-o na página Nexus da AMM.",
	
	--Equipments (There is a Function Error(nil value) in this section, These are just labels that are not connected to any localizable strings in the file)
	Fists = "Punhos", --Line 2377 
	Katana = "Katana",
	Mantis_Blades = "Lâminas de Louva-a-deus",
	Machete = "Facão",
	Hammer = "Martelo",
	Baton = "Bastão",
	Knife = "Faca",
	Crowbar = "Pé de cabra",
	Baseball_Bat = "Taco de beisebol",
	Assault_Rifle = "Fuzil de assalto",
	Sidewinder = "Sidewinder",
	Sniper_Rifle = "Rifle de atirador",
	Shotgun = "Espingarda",
	SMG = "Submetralhadora",
	Handgun = "Revólver", --Line 2391
	
	--Warning / Info / Tooltip
	Warn_CantSave_BlacklistedAppearance = "Você não pode salvar uma aparência na lista negra!",
	Warn_ConfirmDeleteSavedAppearances = "Tem certeza de que deseja excluir todas as suas aparências salvas?",
	Warn_ConfirmDeleteBlacklistedAppearances = "Tem certeza de que deseja excluir todas as suas aparições na lista negra?",
	Warn_ConfirmDeleteSavedDespawns = "Tem certeza de que deseja excluir todos os seus despawns salvos?",
	Warn_ConfirmDeleteAppearanceTriggers = "Tem certeza de que deseja excluir todos os seus gatilhos de aparência?",
	Warn_ConfirmDeleteCurrentAppearance = "Tem certeza de que deseja excluir sua predefinição ativa atual?",
	Warn_WeaponizeNpcAnimationIssues = "Nem todo NPC terá as animações necessárias para usar todo tipo de arma. Podem ocorrer poses em T e animações incorretas.\nTem certeza de que deseja ativá-lo?",
	Warn_ConfirmEnableExperimentalAndSave_Info = "Tem certeza de que deseja ativar os recursos experimentais? AMM pode não funcionar conforme o esperado. Use-o por sua conta e risco!",
	Warn_DeleteFavoritesAskWhichOne_Info = "Se você tem certeza de que deseja excluir todos os seus favoritos, selecione qual deles abaixo:",
	Popup_Error_Title = "Erro",
	Button_Ok = "Ok",
	Popup_FavoriteName = "Nome favorito",
	Popup_RenamePreset = "Renomear predefinição",
	Popup_RenameProp = "Renomear adereço",
	Editor_Title = "Editor de Tema",
	Editor_Field_ThemeName = "Nome do tema",
	Editor_Hint_InsertThemeName = "Insira o novo nome do tema",
	Error_ThemeNameExists = "O nome do tema já existe",
}
