return {

    -- >> SCAN TAB
	BeginItem_TabNameScan = "สแกน",
	
	--Button
	Button_CyclesAppearances = "ลักษณะของวงจร",
	Button_SavesAppearance = "บันทึกลักษณะที่ปรากฏ",
	Button_ClearSavedAppearance = "ล้างลักษณะที่ปรากฏที่บันทึกไว้",
	Button_UnlockDoor = "สลับการล็อคประตู",
	Button_RestoreAccess = "คืนค่าการเข้าถึง",
	Button_UnlockVehicle = "ปลดล็อคยานพาหนะ",
	Button_RepairVehicle = "ซ่อมรถ",
	Button_OpenCloseDoors = "เปิด/ปิดประตู",
	Button_OpenCloseWindows = "เปิด/ปิดหน้าต่าง",
	Button_ToggleEngine = "สลับเครื่องยนต์",
	Button_ToggleAIDriver = "สลับไดรเวอร์ AI",
	Button_ToggleCamera = "สลับกล้อง",
	Button_ToggleRadio = "สลับวิทยุ",
	Button_NextRadioStation = "สถานีวิทยุถัดไป",
	Button_TargetMountedVehicle = "ยานพาหนะที่ติดตั้งเป้าหมาย",
	Button_AssignSeats = "กำหนดที่นั่ง",
	Button_Assign = "มอบหมาย",
	Button_Reset = "รีเซ็ต",
	Button_FakeDie = "ตายปลอม",
	Button_SmallCopy = "คัดลอก",
	
    --Button Label
	Button_Label_Unfollower = "ผู้เลิกติดตาม",
	Button_Label_Follower = "ผู้ติดตาม",
	Button_Label_SaveDespawn = "บันทึกเดสปอว์น",
	Button_Label_ClearSavedDespawn = "ล้าง Despawn ที่บันทึกไว้",
	Button_LabelLockTarget = "ล็อคเป้าหมาย",
	Button_LabelUnlockTarget = "ปลดล็อคเป้าหมาย",
	Label_AddToSpawnFavs = "เพิ่มในรายการโปรดที่วางไข่ได้",
	Label_RemoveFromSpawnFavs = "ลบออกจากรายการโปรดที่วางไข่ได้",
	
    --Checkbox
	Checkbox_SavedDespawnsActive = "Despawns ที่บันทึกไว้ใช้งานอยู่",
	Checkbox_KeepAssigned = "ให้ได้รับมอบหมายเมื่อเปลี่ยนรถ",
	
    --Warning / Info / Tool Tip
	WarnTextAI_FastTravel = "เลือกจุดเดินทางด่วนบนแผนที่ของคุณเพื่อไปต่อ",
	WarnText_DontReloadMods = "อย่าใช้โหลด Mod ทั้งหมดซ้ำ\nโปรดโหลดเกมบันทึกของคุณใหม่หรือย้ายไปยังพื้นที่อื่น",
	Warning_NoTarget_Desc = "ไม่มีเป้าหมาย! ดูที่ NPC ยานพาหนะ หรือวัตถุเพื่อเริ่มต้น",
	ToolTip_DisableCheckboxReloadSave_AbleTotargetClearSavedDespawns = "ปิดการใช้งานช่องทำเครื่องหมายนี้และโหลดบันทึกของคุณใหม่เพื่อให้สามารถกำหนดเป้าหมายล้าง Despawn ที่บันทึกไว้ได้",
	
    --Text
	Build_Mode = "โหมดสร้าง",
	Speed = "ความเร็ว:",
	Search = "ค้นหา",
	Clear = "ชัดเจน",
	Player = "ผู้เล่น",
	Saved = "บันทึกแล้ว",
	Saved_ = "บันทึกแล้ว_",
	Current = "ปัจจุบัน",
	Current_ = "ปัจจุบัน",
	Select_Seat = "เลือกที่นั่ง",
	Target_Info = "ข้อมูลเป้าหมาย",
	Target_Actions = "การกระทำเป้าหมาย",
	No_Appearances = "ไม่มีการปรากฏตัว",
	No_Target = "ไม่มีเป้าหมาย",
	Favorite_Appearance = "รูปลักษณ์ที่ชื่นชอบ",
	Unfavorite_Appearance = "รูปลักษณ์ที่ไม่พึงประสงค์",
	Blacklist_Appearance = "การปรากฏตัวของบัญชีดำ",
	Unblacklist_Appearance = "ยกเลิกการแบล็คลิสต์ลักษณะที่ปรากฏ",
	Saved_Appearance = "ลักษณะที่บันทึกไว้:",
	Current_Appearance = "ลักษณะที่ปรากฏในปัจจุบัน:",
	List_of_Appearances = "รายชื่อที่ปรากฏ",
	Appearance_Trigger = "ทริกเกอร์ลักษณะที่ปรากฏ",
	None = "ไม่มี",
	Default = "ค่าเริ่มต้น",
	Zone = "โซน",
	Area = "พื้นที่",
	Position = "ตำแหน่ง",

	
	-- >> SPAWN TAB
	BeginItem_TabNameSpawn = "วางไข่",
	
	--Button
	Button_Refresh = "รีเฟรช",
	Button_Save = "บันทึก",
	Button_Confirm = "ยืนยัน",
	Button_Cancel = "ยกเลิก",
	Button_SmallSave = "บันทึก",
	Button_SmallRespawn = "เกิดใหม่",
	Button_SmallDespawn = "Despawn",
	Button_SmallDespawn_WithSpace = "Despawn",
	Button_SmallTarget = "เป้าหมาย",
	Button_SmallEquipment = "อุปกรณ์",
	Button_LabelHostile = "ไม่เป็นมิตร",
	Button_LabelFriendly = "เป็นกันเอง",
	
    --Button Label
	Label_Favorite = "ของโปรด",
	Label_Unfavorite = "ไม่เป็นที่ชื่นชอบ",
	
    --Checkbox
    --Warning / Info / Tool Tip
	Warn_PlayerInMenu = "ผู้เล่นในเมนู",
	Warn_AMMonlyfunctions_ingame = "AMM ใช้งานได้เฉพาะในเกมเท่านั้น",
	Warn_SpawnWorksInGame = "การวางไข่ใช้ได้เฉพาะในเกมเท่านั้น",
	Warn_InitError = "ข้อผิดพลาดในการเริ่มต้น",
	Warn_InitError_Info = "โปรดตรวจสอบ AppearanceMenuMod.log สำหรับข้อมูลเพิ่มเติม",
	
    --Text
	Active_Spawns = "วางไข่ที่ใช้งานอยู่",
	NoActiveSpawns = "ไม่มีการวางไข่ที่ใช้งานอยู่",
	Select_To_Spawn = "เลือกเพื่อวางไข่",
	No_Results = "ไม่มีผลลัพธ์",
	ItsEmpty = "ว่างเปล่า :(",
	Existing_Name = "ชื่อที่มีอยู่",
	Name = "ชื่อ",
	
	
	
	-- >> SWAP TAB
	BeginItem_TabNameSwap = "สลับ",
	
	--Button
	Button_SmallRevert = "เปลี่ยนกลับ",
	
    --Button Label
    --Checkbox
    --Warning / Info / Tool Tip
	Warn_ReloadSaveUpdateChanges = "โหลดเกมบันทึกของคุณซ้ำเพื่ออัปเดตการเปลี่ยนแปลง!",
	Warn_NeedReloadSaveUpdateChanges = "คุณจะต้องโหลดบันทึกของคุณซ้ำเพื่ออัปเดตการเปลี่ยนแปลง",
	Warn_ReplacerSwap = "คุณไม่สามารถเปลี่ยนตัวทดแทนได้! ใช้แท็บเครื่องมือในโหมดภาพถ่ายเพื่อกำหนดเป้าหมาย จากนั้นเปลี่ยนรูปลักษณ์จากแท็บวางไข่หรือเครื่องมือเป้าหมาย",
	Warning = "คำเตือน",
	Warning2 = "คำเตือน:",
	SaveSwap_Tooltip = "บันทึกการแลกเปลี่ยนของคุณเพื่อเก็บไว้หลังจากโหลดเกมของคุณใหม่",
	
    --Text
	CantSwapReplacer = "ไม่สามารถเปลี่ยนตัวทดแทนได้",
	Active_Model_Swaps = "การสลับโมเดลที่ใช้งานอยู่",
	Save = "บันทึก",
	Restore = "คืนค่า",
	Current_Target = "เป้าหมายปัจจุบัน:",
	Target_ID = "รหัสเป้าหมาย:",
	SelectSwap_CurrentTarget = "เลือกเพื่อสลับกับเป้าหมายปัจจุบัน:",
	NoNPC_LookNPC = "ไม่พบ NPC! ดูที่ NPC เพื่อเริ่มต้น",
	
	-- Locations Categories
	Residences = "ที่อยู่อาศัย",
	ArasakaAndCorpo = "อาราซากะ แอนด์ คอร์โป",
	ClubsAndBars = "คลับและบาร์",
	HotelsAndPleasure = "โรงแรมและความสุข",
	UndergroundAndCrime = "ใต้ดินและอาชญากรรม",
	GovernmentAndSecurity = "รัฐบาลและความมั่นคง",
	StoryAndUnique = "เรื่องราวและเอกลักษณ์",
	Ripperdocs = "ริปเปอร์ด็อกส์",
	LandmarksAndOpenWorld = "สถานที่สำคัญและโลกเปิด",
	SpoilersAndHidden = "สปอยเลอร์และซ่อนเร้น",
	UserLocations = "สถานที่ตั้งของผู้ใช้",
	
	
	-- >> DECOR TAB
	BeginItem_TabDecor = "ตกแต่ง",
	BeginItem_TabPresets = "ค่าที่ตั้งล่วงหน้า",
	Begin_ComboPresets = "ค่าที่ตั้งล่วงหน้า",
	
	--Button
	Button_SmallClone = "โคลน",
	Button_SmallRemove = "ลบ##",
	Button_SmallRename = "เปลี่ยนชื่อ##",
	Button_SmallUpdate = "อัปเดต##",
	Button_SmallCancel = "ยกเลิก",
	Button_Frame = "กรอบ",
	
    --Button Label
	Button_LabelHide = "ซ่อน",
	Button_LabelUnhide = "ยกเลิกการซ่อน",
	
    --Checkbox
    --Warning / Info / Tool Tip
	Warn_PersistPropSave = "วางไข่อุปกรณ์ประกอบฉากเพื่อตกแต่งบ้านของคุณหรือทุกที่ที่คุณต้องการให้พอใจ! บันทึกอุปกรณ์ประกอบฉากเพื่อให้คงอยู่!",
	Warn_DespawnInProgress_PleaseWait = "กำลังดำเนินการ Despawn โปรดรอ.",
	Warn_PresetsFolder_Info = "การตั้งค่าล่วงหน้าของผู้ใช้จะถูกบันทึกไว้ในโฟลเดอร์ AppearanceMenuMod/User/Decor",
	Warn_CustomPresets_Info = "ค่าที่ตั้งล่วงหน้านี้รวมถึงอุปกรณ์ประกอบฉากแบบกำหนดเอง",
	Warn_CustomPropsModders_Info = "อุปกรณ์ประกอบฉากที่กำหนดเองทำโดย:",
	Warn_GamepadDirectMode_Info = "ช่วยให้สามารถทำงานร่วมกับโหมด Direct ได้ดีขึ้นเมื่อใช้ gamepad นอกจากนี้ยังเปิดใช้งานหน้าต่างข้อมูลขนาดเล็กที่ติดอยู่",
	Warn_PresetTriggerDistanceFar = "การตั้งค่าเป็นไกลอาจทำให้เกิดปัญหาด้านประสิทธิภาพ",
	
    --Text
	MovingAll_PropsTo_SavedProps = "ย้ายอุปกรณ์ประกอบฉากทั้งหมดไปยังอุปกรณ์ประกอบฉากที่บันทึกไว้",
	SelectPropSpawn = "เลือก Prop To Spawn:",
	Spawned_Props = "อุปกรณ์ประกอบฉากที่เกิด",
	New_Preset = "พรีเซ็ตใหม่",
	No_Preset_Available = "ไม่มีค่าที่ตั้งไว้ล่วงหน้า",
	Preset_TriggerDistance = "ระยะทางทริกเกอร์ที่ตั้งไว้ล่วงหน้า",
	MovingSavedProps = "ย้าย %s ไปยังอุปกรณ์ประกอบฉากที่บันทึกไว้",
	UpdateTag = "อัปเดตแท็ก",
	Categories = "หมวดหมู่",
	Decorating = "ตกแต่ง",
	Decor_Tabs = "แท็บตกแต่ง",
	Saved_Props = "อุปกรณ์ประกอบฉากที่บันทึกไว้",
	Show_Nearby_Only = "แสดงสถานที่ใกล้เคียงเท่านั้น",
	Show_Lights_Only = "แสดงไฟเท่านั้น",
	Show_LockedTarget_Only = "แสดงเป้าหมายที่ถูกล็อคเท่านั้น",
	Show_Customizable_Only = "แสดงการปรับแต่งเท่านั้น",
	Show_CustomProps_Only = "แสดงอุปกรณ์ประกอบฉากแบบกำหนดเองเท่านั้น",
	ShowOnMap = "แสดงบนแผนที่",
	Rename = "เปลี่ยนชื่อ",
	Delete = "ลบ",
	Backup = "สำรองข้อมูล",
	Merge = "ผสาน",
	Save_All = "บันทึกทั้งหมด",
	Despawn_All = "Despawn ทั้งหมด",
	Save_ToSpecific_Tag = "บันทึกลงในแท็กเฉพาะ",
	Saved_Props2 = "อุปกรณ์ประกอบฉากที่บันทึกไว้:",
	Move_To_Tag = "ย้ายไปที่แท็ก",
	HideFromMap = "ซ่อนจากแผนที่",
	RemovingAllPropsFromTag = "กำลังนำอุปกรณ์ประกอบฉากทั้งหมดออกจากแท็ก...",
	RemoveAllProps = "ลบอุปกรณ์ประกอบฉากทั้งหมด",
	RemoveHomeMarkerMap = "ลบเครื่องหมายบ้านออกจากแผนที่",
	TeleportToLocation = "เทเลพอร์ตไปยังที่ตั้ง",
	TeleportToTrigger = "เทเลพอร์ตไปยังทริกเกอร์",
	TeleportToMark = "เทเลพอร์ตถึงมาร์ค",
	UpdateTagLocation = "อัปเดตตำแหน่งแท็ก",
	SharePresetWith_ThisTagOnly = "แชร์ค่าที่ตั้งล่วงหน้าด้วยแท็กนี้เท่านั้น",
	SavedPresetFolder_Info = "บันทึกค่าที่ตั้งล่วงหน้าไว้ที่โฟลเดอร์ AppearanceMenuMod/User/Decor",
	NoProps_WithThese_Conditions = "ไม่มีอุปกรณ์ประกอบฉากที่มีเงื่อนไขเหล่านี้",
	AddHomeMarkerMap = "เพิ่มเครื่องหมายบ้านลงในแผนที่",
	Distance = "ระยะทาง",
	Total_Props = "อุปกรณ์ประกอบฉากทั้งหมด:",
	Type_Tag_here = "พิมพ์แท็กที่นี่",
	In_World = "ในโลก",
	Tags = "แท็ก",
	Tag = "แท็ก",
	Both = "ทั้งสองอย่าง",	
	
	-- >> POSES TAB
	BeginItem_TabPoses = "โพสท่า",
	
	--Button
	Button_SmallCopyClipboard = "คัดลอกไปยังคลิปบอร์ด",
	
    --Button Label
    --Checkbox
    --Warning / Info / Tool Tip
    --Text
	Active_Animations = "ภาพเคลื่อนไหวที่ใช้งานอยู่",
	ShowHistory = "แสดงประวัติ",
	ClearHistory = "ล้างประวัติ",
	SelectPoseForCurrentTarget = "เลือกท่าทางสำหรับเป้าหมายปัจจุบัน:",
	LastUsedPoses = "โพสท่าที่ใช้ล่าสุด",
	
	
	
	-- >> TOOLS TAB
	BeginItem_TabTools = "เครื่องมือ",
	BeginItem_TabPhotoModeNibblesReplacer = "โหมดถ่ายภาพทดแทน Nibbles",
	BeginCombo_LookAt = "ดูที่",
	BeginCombo_WeatherControl = "การควบคุมสภาพอากาศ",
	
	--Button
	Button_SkipFrame = "ข้ามเฟรม",
	Button_ToggleLight = "สลับแสง",
	Button_ResetScale = "รีเซ็ตมาตราส่วน",
	Button_ShowAsLookAtTarget = "แสดงเป็นดูที่เป้าหมาย",
	Button_ResetLookAtTarget = "รีเซ็ตการมองที่เป้าหมาย",
	Button_TogglePrimaryWeapon = "ติดตั้งอาวุธหลัก",
	Button_ToggleSecondaryWeapon = "ติดตั้งอาวุธรอง",
	Button_GiveCurrentEquippedWeapon = "มอบอาวุธที่ติดตั้งในปัจจุบัน",
	Button_SmallReset = "รีเซ็ต",
	Button_ResetToPlayer = "รีเซ็ตเป็นผู้เล่น",
	Button_ClearSaved = "ล้างที่บันทึกไว้",
	Button_Cyberpsycho = "สลับ Cyberpsycho",
	Button_ProtectNPCfromActions = "ปกป้อง NPC จากการกระทำ",
	Button_AllFriendly = "เป็นกันเองทั้งหมด",
	Button_AllHostile = "ไม่เป็นมิตรทั้งหมด",
	Button_AllFollower = "ผู้ติดตามทั้งหมด",
	Button_AllFakeDie = "ปลอมตายทั้งหมด",
	Button_AllDie = "ตายทั้งหมด",
	Button_AllDespawn = "เดสปอว์นทั้งหมด",
	Button_InvMachineGun = "ปืนกล",
	Button_InvSpeed2 = "ความเร็ว",
	Button_ToggleMakeup = "สลับการแต่งหน้า",
	Button_TogglePiercings = "สลับการเจาะ",
	Button_ToggleSeamfix = "สลับ Seamfix",
        Button_TargetV = "เป้าหมาย วี",
        Button_Target = "เป้าหมาย",
        Button_TeleportToLocation = "เทเลพอร์ตไปยังที่ตั้ง",
        Button_TeleportToTrigger = "เทเลพอร์ตไปยังทริกเกอร์",
        Button_TeleportToMark = "เทเลพอร์ตถึงมาร์ค",
        Button_RandomLocation = "สุ่ม",
        Button_ShareCurrentLocation = "แบ่งปันตำแหน่งปัจจุบัน",
	Button_GoBackToLastLocation = "กลับไปยังตำแหน่งล่าสุด",
	Button_DeleteSelectedUserLocation = "ลบตำแหน่งผู้ใช้ที่เลือก",
	
	--Slider / Drag 
	Slider_HeadStiffness = "อาการปวดหัว",
	Slider_HeadPoseOverride = "แทนที่ท่าโพสศีรษะ",
	Slider_ChestStiffness = "อาการแน่นหน้าอก",
	Slider_ChestPoseOverride = "แทนที่ท่าหน้าอก",
	Slider_SlowMotion = "สโลว์โมชั่น",
	Slider_DefaultAperture = "รูรับแสงเริ่มต้น",
	Slider_DefaultFieldofView = "มุมมองเริ่มต้น",
	Slider_MovementSpeed = "ความเร็วในการเคลื่อนที่",
	Drag_MovementSpeed = "ความเร็วในการเคลื่อนที่",
	
    --Button Label
	Button_Label_PauseTimeProgression = "ความก้าวหน้าของเวลาหยุดชั่วคราว",
	Button_Label_UnpauseTimeProgression = "ยกเลิกการหยุดความก้าวหน้าของเวลาชั่วคราว",
	Button_Label_UnfreezeTime = "เลิกตรึงเวลา",
	Button_Label_FreezeTime = "แช่แข็งเวลา",
	Button_Label_OpenLightSettings = "เปิดการตั้งค่าแสง",
	Button_Label_UpdateLightTarget = "อัพเดตเป้าหมายแสง",
	Button_Label_Activate = "เปิดใช้งาน",
	Button_Label_Deactivate = "ปิดการใช้งาน",
	Button_Label_ChangeToCrouchStance = "เปลี่ยนเป็นท่าทางหมอบคลาน",
	Button_Label_ChangeToStandStance = "เปลี่ยนเป็นยืนท่าทาง",
	Button_Label_PickUpTarget = "เลือกเป้าหมาย",
	Button_Label_DropTarget = "วางเป้าหมาย",
	Button_Label_FreezeTarget = "แช่แข็งเป้าหมาย",
	Button_Label_UnfreezeTarget = "เลิกตรึงเป้าหมาย",
	Button_Label_OpenTargetTools = "เปิดเครื่องมือเป้าหมาย",
	Button_Label_CloseTargetTools = "ปิดเครื่องมือเป้าหมาย",
	
    --Checkbox
    --Warning / Info / Tool Tip
	Warn_FileNotFound_CollabsFolder_Error = "ไม่พบไฟล์ในโฟลเดอร์ Collabs",
	Warn_ShowXYZ_Orientation_Info = "แสดงลูกศร X, Y และ Z เพื่อให้วางแนวได้ง่ายขึ้นเมื่อเคลื่อนที่เป้าหมาย",
	Warn_LookAtCamera_OptionOff_Info = "ปิดตัวเลือก Look At Camera หนึ่งครั้งหลังจากเปลี่ยนการตั้งค่านี้",
	Warn_DisableLookAtCamera_PhotoMode_Info = "ปิดการใช้งาน 'Look At Camera' ในโหมดภาพถ่ายหนึ่งครั้งเพื่อให้มีผล",
	Warn_RequiresRestart_Info = "ต้องรีสตาร์ทเกมจึงจะมีผล",
	Warn_SlowMotion_PhotoMode_Info = "การเคลื่อนไหวช้าในโหมดภาพถ่ายจะทำงานเฉพาะเมื่อคุณยกเลิกการหยุดชั่วคราวโดยใช้ IGCS",
	Warn_WeatherControl_RequireCodeware = "การควบคุมสภาพอากาศต้องใช้โค้ดแวร์ 1.4+",
	Warn_StopNpc_UnequipWeapon_Info = "การดำเนินการนี้จะหยุด NPC จากการถอดอาวุธที่คุณให้ไว้ หมายเหตุ: NPC จะยังคงถอดอุปกรณ์ตามต้องการในระหว่างการต่อสู้",
	Warn_OutOfCombat_NpcUnequip_Info = "หมายเหตุ: เมื่อออกจากการต่อสู้ NPC จะถอดอาวุธที่กำหนดออกทันที",
	Warn_Photomode_UnfreezeSkipFrames_Info = "ในโหมดภาพถ่าย Unfreeze Target จะข้ามเฟรมในท่าทางแบบเคลื่อนไหว หากต้องการฟังก์ชันหยุดการทำงานเต็มรูปแบบ (ไม่) คุณต้องใช้ Otis Camera Tools (IGCS)",
	Warn_UserLocationsFolder_Info = "ตำแหน่งของผู้ใช้จะถูกบันทึกไว้ในโฟลเดอร์ AppearanceMenuMod/User/Locations",
	Warn_SeeMoreAction_Info = "กำหนดเป้าหมาย V หรือ NPC เพื่อดูการดำเนินการเพิ่มเติม",
	Warn_SeeMoreActionProp_Info = "กำหนดเป้าหมาย NPC หรือ Prop เพื่อดูการดำเนินการเพิ่มเติม",
	Warn_SeamfixPiercingToggle_Info = "การดำเนินการนี้จะบันทึกสถานะสลับการแต่งหน้า การเจาะ และการแก้ไขตะเข็บจนกว่าคุณจะปิดเกม",
	Warn_PassiveMode_Info = "ศัตรูจะยังคงโจมตีคุณหากคุณกระตุ้นการต่อสู้",
	Warn_TppCameraGameplay_Info = "กล้อง TPP ไม่เหมาะกับการเล่นเกมทั่วไป แต่สนุกกับการเดินเล่น ;)",
	Warn_AnimatedHead_PhotoMode_Info = "การแสดงออกในโหมดภาพถ่ายจะไม่ทำงานในขณะที่เปิดใช้งาน Animated Head",
	Warn_ToolsOnly_WorksIngame = "เครื่องมือใช้งานได้เฉพาะในเกมเท่านั้น",
	Warn_InvButtonMachineGun_Info = "คุณพบมันแล้ว! ปืนกลหนักถูกเพิ่มเข้าไปในอุปกรณ์",
	Warn_InvButton_Info = "คุณพบมันแล้ว! Fast Motion มีให้บริการแล้ว",
	InvButtonTip = "ถ้าฉันคลิกที่นี่ล่ะ?",
	InvButtonTip2 = "การคลิกที่นี่ไม่ได้ทำอะไรเลย!",
	InvButtonTip3 = "อย่าคลิกคุณถูกเตือน!",
	
    --Text
	Facial_Expression = "การแสดงออกทางสีหน้า",
	Expressions = "นิพจน์",
	Look_At = "ดูที่",
	Look_At_Camera = "ดูที่กล้อง:",
	Target_Tools = "เครื่องมือเป้าหมาย",
	Rotation = "การหมุน",
	Tilt_Rotation = "เอียง/หมุน",
	Mode = "โหมด:",
	Precision = "ความแม่นยำ",
	Relative = "ญาติ",
	Direct = "โดยตรง",
	AdvMovement = "โฆษณา การเคลื่อนไหว",
	ForceGivenWeapon = "อาวุธที่ให้มา",
	Scale = "สเกล",
	ProportionalMode = "โหมดสัดส่วน",
	General_Actions = "การดำเนินการทั่วไป",
	DisablePassiveMode = "ปิดการใช้งานโหมดพาสซีฟ",
	EnablePassiveMode = "เปิดใช้งานโหมดพาสซีฟ",
	EnableGodMode = "เปิดใช้งานโหมดพระเจ้า",
	DisableGodMode = "ปิดการใช้งานโหมดพระเจ้า",
	Infinite_Oxygen = "ออกซิเจนไม่มีที่สิ้นสุด",
	Select_Location = "เลือกสถานที่",
	Select_Expression = "เลือก นิพจน์",
	Select_Category = "เลือกหมวดหมู่",
	Teleport_Actions = "การดำเนินการเทเลพอร์ต",
	Use_Teleport_Animation = "ใช้เทเลพอร์ตแอนิเมชั่น",
        Filter_Locations = "กรองสถานที่",
        Locations = "สถานที่",
        Default_Locations = "ตำแหน่งเริ่มต้น",
        Collab_Locations = "สถานที่ทำงานร่วมกัน",
        Button_AddTag = "เพิ่มแท็ก",
	Button_FilterByTags = "กรองตามแท็ก",
	Button_Close = "ปิด",
	Favorite_Selected_Location = "รายการโปรดที่เลือกสถานที่",
	Unfavorite_Selected_Location = "ตำแหน่งที่เลือกไม่เป็นที่ชื่นชอบ",
	Edit_Selected_Location = "แก้ไขตำแหน่งที่เลือก",
	Locations_Favorites = "--------- รายการโปรด ----------",
	Locations_UserLocs = "------- ที่ตั้งของผู้ใช้ -------",
	Locations_DefaultLocs = "----------- ค่าเริ่มต้น ----------",
	Share_Location = "แบ่งปันตำแหน่ง",
	Edit_Location = "แก้ไขสถานที่",
	TimeWeather_Actions = "การดำเนินการเวลาและสภาพอากาศ",
	TimeofDay = "เวลาของวัน",
	Time_Actions = "การดำเนินการตามเวลา",
	Rain = "ฝน",
	Light_Rain = "ฝนตกปรอยๆ",
	Cloudy = "มีเมฆมาก",
	Fog = "หมอก",
	Heavy_Clouds = "เมฆหนา",
	Light_Clouds = "เมฆแสง",
	Pollution = "มลพิษ",
	Sandstorm = "พายุทราย",
	Sunny = "ซันนี่",
	Toxic_Rain = "ฝนพิษ",
	Deep_Blue = "ดีพบลู",
	Squat_Morning = "สควอชยามเช้า",
	Cloudy_Morning = "เช้ามีเมฆมาก",
	Rainy_Night = "คืนฝนตก",
	Courier_Clouds = "เมฆคูเรียร์",
	Cursor_LockState = "ล็อคสถานะ",
	PhotoMode_NibblesReplacer = "โหมดถ่ายภาพทดแทน Nibbles",
	PhotoModeEnhancements = "การปรับปรุงโหมดภาพถ่าย",
	Button_ResetReplacerDatabase = "รีเซ็ตฐานข้อมูลผู้แทนที่",
	DisablePhotoModeCursor = "ปิดการใช้งานเคอร์เซอร์โหมดภาพถ่าย",
	TPPCamera_Position = "ตำแหน่งกล้อง TPP",
	AnimatedHeadin_PhotoMode = "หัวเคลื่อนไหวในโหมดภาพถ่าย",
	LockLook_AtCamera = "ล็อคมองที่กล้อง",
	UnlockLook_AtCamera = "ปลดล็อคมองที่กล้อง",
	Save_Toggles_State = "บันทึกสถานะสลับ",
	Toggle_V_Head = "สลับหัว V",
	Toggle_TPP_Camera = "สลับกล้อง TPP",
	Target_Nibbles = "แทะเป้าหมาย",
	Target_Replacer = "เป้าหมายทดแทน",
	Left = "ซ้าย",
	Left_Close = "ปิดซ้าย",
	Right = "ถูกต้อง",
	Right_Close = "ปิดขวา",
	Center_Close = "ปิดศูนย์",
	Center_Far = "ศูนย์ไกล",
	Front_Close = "ปิดหน้า",
	Front_Far = "ด้านหน้าไกล",
	All = "ทั้งหมด",
	Head_Only = "หัวเท่านั้น",
	Eyes_Only = "ดวงตาเท่านั้น",
	Movement = "การเคลื่อนไหว",
	V_Actions = "วี แอคชั่น",
	Invisible_V = "วีที่มองไม่เห็น",
	LikeGTA_byGTATravel = "โดย GTA Travel",
	EnableSpawnedProps = "เปิดใช้งานอุปกรณ์ประกอบฉากที่เกิด",
	LightControl = "การควบคุมแสง",
	Equipment = "อุปกรณ์",
	
	-- >> DIRECTOR TAB
	BeginItem_TabNameDirector = "ผู้อำนวยการ",
	BeginItem_TabNameTriggers = "ทริกเกอร์",
	BeginCombo_StartAppearance = "เริ่มรูปลักษณ์",
	BeginCombo_EndAppearance = "สิ้นสุดการปรากฏตัว",
	BeginCombo_Type = "ประเภท",
	BeginCombo_GoToTarget = "ไปที่เป้าหมาย",
	BeginCombo_PlayVoice = "เล่นเสียง",
	BeginCombo_Attack = "โจมตี",
	BeginCombo_Triggers = "ทริกเกอร์",
	BeginCombo_Scripts = "สคริปต์",
	
	--Button
	Button_Yes = "ใช่",
	Button_No = "ไม่",
	Button_SaveChangesOnly = "บันทึกการเปลี่ยนแปลงเท่านั้น",
	Button_RemoveMark = "ลบมาร์คออก",
	Button_EditMark = "แก้ไข มาร์ค",
        Button_MoveMark = "ย้ายมาร์ค.",
        Button_MoveUp = "เลื่อนขึ้น",
        Button_MoveDown = "เลื่อนลง",
        Button_NewMark = "นิวมาร์ก",
	Button_AddActor = "เพิ่มนักแสดง",
	Button_RemoveActor = "ลบนักแสดง",
	Button_ChangeActor = "เปลี่ยนนักแสดง",
	Button_RadioOnlyOne = "เพียงหนึ่งเดียว",
	Button_RadioRandom = "สุ่ม",
	Button_RadioSequential = "ตามลำดับ",
	Button_SaveTrigger = "บันทึกทริกเกอร์",
	Button_NewCamera = "กล้องใหม่",
	Button_NewScript = "สคริปต์ใหม่",
	Button_DragSpeed = "ความเร็ว",
	Button_ToggleMarker = "สลับเครื่องหมาย",
	Button_TestPose = "ท่าทดสอบ",
	Button_StopPose = "หยุดโพส",
	
    --Button Label
	Button_Label_PlayScript = "เล่นสคริปต์",
	Button_Label_StopScript = "หยุดสคริปต์",
	Button_Label_Stopping = "กำลังหยุด...",
	Button_Label_Restarting = "กำลังรีสตาร์ท...",
	Button_Label_AddMark = "เพิ่มมาร์ค",
	Button_Label_SaveWNewPos = "บันทึกด้วยตำแหน่งใหม่",
	
    --Checkbox
    --Warning / Info / Tool Tip
	Warn_ActorSingleMark_Info = "นักแสดงจะอยู่บนมาร์คคนเดียว",
	Warn_ActorRandomMark_Info = "นักแสดงจะสุ่มย้ายไปมาระหว่างมาร์ค",
	Warn_ActorSequentialMark_Info = "นักแสดงจะย้ายไปมาระหว่างเครื่องหมายตามลำดับตัวเลข",
	Warn_DeleteScript_Info = "คุณแน่ใจหรือไม่ว่าต้องการลบสคริปต์นี้",
	Warn_CloseCamForMove_Info = "ปิดเมนูเพื่อให้สามารถย้ายกล้องได้",
	Warn_CreateScriptsDesc_Info = "สร้างสคริปต์เพื่อเพิ่ม แต่งกาย และกำกับนักแสดงให้แสดงสำหรับเครื่องจักร ภาพหน้าจอ และบทบาทสมมุติ",
	Warn_PremadeScriptsDesc_Info = "สร้างทริกเกอร์เพื่อเปิดใช้งานสคริปต์ที่สร้างไว้ล่วงหน้าในการติดต่อ",
	Warn_CreateCamera_FovZoomDesc_Info = "สร้างกล้องเพื่อเคลื่อนที่ได้อย่างอิสระ ตั้งค่ามุมมองและระดับการซูมต่างๆ",
	Warn_ShowMarksLocations_Info = "แสดงไอคอนที่มองเห็นได้ที่ตำแหน่งมาร์ค",
	Warn_AutoTalkNpc_Info = "สิ่งนี้จะทำให้ NPC พูดทุกๆนาทีเมื่ออยู่ในระยะ (เฉพาะ NPC ที่เปล่งออกมาเท่านั้น)",
	Warn_DirectActorPlayerPosition_Info = "สร้างมาร์คที่ตำแหน่งผู้เล่นปัจจุบันเพื่อย้ายและกำกับนักแสดง",
	Warn_InMenuDirectorDesc = "ผู้กำกับใช้งานได้เฉพาะในเกมเท่านั้น",
	
    --Text
	DirectorMode = "โหมดผู้กำกับ",
	SelectActorToReplace = "เลือกนักแสดงที่จะแทนที่:",
	AddActorToCurrentScript = "เพิ่มนักแสดงในสคริปต์ปัจจุบัน:",
	FacialExpression_WithColon = "การแสดงออกทางสีหน้า:",
	FavoritePoses_WithColon = "โพสท่าที่ชอบ:",
	AddFavorites_Desc = "เพิ่มท่าโพสในรายการโปรดในแท็บท่าโพสก่อน",
	HoldDuration = "ถือระยะเวลา",
	Movement2 = "การเคลื่อนไหว:",
	Actions = "การดำเนินการ:",
	Actors = "นักแสดง",
	Editing = "การแก้ไข",
	AutoTalk = "พูดคุยอัตโนมัติ",
	ActorMarks = "นักแสดงมาร์ค",
	Current_Actors = "นักแสดงปัจจุบัน",
	Marks_Sequence = "ลำดับการทำเครื่องหมาย:",	
	ShowMarks = "แสดงเครื่องหมาย",
	Triggers = "ทริกเกอร์",
	NewTrigger = "ทริกเกอร์ใหม่",
	ShowTrigger = "แสดงทริกเกอร์",
	Title = "ชื่อเรื่อง",
	Select_Trigger = "เลือกทริกเกอร์",
	Select_Script = "เลือกสคริปต์",
	Delete_Trigger = "ลบทริกเกอร์",
	Triggers_On_Off = "ทริกเกอร์เปิด/ปิด",
	Running = "วิ่ง",
	Script_Running = "สคริปต์กำลังทำงาน...",
	Delete_Script = "ลบสคริปต์",
	RepeatInLoop = "ทำซ้ำในวง",
	ActivationRadius = "รัศมีการเปิดใช้งาน",
	Activate = "เปิดใช้งาน",
	Deactivate = "ปิดการใช้งาน",
	FOV = "FOV",
	Zoom = "ซูม",
	LockFrame = "ล็อคเฟรม",
	Walk = "เดิน",
	Sprint = "วิ่ง",
	Sequential = "ตามลำดับ",
	Cameras = "กล้อง",
	NodeView = "มุมมองโหนด",
	TeamA = "ทีมเอ",
	TeamB = "ทีมบี",
	
	
	
	-- >> SETTINGS TAB
	BeginItem_TabNameSettings = "การตั้งค่า",
	BeginItem_TabNameGeneral = "ทั่วไป",
	BeginItem_TabNameCompanions = "สหาย",
	BeginItem_TabNameUI = "ส่วนต่อประสานกับผู้ใช้",
	BeginItem_TabNameExperimental = "การทดลอง",
	BeginItem_TabNamePhotoMode = "โหมดภาพถ่าย",
	
	--Button
	Button_RevertAllModelSwaps = "เปลี่ยนกลับการแลกเปลี่ยนโมเดลทั้งหมด",
	Button_RespawnAll = "เกิดใหม่ทั้งหมด",
	Button_ForceDespawnAll = "บังคับให้ Despawn ทั้งหมด",
	Button_ClearFavorites = "ล้างรายการโปรด",
	Button_ClearAllSavedAppearances = "ล้างลักษณะที่ปรากฏที่บันทึกไว้ทั้งหมด",
	Button_ClearAllBlacklistedAppearances = "ล้างสิ่งที่ปรากฏอยู่ในบัญชีดำทั้งหมด",
	Button_ClearAllAppearanceTriggers = "ล้างทริกเกอร์ลักษณะที่ปรากฏทั้งหมด",
	Button_ClearAllSavedDespawns = "ล้าง Despawns ที่บันทึกไว้ทั้งหมด",
	Button_SmallCreateTheme = "สร้างธีม",
	Button_SmallDeleteTheme = "ลบธีม",
	Button_SmallSet = "ชุด",
	Button_ReloadAppearances = "โหลดลักษณะที่ปรากฏที่กำหนดเองอีกครั้ง",
	
    --Button Label
    --Checkbox
	Checkbox_SpawnAsCompanion = "วางไข่เป็นสหาย",
	Checkbox_SpawnAsFriendly = "วางไข่อย่างเป็นมิตร",
	Checkbox_InvulnerableCompanion = "สหายคงกระพัน",
	Checkbox_RespawnOnLaunch = "เกิดใหม่เมื่อเปิดตัว",
	Checkbox_LockTargetAfterSpawn = "ล็อคเป้าหมายหลังวางไข่",
	Checkbox_OpenTargetToolsAfterSpawn = "เปิดเครื่องมือเป้าหมายหลังจากวางไข่",
	Checkbox_DisplayAxisIndicatorByDefault = "แสดงตัวบ่งชี้แกนตามค่าเริ่มต้น",
	Checkbox_PhotoModeEnhancements = "การปรับปรุงโหมดภาพถ่าย",
	Checkbox_GodModeOnLaunch = "โหมดพระเจ้าเปิดตัว",
	Checkbox_PassiveModeOnLaunch = "โหมดพาสซีฟเมื่อเปิดตัว",
	Checkbox_StreamerMode = "โหมดสตรีมเมอร์",
	Checkbox_OpenWCETOverlay = "เปิดด้วยการซ้อนทับ CET",
	Checkbox_AutoResizingWindow = "หน้าต่างปรับขนาดอัตโนมัติ",
	Checkbox_ScanningReticle = "การสแกนเส้นเล็ง",
	Checkbox_FloatingTargetTools = "เครื่องมือเป้าหมายลอยตัว",
	Checkbox_TabHeaderDescriptions = "คำอธิบายส่วนหัวของแท็บ",
	Checkbox_ExpandFavoritesByDefault = "ขยายรายการโปรดตามค่าเริ่มต้น",
	Checkbox_EnableScrollBars = "เปิดใช้งานแถบเลื่อน",
	Checkbox_AlwaysDisablePhotoModeCursor = "ปิดการใช้งานเคอร์เซอร์โหมดภาพถ่ายเสมอ",
	Checkbox_Camera = "กล้อง",
	Checkbox_DepthOfField = "กรมประมง",
	Checkbox_Effect = "เอฟเฟกต์",
	Checkbox_Stickers = "สติ๊กเกอร์",
	Checkbox_LoadSave = "โหลด/บันทึก",
	Checkbox_ExperimentalFunstuff = "ของทดลอง/สนุกๆ",
	Checkbox_EnableFreezeTargetInPhotoMode = "เปิดใช้งานการตรึงเป้าหมายในโหมดภาพถ่าย",
	Checkbox_WeaponizeCompanions = "สร้างอาวุธให้สหาย",
	Checkbox_AllowPlayerToBeTargetedinPosestab = "อนุญาตให้ผู้เล่นถูกกำหนดเป้าหมายในแท็บโพสท่า",
	Checkbox_AllowPlayerAnimationsonNPCs = "อนุญาตแอนิเมชั่นของผู้เล่นบน NPC",
	Checkbox_AllowExpressionOnNpcPM = "อนุญาตให้ใช้นิพจน์และดู NPC ในโหมดภาพถ่าย",
        Checkbox_ResetTargetPositionPM = "รีเซ็ตตำแหน่งเป้าหมายสำหรับ NPC โหมดภาพถ่าย",
        Checkbox_EnableRandomLocation = "เปิดใช้งานปุ่มสุ่ม: ผู้เล่นเคลื่อนย้ายระยะไกลไปยังตำแหน่งสุ่มจากรายการ",
        Checkbox_RestoreOnLaunch = "คืนค่าเมื่อเปิดตัว",
        Radio_PrimarySlot = "สล็อตหลัก",
        Radio_SecondarySlot = "ช่องรอง",
	
    --Warning / Info / Tool Tip
	Warn_RespawnOnLaunch_Info = "การตั้งค่านี้จะเปิด/ปิดใช้งานการเกิดใหม่ของ NPC ที่บันทึกไว้ก่อนหน้านี้เมื่อโหลดเกม AMM จะบันทึก NPC ที่เกิดของคุณโดยอัตโนมัติเมื่อคุณออกจากเกม",
	Warn_BannedWords_Info = "การตั้งค่านี้จะเปิด/ปิดการใช้งานการปรากฏตัวของ NPC ที่มีคำว่า: เปลือย, เปลือย, xxx, อาบน้ำ, ชุดวันเกิด, pp และอวัยวะเพศชาย",
	Warn_TargetNpcVehicleHotkey = "กำหนดเป้าหมาย NPC หรือยานพาหนะเพื่อตั้งค่าปุ่มลัด",
	Warn_FirstLaunchDecideTabsExpand_Info = "การตั้งค่านี้จะขยายรายการโปรดในแท็บวางไข่ สลับ และตกแต่งตามค่าเริ่มต้นเมื่อ AMM เปิดตัวครั้งแรก",
	Warn_ExperimentalTabDesc_Info = "คุณลักษณะทดลองเพิ่มฟังก์ชันการทำงานมากขึ้น แต่อาจทำงานได้ไม่ดีเท่ากับป้ายกำกับการทดลอง ที่จริงแล้ว ผู้ใช้ AMM ส่วนใหญ่ได้เปิดใช้งานคุณสมบัติทดลองไว้ ดังนั้นอย่ากังวลมากเกินไปและสนุกไปกับมัน!",
	Warn_FreezeTargetPhotoMode_Info = "การตั้งค่านี้มีไว้เพื่อช่วยหยุดภาพเคลื่อนไหวจาก Mods ที่เพิ่มภาพเคลื่อนไหวแบบกำหนดเองให้กับโหมดภาพถ่ายหรือเมื่อคุณยกเลิกการหยุดชั่วคราวโดยใช้ IGCS",
	Warn_WeaponizeCompanions_Info = "สิ่งนี้จะมอบอาวุธและความสามารถในการต่อสู้ให้กับ NPC ทุกคน คาดว่าจะมีการวางตัวแบบ T และแอนิเมชั่นแปลกๆ",
	Warn_PlayerAnimsOnNpc_Info = "เปิดใช้งานสิ่งนี้หากคุณใช้ม็อดที่อนุญาตให้ใช้แอนิเมชั่นของผู้เล่นบน NPC",
	Warn_UnpauseRequiresIGSC = "การตั้งค่านี้ต้องใช้ IGCS เพื่อยกเลิกการหยุดเวลาชั่วคราว",
	Warn_NotInstalled = "ไม่ได้ติดตั้ง",
	Warn_DespawnAllProps = "คุณแน่ใจหรือไม่ว่าต้องการ Despawn อุปกรณ์ประกอบฉากทั้งหมด?",
	
    --Text
	AMM_Version = "เวอร์ชัน AMM:",
	CET_Version = "เวอร์ชัน CET:",
	Codeware_Version = "เวอร์ชันโค้ดแวร์:",
	Game_Version = "เวอร์ชั่นเกม:",
	Companion_Damage = "ความเสียหายของเพื่อนร่วมทาง:",
	Companion_Resistance = "ความต้านทานสหาย:",
	Companion_Distance = "ระยะทางร่วม:",
	xDamage = "x ความเสียหาย",
	xResistance = "x ความต้านทาน",
	SavedAppearancesHotkeys = "ปุ่มลัดลักษณะที่ปรากฏที่บันทึกไว้",
	Favorites = "รายการโปรด",
	Appearances = "การปรากฏตัว",
	Blacklist = "บัญชีดำ",
	AppearanceTriggers = "ทริกเกอร์ลักษณะที่ปรากฏ",
	SavedDespawns = "Despawns ที่บันทึกไว้",
	Interface_Language = "ภาษาอินเทอร์เฟซ:",
	Custom_Appearances = "ลักษณะที่ปรากฏที่กำหนดเอง",
	PhotoModeAdjustments = "การปรับโหมดภาพถ่าย:",
	DisablePhotoModeTabs = "ปิดการใช้งานแท็บโหมดภาพถ่าย:",
	List_Height = "ความสูงของรายการ",
	Listbox_Themes = "ธีมส์",
	Weaponize = "ติดอาวุธ",
	NoAppearanceSet = "ไม่มีการตั้งค่าลักษณะที่ปรากฏ",
	
	
	
	-- >> EXTRA	
	--Texts, warns, tips, info's, buttons and labels etc.
	Seat_FrontRight = "ด้านหน้าขวา",
	Seat_BackRight = "ย้อนกลับขวา",
	Seat_FrontLeft = "ด้านหน้าซ้าย",
	Seat_BackLeft = "กลับซ้าย",
	Label_Door = "ประตู",
	Label_Window = "หน้าต่าง",

	Close = "ปิด",
	Far = "ไกล",
	Moderate = "ปานกลาง",
	
	-- >> Archives Screen
	Warning_MissingRequiredArchives = "AMM ขาดเอกสารสำคัญที่จำเป็นอย่างน้อยหนึ่งรายการ โปรดติดตั้งไฟล์เก็บถาวรที่จำเป็นที่ขาดหายไปในโฟลเดอร์ archive/pc/mod ของคุณ",
	Warning_MissingOptionalArchives = "AMM ไม่มีเอกสารสำคัญอย่างน้อยหนึ่งรายการ สิ่งเหล่านี้เป็นทางเลือกแต่เพิ่มฟังก์ชันการทำงานให้กับ AMM คุณอาจเพิกเฉยต่อคำเตือนเหล่านี้ แต่ AMM อาจทำงานไม่ถูกต้อง",
	
	
	-->> INIT.LUA
	AMMNeedsAttention = "AMM ต้องการความสนใจ",
	MISSING_ARCHIVES = "เอกสารสำคัญที่ขาดหายไป",
	VERSION_INFORMATION = "ข้อมูลเวอร์ชัน",
	CREDITS = "เครดิต",
	UPDATE_HISTORY = "อัปเดตประวัติ",
	Updates = "อัพเดท",
	MISSING = "หายไป",
	REQUIRED = "จำเป็น",
	OPTIONAL = "ไม่จำเป็น",
	WHATS_NEW = "มีอะไรใหม่", --Line 83 Function Error

	--Button
	Button_Ignorewarningsforthisversion = "ละเว้นคำเตือนสำหรับเวอร์ชันนี้",
	Button_Credits = "เครดิต",
	Button_Cool = "เจ๋ง!",

	--Button Label
	Label_SpawnFavorites = "วางไข่รายการโปรด",
	Label_SwapFavorites = "สลับรายการโปรด",
	Label_FavoriteAppearances = "การปรากฏตัวที่ชื่นชอบ",
	Label_Cancel = "ยกเลิก",

	--Text
	Hotkey_i = "ปุ่มลัด %i",

	--Node - Function Error(nil value) 
	Top = "ด้านบน", --Line 116
	Bottom = "ก้น",
	Off = "ปิด",
	
	--Voice Overs
	Label_GreetV = "ทักทาย วี",
	Label_FearFoll = "กลัวฟอล",
	Label_FearToll = "กลัวค่าผ่านทาง",
	Label_FearBeg = "กลัวขอร้อง",
	Label_FearRun = "กลัววิ่ง",
	Label_StealthSearch = "ค้นหาชิงทรัพย์",
	Label_StealthDeath = "ความตายที่ซ่อนเร้น",
	Label_StealthRestore = "การเรียกคืนการลักลอบ",
	Label_StealthEnd = "จุดสิ้นสุดการลักลอบ",
	Label_CuriousGrunt = "Grunt อยากรู้อยากเห็น",
	Label_GrappleGrunt = "กริปเปิ้ล แกรนท์",
	Label_Bump = "บั๊ม",
	Label_VehicleBump = "รถชน",
	Label_TurretWarning = "คำเตือนป้อมปราการ",
	Label_OctantWarning = "คำเตือนออกเทนต์",
	Label_DroneWarning = "คำเตือนโดรน",
	Label_MechWarning = "คำเตือนเกี่ยวกับเครื่องจักร",
	Label_EliteWarning = "คำเตือนชั้นสูง",
	Label_CameraWarning = "คำเตือนเกี่ยวกับกล้อง",
	Label_EnemyWarning = "คำเตือนศัตรู",
	Label_HeavyWarning = "คำเตือนหนัก",
	Label_SniperWarning = "คำเตือนสไนเปอร์",
	Label_AnyDamage = "ความเสียหายใดๆ",
	Label_Danger = "อันตราย",
	Label_CombatStart = "เริ่มการต่อสู้",
	Label_CombatEnd = "การต่อสู้สิ้นสุด",
	Label_CombatTargetHit = "ต่อสู้โจมตีเป้าหมาย",
	Label_PedestrianHit = "การตีคนเดินเท้า",
	Label_LightHit = "โจมตีเบา",
	Label_Curse = "คำสาป",
	Label_Irritated = "ระคายเคือง",
	Label_GrenadeThrow = "ระเบิดมือขว้าง",
	Label_Gotakill = "โดนฆ่า!",
	
	--Expressions
	Neutral = "เป็นกลาง",
	Joy = "จอย",
	Smile = "ยิ้ม",
	Sad = "เศร้า",
	Surprise = "เซอร์ไพรส์",
	Aggressive = "ก้าวร้าว",
	Anger = "ความโกรธ",
	Interested = "สนใจ",
	Disinterested = "ไม่สนใจ",
	Disappointed = "ผิดหวัง",
	Disgust = "รังเกียจ",
	Exertion = "ความพยายาม",
	Nervous = "ประสาท",
	Fear = "ความกลัว",
	Terrified = "หวาดกลัว",
	Pain = "ความเจ็บปวด",
	Sleepy = "ง่วงนอน",
	Unconscious = "หมดสติ",
	Dead = "ตายแล้ว",

	-- Extra Expressions
	Frown = "ขมวดคิ้ว",
	Shocked = "ตกใจ",
	Annoyed_2 = "รำคาญ2",
	Contempt = "ดูถูก",
	Irritated = "ระคายเคือง",
	Sceptical_1 = "สงสัย1",
	Sceptical_2 = "สงสัย2",
	Annoyed_1 = "รำคาญ1",
	Offended = "ขุ่นเคือง",
	Disgusted = "เบื่อหน่าย",
	Disappointed_2 = "ผิดหวัง2",
	Alert = "การแจ้งเตือน",
	Crying = "ร้องไห้",
	Embarrassed = "เขินอาย",
	Humiliated = "อับอายขายหน้า",
	Impatient = "ใจร้อน",
	Anguished = "ปวดร้าว",
	Worried = "กังวล",
	Guilty = "มีความผิด",
	Grieving = "เสียใจ",
	RestrainedAnger = "ระงับความโกรธ",
	Afraid = "กลัว",
	LookingUpAnnoyed = "เงยหน้าขึ้นมองอย่างหงุดหงิด",
	Offended_2 = "รุกราน 2",
	Resentful = "ไม่พอใจ",
	SadExtra = "เศร้าเสริม",
	NervousBreath = "ลมหายใจประสาท",
	ScreamingLong = "กรี๊ดยาว",
	ScreamingShort = "กรี๊ดสั้น",
	ScaredBreath = "ลมหายใจที่หวาดกลัว",
	CryingPainful = "ร้องไห้อย่างเจ็บปวด",
	SelfReflectAnger = "สะท้อนความโกรธด้วยตนเอง",
	IndulgentSmile = "ยิ้มแย้มแจ่มใส",
	Impressed = "ประทับใจ",
	LongSmile = "ยิ้มยาว",
	ShortSmile = "ยิ้มสั้นๆ",
	SimpleSmile = "ยิ้มง่าย",
	Confident = "มั่นใจ",
	Relief = "บรรเทา",
	Impressed_2 = "ความประทับใจ2",
	Admiring = "ชื่นชม",
	Fascinated = "หลงใหล",
	RaisedBrows = "ยกคิ้ว",
	LookingUpThinking = "มองขึ้นไปคิด",
	LeftGlanceProcessing = "การประมวลผลการมองซ้าย",
	LeftGlanceCloseUp = "เหลือบมองปิดขึ้น",
	LookingAround = "มองไปรอบ ๆ",
	LookingDownThinking = "มองลงไปครุ่นคิด",
	LookingAroundAlt = "มองไปรอบๆ Alt",
	EyesDartFromLeft = "ดวงตาพุ่งจากซ้าย",
	EyesDartFromRight = "ดวงตาพุ่งจากขวา",
	EyesDartToRight = "ตาโผไปทางขวา",
	LookingLeft = "มองซ้าย",
	LookingUpThinking_2 = "มองขึ้นไปคิด 2",
	RightGlanceProcessing = "การประมวลผลอย่างรวดเร็ว",
	LookingDown = "มองลงมา",
	Left90GlanceClose = "ซ้าย90เหลือบมอง ปิด",
	LookingUp = "มองขึ้นไป",
	Right90GlanceClose = "ขวา90Glance ปิด",
	LookingLeftUp = "มองซ้ายขึ้น",
	LookingRightUp = "มองไปทางขวาขึ้นไป",
	ReadingDown = "กำลังอ่านอยู่",
	ReadingUp = "กำลังอ่านอยู่",
	ReadingMiddle = "การอ่านกลาง",
	FrontCloseGlance = "ภาพรวมปิดด้านหน้า",
	WinkLeft = "ขยิบตาซ้าย",
	EyeRoll = "กลอกตา",
	Squint = "เหล่",
	FalseSmile_2 = "รอยยิ้มจอมปลอม2",
	FalseSmile_1 = "รอยยิ้มจอมปลอม1",
	ListeningNewInfo = "ฟังข้อมูลใหม่",
	WhatDoYouWant = "คุณต้องการอะไร",
	Maybe = "อาจจะ",
	SearchingForWords = "ค้นหาคำ",
	What = "อะไร",
	Where = "ที่ไหน",
	SureSure = "ชัวร์ ชัวร์",
	ListenToMe = "ฟังฉัน",
	StopThePolice = "หยุดตำรวจ",
	HurryUp = "รีบหน่อย",
	ShutUp = "หุบปาก",
	WinkRight = "ขยิบตาขวา",
	MockingSmile = "รอยยิ้มเยาะเย้ย",
	AsymmetricalSmile = "รอยยิ้มที่ไม่สมมาตร",
	SarcasticSmile = "ยิ้มประชด",
	Sex = "เซ็กส์",
	LipBite_1 = "ลิปกัด 1",
	LipBite_2 = "ลิปกัด 2",
	Moan = "คราง",
	LipBite_3 = "ลิปกัด 3",
	Pout = "หน้ามุ่ย",
	SexySmile = "ยิ้มเซ็กซี่",
	Swallow = "กลืน",
	SensualSmile = "รอยยิ้มที่เย้ายวน",
	SexScene_1 = "ฉากเซ็กส์ 1",
	SexScene_2 = "ฉากเซ็กส์ 2",
	Kiss = "จูบ",
	UsingInhaler = "การใช้เครื่องช่วยหายใจ",
	ShortYawn = "หาวสั้น",
	Yawn = "หาว",
	Coughing = "ไอ",
	Bite = "กัด",	
	EatingFast = "กินเร็ว",
	ShortDrink = "เครื่องดื่มระยะสั้น",
	Drinking = "การดื่ม",
	FastBite = "กัดอย่างรวดเร็ว",
	LongDrink = "ดื่มนาน",
	ShortSmoking = "สูบบุหรี่สั้น",
	LongSmoking = "สูบบุหรี่นาน",
	Smoking = "สูบบุหรี่",
	Eating_1 = "การรับประทานอาหาร 1",
	Eating_2 = "การรับประทานอาหาร2",
	Eating_3 = "การรับประทานอาหาร 3",
	Eating_4 = "การรับประทานอาหาร 4",
	Vomit = "อาเจียน",
	BeingRevived = "กำลังฟื้นคืนชีพ",
	MalwarePositive = "มัลแวร์เป็นบวก",
	MalwareNegative = "มัลแวร์เชิงลบ",
	MalwareInfected = "มัลแวร์ที่ติดไวรัส",
	FaceMorphActivate = "เปิดใช้งาน Face Morph",
	LieNetChairSleep = "นอนมุ้งเก้าอี้นอน",
	LieNetChairBreathe = "นอนเก้าอี้ตาข่าย หายใจ",
	NetrunnerDeathUnplugged = "Netrunner Death Unplugged",
	VeryItchyNose = "คันจมูกมาก",
	RollerCoasterNervous = "รถไฟเหาะประสาท",
	Pfft = "Pfft",
	Hahaha = "ฮ่าๆ",
	Sniff = "สูดอากาศ",
	Ahaaa = "อ่าาา",
	Heh = "เฮ้",
	Huh = "ฮะ",
	Haaa = "ฮ่าๆ",
	Sigh_Lipsync = "ถอนหายใจ ลิปซิงค์",
	Hmm = "อืม",
	Whispering_1 = "เสียงกระซิบ 1",
	Whispering_2 = "เสียงกระซิบ 2",
	ApprovalYes = "การอนุมัติใช่",
	SubtleYes = "ละเอียด ใช่",
	QuickNoShake = "รวดเร็วไม่สั่นไหว",
	FirmYes = "มั่นคงใช่",
	LongNo = "ยาว",
	SubtleNo = "เลขที่ละเอียดอ่อน",
	NoContempt = "ไม่มีการดูหมิ่น",
	NoDisapproval = "ไม่มีการปฏิเสธ",
	FirmNo = "หมายเลขบริษัท",
	NoEnthusiastic = "ไม่มีความกระตือรือร้น",
	MockingYes = "ล้อเลียนใช่",
	EnthusiasticYes = "กระตือรือร้น ใช่",
	AsymmetricalCornerUp = "มุมไม่สมมาตรขึ้น",
	CornersUp = "มุมขึ้น",
	SoftSigh = "ถอนหายใจเบาๆ",
	BreathGasp = "ลมหายใจ",
	AssymetricalSneer = "การเยาะเย้ยไม่สมมาตร",
	CrimpingLips = "จีบริมฝีปาก",
	BrowsDown = "คิ้วลง",
	BrowsLeftUp = "คิ้วซ้ายขึ้น",
	BrowsRightUp = "คิ้วขวาขึ้น",
	BrowsUp = "คิ้วขึ้น",
	ClosedEyes_1 = "ปิดตา1",
	ClosedEyes_2 = "ปิดตา2",
	EyesClosed = "ปิดตา",
	LookRight = "มองขวา",
	FastBlink = "กะพริบตาอย่างรวดเร็ว",
	SlowBlink = "กะพริบช้าๆ",
	NormalBlink = "กะพริบตาปกติ",
	TinyBlink = "กะพริบตาเล็ก ๆ",
	HalfBlink = "กะพริบตาครึ่ง",
	RegularSaccade = "Saccade ปกติ",
	FrequentSaccade = "Saccade บ่อยครั้ง",
	PhotoCloseupEyes = "ภาพโคลสอัพดวงตา",
	PhotoCloseupLips = "ภาพโคลสอัพริมฝีปาก",
	PhotoCloseupHair = "ภาพโคลสอัพผม",
	PhotoCloseupChin = "ภาพถ่ายโคลสอัพคาง",
	PhotoCloseupNose = "ภาพถ่ายโคลสอัพจมูก",
	PhotoCloseup = "ภาพถ่ายโคลสอัพ",
	PhotoCloseupPleased = "ภาพถ่ายโคลสอัพยินดี",
	PhotoCloseupBody = "ภาพถ่ายโคลสอัพร่างกาย",
	PhotoCloseupTeeth = "ภาพถ่ายโคลสอัพฟัน",
	PhotoCloseupIN = "ภาพถ่ายโคลสอัพใน",
	PhotoCloseupOUT = "ภาพถ่ายโคลสอัพออก",
	Bored = "เบื่อ",
	Charming = "มีเสน่ห์",
	Furious = "โกรธมาก",
	Happy = "มีความสุข",
	Pissed = "โกรธ",
	Pleased = "ยินดี",
	Scared = "กลัว",
	Surprised = "ประหลาดใจ",
	Sadness = "ความโศกเศร้า",
	Whistling = "ผิวปาก",
	Singing_1 = "ร้องเพลง 1",
	Singing_2 = "ร้องเพลง2",
	Singing_3 = "ร้องเพลง 3",
	Alerted = "แจ้งเตือน",
	Hit_1 = "ตี 1",
	Hit_2 = "ตี 2",
	Wounded = "ได้รับบาดเจ็บ",
	Death = "ความตาย",

	-- Expressions Category
	Negative = "เชิงลบ",
	Positive = "แง่บวก",
	Contemplative = "ครุ่นคิด",
	Social = "สังคม",
	Sexual = "ทางเพศ",
	Action = "การดำเนินการ",
	Vocal = "เสียงร้อง",
	Yes_N_No = "ใช่และไม่ใช่",
	Nuance = "แตกต่างกันนิดหน่อย",
	Static = "คงที่",
	Combat = "การต่อสู้",
	
	--Props
	AMM_Props_Desc = "เพิ่มอุปกรณ์ประกอบฉาก ตัวละคร และยานพาหนะ AMM จะไม่เปิดตัวหากไม่มีสิ่งนี้",
	AMM_JohnnyCompanion_Desc = "เพิ่ม Johnny Silverhand เป็นตัวละครที่สามารถวางไข่ได้",
	AMM_ScenesPack_Desc = "เพิ่มภาพเคลื่อนไหวฉาก 9358 ให้กับระบบ Poses\nดาวน์โหลดได้ที่หน้า Nexus ของ AMM",
	AMM_SoundPack_Desc = "เพิ่มเอฟเฟกต์เสียงที่สามารถวางไข่ได้",
	AMM_KerryPP_Desc = "เพิ่มรูปลักษณ์เปลือยใหม่",
	AMM_BenjaminStonePP_Desc = "เพิ่มรูปลักษณ์เปลือยใหม่",
	AMM_RiverPP_Desc = "เพิ่มรูปลักษณ์เปลือยใหม่",
	AMM_YorinobuPP_Desc = "เพิ่มรูปลักษณ์เปลือยใหม่",
	AMM_LizzyIncognito_Desc = "เพิ่มรูปลักษณ์ใหม่",
	AMM_MeredithXtra_Desc = "เพิ่มรูปลักษณ์ใหม่",
	AMM_DelamainFix_Desc = "เพิ่มเดลาเมนให้เต็มตัว",
	AMM_HanakoNoMakeup_Desc = "อนุญาตให้ AMM ลบการแต่งหน้าของ Hanako เมื่อใช้รูปลักษณ์แบบกำหนดเอง",
	AMM_JudyBodyRevamp_Desc = "แทนที่ร่างของจูดี้ด้วยร่างที่ปรับปรุงใหม่",
	AMM_PanamBodyRevamp_Desc = "แทนที่ร่างของ Panam ด้วยอันที่ปรับปรุงใหม่",
	AMM_MistyBodyRevamp_Desc = "แทนที่ร่างของ Misty ด้วยร่างที่ปรับปรุงใหม่\nดาวน์โหลดได้ที่หน้า Nexus ของ AMM",
	AMM_1VesHanakoFixedBodyNaked_Desc = "แทนที่ร่างของฮานาโกะด้วยร่างที่ปรับปรุงใหม่",
	AMM_PinkyDudeANIMFacialExpressionsFemV_Desc = "เปิดใช้งานเครื่องมือการแสดงออกทางสีหน้าใน Female V",
	AMM_PinkyDudeANIMFacialExpressionsMaleV_Desc = "เปิดใช้งานเครื่องมือการแสดงออกทางสีหน้าใน Male V",
	AMM_DinoTattooFixArchive_Desc = "แทนที่ตาข่ายและพื้นผิว",
	AMM_SongbirdBodyFixArchive_Desc = "แทนที่ร่างกายเพื่อแก้ไขพื้นที่สีเทา ยังไม่สมบูรณ์แบบ",
	AMM_RitaWheelerCombatEnablerArchive_Desc = "แทนที่ไฟล์เอนทิตีเพื่อเปิดใช้งานภาพเคลื่อนไหวการต่อสู้",
	AMM_CheriAppearances_Desc = "เพิ่มรูปลักษณ์ใหม่ ดาวน์โหลดได้ที่หน้า Nexus ของ AMM",
	AMM_BryceNaked_Desc = "เพิ่มรูปลักษณ์เปลือยใหม่ ดาวน์โหลดได้ที่หน้า Nexus ของ AMM",
	AMM_EvelynNaked_Desc = "แก้ไขร่างกายของเธอให้ดูเปลือยเปล่า ดาวน์โหลดได้ที่หน้า Nexus ของ AMM",
	AMM_SaburoAppearances_Desc = "เพิ่มรูปลักษณ์ใหม่ ดาวน์โหลดได้ที่หน้า Nexus ของ AMM",
	AMM_TbugAppearances_Desc = "เพิ่มรูปลักษณ์ใหม่ ดาวน์โหลดได้ที่หน้า Nexus ของ AMM",
	AMM_8ug8eagAppearances_Desc = "เพิ่มรูปลักษณ์ใหม่ ดาวน์โหลดได้ที่หน้า Nexus ของ AMM",
	
	--Equipments (There is a Function Error(nil value) in this section, These are just labels that are not connected to any localizable strings in the file)
	Fists = "กำปั้น", --Line 2377 
	Katana = "คาทานา",
	Mantis_Blades = "ตั๊กแตนตำข้าวใบมีด",
	Machete = "มีดมาเชเต้",
	Hammer = "ค้อน",
	Baton = "บาตัน",
	Knife = "มีด",
	Crowbar = "ชะแลง",
	Baseball_Bat = "ไม้เบสบอล",
	Assault_Rifle = "ปืนไรเฟิลจู่โจม",
	Sidewinder = "ไซด์วินเดอร์",
	Sniper_Rifle = "สไนเปอร์ไรเฟิล",
	Shotgun = "ปืนลูกซอง",
	SMG = "SMG",
	Handgun = "ปืนพก", --Line 2391
	
	--Warning / Info / Tooltip
	Warn_CantSave_BlacklistedAppearance = "คุณไม่สามารถบันทึกลักษณะที่ปรากฏในรายการที่ไม่อนุญาตได้!",
	Warn_ConfirmDeleteSavedAppearances = "คุณแน่ใจหรือไม่ว่าต้องการลบลักษณะที่ปรากฏที่บันทึกไว้ทั้งหมด",
	Warn_ConfirmDeleteBlacklistedAppearances = "คุณแน่ใจหรือไม่ว่าต้องการลบการปรากฏตัวในรายการที่ไม่อนุญาตทั้งหมด",
	Warn_ConfirmDeleteSavedDespawns = "คุณแน่ใจหรือไม่ว่าต้องการลบ Despawn ที่บันทึกไว้ทั้งหมด",
	Warn_ConfirmDeleteAppearanceTriggers = "คุณแน่ใจหรือไม่ว่าต้องการลบทริกเกอร์ลักษณะที่ปรากฏทั้งหมด",
	Warn_ConfirmDeleteCurrentAppearance = "คุณแน่ใจหรือไม่ว่าต้องการลบค่าที่ตั้งไว้ล่วงหน้าที่ใช้งานอยู่ในปัจจุบัน",
	Warn_WeaponizeNpcAnimationIssues = "ไม่ใช่ NPC ทุกคนจะมีแอนิเมชั่นที่จำเป็นต่อการใช้อาวุธทุกประเภท การวางตัว T และภาพเคลื่อนไหวที่ไม่ถูกต้องอาจเกิดขึ้น\nคุณแน่ใจหรือไม่ว่าต้องการเปิดใช้งาน",
	Warn_ConfirmEnableExperimentalAndSave_Info = "คุณแน่ใจหรือไม่ว่าต้องการเปิดใช้งานคุณลักษณะทดลอง AMM อาจไม่ทำงานตามที่คาดไว้ ใช้มันด้วยความเสี่ยงของคุณเอง!",
	Warn_DeleteFavoritesAskWhichOne_Info = "หากคุณแน่ใจว่าต้องการลบรายการโปรดทั้งหมด ให้เลือกรายการใดรายการหนึ่งด้านล่าง:",
	Popup_Error_Title = "เกิดข้อผิดพลาด",
	Button_Ok = "ตกลง",
	Popup_FavoriteName = "ชื่อที่ชอบ",
	Popup_RenamePreset = "เปลี่ยนชื่อที่ตั้งไว้ล่วงหน้า",
	Popup_RenameProp = "เปลี่ยนชื่อข้อเสนอ",
	Editor_Title = "ตัวแก้ไขธีม",
	Editor_Field_ThemeName = "ชื่อธีม",
	Editor_Hint_InsertThemeName = "ใส่ชื่อธีมใหม่",
	Error_ThemeNameExists = "มีชื่อธีมนี้อยู่แล้ว",
}
