return {

    -- >> SCAN TAB
	BeginItem_TabNameScan = "Сканувати",
	
	--Button
	Button_CyclesAppearances = "Зовнішній вигляд циклу",
	Button_SavesAppearance = "Зберегти зовнішній вигляд",
	Button_ClearSavedAppearance = "Очистити збережений зовнішній вигляд",
	Button_UnlockDoor = "Перемкнути дверний замок",
	Button_RestoreAccess = "Відновити доступ",
	Button_UnlockVehicle = "Розблокувати автомобіль",
	Button_RepairVehicle = "Ремонт автомобіля",
	Button_OpenCloseDoors = "Відкрити/закрити двері",
	Button_OpenCloseWindows = "Відкрити/закрити Windows",
	Button_ToggleEngine = "Переключити двигун",
	Button_ToggleAIDriver = "Перемкнути драйвер AI",
	Button_ToggleCamera = "Перемкнути камеру",
	Button_ToggleRadio = "Переключити радіо",
	Button_NextRadioStation = "Наступна радіостанція",
	Button_TargetMountedVehicle = "Цільова машина",
	Button_AssignSeats = "Призначити місця",
	Button_Assign = "Призначити",
	Button_Reset = "Скинути",
	Button_FakeDie = "Фальшивий кубик",
	Button_SmallCopy = "Копіювати",
	
    --Button Label
	Button_Label_Unfollower = "Скасувати підписку",
	Button_Label_Follower = "Послідовник",
	Button_Label_SaveDespawn = "Зберегти Despawn",
	Button_Label_ClearSavedDespawn = "Очистити збережений Despawn",
	Button_LabelLockTarget = "Заблокувати ціль",
	Button_LabelUnlockTarget = "Розблокувати ціль",
	Label_AddToSpawnFavs = "Додайте до вибраного, що створюється",
	Label_RemoveFromSpawnFavs = "Видалити з вибраного, що створюється",
	
    --Checkbox
	Checkbox_SavedDespawnsActive = "Збережено Despawns Active",
	Checkbox_KeepAssigned = "Зберігайте призначення під час зміни автомобіля",
	
    --Warning / Info / Tool Tip
	WarnTextAI_FastTravel = "Виберіть точку Fast Travel на карті, щоб вирушити",
	WarnText_DontReloadMods = "Не використовуйте Reload All Mods.\nПерезавантажте збережену гру або перейдіть до іншої області.",
	Warning_NoTarget_Desc = "Немає цілі! Для початку подивіться на NPC, транспортний засіб або об’єкт",
	ToolTip_DisableCheckboxReloadSave_AbleTotargetClearSavedDespawns = "Вимкніть цей прапорець і оновіть своє збереження, щоб мати можливість націлити Clear Saved Despawns",
	
    --Text
	Build_Mode = "Режим збірки",
	Speed = "швидкість:",
	Search = "Пошук",
	Clear = "ясно",
	Player = "гравець",
	Saved = "Збережено",
	Saved_ = "Збережено_",
	Current = "поточний",
	Current_ = "поточний",
	Select_Seat = "Виберіть місце",
	Target_Info = "Цільова інформація",
	Target_Actions = "Цільові дії",
	No_Appearances = "Немає виступів",
	No_Target = "Немає мети",
	Favorite_Appearance = "Улюблена зовнішність",
	Unfavorite_Appearance = "Неулюблений зовнішній вигляд",
	Blacklist_Appearance = "Зовнішній вигляд чорного списку",
	Unblacklist_Appearance = "Видалення з чорного списку",
	Saved_Appearance = "Збережений зовнішній вигляд:",
	Current_Appearance = "Поточний зовнішній вигляд:",
	List_of_Appearances = "Список виступів",
	Appearance_Trigger = "Тригер зовнішнього вигляду",
	None = "жодного",
	Default = "За замовчуванням",
	Zone = "зона",
	Area = "Площа",
	Position = "Позиція",

	
	-- >> SPAWN TAB
	BeginItem_TabNameSpawn = "Спаун",
	
	--Button
	Button_Refresh = "Оновити",
	Button_Save = "зберегти",
	Button_Confirm = "Підтвердити",
	Button_Cancel = "Скасувати",
	Button_SmallSave = "зберегти",
	Button_SmallRespawn = "Відродження",
	Button_SmallDespawn = "Деспаун",
	Button_SmallDespawn_WithSpace = "Деспаун",
	Button_SmallTarget = "Цільова",
	Button_SmallEquipment = "Обладнання",
	Button_LabelHostile = "Ворожий",
	Button_LabelFriendly = "дружній",
	
    --Button Label
	Label_Favorite = "улюблений",
	Label_Unfavorite = "Вилучити з обраного",
	
    --Checkbox
    --Warning / Info / Tool Tip
	Warn_PlayerInMenu = "Гравець у меню",
	Warn_AMMonlyfunctions_ingame = "AMM працює лише в грі",
	Warn_SpawnWorksInGame = "Спавн працює лише в грі",
	Warn_InitError = "Помилка ініціалізації",
	Warn_InitError_Info = "Будь ласка, перевірте AppearanceMenuMod.log для отримання додаткової інформації.",
	
    --Text
	Active_Spawns = "Активні спауни",
	NoActiveSpawns = "Немає активних спавнів",
	Select_To_Spawn = "Виберіть для створення",
	No_Results = "Немає результатів",
	ItsEmpty = "Це пусто :(",
	Existing_Name = "Існуюча назва",
	Name = "Ім'я",
	
	
	
	-- >> SWAP TAB
	BeginItem_TabNameSwap = "Обмін",
	
	--Button
	Button_SmallRevert = "Повернути",
	
    --Button Label
    --Checkbox
    --Warning / Info / Tool Tip
	Warn_ReloadSaveUpdateChanges = "Перезавантажте збережену гру, щоб оновити зміни!",
	Warn_NeedReloadSaveUpdateChanges = "Вам потрібно буде перезавантажити збереження, щоб оновити зміни.",
	Warn_ReplacerSwap = "Ви не можете поміняти замінник! Використовуйте вкладку «Інструменти» в режимі фото, щоб націлитися на них, а потім змініть їх зовнішній вигляд із вкладки «Відродження» або «Інструменти націлювання».",
	Warning = "ПОПЕРЕДЖЕННЯ",
	Warning2 = "ПОПЕРЕДЖЕННЯ:",
	SaveSwap_Tooltip = "Збережіть свої обміни, щоб зберегти їх після перезавантаження гри.",
	
    --Text
	CantSwapReplacer = "Неможливо замінити Replacer",
	Active_Model_Swaps = "Активні заміни моделей",
	Save = "зберегти",
	Restore = "Відновити",
	Current_Target = "Поточна мета:",
	Target_ID = "ID цілі:",
	SelectSwap_CurrentTarget = "Виберіть для заміни з поточною метою:",
	NoNPC_LookNPC = "NPC не знайдено! Подивіться на NPC, щоб почати",
	
	-- Locations Categories
	Residences = "Резиденції",
	ArasakaAndCorpo = "Arasaka & Corpo",
	ClubsAndBars = "Клуби та бари",
	HotelsAndPleasure = "Готелі та розваги",
	UndergroundAndCrime = "Підпілля та злочинність",
	GovernmentAndSecurity = "Уряд і безпека",
	StoryAndUnique = "Історія та унікальність",
	Ripperdocs = "Ripperdocs",
	LandmarksAndOpenWorld = "Пам'ятки та відкритий світ",
	SpoilersAndHidden = "Спойлери та приховані",
	UserLocations = "Розташування користувачів",
	
	
	-- >> DECOR TAB
	BeginItem_TabDecor = "Декор",
	BeginItem_TabPresets = "Предустановки",
	Begin_ComboPresets = "Предустановки",
	
	--Button
	Button_SmallClone = "Клон",
	Button_SmallRemove = "видалити##",
	Button_SmallRename = "Перейменувати##",
	Button_SmallUpdate = "Оновити ##",
	Button_SmallCancel = "Скасувати",
	Button_Frame = "рамка",
	
    --Button Label
	Button_LabelHide = "Сховати",
	Button_LabelUnhide = "Показати",
	
    --Checkbox
    --Warning / Info / Tool Tip
	Warn_PersistPropSave = "Spawn Props, щоб прикрасити ваш будинок або будь-де, де ви забажаєте, до душі! Зберігайте реквизити, щоб зберегти їх!",
	Warn_DespawnInProgress_PleaseWait = "Despawn у процесі. Будь ласка, зачекайте.",
	Warn_PresetsFolder_Info = "Попередні налаштування користувача зберігаються в папці AppearanceMenuMod/User/Decor",
	Warn_CustomPresets_Info = "Цей стиль містить власні властивості",
	Warn_CustomPropsModders_Info = "Нестандартний реквізит виготовлений:",
	Warn_GamepadDirectMode_Info = "Це забезпечує кращу інтеграцію з режимом Direct під час використання геймпада. Це також дозволяє невелике інформаційне віконце, яке тримається навколо.",
	Warn_PresetTriggerDistanceFar = "Якщо встановити значення Far, це може спричинити проблеми з продуктивністю.",
	
    --Text
	MovingAll_PropsTo_SavedProps = "Переміщення всіх реквізитів до збережених реквізитів",
	SelectPropSpawn = "Виберіть опору для появи:",
	Spawned_Props = "Породжений реквізит",
	New_Preset = "Нове налаштування",
	No_Preset_Available = "Немає попереднього налаштування",
	Preset_TriggerDistance = "Попередньо встановлена відстань тригера",
	MovingSavedProps = "Переміщення %s до збережених пропозицій",
	UpdateTag = "Оновити тег",
	Categories = "Категорії",
	Decorating = "Декорування",
	Decor_Tabs = "Вкладки декору",
	Saved_Props = "Збережені реквізити",
	Show_Nearby_Only = "Показати лише поблизу",
	Show_Lights_Only = "Показувати лише світло",
	Show_LockedTarget_Only = "Показати лише заблоковану ціль",
	Show_Customizable_Only = "Показати лише настроювані",
	Show_CustomProps_Only = "Показати лише власний реквізит",
	ShowOnMap = "Показати на карті",
	Rename = "Перейменувати",
	Delete = "Видалити",
	Backup = "Резервне копіювання",
	Merge = "Об’єднати",
	Save_All = "Зберегти все",
	Despawn_All = "Деспаун Все",
	Save_ToSpecific_Tag = "Зберегти в певний тег",
	Saved_Props2 = "Збережені реквізити:",
	Move_To_Tag = "Перемістити до тегу",
	HideFromMap = "Приховати з карти",
	RemovingAllPropsFromTag = "Видалення всіх реквізитів із тегу...",
	RemoveAllProps = "Видалити всі реквізити",
	RemoveHomeMarkerMap = "Видалити маркер дому з карти",
	TeleportToLocation = "Телепорт до місця розташування",
	TeleportToTrigger = "Телепорт до тригера",
	TeleportToMark = "Телепорт до позначки",
	UpdateTagLocation = "Оновити розташування тегу",
	SharePresetWith_ThisTagOnly = "Поділитися шаблоном лише з цим тегом",
	SavedPresetFolder_Info = "Збережений стиль у папці AppearanceMenuMod/User/Decor",
	NoProps_WithThese_Conditions = "Без реквізиту з такими умовами",
	AddHomeMarkerMap = "Додайте маркер будинку на карту",
	Distance = "Відстань",
	Total_Props = "Загальний реквізит:",
	Type_Tag_here = "Введіть тег тут",
	In_World = "У Світі",
	Tags = "Теги",
	Tag = "Тег",
	Both = "Обидва",	
	
	-- >> POSES TAB
	BeginItem_TabPoses = "Пози",
	
	--Button
	Button_SmallCopyClipboard = "Копіювати в буфер обміну",
	
    --Button Label
    --Checkbox
    --Warning / Info / Tool Tip
    --Text
	Active_Animations = "Активні анімації",
	ShowHistory = "Показати історію",
	ClearHistory = "Очистити історію",
	SelectPoseForCurrentTarget = "Виберіть позу для поточної цілі:",
	LastUsedPoses = "Останні використані пози",
	
	
	
	-- >> TOOLS TAB
	BeginItem_TabTools = "Інструменти",
	BeginItem_TabPhotoModeNibblesReplacer = "Photo Mode Nibbles Replacer",
	BeginCombo_LookAt = "Подивіться",
	BeginCombo_WeatherControl = "Контроль погоди",
	
	--Button
	Button_SkipFrame = "Пропустити кадр",
	Button_ToggleLight = "Перемкнути світло",
	Button_ResetScale = "Скинути шкалу",
	Button_ShowAsLookAtTarget = "Показати як дивитися на ціль",
	Button_ResetLookAtTarget = "Скинути погляд на ціль",
	Button_TogglePrimaryWeapon = "Одягніть основну зброю",
	Button_ToggleSecondaryWeapon = "Одягніть вторинну зброю",
	Button_GiveCurrentEquippedWeapon = "Дайте поточну споряджену зброю",
	Button_SmallReset = "Скинути",
	Button_ResetToPlayer = "Скинути до гравця",
	Button_ClearSaved = "Очистити збережене",
	Button_Cyberpsycho = "Переключити Cyberpsycho",
	Button_ProtectNPCfromActions = "Захист NPC від дій",
	Button_AllFriendly = "Всі дружні",
	Button_AllHostile = "Все вороже",
	Button_AllFollower = "Усі послідовники",
	Button_AllFakeDie = "Усі фальшиві вмирають",
	Button_AllDie = "Всі помруть",
	Button_AllDespawn = "Весь Despawn",
	Button_InvMachineGun = "Кулемет",
	Button_InvSpeed2 = "швидкість",
	Button_ToggleMakeup = "Переключити макіяж",
	Button_TogglePiercings = "Перемкнути пірсинг",
	Button_ToggleSeamfix = "Перемкнути фіксацію швів",
        Button_TargetV = "Ціль V",
        Button_Target = "Цільова",
        Button_TeleportToLocation = "Телепорт до місця розташування",
        Button_TeleportToTrigger = "Телепорт до тригера",
        Button_TeleportToMark = "Телепорт до позначки",
        Button_RandomLocation = "Випадковий",
        Button_ShareCurrentLocation = "Поділитися поточним місцезнаходженням",
	Button_GoBackToLastLocation = "Повернутися до останнього розташування",
	Button_DeleteSelectedUserLocation = "Видалити вибране розташування користувача",
	
	--Slider / Drag 
	Slider_HeadStiffness = "Ригідність голови",
	Slider_HeadPoseOverride = "Заміна пози голови",
	Slider_ChestStiffness = "Ригідність грудей",
	Slider_ChestPoseOverride = "Перевизначення пози грудей",
	Slider_SlowMotion = "Повільний рух",
	Slider_DefaultAperture = "Діафрагма за замовчуванням",
	Slider_DefaultFieldofView = "Стандартне поле зору",
	Slider_MovementSpeed = "Швидкість руху",
	Drag_MovementSpeed = "Швидкість руху",
	
    --Button Label
	Button_Label_PauseTimeProgression = "Призупинити прогресування часу",
	Button_Label_UnpauseTimeProgression = "Скасувати паузу",
	Button_Label_UnfreezeTime = "Розморозити час",
	Button_Label_FreezeTime = "Час заморожування",
	Button_Label_OpenLightSettings = "Відкрийте налаштування світла",
	Button_Label_UpdateLightTarget = "Оновити Light Target",
	Button_Label_Activate = "активувати",
	Button_Label_Deactivate = "Дезактивувати",
	Button_Label_ChangeToCrouchStance = "Змініть положення на присідання",
	Button_Label_ChangeToStandStance = "Перейти в стійку",
	Button_Label_PickUpTarget = "Візьміть ціль",
	Button_Label_DropTarget = "Відпустіть ціль",
	Button_Label_FreezeTarget = "Заморозити ціль",
	Button_Label_UnfreezeTarget = "Розморозити ціль",
	Button_Label_OpenTargetTools = "Відкрийте Цільові інструменти",
	Button_Label_CloseTargetTools = "Закрийте цільові інструменти",
	
    --Checkbox
    --Warning / Info / Tool Tip
	Warn_FileNotFound_CollabsFolder_Error = "файл не знайдено в папці Collabs",
	Warn_ShowXYZ_Orientation_Info = "Показуйте стрілки X, Y і Z для легшої орієнтації під час переміщення цілі.",
	Warn_LookAtCamera_OptionOff_Info = "Вимкніть опцію «Погляд на камеру» після зміни цього параметра",
	Warn_DisableLookAtCamera_PhotoMode_Info = "Один раз вимкніть «Подивитися на камеру» в режимі фото, щоб діяти",
	Warn_RequiresRestart_Info = "Щоб набуло чинності, потрібно перезапустити гру",
	Warn_SlowMotion_PhotoMode_Info = "Уповільнений рух у фоторежимі працює, лише якщо відновити паузу за допомогою IGCS",
	Warn_WeatherControl_RequireCodeware = "Weather Control потребує Codeware 1.4+",
	Warn_StopNpc_UnequipWeapon_Info = "Це не дозволить NPC зняти вашу зброю. Примітка: під час бою NPC все одно зніме спорядження за бажанням.",
	Warn_OutOfCombat_NpcUnequip_Info = "Примітка: поза боєм NPC негайно зніме дану зброю.",
	Warn_Photomode_UnfreezeSkipFrames_Info = "У фоторежимі Unfreeze Target пропускатиме кадри в анімованих позах. Для повної функції (роз)заморожування вам потрібно використовувати Otis Camera Tools (IGCS).",
	Warn_UserLocationsFolder_Info = "Розташування користувачів зберігається в папці AppearanceMenuMod/User/Locations",
	Warn_SeeMoreAction_Info = "Ціль V або NPC, щоб побачити більше дій",
	Warn_SeeMoreActionProp_Info = "Цільовий NPC або Prop, щоб побачити більше дій",
	Warn_SeamfixPiercingToggle_Info = "Це збереже стан перемикачів «Макіяж», «Пірсинг» і «Виправлення швів», доки ви не закриєте гру.",
	Warn_PassiveMode_Info = "Вороги все одно атакуватимуть вас, якщо ви активуєте бій",
	Warn_TppCameraGameplay_Info = "TPP Camera не підходить для звичайних ігор, але гуляти весело ;)",
	Warn_AnimatedHead_PhotoMode_Info = "Вирази в режимі фото не працюватимуть, якщо ввімкнено анімовану голову.",
	Warn_ToolsOnly_WorksIngame = "Інструменти працюють лише в грі",
	Warn_InvButtonMachineGun_Info = "Ви знайшли його! Важкий кулемет додано до спорядження.",
	Warn_InvButton_Info = "Ви знайшли його! Тепер доступна функція Fast Motion.",
	InvButtonTip = "Що якщо я клацну тут?",
	InvButtonTip2 = "Клацання тут нічого не дає!",
	InvButtonTip3 = "НЕ КЛАЦАЙТЕ, ВАС ПОПЕРЕДЖАЛИ!",
	
    --Text
	Facial_Expression = "Вираз обличчя",
	Expressions = "Вирази",
	Look_At = "Подивіться",
	Look_At_Camera = "Подивіться на камеру:",
	Target_Tools = "Цільові інструменти",
	Rotation = "Обертання",
	Tilt_Rotation = "Нахил/Обертання",
	Mode = "режим:",
	Precision = "Точність",
	Relative = "Відносна",
	Direct = "Прямий",
	AdvMovement = "Adv. Рух",
	ForceGivenWeapon = "Примусова зброя",
	Scale = "масштаб",
	ProportionalMode = "Пропорційний режим",
	General_Actions = "Загальні дії",
	DisablePassiveMode = "Вимкніть пасивний режим",
	EnablePassiveMode = "Увімкніть пасивний режим",
	EnableGodMode = "Увімкніть режим Бога",
	DisableGodMode = "Вимкніть режим Бога",
	Infinite_Oxygen = "Нескінченний кисень",
	Select_Location = "Виберіть Розташування",
	Select_Expression = "Виберіть Вираз",
	Select_Category = "Виберіть категорію",
	Teleport_Actions = "Дії телепортації",
	Use_Teleport_Animation = "Використовуйте анімацію телепорту",
        Filter_Locations = "Розташування фільтрів",
        Locations = "Розташування",
        Default_Locations = "Розташування за умовчанням",
        Collab_Locations = "Місця співпраці",
        Button_AddTag = "Додати тег",
	Button_FilterByTags = "Фільтрувати за тегами",
	Button_Close = "Закрити",
	Favorite_Selected_Location = "Улюблене вибране місце",
	Unfavorite_Selected_Location = "Скасувати вибране місце",
	Edit_Selected_Location = "Редагувати вибране місце",
	Locations_Favorites = "--------- Вибране ----------",
	Locations_UserLocs = "------- Розташування користувачів -------",
	Locations_DefaultLocs = "----------- За умовчанням ----------",
	Share_Location = "Поділитися місцезнаходженням",
	Edit_Location = "Редагувати місцезнаходження",
	TimeWeather_Actions = "Дії часу та погоди",
	TimeofDay = "Час доби",
	Time_Actions = "Дії часу",
	Rain = "Дощ",
	Light_Rain = "Легкий дощ",
	Cloudy = "Хмарно",
	Fog = "Туман",
	Heavy_Clouds = "Важкі хмари",
	Light_Clouds = "Легка хмарність",
	Pollution = "забруднення",
	Sandstorm = "Піщана буря",
	Sunny = "Сонячно",
	Toxic_Rain = "Токсичний дощ",
	Deep_Blue = "Deep Blue",
	Squat_Morning = "Ранок присідань",
	Cloudy_Morning = "Хмарний ранок",
	Rainy_Night = "Дощова ніч",
	Courier_Clouds = "Кур'єр Хмари",
	Cursor_LockState = "Стан блокування",
	PhotoMode_NibblesReplacer = "Photo Mode Nibbles Replacer",
	PhotoModeEnhancements = "Покращення режиму фото",
	Button_ResetReplacerDatabase = "Скинути базу даних Replacer",
	DisablePhotoModeCursor = "Вимкнути курсор режиму фото",
	TPPCamera_Position = "Розташування камери ТЕС",
	AnimatedHeadin_PhotoMode = "Анімована голова в режимі фото",
	LockLook_AtCamera = "Заблокувати погляд на камеру",
	UnlockLook_AtCamera = "Розблокувати подивіться на камеру",
	Save_Toggles_State = "Зберегти Перемикає стан",
	Toggle_V_Head = "Перемкнути V Head",
	Toggle_TPP_Camera = "Перемкнути камеру TPP",
	Target_Nibbles = "Цільові кусачки",
	Target_Replacer = "Цільовий замінник",
	Left = "Ліворуч",
	Left_Close = "Ліворуч Закрити",
	Right = "правильно",
	Right_Close = "Праворуч Закрити",
	Center_Close = "Center Close",
	Center_Far = "Центр Дальній",
	Front_Close = "Закрити спереду",
	Front_Far = "Передній Далекий",
	All = "всі",
	Head_Only = "Тільки голова",
	Eyes_Only = "Тільки очі",
	Movement = "Рух",
	V_Actions = "V Дії",
	Invisible_V = "Невидимий В",
	LikeGTA_byGTATravel = "від GTA Travel",
	EnableSpawnedProps = "Увімкнути створені пропозиції",
	LightControl = "Контроль світла",
	Equipment = "Обладнання",
	
	-- >> DIRECTOR TAB
	BeginItem_TabNameDirector = "Директор",
	BeginItem_TabNameTriggers = "Тригери",
	BeginCombo_StartAppearance = "Почати зовнішній вигляд",
	BeginCombo_EndAppearance = "Кінцевий зовнішній вигляд",
	BeginCombo_Type = "Тип",
	BeginCombo_GoToTarget = "Перейти до цілі",
	BeginCombo_PlayVoice = "Відтворення голосу",
	BeginCombo_Attack = "Атака",
	BeginCombo_Triggers = "Тригери",
	BeginCombo_Scripts = "Сценарії",
	
	--Button
	Button_Yes = "так",
	Button_No = "немає",
	Button_SaveChangesOnly = "Тільки зберегти зміни",
	Button_RemoveMark = "Видалити позначку",
	Button_EditMark = "Редагувати позначку",
        Button_MoveMark = "Перемістити Марка",
        Button_MoveUp = "Рух вгору",
        Button_MoveDown = "Рух вниз",
        Button_NewMark = "Новий Марк",
	Button_AddActor = "Додати актора",
	Button_RemoveActor = "Видалити актора",
	Button_ChangeActor = "Змінити актора",
	Button_RadioOnlyOne = "Тільки один",
	Button_RadioRandom = "Випадковий",
	Button_RadioSequential = "Послідовний",
	Button_SaveTrigger = "Зберегти тригер",
	Button_NewCamera = "Нова камера",
	Button_NewScript = "Новий сценарій",
	Button_DragSpeed = "швидкість",
	Button_ToggleMarker = "Переключити маркер",
	Button_TestPose = "Тестова поза",
	Button_StopPose = "Поза зупинки",
	
    --Button Label
	Button_Label_PlayScript = "Грати сценарій",
	Button_Label_StopScript = "Зупинити сценарій",
	Button_Label_Stopping = "Зупинка...",
	Button_Label_Restarting = "Перезапуск...",
	Button_Label_AddMark = "Додати Марка",
	Button_Label_SaveWNewPos = "Зберегти з новою позицією",
	
    --Checkbox
    --Warning / Info / Tool Tip
	Warn_ActorSingleMark_Info = "Актор залишиться на одній марці",
	Warn_ActorRandomMark_Info = "Актор буде випадковим чином переміщатися між мітками",
	Warn_ActorSequentialMark_Info = "Актор буде переміщатися між мітками в порядку номерів",
	Warn_DeleteScript_Info = "Ви впевнені, що хочете видалити цей сценарій?",
	Warn_CloseCamForMove_Info = "Закрийте меню, щоб мати можливість переміщати камеру",
	Warn_CreateScriptsDesc_Info = "Створюйте сценарії, щоб додавати, одягати та спрямовувати акторів, щоб грати для машиніми, знімків екрана та рольових ігор.",
	Warn_PremadeScriptsDesc_Info = "Створюйте тригери, щоб активувати попередньо створені сценарії під час контакту.",
	Warn_CreateCamera_FovZoomDesc_Info = "Створюйте камери, щоб вільно пересуватися, встановлюйте різні поля огляду та рівні масштабування.",
	Warn_ShowMarksLocations_Info = "Відображає видимий значок у місцях позначки",
	Warn_AutoTalkNpc_Info = "Це змусить NPC говорити один раз кожну хвилину, коли вони знаходяться в радіусі дії (лише голосові NPC)",
	Warn_DirectActorPlayerPosition_Info = "Створіть позначку на поточній позиції гравця, щоб переміщати та керувати акторами",
	Warn_InMenuDirectorDesc = "Директор працює тільки в грі",
	
    --Text
	DirectorMode = "Режим директора",
	SelectActorToReplace = "Виберіть актора для заміни:",
	AddActorToCurrentScript = "Додати актора до поточного сценарію:",
	FacialExpression_WithColon = "Вираз обличчя:",
	FavoritePoses_WithColon = "Улюблені пози:",
	AddFavorites_Desc = "Спочатку додайте пози до вибраного на вкладці «Пози».",
	HoldDuration = "Тривалість утримання",
	Movement2 = "Рух:",
	Actions = "Дії:",
	Actors = "Актори",
	Editing = "Редагування",
	AutoTalk = "Автоматична розмова",
	ActorMarks = "Актор Маркс",
	Current_Actors = "Актуальні актори",
	Marks_Sequence = "Послідовність позначок:",	
	ShowMarks = "Показати позначки",
	Triggers = "Тригери",
	NewTrigger = "Новий тригер",
	ShowTrigger = "Показати тригер",
	Title = "Назва",
	Select_Trigger = "Виберіть Тригер",
	Select_Script = "Виберіть Сценарій",
	Delete_Trigger = "Видалити тригер",
	Triggers_On_Off = "Тригери On/Off",
	Running = "Біг",
	Script_Running = "Виконується сценарій...",
	Delete_Script = "Видалити сценарій",
	RepeatInLoop = "Цикл повторення",
	ActivationRadius = "Радіус активації",
	Activate = "активувати",
	Deactivate = "Дезактивувати",
	FOV = "FOV",
	Zoom = "Збільшити",
	LockFrame = "Рамка замка",
	Walk = "Прогулянка",
	Sprint = "спринт",
	Sequential = "Послідовний",
	Cameras = "Фотоапарати",
	NodeView = "Вид вузла",
	TeamA = "Команда А",
	TeamB = "Команда Б",
	
	
	
	-- >> SETTINGS TAB
	BeginItem_TabNameSettings = "Налаштування",
	BeginItem_TabNameGeneral = "Загальний",
	BeginItem_TabNameCompanions = "Компаньйони",
	BeginItem_TabNameUI = "Інтерфейс користувача",
	BeginItem_TabNameExperimental = "Експериментальний",
	BeginItem_TabNamePhotoMode = "Режим фото",
	
	--Button
	Button_RevertAllModelSwaps = "Скасувати всі заміни моделей",
	Button_RespawnAll = "Відродження всіх",
	Button_ForceDespawnAll = "Примусово позбутися всіх",
	Button_ClearFavorites = "Очистити вибране",
	Button_ClearAllSavedAppearances = "Очистити всі збережені вигляди",
	Button_ClearAllBlacklistedAppearances = "Очистити всі виступи в чорному списку",
	Button_ClearAllAppearanceTriggers = "Очистити всі тригери зовнішнього вигляду",
	Button_ClearAllSavedDespawns = "Очистити всі збережені Despawns",
	Button_SmallCreateTheme = "Створити тему",
	Button_SmallDeleteTheme = "Видалити тему",
	Button_SmallSet = "встановити",
	Button_ReloadAppearances = "Перезавантажте користувацькі вигляди",
	
    --Button Label
    --Checkbox
	Checkbox_SpawnAsCompanion = "Spawn As Companion",
	Checkbox_SpawnAsFriendly = "Spawn As Friendly",
	Checkbox_InvulnerableCompanion = "Невразливий компаньйон",
	Checkbox_RespawnOnLaunch = "Відродження під час запуску",
	Checkbox_LockTargetAfterSpawn = "Заблокувати ціль після появи",
	Checkbox_OpenTargetToolsAfterSpawn = "Відкрийте цільові інструменти після появи",
	Checkbox_DisplayAxisIndicatorByDefault = "Відображення індикатора осі за замовчуванням",
	Checkbox_PhotoModeEnhancements = "Покращення режиму фото",
	Checkbox_GodModeOnLaunch = "Режим Бога при запуску",
	Checkbox_PassiveModeOnLaunch = "Пасивний режим під час запуску",
	Checkbox_StreamerMode = "Режим стримера",
	Checkbox_OpenWCETOverlay = "Відкрити за допомогою CET Overlay",
	Checkbox_AutoResizingWindow = "Автоматичне змінення розміру вікна",
	Checkbox_ScanningReticle = "Сканування візирної сітки",
	Checkbox_FloatingTargetTools = "Інструменти плаваючої цілі",
	Checkbox_TabHeaderDescriptions = "Описи заголовків вкладок",
	Checkbox_ExpandFavoritesByDefault = "Розгорнути «Вибране за замовчуванням».",
	Checkbox_EnableScrollBars = "Увімкнути смуги прокрутки",
	Checkbox_AlwaysDisablePhotoModeCursor = "Завжди вимикайте курсор режиму фото",
	Checkbox_Camera = "Камера",
	Checkbox_DepthOfField = "DOF",
	Checkbox_Effect = "Ефект",
	Checkbox_Stickers = "наклейки",
	Checkbox_LoadSave = "Завантажити/Зберегти",
	Checkbox_ExperimentalFunstuff = "Експериментальні/веселі речі",
	Checkbox_EnableFreezeTargetInPhotoMode = "Увімкнути заморожування цілі в режимі фото",
	Checkbox_WeaponizeCompanions = "Озброїти компаньйонів",
	Checkbox_AllowPlayerToBeTargetedinPosestab = "Дозволити націлювання на гравця на вкладці «Пози».",
	Checkbox_AllowPlayerAnimationsonNPCs = "Дозволити анімацію гравця на NPC",
	Checkbox_AllowExpressionOnNpcPM = "Дозволити вирази та дивитися для NPC у фоторежимі",
        Checkbox_ResetTargetPositionPM = "Скидання цільової позиції для NPC у фоторежимі",
        Checkbox_EnableRandomLocation = "Увімкнути кнопку «Випадкове»: телепортувати гравця у випадкове місце зі списку",
        Checkbox_RestoreOnLaunch = "Відновити під час запуску",
        Radio_PrimarySlot = "Основний слот",
        Radio_SecondarySlot = "Вторинний слот",
	
    --Warning / Info / Tool Tip
	Warn_RespawnOnLaunch_Info = "Цей параметр увімкне/вимкне відродження попередньо збережених NPC під час завантаження гри. AMM автоматично зберігає створених вами NPC, коли ви виходите з гри.",
	Warn_BannedWords_Info = "Цей параметр увімкне/вимкне появу NPC, що містить слова: naked, nude, xxx, shower, birthday_suit, pp і penis.",
	Warn_TargetNpcVehicleHotkey = "Цільовий NPC або транспортний засіб для встановлення гарячих клавіш",
	Warn_FirstLaunchDecideTabsExpand_Info = "Цей параметр за замовчуванням розгорне «Вибране» на вкладках «Створення», «Зміна» та «Декор» під час першого запуску AMM.",
	Warn_ExperimentalTabDesc_Info = "Експериментальні функції додають більше функціональності, але вони можуть працювати не так добре, тому експериментальна позначка. Фактично, у більшості користувачів AMM увімкнено експериментальні функції. Тож не хвилюйтеся надто й отримуйте задоволення!",
	Warn_FreezeTargetPhotoMode_Info = "Цей параметр призначений для того, щоб допомогти заморозити анімацію з модів, які додають спеціальну анімацію до поз у фоторежимі або коли ви відновлюєте паузу за допомогою IGCS.",
	Warn_WeaponizeCompanions_Info = "Це дасть зброю та бойові здібності всім NPC. Очікуються Т-пози та дивні анімації.",
	Warn_PlayerAnimsOnNpc_Info = "Увімкніть це, якщо ви використовуєте мод, який дозволяє використовувати анімацію гравця на NPC.",
	Warn_UnpauseRequiresIGSC = "Для цього параметра IGCS потрібен час для відновлення паузи.",
	Warn_NotInstalled = "НЕ ВСТАНОВЛЕНО",
	Warn_DespawnAllProps = "Ви впевнені, що хочете видалити весь реквізит?",
	
    --Text
	AMM_Version = "Версія AMM:",
	CET_Version = "CET версія:",
	Codeware_Version = "Версія програмного забезпечення:",
	Game_Version = "Версія гри:",
	Companion_Damage = "Companion Damage:",
	Companion_Resistance = "Опір супутника:",
	Companion_Distance = "Відстань супутника:",
	xDamage = "x Пошкодження",
	xResistance = "x Опір",
	SavedAppearancesHotkeys = "Гарячі клавіші збережених зображень",
	Favorites = "Вибране",
	Appearances = "Поява",
	Blacklist = "Чорний список",
	AppearanceTriggers = "Тригери зовнішнього вигляду",
	SavedDespawns = "Врятовані Despawns",
	Interface_Language = "Мова інтерфейсу:",
	Custom_Appearances = "Нестандартний вигляд",
	PhotoModeAdjustments = "Налаштування режиму фото:",
	DisablePhotoModeTabs = "Вимкнути вкладки фоторежиму:",
	List_Height = "Висота списку",
	Listbox_Themes = "Теми",
	Weaponize = "Озброюватися",
	NoAppearanceSet = "Немає набору зовнішності",
	
	
	
	-- >> EXTRA	
	--Texts, warns, tips, info's, buttons and labels etc.
	Seat_FrontRight = "Передній правий",
	Seat_BackRight = "Назад праворуч",
	Seat_FrontLeft = "Передній лівий",
	Seat_BackLeft = "Назад ліворуч",
	Label_Door = "двері",
	Label_Window = "Вікно",

	Close = "Закрити",
	Far = "далеко",
	Moderate = "Помірний",
	
	-- >> Archives Screen
	Warning_MissingRequiredArchives = "У AMM відсутні один або кілька необхідних архівів. Встановіть будь-який відсутній необхідний архів у папку archive/pc/mod.",
	Warning_MissingOptionalArchives = "У AMM відсутні один або кілька архівів. Вони необов’язкові, але додають функціональність AMM. Ви можете ігнорувати ці попередження, але AMM може не працювати належним чином.",
	
	
	-->> INIT.LUA
	AMMNeedsAttention = "AMM потребує уваги",
	MISSING_ARCHIVES = "ВІДСУТНІ АРХІВИ",
	VERSION_INFORMATION = "ІНФОРМАЦІЯ ВЕРСІЇ",
	CREDITS = "КРЕДИТИ",
	UPDATE_HISTORY = "ОНОВИТИ ІСТОРІЮ",
	Updates = "Оновлення",
	MISSING = "ВІДСУТИЙ",
	REQUIRED = "ОБОВ'ЯЗКОВО",
	OPTIONAL = "НЕОБОВ'ЯЗКОВО",
	WHATS_NEW = "ЩО НОВОГО", --Line 83 Function Error

	--Button
	Button_Ignorewarningsforthisversion = "Ігнорувати попередження для цієї версії",
	Button_Credits = "Кредити",
	Button_Cool = "Круто!",

	--Button Label
	Label_SpawnFavorites = "Spawn Favorites",
	Label_SwapFavorites = "Поміняти улюблені",
	Label_FavoriteAppearances = "Улюблені виступи",
	Label_Cancel = "Скасувати",

	--Text
	Hotkey_i = "Гаряча клавіша %i",

	--Node - Function Error(nil value) 
	Top = "Топ", --Line 116
	Bottom = "Дно",
	Off = "Вимкнено",
	
	--Voice Overs
	Label_GreetV = "Вітаю В",
	Label_FearFoll = "Fear Foll",
	Label_FearToll = "Страх Толл",
	Label_FearBeg = "страх поч",
	Label_FearRun = "Fear Run",
	Label_StealthSearch = "Невидимий пошук",
	Label_StealthDeath = "Прихована смерть",
	Label_StealthRestore = "Приховане відновлення",
	Label_StealthEnd = "Стелс-кінець",
	Label_CuriousGrunt = "Цікавий Грант",
	Label_GrappleGrunt = "Грейфер Грант",
	Label_Bump = "Шишка",
	Label_VehicleBump = "Вибоїна автомобіля",
	Label_TurretWarning = "Попередження про турель",
	Label_OctantWarning = "Октант Попередження",
	Label_DroneWarning = "Попередження про дрон",
	Label_MechWarning = "Механічне попередження",
	Label_EliteWarning = "Елітне попередження",
	Label_CameraWarning = "Попередження про камеру",
	Label_EnemyWarning = "Попередження ворога",
	Label_HeavyWarning = "Серйозне попередження",
	Label_SniperWarning = "Попередження про снайпера",
	Label_AnyDamage = "Будь-які пошкодження",
	Label_Danger = "Небезпека",
	Label_CombatStart = "Бойовий старт",
	Label_CombatEnd = "Кінець бою",
	Label_CombatTargetHit = "Бойове влучення в ціль",
	Label_PedestrianHit = "Наїзд на пішохода",
	Label_LightHit = "Легкий удар",
	Label_Curse = "Прокляття",
	Label_Irritated = "роздратований",
	Label_GrenadeThrow = "Кидок гранати",
	Label_Gotakill = "Отримав вбивство!",
	
	--Expressions
	Neutral = "Нейтральний",
	Joy = "Радість",
	Smile = "Посміхніться",
	Sad = "Сумно",
	Surprise = "Сюрприз",
	Aggressive = "Агресивний",
	Anger = "гнів",
	Interested = "зацікавлений",
	Disinterested = "Безкорисливий",
	Disappointed = "Розчарований",
	Disgust = "Огида",
	Exertion = "навантаження",
	Nervous = "нервовий",
	Fear = "Страх",
	Terrified = "Наляканий",
	Pain = "Біль",
	Sleepy = "Сонний",
	Unconscious = "Без свідомості",
	Dead = "Мертвий",

	-- Extra Expressions
	Frown = "Хмуритися",
	Shocked = "Шокований",
	Annoyed_2 = "Роздратований 2",
	Contempt = "Презирство",
	Irritated = "роздратований",
	Sceptical_1 = "Скептичний 1",
	Sceptical_2 = "Скептичний 2",
	Annoyed_1 = "Роздратований 1",
	Offended = "Ображений",
	Disgusted = "Огидно",
	Disappointed_2 = "Розчарований 2",
	Alert = "Попередження",
	Crying = "Плаче",
	Embarrassed = "Збентежений",
	Humiliated = "Принижені",
	Impatient = "Нетерплячий",
	Anguished = "Засмучений",
	Worried = "хвилювався",
	Guilty = "Винні",
	Grieving = "Скорботний",
	RestrainedAnger = "Стриманий гнів",
	Afraid = "боїться",
	LookingUpAnnoyed = "Роздратований погляд",
	Offended_2 = "Ображений 2",
	Resentful = "Ображений",
	SadExtra = "Сумний екстра",
	NervousBreath = "Нервове дихання",
	ScreamingLong = "Довгий крик",
	ScreamingShort = "Screaming Short",
	ScaredBreath = "Перелякане дихання",
	CryingPainful = "Плач болячий",
	SelfReflectAnger = "Самовідображення гніву",
	IndulgentSmile = "Поблажлива усмішка",
	Impressed = "Вражений",
	LongSmile = "Довга усмішка",
	ShortSmile = "Коротка усмішка",
	SimpleSmile = "Проста усмішка",
	Confident = "Впевнений",
	Relief = "рельєф",
	Impressed_2 = "Вражений 2",
	Admiring = "Милуючись",
	Fascinated = "Зачарований",
	RaisedBrows = "Підняті брови",
	LookingUpThinking = "Дивлячись Мислення",
	LeftGlanceProcessing = "Обробка лівого погляду",
	LeftGlanceCloseUp = "Лівий погляд крупним планом",
	LookingAround = "Озираючись навколо",
	LookingDownThinking = "Дивлячись вниз мислення",
	LookingAroundAlt = "Розглядаючи Альт",
	EyesDartFromLeft = "Очі стріляють зліва",
	EyesDartFromRight = "Очі стріляють справа",
	EyesDartToRight = "Очі кидаються вправо",
	LookingLeft = "Дивлячись ліворуч",
	LookingUpThinking_2 = "Дивитися вгору, думати 2",
	RightGlanceProcessing = "Обробка правого погляду",
	LookingDown = "Дивлячись вниз",
	Left90GlanceClose = "Left90Glance Close",
	LookingUp = "Дивлячись вгору",
	Right90GlanceClose = "Right90Glance Close",
	LookingLeftUp = "Дивлячись вліво вгору",
	LookingRightUp = "Дивлячись прямо вгору",
	ReadingDown = "Читання вниз",
	ReadingUp = "Читання вгору",
	ReadingMiddle = "Середина читання",
	FrontCloseGlance = "Близький погляд спереду",
	WinkLeft = "Wink Ліворуч",
	EyeRoll = "Закочування очей",
	Squint = "Примружитися",
	FalseSmile_2 = "Фальшива усмішка 2",
	FalseSmile_1 = "Фальшива усмішка 1",
	ListeningNewInfo = "Прослуховування нової інформації",
	WhatDoYouWant = "Що ти хочеш",
	Maybe = "можливо",
	SearchingForWords = "Пошук слів",
	What = "Що",
	Where = "Де",
	SureSure = "Звичайно, Звичайно",
	ListenToMe = "Слухай мене",
	StopThePolice = "Зупиніть поліцію",
	HurryUp = "Поспішайте",
	ShutUp = "Замовкни",
	WinkRight = "Wink Right",
	MockingSmile = "Глузлива усмішка",
	AsymmetricalSmile = "Асиметрична посмішка",
	SarcasticSmile = "Саркастична усмішка",
	Sex = "секс",
	LipBite_1 = "Укус губи 1",
	LipBite_2 = "Укус губи 2",
	Moan = "стогін",
	LipBite_3 = "Укус губи 3",
	Pout = "надутися",
	SexySmile = "Сексуальна усмішка",
	Swallow = "Ластівка",
	SensualSmile = "Чуттєва усмішка",
	SexScene_1 = "Сексуальна сцена 1",
	SexScene_2 = "Сексуальна сцена 2",
	Kiss = "поцілунок",
	UsingInhaler = "Використання інгалятора",
	ShortYawn = "Коротке позіхання",
	Yawn = "позіхати",
	Coughing = "Кашель",
	Bite = "Укус",	
	EatingFast = "Швидка їжа",
	ShortDrink = "Короткий напій",
	Drinking = "пити",
	FastBite = "Швидкий укус",
	LongDrink = "Довгий напій",
	ShortSmoking = "Короткий куріння",
	LongSmoking = "Тривале куріння",
	Smoking = "куріння",
	Eating_1 = "Їсти 1",
	Eating_2 = "їсти 2",
	Eating_3 = "Їсти 3",
	Eating_4 = "Їсти 4",
	Vomit = "Блювота",
	BeingRevived = "Будучи відродженим",
	MalwarePositive = "Шкідливе програмне забезпечення",
	MalwareNegative = "Шкідливе програмне забезпечення негативно",
	MalwareInfected = "Інфіковано шкідливим програмним забезпеченням",
	FaceMorphActivate = "Активація трансформації обличчя",
	LieNetChairSleep = "Брехня Сітка Стілець Сон",
	LieNetChairBreathe = "Стілець Lie Net Breathe",
	NetrunnerDeathUnplugged = "Netrunner Death Unplugged",
	VeryItchyNose = "Дуже свербить ніс",
	RollerCoasterNervous = "Американські гірки Нервовий",
	Pfft = "пфф",
	Hahaha = "Ха-ха-ха",
	Sniff = "Понюхати",
	Ahaaa = "Ахааа",
	Heh = "хех",
	Huh = "га",
	Haaa = "Хааа",
	Sigh_Lipsync = "Зітхання Lipsync",
	Hmm = "Хм",
	Whispering_1 = "Шепіт 1",
	Whispering_2 = "Шепіт 2",
	ApprovalYes = "Схвалення Так",
	SubtleYes = "Тонкий Так",
	QuickNoShake = "Швидкий без струшування",
	FirmYes = "Твердо Так",
	LongNo = "довгий номер",
	SubtleNo = "Тонкий номер",
	NoContempt = "Без презирства",
	NoDisapproval = "Жодного несхвалення",
	FirmNo = "№ фірми",
	NoEnthusiastic = "Без ентузіазму",
	MockingYes = "Знущання Так",
	EnthusiasticYes = "З ентузіазмом Так",
	AsymmetricalCornerUp = "Асиметричний кут вгору",
	CornersUp = "Кути вгору",
	SoftSigh = "М'яке зітхання",
	BreathGasp = "Дихання",
	AssymetricalSneer = "Асиметрична насмішка",
	CrimpingLips = "Гофрування губ",
	BrowsDown = "Брови вниз",
	BrowsLeftUp = "Брови вліво вгору",
	BrowsRightUp = "Брови вгору",
	BrowsUp = "Брови вгору",
	ClosedEyes_1 = "Закриті очі 1",
	ClosedEyes_2 = "Закриті очі 2",
	EyesClosed = "Заплющені очі",
	LookRight = "Дивіться праворуч",
	FastBlink = "Швидке моргання",
	SlowBlink = "Повільне моргання",
	NormalBlink = "Нормальне моргання",
	TinyBlink = "Tiny Blink",
	HalfBlink = "Напівблимання",
	RegularSaccade = "Регулярна саккада",
	FrequentSaccade = "Часта саккада",
	PhotoCloseupEyes = "Фото крупним планом очі",
	PhotoCloseupLips = "Фото крупним планом губи",
	PhotoCloseupHair = "Фото крупним планом волосся",
	PhotoCloseupChin = "Фото крупним планом підборіддя",
	PhotoCloseupNose = "Фото крупним планом ніс",
	PhotoCloseup = "Фото крупним планом",
	PhotoCloseupPleased = "Фото крупним планом задоволений",
	PhotoCloseupBody = "Фото крупним планом тіла",
	PhotoCloseupTeeth = "Фото крупним планом зубів",
	PhotoCloseupIN = "Фото крупним планом IN",
	PhotoCloseupOUT = "Фото крупним планом OUT",
	Bored = "Нудно",
	Charming = "Чарівний",
	Furious = "Розлючений",
	Happy = "Щаслива",
	Pissed = "Розлючений",
	Pleased = "Задоволений",
	Scared = "Наляканий",
	Surprised = "Здивований",
	Sadness = "Печаль",
	Whistling = "Свистячий",
	Singing_1 = "Спів 1",
	Singing_2 = "Спів 2",
	Singing_3 = "Спів 3",
	Alerted = "Попереджений",
	Hit_1 = "Хіт 1",
	Hit_2 = "Хіт 2",
	Wounded = "Поранений",
	Death = "Смерть",

	-- Expressions Category
	Negative = "Негативний",
	Positive = "Позитивний",
	Contemplative = "Споглядальний",
	Social = "Соціальний",
	Sexual = "Сексуальний",
	Action = "Дія",
	Vocal = "Вокал",
	Yes_N_No = "Так і Ні",
	Nuance = "Нюанс",
	Static = "Статичний",
	Combat = "Бойовий",
	
	--Props
	AMM_Props_Desc = "Додає реквізит, персонажів і транспортні засоби. Без цього AMM не запуститься.",
	AMM_JohnnyCompanion_Desc = "Додає Джонні Сільверхенда як персонажа, який можна створити.",
	AMM_ScenesPack_Desc = "Додає 9358 сцен анімації до системи поз.\nЗавантажте його на сторінці Nexus AMM.",
	AMM_SoundPack_Desc = "Додає створювані звукові ефекти.",
	AMM_KerryPP_Desc = "Додає новий оголений вигляд.",
	AMM_BenjaminStonePP_Desc = "Додає новий оголений вигляд.",
	AMM_RiverPP_Desc = "Додає новий оголений вигляд.",
	AMM_YorinobuPP_Desc = "Додає новий оголений вигляд.",
	AMM_LizzyIncognito_Desc = "Додає новий зовнішній вигляд.",
	AMM_MeredithXtra_Desc = "Додає новий зовнішній вигляд.",
	AMM_DelamainFix_Desc = "Додає Delamain повне тіло.",
	AMM_HanakoNoMakeup_Desc = "Дозволяє AMM видаляти макіяж Ханако під час використання спеціального вигляду.",
	AMM_JudyBodyRevamp_Desc = "Замінює тіло Джуді на нове покращене.",
	AMM_PanamBodyRevamp_Desc = "Замінює тіло Панама на нове покращене.",
	AMM_MistyBodyRevamp_Desc = "Замінює тіло Місті на нове покращене.\nЗавантажте його на сторінці Nexus AMM.",
	AMM_1VesHanakoFixedBodyNaked_Desc = "Замінює тіло Ханако на нове покращене.",
	AMM_PinkyDudeANIMFacialExpressionsFemV_Desc = "Вмикає інструменти виразу обличчя на Female V",
	AMM_PinkyDudeANIMFacialExpressionsMaleV_Desc = "Вмикає інструменти виразу обличчя на Male V",
	AMM_DinoTattooFixArchive_Desc = "Замінює сітку та текстуру.",
	AMM_SongbirdBodyFixArchive_Desc = "Замінює тіло, щоб виправити сіру область. Ще не ідеальний.",
	AMM_RitaWheelerCombatEnablerArchive_Desc = "Замінює файл сутності, щоб увімкнути анімацію бою.",
	AMM_CheriAppearances_Desc = "Додає нові образи. Завантажте його на сторінці Nexus AMM.",
	AMM_BryceNaked_Desc = "Додає новий оголений вигляд. Завантажте його на сторінці Nexus AMM.",
	AMM_EvelynNaked_Desc = "Фіксує своє тіло, щоб вона виглядала оголеною. Завантажте його на сторінці Nexus AMM.",
	AMM_SaburoAppearances_Desc = "Додає нові образи. Завантажте його на сторінці Nexus AMM.",
	AMM_TbugAppearances_Desc = "Додає нові образи. Завантажте його на сторінці Nexus AMM.",
	AMM_8ug8eagAppearances_Desc = "Додає нові образи. Завантажте його на сторінці Nexus AMM.",
	
	--Equipments (There is a Function Error(nil value) in this section, These are just labels that are not connected to any localizable strings in the file)
	Fists = "Кулаки", --Line 2377 
	Katana = "Катана",
	Mantis_Blades = "Леза богомола",
	Machete = "Мачете",
	Hammer = "Молоток",
	Baton = "Батон",
	Knife = "Ніж",
	Crowbar = "Лом",
	Baseball_Bat = "Бейсбольна бита",
	Assault_Rifle = "Штурмова гвинтівка",
	Sidewinder = "Сайдвіндер",
	Sniper_Rifle = "Снайперська гвинтівка",
	Shotgun = "Дробовик",
	SMG = "SMG",
	Handgun = "Пістолет", --Line 2391
	
	--Warning / Info / Tooltip
	Warn_CantSave_BlacklistedAppearance = "Ви не можете зберегти вигляд у чорному списку!",
	Warn_ConfirmDeleteSavedAppearances = "Ви впевнені, що бажаєте видалити всі збережені виступи?",
	Warn_ConfirmDeleteBlacklistedAppearances = "Ви впевнені, що хочете видалити всі свої виступи в чорному списку?",
	Warn_ConfirmDeleteSavedDespawns = "Ви впевнені, що хочете видалити всі збережені деспауни?",
	Warn_ConfirmDeleteAppearanceTriggers = "Ви впевнені, що хочете видалити всі тригери появи?",
	Warn_ConfirmDeleteCurrentAppearance = "Ви впевнені, що бажаєте видалити поточний активний стиль?",
	Warn_WeaponizeNpcAnimationIssues = "Не кожен NPC матиме необхідні анімації для використання кожного типу зброї. Можуть виникнути Т-пози та неправильна анімація.\nВи впевнені, що бажаєте його ввімкнути?",
	Warn_ConfirmEnableExperimentalAndSave_Info = "Ви впевнені, що бажаєте ввімкнути експериментальні функції? AMM може не працювати належним чином. Використовуйте його на свій страх і ризик!",
	Warn_DeleteFavoritesAskWhichOne_Info = "Якщо ви впевнені, що хочете видалити всі свої вибрані, виберіть потрібне нижче:",
	Popup_Error_Title = "Помилка",
	Button_Ok = "добре",
	Popup_FavoriteName = "Улюблене ім'я",
	Popup_RenamePreset = "Перейменувати стиль",
	Popup_RenameProp = "Перейменувати Prop",
	Editor_Title = "Редактор тем",
	Editor_Field_ThemeName = "Назва теми",
	Editor_Hint_InsertThemeName = "Вставте назву нової теми",
	Error_ThemeNameExists = "Назва теми вже існує",
}
