return {

    -- >> SCAN TAB
	BeginItem_TabNameScan = "掃描",
	
	--Button
	Button_CyclesAppearances = "循環外觀",
	Button_SavesAppearance = "儲存外觀",
	Button_ClearSavedAppearance = "清除保存的外觀",
	Button_UnlockDoor = "撥動門鎖",
	Button_RestoreAccess = "恢復訪問",
	Button_UnlockVehicle = "解鎖車輛",
	Button_RepairVehicle = "維修車輛",
	Button_OpenCloseDoors = "打開/關閉門",
	Button_OpenCloseWindows = "開啟/關閉視窗",
	Button_ToggleEngine = "切換引擎",
	Button_ToggleAIDriver = "切換人工智慧驅動程式",
	Button_ToggleCamera = "切換相機",
	Button_ToggleRadio = "切換收音機",
	Button_NextRadioStation = "下一個廣播電台",
	Button_TargetMountedVehicle = "目標車載",
	Button_AssignSeats = "分配座位",
	Button_Assign = "分配",
	Button_Reset = "重置",
	Button_FakeDie = "假模具",
	Button_SmallCopy = "複製",
	
    --Button Label
	Button_Label_Unfollower = "取消追蹤",
	Button_Label_Follower = "追隨者",
	Button_Label_SaveDespawn = "拯救消失者",
	Button_Label_ClearSavedDespawn = "清除已儲存的消失",
	Button_LabelLockTarget = "鎖定目標",
	Button_LabelUnlockTarget = "解鎖目標",
	Label_AddToSpawnFavs = "新增至可生成的收藏夾",
	Label_RemoveFromSpawnFavs = "從可產生的收藏夾中刪除",
	
    --Checkbox
	Checkbox_SavedDespawnsActive = "已儲存的消失活動",
	Checkbox_KeepAssigned = "換車時保持分配",
	
    --Warning / Info / Tool Tip
	WarnTextAI_FastTravel = "在地圖上選擇一個快速旅行點即可出發",
	WarnText_DontReloadMods = "不要使用“重新加載所有模組”。\n请重新加载您的保存游戏或移动到其他区域。",
	Warning_NoTarget_Desc = "沒有目標！查看 NPC、車輛或物體即可開始",
	ToolTip_DisableCheckboxReloadSave_AbleTotargetClearSavedDespawns = "禁用此复选框并重新加载您的保存，以便能够瞄准清除已保存的消失",
	
    --Text
	Build_Mode = "建構模式",
	Speed = "速度：",
	Search = "搜尋",
	Clear = "清除",
	Player = "玩家",
	Saved = "已儲存",
	Saved_ = "已儲存_",
	Current = "目前",
	Current_ = "目前",
	Select_Seat = "選擇座位",
	Target_Info = "目標訊息",
	Target_Actions = "目標行動",
	No_Appearances = "沒有出場",
	No_Target = "無目標",
	Favorite_Appearance = "最喜歡的外表",
	Unfavorite_Appearance = "不喜歡的外表",
	Blacklist_Appearance = "黑名單出現",
	Unblacklist_Appearance = "取消黑名單外觀",
	Saved_Appearance = "保存的外觀：",
	Current_Appearance = "目前外觀：",
	List_of_Appearances = "出場名單",
	Appearance_Trigger = "外觀觸發",
	None = "無",
	Default = "預設",
	Zone = "專區",
	Area = "面積",
	Position = "職位",

	
	-- >> SPAWN TAB
	BeginItem_TabNameSpawn = "產生",
	
	--Button
	Button_Refresh = "重新整理",
	Button_Save = "儲存",
	Button_Confirm = "確認",
	Button_Cancel = "取消",
	Button_SmallSave = "儲存",
	Button_SmallRespawn = "重生",
	Button_SmallDespawn = "消失",
	Button_SmallDespawn_WithSpace = "消失",
	Button_SmallTarget = "目標",
	Button_SmallEquipment = "裝置",
	Button_LabelHostile = "敵對的",
	Button_LabelFriendly = "友善",
	
    --Button Label
	Label_Favorite = "最愛",
	Label_Unfavorite = "不喜歡",
	
    --Checkbox
    --Warning / Info / Tool Tip
	Warn_PlayerInMenu = "選單中的播放器",
	Warn_AMMonlyfunctions_ingame = "AMM僅在遊戲中起作用",
	Warn_SpawnWorksInGame = "生成僅在遊戲中有效",
	Warn_InitError = "初始化錯誤",
	Warn_InitError_Info = "請檢查 AppearanceMenuMod.log 以了解更多資訊。",
	
    --Text
	Active_Spawns = "活躍的生成",
	NoActiveSpawns = "沒有活躍的生成",
	Select_To_Spawn = "選擇生成",
	No_Results = "沒有結果",
	ItsEmpty = "是空的:(",
	Existing_Name = "現有名稱",
	Name = "名稱",
	
	
	
	-- >> SWAP TAB
	BeginItem_TabNameSwap = "互換",
	
	--Button
	Button_SmallRevert = "恢復",
	
    --Button Label
    --Checkbox
    --Warning / Info / Tool Tip
	Warn_ReloadSaveUpdateChanges = "重新加載您的保存遊戲以更新更改！",
	Warn_NeedReloadSaveUpdateChanges = "您將需要重新載入儲存以更新變更。",
	Warn_ReplacerSwap = "不能換替代品啊！在照片模式下使用「工具」標籤來定位它們，然後從「產生」標籤或「目標工具」切換它們的外觀。",
	Warning = "警告",
	Warning2 = "警告：",
	SaveSwap_Tooltip = "保存您的交換內容，以便在重新加載遊戲後保留它們。",
	
    --Text
	CantSwapReplacer = "無法更換替代品",
	Active_Model_Swaps = "主動模型交換",
	Save = "儲存",
	Restore = "恢復",
	Current_Target = "目前目標：",
	Target_ID = "目標ID：",
	SelectSwap_CurrentTarget = "選擇與目前目標交換：",
	NoNPC_LookNPC = "未找到 NPC！看NPC開始",
	
	-- Locations Categories
	Residences = "住宅",
	ArasakaAndCorpo = "荒坂公司",
	ClubsAndBars = "俱樂部和酒吧",
	HotelsAndPleasure = "飯店及休閒",
	UndergroundAndCrime = "地下與犯罪",
	GovernmentAndSecurity = "政府與安全",
	StoryAndUnique = "故事與獨特",
	Ripperdocs = "開膛手文檔",
	LandmarksAndOpenWorld = "地標和開放世界",
	SpoilersAndHidden = "劇透與隱藏",
	UserLocations = "使用者位置",
	
	
	-- >> DECOR TAB
	BeginItem_TabDecor = "裝飾",
	BeginItem_TabPresets = "預設",
	Begin_ComboPresets = "預設",
	
	--Button
	Button_SmallClone = "複製",
	Button_SmallRemove = "刪除##",
	Button_SmallRename = "重命名##",
	Button_SmallUpdate = "更新##",
	Button_SmallCancel = "取消",
	Button_Frame = "框架",
	
    --Button Label
	Button_LabelHide = "隱藏",
	Button_LabelUnhide = "取消隱藏",
	
    --Checkbox
    --Warning / Info / Tool Tip
	Warn_PersistPropSave = "生成道具来装饰你的房子或任何你想要的地方！保存道具讓它們堅持下去！",
	Warn_DespawnInProgress_PleaseWait = "正在消失。請稍等。",
	Warn_PresetsFolder_Info = "使用者預設保存在 AppearanceMenuMod/User/Decor 資料夾中",
	Warn_CustomPresets_Info = "此預設包括自訂道具",
	Warn_CustomPropsModders_Info = "客製化道具製作者：",
	Warn_GamepadDirectMode_Info = "這可以在使用遊戲手把時更好地與直接模式整合。它還啟用了一個小的信息視窗。",
	Warn_PresetTriggerDistanceFar = "設定為“遠”可能會導致效能問題。",
	
    --Text
	MovingAll_PropsTo_SavedProps = "將所有道具移至已儲存的道具",
	SelectPropSpawn = "選擇要生成的道具：",
	Spawned_Props = "生成的道具",
	New_Preset = "新預設",
	No_Preset_Available = "無可用預設",
	Preset_TriggerDistance = "預設觸發距離",
	MovingSavedProps = "將 %s 移至已儲存的道具",
	UpdateTag = "更新標籤",
	Categories = "類別",
	Decorating = "裝飾",
	Decor_Tabs = "裝飾標籤",
	Saved_Props = "保存的道具",
	Show_Nearby_Only = "僅顯示附近",
	Show_Lights_Only = "僅顯示燈光",
	Show_LockedTarget_Only = "僅顯示鎖定目標",
	Show_Customizable_Only = "僅顯示可自訂的",
	Show_CustomProps_Only = "僅顯示自訂道具",
	ShowOnMap = "在地圖上顯示",
	Rename = "重新命名",
	Delete = "刪除",
	Backup = "備份",
	Merge = "合併",
	Save_All = "全部保存",
	Despawn_All = "全部消失",
	Save_ToSpecific_Tag = "儲存到特定標籤",
	Saved_Props2 = "保存的道具：",
	Move_To_Tag = "移至標籤",
	HideFromMap = "從地圖中隱藏",
	RemovingAllPropsFromTag = "正在從標籤中刪除所有道具...",
	RemoveAllProps = "移除所有道具",
	RemoveHomeMarkerMap = "從地圖上刪除主頁標記",
	TeleportToLocation = "傳送到地點",
	TeleportToTrigger = "傳送至觸發點",
	TeleportToMark = "傳送到標記",
	UpdateTagLocation = "更新標籤位置",
	SharePresetWith_ThisTagOnly = "僅與此標籤共用預設",
	SavedPresetFolder_Info = "已儲存預設到 AppearanceMenuMod/User/Decor 資料夾",
	NoProps_WithThese_Conditions = "沒有道具符合這些條件",
	AddHomeMarkerMap = "將主頁標記新增至地圖",
	Distance = "距離",
	Total_Props = "道具總數：",
	Type_Tag_here = "在此輸入標籤",
	In_World = "在世界上",
	Tags = "標籤",
	Tag = "標籤",
	Both = "兩者都",	
	
	-- >> POSES TAB
	BeginItem_TabPoses = "姿勢",
	
	--Button
	Button_SmallCopyClipboard = "複製到剪貼簿",
	
    --Button Label
    --Checkbox
    --Warning / Info / Tool Tip
    --Text
	Active_Animations = "活動動畫",
	ShowHistory = "顯示歷史",
	ClearHistory = "清除歷史記錄",
	SelectPoseForCurrentTarget = "選擇目前目標的姿勢：",
	LastUsedPoses = "最後使用的姿勢",
	
	
	
	-- >> TOOLS TAB
	BeginItem_TabTools = "工具",
	BeginItem_TabPhotoModeNibblesReplacer = "照片模式半位元組替換器",
	BeginCombo_LookAt = "看看",
	BeginCombo_WeatherControl = "天氣控制",
	
	--Button
	Button_SkipFrame = "跳幀",
	Button_ToggleLight = "切換燈",
	Button_ResetScale = "重置比例",
	Button_ShowAsLookAtTarget = "顯示為注視目標",
	Button_ResetLookAtTarget = "重置查看目標",
	Button_TogglePrimaryWeapon = "裝備主武器",
	Button_ToggleSecondaryWeapon = "裝備副武器",
	Button_GiveCurrentEquippedWeapon = "給予當前裝備的武器",
	Button_SmallReset = "重置",
	Button_ResetToPlayer = "重設為播放器",
	Button_ClearSaved = "清除已儲存",
	Button_Cyberpsycho = "切換 Cyberpsycho",
	Button_ProtectNPCfromActions = "保護 NPC 免受行動傷害",
	Button_AllFriendly = "一切友好",
	Button_AllHostile = "全部充滿敵意",
	Button_AllFollower = "所有追蹤者",
	Button_AllFakeDie = "所有假模具",
	Button_AllDie = "全部死亡",
	Button_AllDespawn = "全部消失",
	Button_InvMachineGun = "機關槍",
	Button_InvSpeed2 = "速度",
	Button_ToggleMakeup = "切換化妝",
	Button_TogglePiercings = "切換穿孔",
	Button_ToggleSeamfix = "切換接縫修復",
        Button_TargetV = "目標V",
        Button_Target = "目標",
        Button_TeleportToLocation = "傳送到地點",
        Button_TeleportToTrigger = "傳送至觸發點",
        Button_TeleportToMark = "傳送到標記",
        Button_RandomLocation = "隨機",
        Button_ShareCurrentLocation = "分享當前位置",
	Button_GoBackToLastLocation = "回到上一個位置",
	Button_DeleteSelectedUserLocation = "刪除選定的用戶位置",
	
	--Slider / Drag 
	Slider_HeadStiffness = "頭部僵硬",
	Slider_HeadPoseOverride = "頭部姿勢覆蓋",
	Slider_ChestStiffness = "胸部僵硬",
	Slider_ChestPoseOverride = "胸部姿勢覆蓋",
	Slider_SlowMotion = "慢動作",
	Slider_DefaultAperture = "預設光圈",
	Slider_DefaultFieldofView = "預設視野",
	Slider_MovementSpeed = "移動速度",
	Drag_MovementSpeed = "移動速度",
	
    --Button Label
	Button_Label_PauseTimeProgression = "暫停時間進展",
	Button_Label_UnpauseTimeProgression = "取消暫停時間進度",
	Button_Label_UnfreezeTime = "解凍時間",
	Button_Label_FreezeTime = "凍結時間",
	Button_Label_OpenLightSettings = "開啟燈光設置",
	Button_Label_UpdateLightTarget = "更新光目標",
	Button_Label_Activate = "啟用設定",
	Button_Label_Deactivate = "停用",
	Button_Label_ChangeToCrouchStance = "改為蹲伏姿勢",
	Button_Label_ChangeToStandStance = "改變站立姿勢",
	Button_Label_PickUpTarget = "拾取目標",
	Button_Label_DropTarget = "掉落目標",
	Button_Label_FreezeTarget = "凍結目標",
	Button_Label_UnfreezeTarget = "解凍目標",
	Button_Label_OpenTargetTools = "開啟目標工具",
	Button_Label_CloseTargetTools = "關閉目標工具",
	
    --Checkbox
    --Warning / Info / Tool Tip
	Warn_FileNotFound_CollabsFolder_Error = "在 Collabs 資料夾中找不到文件",
	Warn_ShowXYZ_Orientation_Info = "顯示 X、Y 和 Z 箭頭，以便在移動目標時更輕鬆定位。",
	Warn_LookAtCamera_OptionOff_Info = "更改此設定後，將“查看相機”選項關閉一次",
	Warn_DisableLookAtCamera_PhotoMode_Info = "在照片模式下停用「看相機」一次即可生效",
	Warn_RequiresRestart_Info = "需要重啟遊戲才能生效",
	Warn_SlowMotion_PhotoMode_Info = "只有當您使用 IGCS 取消暫停時，照片模式下的慢動作才有效",
	Warn_WeatherControl_RequireCodeware = "天氣控制需要 Codeware 1.4+",
	Warn_StopNpc_UnequipWeapon_Info = "這將阻止 NPC 卸下你的給定武器。注意：戰鬥中NPC仍然會隨意脫裝備。",
	Warn_OutOfCombat_NpcUnequip_Info = "注意：在非戰鬥狀態下，NPC 將立即取消裝備給定的武器。",
	Warn_Photomode_UnfreezeSkipFrames_Info = "在照片模式下，解凍目標將跳過動畫姿勢中的畫面。要獲得完整（取消）凍結功能，您需要使用 Otis Camera Tools (IGCS)。",
	Warn_UserLocationsFolder_Info = "使用者位置保存在 AppearanceMenuMod/User/Locations 資料夾中",
	Warn_SeeMoreAction_Info = "瞄準 V 或 NPC 查看更多動作",
	Warn_SeeMoreActionProp_Info = "瞄準 NPC 或道具以查看更多操作",
	Warn_SeamfixPiercingToggle_Info = "這將保存化妝、穿孔和接縫修復切換狀態，直到您關閉遊戲。",
	Warn_PassiveMode_Info = "如果你觸發戰鬥，敵人仍然會攻擊你",
	Warn_TppCameraGameplay_Info = "TPP 相機不適合常規遊戲，但散步時很有趣;)",
	Warn_AnimatedHead_PhotoMode_Info = "啟用動畫頭像後，照片模式表情將無法運作。",
	Warn_ToolsOnly_WorksIngame = "工具只能在遊戲中使用",
	Warn_InvButtonMachineGun_Info = "你找到了！裝備中添加了重機槍。",
	Warn_InvButton_Info = "你找到了！快速運動現已推出。",
	InvButtonTip = "如果我點擊這裡怎麼辦？",
	InvButtonTip2 = "點這裡沒有任何作用！",
	InvButtonTip3 = "不要點擊您已收到警告！",
	
    --Text
	Facial_Expression = "臉部表情",
	Expressions = "表達式",
	Look_At = "看看",
	Look_At_Camera = "看相機：",
	Target_Tools = "目標工具",
	Rotation = "旋轉",
	Tilt_Rotation = "傾斜/旋轉",
	Mode = "模式：",
	Precision = "精確度",
	Relative = "相對",
	Direct = "直接",
	AdvMovement = "副詞。運動",
	ForceGivenWeapon = "武力賦予武器",
	Scale = "規模",
	ProportionalMode = "比例模式",
	General_Actions = "一般行動",
	DisablePassiveMode = "禁用被動模式",
	EnablePassiveMode = "啟用被動模式",
	EnableGodMode = "開啟上帝模式",
	DisableGodMode = "禁用上帝模式",
	Infinite_Oxygen = "無限氧氣",
	Select_Location = "選擇位置",
	Select_Expression = "選擇表達式",
	Select_Category = "選擇類別",
	Teleport_Actions = "傳送動作",
	Use_Teleport_Animation = "使用傳送動畫",
        Filter_Locations = "過濾位置",
        Locations = "地點",
        Default_Locations = "預設位置",
        Collab_Locations = "合作地點",
        Button_AddTag = "添加標籤",
	Button_FilterByTags = "按標籤過濾",
	Button_Close = "關閉",
	Favorite_Selected_Location = "最喜歡的選定地點",
	Unfavorite_Selected_Location = "不喜歡的所選位置",
	Edit_Selected_Location = "編輯選定位置",
	Locations_Favorites = "--------- 收藏夾 ----------",
	Locations_UserLocs = "-------- 使用者位置 --------",
	Locations_DefaultLocs = "----------- 預設 ----------",
	Share_Location = "分享位置",
	Edit_Location = "編輯位置",
	TimeWeather_Actions = "時間和天氣行動",
	TimeofDay = "一天中的時間",
	Time_Actions = "時間行動",
	Rain = "雨",
	Light_Rain = "小雨",
	Cloudy = "多雲",
	Fog = "霧",
	Heavy_Clouds = "烏雲密布",
	Light_Clouds = "輕雲",
	Pollution = "污染",
	Sandstorm = "沙塵暴",
	Sunny = "陽光明媚",
	Toxic_Rain = "毒雨",
	Deep_Blue = "深藍",
	Squat_Morning = "早上深蹲",
	Cloudy_Morning = "上午多雲",
	Rainy_Night = "雨夜",
	Courier_Clouds = "快遞雲",
	Cursor_LockState = "鎖定狀態",
	PhotoMode_NibblesReplacer = "照片模式半位元組替換器",
	PhotoModeEnhancements = "照片模式增強",
	Button_ResetReplacerDatabase = "重置替換資料庫",
	DisablePhotoModeCursor = "停用照片模式遊標",
	TPPCamera_Position = "TPP 相機位置",
	AnimatedHeadin_PhotoMode = "照片模式的動畫頭部",
	LockLook_AtCamera = "鎖定查看相機",
	UnlockLook_AtCamera = "解鎖查看相機",
	Save_Toggles_State = "儲存切換狀態",
	Toggle_V_Head = "切換 V 頭",
	Toggle_TPP_Camera = "切換 TPP 相機",
	Target_Nibbles = "目標蠶食",
	Target_Replacer = "目標替代者",
	Left = "左",
	Left_Close = "左關閉",
	Right = "右",
	Right_Close = "右關閉",
	Center_Close = "中心關閉",
	Center_Far = "中心遠",
	Front_Close = "前關閉",
	Front_Far = "前遠",
	All = "全部",
	Head_Only = "僅頭部",
	Eyes_Only = "僅眼睛",
	Movement = "運動",
	V_Actions = "五、行動",
	Invisible_V = "隱形V",
	LikeGTA_byGTATravel = "由 GTA 旅遊提供",
	EnableSpawnedProps = "啟用生成的道具",
	LightControl = "光控",
	Equipment = "裝置",
	
	-- >> DIRECTOR TAB
	BeginItem_TabNameDirector = "導演",
	BeginItem_TabNameTriggers = "觸發器",
	BeginCombo_StartAppearance = "開始外觀",
	BeginCombo_EndAppearance = "最終外觀",
	BeginCombo_Type = "類型",
	BeginCombo_GoToTarget = "前往目標",
	BeginCombo_PlayVoice = "播放語音",
	BeginCombo_Attack = "攻擊",
	BeginCombo_Triggers = "觸發器",
	BeginCombo_Scripts = "腳本",
	
	--Button
	Button_Yes = "是的",
	Button_No = "否",
	Button_SaveChangesOnly = "僅儲存變更",
	Button_RemoveMark = "刪除標記",
	Button_EditMark = "編輯標記",
        Button_MoveMark = "移動標記",
        Button_MoveUp = "向上移動",
        Button_MoveDown = "下移",
        Button_NewMark = "新馬克",
	Button_AddActor = "添加演員",
	Button_RemoveActor = "刪除演員",
	Button_ChangeActor = "更換演員",
	Button_RadioOnlyOne = "只有一個",
	Button_RadioRandom = "隨機",
	Button_RadioSequential = "順序",
	Button_SaveTrigger = "儲存觸發器",
	Button_NewCamera = "新相機",
	Button_NewScript = "新腳本",
	Button_DragSpeed = "速度",
	Button_ToggleMarker = "切換標記",
	Button_TestPose = "測試姿勢",
	Button_StopPose = "停止姿勢",
	
    --Button Label
	Button_Label_PlayScript = "播放腳本",
	Button_Label_StopScript = "停止腳本",
	Button_Label_Stopping = "停止...",
	Button_Label_Restarting = "正在重新啟動...",
	Button_Label_AddMark = "添加標記",
	Button_Label_SaveWNewPos = "儲存新位置",
	
    --Checkbox
    --Warning / Info / Tool Tip
	Warn_ActorSingleMark_Info = "演員將留在單一標記上",
	Warn_ActorRandomMark_Info = "演員將在標記之間隨機移動",
	Warn_ActorSequentialMark_Info = "演員將按數字順序在標記之間移動",
	Warn_DeleteScript_Info = "您確定要刪除該腳本嗎？",
	Warn_CloseCamForMove_Info = "關閉選單即可移動相機",
	Warn_CreateScriptsDesc_Info = "创建脚本来添加、打扮和指导演员，以执行机械模型、屏幕截图和角色扮演。",
	Warn_PremadeScriptsDesc_Info = "建立觸發器以在接觸時啟動預製腳本。",
	Warn_CreateCamera_FovZoomDesc_Info = "创建相机以自由移动，设置不同的视野和缩放级别。",
	Warn_ShowMarksLocations_Info = "在標記位置顯示可見圖標",
	Warn_AutoTalkNpc_Info = "这将使 NPC 在范围内每分钟说话一次（仅限有声音的 NPC）",
	Warn_DirectActorPlayerPosition_Info = "在當前玩家位置建立標記以移動和引導演員",
	Warn_InMenuDirectorDesc = "導演只在遊戲中工作",
	
    --Text
	DirectorMode = "導演模式",
	SelectActorToReplace = "選擇要替換的演員：",
	AddActorToCurrentScript = "將演員新增至目前腳本：",
	FacialExpression_WithColon = "臉部表情：",
	FavoritePoses_WithColon = "最喜歡的姿勢：",
	AddFavorites_Desc = "首先在「姿勢」標籤中將姿勢新增至收藏夾",
	HoldDuration = "保持時間",
	Movement2 = "運動：",
	Actions = "行動：",
	Actors = "演員",
	Editing = "編輯",
	AutoTalk = "自動通話",
	ActorMarks = "演員馬克",
	Current_Actors = "現任演員",
	Marks_Sequence = "標記順序：",	
	ShowMarks = "顯示標記",
	Triggers = "觸發器",
	NewTrigger = "新觸發器",
	ShowTrigger = "顯示觸發器",
	Title = "標題",
	Select_Trigger = "選擇觸發器",
	Select_Script = "選擇腳本",
	Delete_Trigger = "刪除觸發器",
	Triggers_On_Off = "觸發器開/關",
	Running = "跑步",
	Script_Running = "腳本運行...",
	Delete_Script = "刪除腳本",
	RepeatInLoop = "循環重複",
	ActivationRadius = "啟動半徑",
	Activate = "啟用設定",
	Deactivate = "停用",
	FOV = "視場角",
	Zoom = "變焦",
	LockFrame = "鎖架",
	Walk = "行人徒步區",
	Sprint = "衝刺",
	Sequential = "順序",
	Cameras = "相機",
	NodeView = "節點視圖",
	TeamA = "A隊",
	TeamB = "B隊",
	
	
	
	-- >> SETTINGS TAB
	BeginItem_TabNameSettings = "設定",
	BeginItem_TabNameGeneral = "一般",
	BeginItem_TabNameCompanions = "同伴",
	BeginItem_TabNameUI = "使用者介面",
	BeginItem_TabNameExperimental = "實驗性的",
	BeginItem_TabNamePhotoMode = "照片模式",
	
	--Button
	Button_RevertAllModelSwaps = "恢復所有模型交換",
	Button_RespawnAll = "全部重生",
	Button_ForceDespawnAll = "強迫全部消失",
	Button_ClearFavorites = "清除收藏夾",
	Button_ClearAllSavedAppearances = "清除所有已儲存的外觀",
	Button_ClearAllBlacklistedAppearances = "清除所有列入黑名單的出現",
	Button_ClearAllAppearanceTriggers = "清除所有外觀觸發器",
	Button_ClearAllSavedDespawns = "清除所有已儲存的消失",
	Button_SmallCreateTheme = "創建主題",
	Button_SmallDeleteTheme = "刪除主題",
	Button_SmallSet = "套裝",
	Button_ReloadAppearances = "重新載入自訂外觀",
	
    --Button Label
    --Checkbox
	Checkbox_SpawnAsCompanion = "生成為同伴",
	Checkbox_SpawnAsFriendly = "生成為友好",
	Checkbox_InvulnerableCompanion = "無敵夥伴",
	Checkbox_RespawnOnLaunch = "發射時重生",
	Checkbox_LockTargetAfterSpawn = "產生後鎖定目標",
	Checkbox_OpenTargetToolsAfterSpawn = "生成後開啟目標工具",
	Checkbox_DisplayAxisIndicatorByDefault = "預設顯示軸指示器",
	Checkbox_PhotoModeEnhancements = "照片模式增強",
	Checkbox_GodModeOnLaunch = "上帝模式即將上線",
	Checkbox_PassiveModeOnLaunch = "啟動時的被動模式",
	Checkbox_StreamerMode = "流光模式",
	Checkbox_OpenWCETOverlay = "使用 CET 覆蓋打開",
	Checkbox_AutoResizingWindow = "自動調整視窗大小",
	Checkbox_ScanningReticle = "掃描十字線",
	Checkbox_FloatingTargetTools = "浮動目標工具",
	Checkbox_TabHeaderDescriptions = "選項卡標題說明",
	Checkbox_ExpandFavoritesByDefault = "預設展開收藏夾",
	Checkbox_EnableScrollBars = "啟用捲軸",
	Checkbox_AlwaysDisablePhotoModeCursor = "始終停用照片模式遊標",
	Checkbox_Camera = "相機",
	Checkbox_DepthOfField = "自由度",
	Checkbox_Effect = "效果",
	Checkbox_Stickers = "貼紙",
	Checkbox_LoadSave = "載入/儲存",
	Checkbox_ExperimentalFunstuff = "實驗/有趣的東西",
	Checkbox_EnableFreezeTargetInPhotoMode = "在照片模式下啟用凍結目標",
	Checkbox_WeaponizeCompanions = "武器化同伴",
	Checkbox_AllowPlayerToBeTargetedinPosestab = "允許在「姿勢」標籤中將玩家作為目標",
	Checkbox_AllowPlayerAnimationsonNPCs = "允許 NPC 上的玩家動畫",
	Checkbox_AllowExpressionOnNpcPM = "在照片模式下允許 NPC 表情和注視",
        Checkbox_ResetTargetPositionPM = "重置照片模式 NPC 的目標位置",
        Checkbox_EnableRandomLocation = "啟用隨機按鈕：將玩家傳送到清單中的隨機位置",
        Checkbox_RestoreOnLaunch = "啟動時恢復",
        Radio_PrimarySlot = "主插槽",
        Radio_SecondarySlot = "次要插槽",
	
    --Warning / Info / Tool Tip
	Warn_RespawnOnLaunch_Info = "此設定將啟用/停用在遊戲載入時重生之前儲存的 NPC。當您退出遊戲時，AMM 會自動儲存您產生的 NPC。",
	Warn_BannedWords_Info = "此設定將啟用/停用包含以下單字的 NPC 外觀：naked、nude、xxx、shower、birthday_suit、pp 和 penis。",
	Warn_TargetNpcVehicleHotkey = "目標 NPC 或車輛設定熱鍵",
	Warn_FirstLaunchDecideTabsExpand_Info = "当 AMM 首次启动时，此设置将默认展开 Spawn、Swap 和 Decor 选项卡中的收藏夹。",
	Warn_ExperimentalTabDesc_Info = "實驗性功能增加了更多功能，但它們可能無法很好地工作，因此是實驗性標籤。事實上，大多數 AMM 使用者都啟用了實驗性功能。所以不用擔心太多，玩得開心！",
	Warn_FreezeTargetPhotoMode_Info = "此設定旨在幫助凍結將自訂動畫新增至照片模式姿勢的 mods 中的動畫，或當您使用 IGCS 取消暫停時。",
	Warn_WeaponizeCompanions_Info = "這將為所有 NPC 提供武器和戰鬥能力。預計會出現 T 形姿勢和奇怪的動畫。",
	Warn_PlayerAnimsOnNpc_Info = "如果您使用的模組允許在 NPC 上使用玩家動畫，請啟用此選項。",
	Warn_UnpauseRequiresIGSC = "此設定需要 IGCS 取消暫停時間。",
	Warn_NotInstalled = "未安裝",
	Warn_DespawnAllProps = "您確定要 Despawn 所有道具嗎？",
	
    --Text
	AMM_Version = "AMM版本：",
	CET_Version = "英文六級考試版本：",
	Codeware_Version = "程式碼軟體版本：",
	Game_Version = "遊戲版本：",
	Companion_Damage = "同伴傷害：",
	Companion_Resistance = "同儕抵抗力：",
	Companion_Distance = "同伴距離：",
	xDamage = "x 傷害",
	xResistance = "x 電阻",
	SavedAppearancesHotkeys = "儲存的外觀熱鍵",
	Favorites = "收藏夾",
	Appearances = "出場次數",
	Blacklist = "黑名單",
	AppearanceTriggers = "外觀觸發因素",
	SavedDespawns = "拯救消失者",
	Interface_Language = "介面語言：",
	Custom_Appearances = "自訂外觀",
	PhotoModeAdjustments = "照片模式調整：",
	DisablePhotoModeTabs = "停用照片模式標籤：",
	List_Height = "列表高度",
	Listbox_Themes = "主題",
	Weaponize = "武器化",
	NoAppearanceSet = "無外觀設定",
	
	
	
	-- >> EXTRA	
	--Texts, warns, tips, info's, buttons and labels etc.
	Seat_FrontRight = "右前",
	Seat_BackRight = "右後",
	Seat_FrontLeft = "左前",
	Seat_BackLeft = "左後",
	Label_Door = "門",
	Label_Window = "窗戶",

	Close = "關閉",
	Far = "遠",
	Moderate = "中等",
	
	-- >> Archives Screen
	Warning_MissingRequiredArchives = "AMM 缺少一個或多個所需的檔案。請在 archive/pc/mod 資料夾中安裝任何缺少的所需檔案。",
	Warning_MissingOptionalArchives = "AMM 缺少一個或多個檔案。這些是可選的，但可以為 AMM 添加功能。您可以忽略這些警告，但 AMM 可能無法正常運作。",
	
	
	-->> INIT.LUA
	AMMNeedsAttention = "AMM需要注意",
	MISSING_ARCHIVES = "遺失的檔案",
	VERSION_INFORMATION = "版本資訊",
	CREDITS = "學分",
	UPDATE_HISTORY = "更新歷史",
	Updates = "更新",
	MISSING = "失蹤",
	REQUIRED = "必填",
	OPTIONAL = "可選",
	WHATS_NEW = "新訊息", --Line 83 Function Error

	--Button
	Button_Ignorewarningsforthisversion = "忽略此版本的警告",
	Button_Credits = "製作人員",
	Button_Cool = "酷！",

	--Button Label
	Label_SpawnFavorites = "生成收藏夾",
	Label_SwapFavorites = "交換最愛",
	Label_FavoriteAppearances = "最喜歡的出場",
	Label_Cancel = "取消",

	--Text
	Hotkey_i = "熱鍵%i",

	--Node - Function Error(nil value) 
	Top = "頂部", --Line 116
	Bottom = "底部",
	Off = "關閉",
	
	--Voice Overs
	Label_GreetV = "問候V",
	Label_FearFoll = "恐懼福爾",
	Label_FearToll = "恐懼造成的損失",
	Label_FearBeg = "恐懼乞求",
	Label_FearRun = "恐懼奔跑",
	Label_StealthSearch = "隱性搜尋",
	Label_StealthDeath = "隱密死亡",
	Label_StealthRestore = "隱形恢復",
	Label_StealthEnd = "隱密終結",
	Label_CuriousGrunt = "好奇的咕嚕聲",
	Label_GrappleGrunt = "抓斗步兵",
	Label_Bump = "凹凸",
	Label_VehicleBump = "車輛碰撞",
	Label_TurretWarning = "砲塔警告",
	Label_OctantWarning = "八分圓警告",
	Label_DroneWarning = "無人機警告",
	Label_MechWarning = "機甲警告",
	Label_EliteWarning = "精英警告",
	Label_CameraWarning = "相機警告",
	Label_EnemyWarning = "敵人警告",
	Label_HeavyWarning = "嚴重警告",
	Label_SniperWarning = "狙擊手警告",
	Label_AnyDamage = "任何損壞",
	Label_Danger = "危險",
	Label_CombatStart = "戰鬥開始",
	Label_CombatEnd = "戰鬥結束",
	Label_CombatTargetHit = "戰鬥目標命中",
	Label_PedestrianHit = "行人撞擊",
	Label_LightHit = "輕擊",
	Label_Curse = "詛咒",
	Label_Irritated = "惱怒",
	Label_GrenadeThrow = "投擲手榴彈",
	Label_Gotakill = "殺了！",
	
	--Expressions
	Neutral = "中性",
	Joy = "喜悅",
	Smile = "微笑",
	Sad = "悲傷",
	Surprise = "驚喜",
	Aggressive = "好鬥的",
	Anger = "憤怒",
	Interested = "有興趣",
	Disinterested = "無私",
	Disappointed = "失望",
	Disgust = "厭惡",
	Exertion = "努力",
	Nervous = "緊張",
	Fear = "恐懼",
	Terrified = "害怕",
	Pain = "疼痛",
	Sleepy = "睏了",
	Unconscious = "失去知覺",
	Dead = "死了",

	-- Extra Expressions
	Frown = "皺眉",
	Shocked = "震驚",
	Annoyed_2 = "生氣2",
	Contempt = "蔑視",
	Irritated = "惱怒",
	Sceptical_1 = "持懷疑態度 1",
	Sceptical_2 = "持懷疑態度2",
	Annoyed_1 = "生氣 1",
	Offended = "被冒犯了",
	Disgusted = "厭惡",
	Disappointed_2 = "失望2",
	Alert = "警報",
	Crying = "哭泣",
	Embarrassed = "不好意思",
	Humiliated = "羞辱",
	Impatient = "不耐煩",
	Anguished = "痛苦的",
	Worried = "擔心",
	Guilty = "有罪",
	Grieving = "悲傷",
	RestrainedAnger = "克制憤怒",
	Afraid = "害怕",
	LookingUpAnnoyed = "生氣地抬頭看",
	Offended_2 = "冒犯了 2",
	Resentful = "怨恨的",
	SadExtra = "悲傷額外",
	NervousBreath = "緊張的呼吸",
	ScreamingLong = "長嘯",
	ScreamingShort = "尖叫短片",
	ScaredBreath = "害怕的呼吸",
	CryingPainful = "哭泣痛苦",
	SelfReflectAnger = "自我反思憤怒",
	IndulgentSmile = "寬容的微笑",
	Impressed = "印象深刻",
	LongSmile = "長笑",
	ShortSmile = "短暫的微笑",
	SimpleSmile = "簡單的微笑",
	Confident = "自信",
	Relief = "救濟",
	Impressed_2 = "印象深刻2",
	Admiring = "欣賞",
	Fascinated = "著迷",
	RaisedBrows = "揚起眉毛",
	LookingUpThinking = "抬頭思考",
	LeftGlanceProcessing = "左視處理",
	LeftGlanceCloseUp = "左瞥特寫",
	LookingAround = "環顧四周",
	LookingDownThinking = "低頭思考",
	LookingAroundAlt = "環顧四周",
	EyesDartFromLeft = "眼睛從左邊看",
	EyesDartFromRight = "眼睛從右邊飛出",
	EyesDartToRight = "眼睛向右看",
	LookingLeft = "向左看",
	LookingUpThinking_2 = "抬頭思考2",
	RightGlanceProcessing = "右視處理",
	LookingDown = "往下看",
	Left90GlanceClose = "左90掃視關閉",
	LookingUp = "抬頭仰望",
	Right90GlanceClose = "右90掃視關閉",
	LookingLeftUp = "向左看",
	LookingRightUp = "向右看",
	ReadingDown = "向下閱讀",
	ReadingUp = "讀起來",
	ReadingMiddle = "讀中",
	FrontCloseGlance = "正面近視",
	WinkLeft = "向左眨眼",
	EyeRoll = "翻白眼",
	Squint = "斜視",
	FalseSmile_2 = "虛假的微笑2",
	FalseSmile_1 = "虛假的微笑1",
	ListeningNewInfo = "聆聽新訊息",
	WhatDoYouWant = "你想要什麼",
	Maybe = "也許",
	SearchingForWords = "尋找詞語",
	What = "什麼",
	Where = "哪裡",
	SureSure = "當然可以",
	ListenToMe = "聽我說",
	StopThePolice = "阻止警察",
	HurryUp = "快點",
	ShutUp = "閉嘴",
	WinkRight = "向右眨眼",
	MockingSmile = "嘲笑的微笑",
	AsymmetricalSmile = "不對稱的微笑",
	SarcasticSmile = "諷刺的微笑",
	Sex = "性別",
	LipBite_1 = "咬嘴唇 1",
	LipBite_2 = "咬唇2",
	Moan = "呻吟",
	LipBite_3 = "咬唇3",
	Pout = "撅嘴",
	SexySmile = "性感的微笑",
	Swallow = "燕子",
	SensualSmile = "感性的微笑",
	SexScene_1 = "性愛場景1",
	SexScene_2 = "性愛場景2",
	Kiss = "吻",
	UsingInhaler = "使用吸入器",
	ShortYawn = "短打哈欠",
	Yawn = "打哈欠",
	Coughing = "咳嗽",
	Bite = "咬",	
	EatingFast = "吃得快",
	ShortDrink = "短飲",
	Drinking = "飲酒",
	FastBite = "快速咬合",
	LongDrink = "長飲",
	ShortSmoking = "短時間吸煙",
	LongSmoking = "長期吸煙",
	Smoking = "吸煙",
	Eating_1 = "吃1",
	Eating_2 = "吃2",
	Eating_3 = "吃3",
	Eating_4 = "吃4",
	Vomit = "嘔吐",
	BeingRevived = "被復活",
	MalwarePositive = "惡意軟體呈陽性",
	MalwareNegative = "惡意軟體負面",
	MalwareInfected = "惡意軟體感染",
	FaceMorphActivate = "臉部變形激活",
	LieNetChairSleep = "躺網椅睡覺",
	LieNetChairBreathe = "躺網椅呼吸",
	NetrunnerDeathUnplugged = "網路行者死亡已拔掉插頭",
	VeryItchyNose = "鼻子非常癢",
	RollerCoasterNervous = "雲霄飛車緊張",
	Pfft = "噗噗",
	Hahaha = "哈哈哈",
	Sniff = "嗅聞",
	Ahaaa = "啊哈",
	Heh = "呵呵",
	Huh = "呵呵",
	Haaa = "哈哈",
	Sigh_Lipsync = "嘆口氣同步",
	Hmm = "嗯",
	Whispering_1 = "低語 1",
	Whispering_2 = "竊竊私語2",
	ApprovalYes = "批准 是",
	SubtleYes = "微妙的是",
	QuickNoShake = "快速無震動",
	FirmYes = "堅定 是",
	LongNo = "長無",
	SubtleNo = "微妙的不",
	NoContempt = "沒有蔑視",
	NoDisapproval = "沒有反對",
	FirmNo = "公司編號",
	NoEnthusiastic = "沒有熱情",
	MockingYes = "嘲笑 是的",
	EnthusiasticYes = "熱情 是的",
	AsymmetricalCornerUp = "不對稱角向上",
	CornersUp = "角球向上",
	SoftSigh = "輕嘆息",
	BreathGasp = "喘氣",
	AssymetricalSneer = "不對稱的冷笑",
	CrimpingLips = "壓接嘴唇",
	BrowsDown = "向下瀏覽",
	BrowsLeftUp = "眉毛左上",
	BrowsRightUp = "眉毛向上",
	BrowsUp = "向上瀏覽",
	ClosedEyes_1 = "閉著眼睛1",
	ClosedEyes_2 = "閉上眼睛2",
	EyesClosed = "閉著眼睛",
	LookRight = "向右看",
	FastBlink = "快速閃爍",
	SlowBlink = "慢速眨眼",
	NormalBlink = "正常眨眼",
	TinyBlink = "小眨眼",
	HalfBlink = "半眨眼",
	RegularSaccade = "常規掃視",
	FrequentSaccade = "頻繁掃視",
	PhotoCloseupEyes = "照片特寫眼睛",
	PhotoCloseupLips = "嘴唇特寫照片",
	PhotoCloseupHair = "照片特寫頭髮",
	PhotoCloseupChin = "照片特寫巴",
	PhotoCloseupNose = "照片特寫鼻子",
	PhotoCloseup = "照片特寫",
	PhotoCloseupPleased = "照片特寫很高興",
	PhotoCloseupBody = "照片特寫身體",
	PhotoCloseupTeeth = "照片特寫牙齒",
	PhotoCloseupIN = "照片特寫在",
	PhotoCloseupOUT = "照片特寫輸出",
	Bored = "無聊",
	Charming = "迷人",
	Furious = "憤怒的",
	Happy = "快樂",
	Pissed = "生氣",
	Pleased = "高興",
	Scared = "害怕",
	Surprised = "驚訝",
	Sadness = "悲傷",
	Whistling = "吹口哨",
	Singing_1 = "唱歌1",
	Singing_2 = "唱歌2",
	Singing_3 = "唱歌3",
	Alerted = "已發出警報",
	Hit_1 = "擊中 1",
	Hit_2 = "擊中 2",
	Wounded = "受傷",
	Death = "死亡",

	-- Expressions Category
	Negative = "陰性",
	Positive = "積極",
	Contemplative = "沉思的",
	Social = "社群",
	Sexual = "性",
	Action = "行動",
	Vocal = "聲樂",
	Yes_N_No = "是與否",
	Nuance = "細微差別",
	Static = "靜態",
	Combat = "戰鬥",
	
	--Props
	AMM_Props_Desc = "增加道具、角色和車輛。如果沒有這個，AMM 就不會啟動。",
	AMM_JohnnyCompanion_Desc = "添加約翰尼銀手作為可生成的角色。",
	AMM_ScenesPack_Desc = "為姿勢系統新增 9358 個場景動畫。\n在 AMM 的 Nexus 頁面上下載。",
	AMM_SoundPack_Desc = "新增可產生的音效。",
	AMM_KerryPP_Desc = "添加新的裸體外觀。",
	AMM_BenjaminStonePP_Desc = "添加新的裸體外觀。",
	AMM_RiverPP_Desc = "添加新的裸體外觀。",
	AMM_YorinobuPP_Desc = "添加新的裸體外觀。",
	AMM_LizzyIncognito_Desc = "新增外觀。",
	AMM_MeredithXtra_Desc = "新增外觀。",
	AMM_DelamainFix_Desc = "為德拉曼添加全身。",
	AMM_HanakoNoMakeup_Desc = "允許 AMM 在使用自訂外觀時去除花子的妝容。",
	AMM_JudyBodyRevamp_Desc = "用新改良的身體取代朱迪的身體。",
	AMM_PanamBodyRevamp_Desc = "用新的改良型取代了帕納姆的車身。",
	AMM_MistyBodyRevamp_Desc = "用新改進的身體替換了米絲蒂的身體。\n在 AMM 的 Nexus 頁面上下載。",
	AMM_1VesHanakoFixedBodyNaked_Desc = "將花子的身體換成新改良的身體。",
	AMM_PinkyDudeANIMFacialExpressionsFemV_Desc = "啟用 Female V 的臉部表情工具",
	AMM_PinkyDudeANIMFacialExpressionsMaleV_Desc = "啟用 Male V 的臉部表情工具",
	AMM_DinoTattooFixArchive_Desc = "替換網格和紋理。",
	AMM_SongbirdBodyFixArchive_Desc = "替換主體以修復灰色區域。還不完美。",
	AMM_RitaWheelerCombatEnablerArchive_Desc = "取代實體檔案以啟用戰鬥動畫。",
	AMM_CheriAppearances_Desc = "新增外觀。在 AMM 的 Nexus 頁面上下載。",
	AMM_BryceNaked_Desc = "添加新的裸體外觀。在 AMM 的 Nexus 頁面上下載。",
	AMM_EvelynNaked_Desc = "修復她的身體以允許裸體出現。在 AMM 的 Nexus 頁面上下載。",
	AMM_SaburoAppearances_Desc = "新增外觀。在 AMM 的 Nexus 頁面上下載。",
	AMM_TbugAppearances_Desc = "新增外觀。在 AMM 的 Nexus 頁面上下載。",
	AMM_8ug8eagAppearances_Desc = "新增外觀。在 AMM 的 Nexus 頁面上下載。",
	
	--Equipments (There is a Function Error(nil value) in this section, These are just labels that are not connected to any localizable strings in the file)
	Fists = "拳頭", --Line 2377 
	Katana = "武士刀",
	Mantis_Blades = "螳螂刀片",
	Machete = "彎刀",
	Hammer = "錘子",
	Baton = "接力棒",
	Knife = "刀",
	Crowbar = "撬棍",
	Baseball_Bat = "棒球棒",
	Assault_Rifle = "突擊步槍",
	Sidewinder = "響尾蛇",
	Sniper_Rifle = "狙擊步槍",
	Shotgun = "霰彈槍",
	SMG = "衝鋒槍",
	Handgun = "手槍", --Line 2391
	
	--Warning / Info / Tooltip
	Warn_CantSave_BlacklistedAppearance = "您無法儲存列入黑名單的外觀！",
	Warn_ConfirmDeleteSavedAppearances = "您確定要刪除所有已儲存的外觀嗎？",
	Warn_ConfirmDeleteBlacklistedAppearances = "您確定要刪除所有列入黑名單的外觀嗎？",
	Warn_ConfirmDeleteSavedDespawns = "您確定要刪除所有已儲存的消失嗎？",
	Warn_ConfirmDeleteAppearanceTriggers = "您確定要刪除所有外觀觸發器嗎？",
	Warn_ConfirmDeleteCurrentAppearance = "您確定要刪除目前活動預設嗎？",
	Warn_WeaponizeNpcAnimationIssues = "並非每個 NPC 都有使用每種武器所需的動畫。可能會出現 T 形姿勢和不正確的動畫。\n您確定要啟用它嗎？",
	Warn_ConfirmEnableExperimentalAndSave_Info = "您確定要啟用實驗性功能嗎？ AMM 可能無法如預期運作。使用它需要您自擔風險！",
	Warn_DeleteFavoritesAskWhichOne_Info = "如果您确定要删除所有收藏夹，请选择以下一项：",
	Popup_Error_Title = "錯誤",
	Button_Ok = "好的",
	Popup_FavoriteName = "最喜歡的名字",
	Popup_RenamePreset = "重新命名預設",
	Popup_RenameProp = "重命名道具",
	Editor_Title = "主題編輯器",
	Editor_Field_ThemeName = "主題名稱",
	Editor_Hint_InsertThemeName = "插入新主題名稱",
	Error_ThemeNameExists = "主題名稱已存在",
}
